In [13]:
import pickle
from pathlib import Path
import pandas as pd

In [14]:
file_path = Path("output/GROUPE_LANDOR/LANDOR_tables.pkl")

with open(file_path, "rb") as f:
    data = pickle.load(f)

print("Type de données :", type(data))

Type de données : <class 'dict'>

In [15]:
print("Contenu (clés principales) :")
print(data.keys())

Contenu (clés principales) :
dict_keys([2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024])

In [16]:
year = 2014  # 👉 change ici l'année que tu veux

if year in data:
    tables = data[year]

    print("="*60)
    print(f"📅 Année : {year}")
    print(f"📊 Nombre de tableaux : {len(tables)}")

    for i, df in enumerate(tables):
        print("\n------------------------------")
        print(f"Tableau {i+1}")
        display(df)
else:
    print("❌ Année introuvable :", year)

============================================================
📅 Année : 2014
📊 Nombre de tableaux : 31

------------------------------
Tableau 1

,ACTIFS,Unnamed: 0,Unnamed: 1,Unnamed: 2
0,NaN,Notes,31-déc.-2014,31-déc.-2013
1,ACTIFS NON COURANTS,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,Actifs Immobilisés,NaN,NaN,NaN
4,IMMOBILISATIONS INCORPORELLES,4.1,2 473 814,1 630 914
5,Moins(Amortissement),NaN,<1 139 760>,<900 535>
6,Total Immobilisations incorporelles,NaN,1 334 054,730 379
7,NaN,NaN,NaN,NaN
8,IMMOBILISATIONS CORPORELLES,4.2,39 663 411,35 887 390
9,Moins(Amortissement),NaN,<13 900 515>,<10 994 265>
10,Total Immobilisations corporelles (*),NaN,25 762 896,24 893 126
11,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN
13,IMMOBILISATIONS FINANCIERES,4.3,25 338,36 009
14,NaN,NaN,NaN,NaN
15,Total des Actifs Immobilisés,NaN,27 122 288,25 659 513
16,NaN,NaN,NaN,NaN
17,Autres Actifs Non Courants,4.4,2 169 429,2 460 877
18,NaN,NaN,NaN,NaN
19,TOTAL DES ACTIFS NON COURANTS,NaN,29 291 717,28 120 390
20,NaN,NaN,NaN,NaN
21,ACTIFS COURANTS,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN
23,Stocks,4.5,12 813 063,17 476 884
24,Moins ( provisions),NaN,<208 841>,<2 212 131>
25,Total des Stocks,NaN,12 604 222,15 264 753
26,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN
28,Clients Et Comptes Rattachés,4.6,9 038 028,7 403 325
29,Moins ( provisions),NaN,<2 100 280>,<1 657 454>
30,Total des Clients et comptes rattachés (*),NaN,6 937 748,5 745 871
31,NaN,NaN,NaN,NaN
32,Autres Actifs Courants,4.7,5 084 820,7 656 192
33,NaN,NaN,NaN,NaN
34,Liquidités Et Equivalents De Liquidités (*),4.8,1 886 007,3 470 474
35,NaN,NaN,NaN,NaN
36,TOTAL DES ACTIFS COURANTS,NaN,26 512 797,32 137 290
37,NaN,NaN,NaN,NaN
38,TOTAL DES ACTIFS,NaN,55 804 514,60 257 680

------------------------------
Tableau 2

,CAPITAUX PROPRES ET PASSIFS,Unnamed: 0,Unnamed: 1,Unnamed: 2
0,NaN,Notes,31-déc.-2014,31-déc.-2013
1,CAPITAUX PROPRES,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,Capital Social,5.1,4 846 875,4 700 000
4,NaN,NaN,NaN,NaN
5,Réserves consolidées,5.1,<11 026 566>,<4 498 074>
6,NaN,NaN,NaN,NaN
7,Autres Capitaux Propres,5.1,12 043 724,11 686 522
8,NaN,NaN,NaN,NaN
9,Résultat Consolidés,5.1,<2 825 591>,<6 081 569>
10,NaN,NaN,NaN,NaN
11,Intérêts minoritaires,NaN,139,153 375
12,NaN,NaN,NaN,NaN
13,TOTAL DES CAPITAUX PROPRES APRES AFFECTATION,NaN,3 038 581,5 960 254
14,NaN,NaN,NaN,NaN
15,PASSIFS,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN
17,Passifs Non Courants,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN
19,Emprunts,5.2,12 979 557,13 436 843
20,Provisions,5.3,641 470,214 470
21,Total Des Passifs Non Courants,NaN,13 621 027,13 651 313
22,NaN,NaN,NaN,NaN
23,Passifs Courants,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN
25,Fournisseurs Et Comptes Rattachés (*),5.4,8 443 362,15 640 324
26,NaN,NaN,NaN,NaN
27,Autres Passifs Courants (*),5.5,3 580 940,3 962 025
28,NaN,NaN,NaN,NaN
29,Concours Bancaires Et Autres Passifs Financier...,5.6,27 120 604,21 043 763
30,NaN,NaN,NaN,NaN
31,Total Des Passifs Courants,NaN,39 144 906,40 646 112
32,NaN,NaN,NaN,NaN
33,TOTAL DES PASSIFS,NaN,52 765 933,54 297 425
34,NaN,NaN,NaN,NaN
35,TOTAL DES CAPITAUX PROPRES ET PASSIFS,NaN,55 804 514,60 257 680

------------------------------
Tableau 3

,ETAT DE RESULTAT,Unnamed: 0,Unnamed: 1,Unnamed: 2
0,NaN,Notes,31-déc.-2014,31-déc.-2013
1,NaN,NaN,NaN,NaN
2,PRODUITS D'EXPLOITATION,6.1,NaN,NaN
3,Revenus,NaN,67 000 511,70 263 927
4,NaN,NaN,NaN,NaN
5,Autres Produits d'Exploitation,NaN,184 722,867 299
6,NaN,NaN,NaN,NaN
7,Total Des Produits D'exploitation,NaN,67 185 233,71 131 227
8,NaN,NaN,NaN,NaN
9,CHARGES D'EXPLOITATION,NaN,NaN,NaN
10,Variation de Stocks des Produits Finis (*),NaN,<162 565>,<578 015>
11,NaN,NaN,NaN,NaN
12,Achats Consommés,6.2,42 129 153,47 398 746
13,Achats,NaN,39 565 859,48 970 943
14,Variations Des Stocks (*),NaN,2 563 294,<1 572 197>
15,NaN,NaN,NaN,NaN
16,Autres achats,6.3,2 929 471,3 670 330
17,Charges De Personnel,6.4,8 973 033,7 805 895
18,Dotations Aux Amortissements Et Provisions,6.5,5 185 286,6 503 832
19,Autres Charges D'exploitation (*),6.6,8 958 890,9 527 630
20,Total Des Charges D'exploitation,NaN,68 175 833,74 906 433
21,NaN,NaN,NaN,NaN
22,RESULTAT D'EXPLOITATION,NaN,<828 035>,<3 197 192>
23,NaN,NaN,NaN,NaN
24,Charges Financières Nettes (*),6.7,2 666 689,3 154 363
25,Produits des palcements,NaN,-,13 203
26,Autres Gains Ordinaires,6.8,445 742,411 811
27,Autres Pertes Ordinaires,6.9,56 128,5 227
28,NaN,NaN,NaN,NaN
29,RESULTAT DES ACTIVITES ORDINAIRES AVANT IMPOT,NaN,<3 105 110>,<5 931 767>
30,NaN,NaN,NaN,NaN
31,Impot sur les bénéfices,NaN,<155 881>,<403 158>
32,Impôt différé,6.10,272 350,253 357
33,RESULTAT DES ACTIVITES ORDINAIRES APRES IMPOT,NaN,<2 988 641>,<6 081 569>

------------------------------
Tableau 4

                           ETAT DE FLUX DE TRESORERIE    Unnamed: 0
0                                        31-déc.-2014  31-déc.-2013
1                                                 NaN           NaN
2            FLUX DE TRESORERIE LIES A L'EXPLOITATION           NaN
3                                                 NaN           NaN
4          Encaissements Reçus des Clients 76 161 867    76 475 780
5                        Autres Encaissements 746 849     4 147 355
6        Sommes Versées aux Fournisseurs <59 177 539>  <70 098 701>
7                       Autres Paiements <19 468 631>  <16 023 934>
8                            Intérêts payés <914 295>     <602 675>
9                                                 NaN           NaN
10  Flux de Trésorerie provenant de (affecté à) l'...   <6 102 175>
11                                                NaN           NaN
12         FLUX DE TRESORERIE LIES A L'INVESTISSEMENT           NaN
13                                                NaN           NaN
14  Décaissements / acquisitions d'immob corp et i...  <10 683 924>
15  Encaissements / cessions d'immob corp et incor...       105 884
16   Décaissements / acquisitions d'immob financières           NaN
17                                                NaN       <7 720>
18  Flux de Trésorerie provenant des (affecté aux)...           NaN
19          <10 585 760> d'investissement <2 547 876>           NaN
20                                                NaN           NaN
21             FLUX DE TRESORERIE LIES AU FINANCEMENT           NaN
22                                                NaN           NaN
23       Encaissements suite à l'émission d'actions -    10 920 000
24             Encaissements provenant des emprunts -     8 500 000
25   Encaissements sur Financement de Stock et autres           NaN
26                 Encaissements subvention 1 250 649     1 905 000
27     Décaissements sur Financement de Stock 788 628           NaN
28               Remboursement d'emprunts <1 212 142>   <3 694 479>
29                                                NaN           NaN
30  Flux de Trésorerie provenant des (affecté aux)...           NaN
31                  17 630 521 de financement 827 135           NaN
32                                                NaN           NaN
33   INCIDENCES DES VARIATIONS DES TAUX DE CHANGE SUR           NaN
34                                                NaN           NaN
35  LES LIQUIDITES ET EQUIVALENTS DE LIQUIDITES 21...     <821 229>
36                                                NaN           NaN
37                VARIATION DE TRESORERIE <4 157 987>       121 357
38                                                NaN           NaN
39      Trésorerie au début de l'exercice <9 512 110>   <9 633 468>
40                                                NaN           NaN
41  Trésorerie à la clôture de l'exercice <13 670 ...   <9 512 110>

------------------------------
Tableau 5

,Unnamed: 0,Désignation,Qualité,Pourcentage de,Méthode de
0,NaN,NaN,NaN,contrôle,consolidation
1,1_LAND’OR,NaN,Mère,100 %,Société consolidante
2,2_LFS,NaN,Filiale,"99,97 %",Intégration globale
3,3_ ECHARIKA ALYBIA...,NaN,Filiale,65 %,Intégration globale
4,4_LMFS,NaN,Filiale,100%,Intégration globale
5,5_LAND’OR USA HOLDINGS INC,NaN,Filiale,100%,Intégration globale

------------------------------
Tableau 6

,"2.12Ecart de conversion\r\rLa comptabilisation des opérations réalisées entre deux sociétés utilisant des devises différentes conduit\rà la clôture à des écarts lors de la conversion des comptes des entreprises étrangères. Le résultat et la\rsituationfinancièred’uneentitédoiventêtreconvertisdelamonnaiefonctionnelleàuneautre\rmonnaie de présentation.\r-Les actifs et les passifs de chaque bilan présenté doivent être convertis au cours de clôture à la\rdate de chacun de ces bilans ;\r-Les produits et les charges de chaque compte de résultat doivent être convertis au cours de\rchange en vigueur aux dates des transactions ;et\r-Tous les écarts de change en résultant doivent être comptabilisés en tant que composante\rdistincte des capitaux propres.\r\r2.13Impôt différé\r\rLes sociétés du Land’Or sont soumises à l’impôt sur les sociétés (IS) selon les règles et les\rtaux en vigueur du pays ou la société est implantée.\rIl a été tenu compte d’un impôt différé pour les retraitements de consolidation ayant une incidence sur\rle résultat ainsi qu’une mise à jour des actifs et des passifs des impôts différés au taux en vigueur à la\rclôture de l’exercice comptable.\r\r3CHANGEMENT DE METHODE DE PRESENTATION\r\rAu cours de l’exercice 2014, la société Land’Or a procédé à un changement dans la présentation de\rcertains postes des états financiers. La colonne comparative a été retraitée. Les principaux\rretraitements se présentent comme suit :\r\r3.1Changement de méthode de présentation des postes de bilan:\r\r•Les immobilisations à statut juridique particuliers ont été reclassées vers la catégorie immobilisations\rcorporelles.\r\r•Les avances clients précédemment classées parmi la rubrique « clients et comptes rattachés »\rsont désormais présentées parmi les autres passifs courants.\r\r•Les chèques à encaisser précédemment classés parmi la rubrique « Liquidités et équivalents de\rLiquidités » sont désormais présentés parmi les clients et comptes rattachés.\r\r•Les échéances à moins d’un an relatives au contrat de leasing présentées parmi les « fournisseurs\ret comptes rattachés » lors des périodes précédentes ont été reclassées parmi les « Concours\rbancaires et autres passifs financiers ».\r\rRetraitement des postes du bilan au 31 décembre 2013:\r\r\r31/12/2013 avant31/12/2013 après\rPostes retraitésreclassement reclassement\rreclassement\rImmobilisations à statut juridique particulier1 048 776<1 048 776>-\rImmobilisations corporelles23 844 3491 048 77624 893 125\rClients et comptes rattachés6 708 602694 7237 403 325\rAutres Passifs Courants<4 353 898>391 874<3 962 025>\rLiquidités et équivalents de liquidités4 165 197<694 723>3 470 474\rFournisseurs et compte rattachés<15 613 477><26 847><15 640 324>\rAutres actifs courants7 821 92838 4237 860 351\rConcours bancaires et autres passifs financiers<20 640 314><403 450><21 043 763>\r\r\r\r3.2Changement de méthode de présentation des postes de l’état de résultat\r\r•La variation de stocks de produits semi finis précédemment présentée parmi la variation de stock\rde matières premières a été reclassée vers la variation de stock de produits finis.",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,NaN,NaN,31/12/2013 avant,NaN,NaN,31/12/2013 après,NaN
1,NaN,NaN,NaN,reclassement,reclassement,NaN,NaN,NaN
2,NaN,Immobilisations à statut juridique particulier,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Immobilisations corporelles,NaN,NaN,NaN,NaN,NaN,NaN

------------------------------
Tableau 7

,"2.12Ecart de conversion\r\rLa comptabilisation des opérations réalisées entre deux sociétés utilisant des devises différentes conduit\rà la clôture à des écarts lors de la conversion des comptes des entreprises étrangères. Le résultat et la\rsituationfinancièred’uneentitédoiventêtreconvertisdelamonnaiefonctionnelleàuneautre\rmonnaie de présentation.\r-Les actifs et les passifs de chaque bilan présenté doivent être convertis au cours de clôture à la\rdate de chacun de ces bilans ;\r-Les produits et les charges de chaque compte de résultat doivent être convertis au cours de\rchange en vigueur aux dates des transactions ;et\r-Tous les écarts de change en résultant doivent être comptabilisés en tant que composante\rdistincte des capitaux propres.\r\r2.13Impôt différé\r\rLes sociétés du Land’Or sont soumises à l’impôt sur les sociétés (IS) selon les règles et les\rtaux en vigueur du pays ou la société est implantée.\rIl a été tenu compte d’un impôt différé pour les retraitements de consolidation ayant une incidence sur\rle résultat ainsi qu’une mise à jour des actifs et des passifs des impôts différés au taux en vigueur à la\rclôture de l’exercice comptable.\r\r3CHANGEMENT DE METHODE DE PRESENTATION\r\rAu cours de l’exercice 2014, la société Land’Or a procédé à un changement dans la présentation de\rcertains postes des états financiers. La colonne comparative a été retraitée. Les principaux\rretraitements se présentent comme suit :\r\r3.1Changement de méthode de présentation des postes de bilan:\r\r•Les immobilisations à statut juridique particuliers ont été reclassées vers la catégorie immobilisations\rcorporelles.\r\r•Les avances clients précédemment classées parmi la rubrique « clients et comptes rattachés »\rsont désormais présentées parmi les autres passifs courants.\r\r•Les chèques à encaisser précédemment classés parmi la rubrique « Liquidités et équivalents de\rLiquidités » sont désormais présentés parmi les clients et comptes rattachés.\r\r•Les échéances à moins d’un an relatives au contrat de leasing présentées parmi les « fournisseurs\ret comptes rattachés » lors des périodes précédentes ont été reclassées parmi les « Concours\rbancaires et autres passifs financiers ».\r\rRetraitement des postes du bilan au 31 décembre 2013:\r\r\r31/12/2013 avant31/12/2013 après\rPostes retraitésreclassement reclassement\rreclassement\rImmobilisations à statut juridique particulier1 048 776<1 048 776>-\rImmobilisations corporelles23 844 3491 048 77624 893 125\rClients et comptes rattachés6 708 602694 7237 403 325\rAutres Passifs Courants<4 353 898>391 874<3 962 025>\rLiquidités et équivalents de liquidités4 165 197<694 723>3 470 474\rFournisseurs et compte rattachés<15 613 477><26 847><15 640 324>\rAutres actifs courants7 821 92838 4237 860 351\rConcours bancaires et autres passifs financiers<20 640 314><403 450><21 043 763>\r\r\r\r3.2Changement de méthode de présentation des postes de l’état de résultat\r\r•La variation de stocks de produits semi finis précédemment présentée parmi la variation de stock\rde matières premières a été reclassée vers la variation de stock de produits finis.",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,NaN,NaN,NaN,31/12/2013 avant,NaN
1,NaN,NaN,NaN,reclassement,NaN
2,NaN,Immobilisations à statut juridique particulier,NaN,NaN,NaN
3,NaN,Immobilisations corporelles,NaN,NaN,NaN

------------------------------
Tableau 8

,"4ACTIF\r\r\r4.1Immobilisations incorporelles\r\rLe détail de cette rubrique au 31/12/2014 est le suivant :\r31/12/201431/12/2013\rLogiciel Informatique2 410 3431 064 484\rDépôt de marques49 26441 410\rImmobilisations en cours14 207525 020\rTotal brut2 473 8141 630 914\rAmortissement<1 139 760><900 535>\rTotal net1 334 054730 379\r\r\rLa variation du solde de la rubrique immobilisation en cours de 510 813 DT est relative à la mise en\rservice de projet SAP le 01/10/2014 .\r\r4.2Immobilisations corporelles\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rTerrain nu1 321 6001 321 600\rTerrain bâti230 400230 400\rBâtiment industriel6 135 4815 910 243\rInstallations générales, agencements et aménagements des\r3 886 3462 770 773\rconstructions\rInstallations techniques4 208 0773 917 739\rMatériels industriels15 526 90715 415 149\rOutillages industriels1 687 3221 642 586\rMatériels de transport des personnes638 850713 298\rMatériels de transport acquis en leasing3 098 1612 189 369\rEquipements de bureau307 142250 370\rMatériels informatiques1 244 152929 481\rImmobilisations encours1 378 973596 382\rTotal brut39 663 41135 887 390\rAmortissement CORP<13 900 515><10 994 265>\rTotal net25 762 89624 893 125\r\r\r\r4.3Immobilisations Financières\r\rCette rubrique se détaille au 31/12/2014 comme suit :\r31/12/201431/12/2013\rDépôts et cautionnements25 33836 009\rTotal net25 33836 009\r\r\r4.4Autres actifs non courants\r\rLe solde de cette rubrique s'analyse comme suit:\r31/12/201431/12/2013\rFrais préliminaires11 940 3432 761 372\rCharges à répartir1 227 6528 638 347\rTotal brut13 167 99511 399 719\rRésorptions<10 998 566><8 938 842>\rTotal net2 169 4292 460 877",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,31/12/2014,NaN,NaN,31/12/2013,NaN
1,NaN,errain nu,NaN,NaN,1 321 60,NaN,NaN,1 321 600,NaN
2,NaN,errain bâti,NaN,NaN,230 40,NaN,NaN,230 400,NaN
3,NaN,âtiment industriel,NaN,NaN,6 135 48,NaN,NaN,5 910 243,NaN
4,NaN,"nstallations générales, agencements et aménag...",NaN,3 886 346,2 770 773,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,3 886 34,2 770 773,NaN,NaN,NaN
6,NaN,onstructions,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,nstallations techniques,NaN,NaN,4 208 07,NaN,NaN,3 917 739,NaN
8,NaN,atériels industriels,NaN,NaN,15 526 90,NaN,NaN,15 415 149,NaN
9,NaN,utillages industriels,NaN,NaN,1 687 32,NaN,NaN,1 642 586,NaN
10,NaN,atériels de transport des personnes,NaN,NaN,638 85,NaN,NaN,713 298,NaN
11,NaN,atériels de transport acquis en leasing,NaN,NaN,3 098 16,NaN,NaN,2 189 369,NaN
12,NaN,quipements de bureau,NaN,NaN,307 14,NaN,NaN,250 370,NaN
13,NaN,atériels informatiques,NaN,NaN,1 244 15,NaN,NaN,929 481,NaN
14,NaN,mmobilisations encours,NaN,NaN,1 378 97,NaN,NaN,596 382,NaN
15,NaN,otal brut,NaN,NaN,39 663 41,NaN,NaN,35 887 390,NaN
16,NaN,mortissement CORP,NaN,NaN,<13 900 515,NaN,NaN,<10 994 265>,NaN
17,NaN,otal net,NaN,NaN,25 762 89,NaN,NaN,24 893 125,NaN

------------------------------
Tableau 9

,"4ACTIF\r\r\r4.1Immobilisations incorporelles\r\rLe détail de cette rubrique au 31/12/2014 est le suivant :\r31/12/201431/12/2013\rLogiciel Informatique2 410 3431 064 484\rDépôt de marques49 26441 410\rImmobilisations en cours14 207525 020\rTotal brut2 473 8141 630 914\rAmortissement<1 139 760><900 535>\rTotal net1 334 054730 379\r\r\rLa variation du solde de la rubrique immobilisation en cours de 510 813 DT est relative à la mise en\rservice de projet SAP le 01/10/2014 .\r\r4.2Immobilisations corporelles\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rTerrain nu1 321 6001 321 600\rTerrain bâti230 400230 400\rBâtiment industriel6 135 4815 910 243\rInstallations générales, agencements et aménagements des\r3 886 3462 770 773\rconstructions\rInstallations techniques4 208 0773 917 739\rMatériels industriels15 526 90715 415 149\rOutillages industriels1 687 3221 642 586\rMatériels de transport des personnes638 850713 298\rMatériels de transport acquis en leasing3 098 1612 189 369\rEquipements de bureau307 142250 370\rMatériels informatiques1 244 152929 481\rImmobilisations encours1 378 973596 382\rTotal brut39 663 41135 887 390\rAmortissement CORP<13 900 515><10 994 265>\rTotal net25 762 89624 893 125\r\r\r\r4.3Immobilisations Financières\r\rCette rubrique se détaille au 31/12/2014 comme suit :\r31/12/201431/12/2013\rDépôts et cautionnements25 33836 009\rTotal net25 33836 009\r\r\r4.4Autres actifs non courants\r\rLe solde de cette rubrique s'analyse comme suit:\r31/12/201431/12/2013\rFrais préliminaires11 940 3432 761 372\rCharges à répartir1 227 6528 638 347\rTotal brut13 167 99511 399 719\rRésorptions<10 998 566><8 938 842>\rTotal net2 169 4292 460 877",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,31/12/2014,NaN,NaN,31/12/201,NaN
1,NaN,épôts et cautionnements,NaN,NaN,25 33,NaN,NaN,36 00,NaN
2,NaN,otal net,NaN,NaN,25 33,NaN,NaN,36 00,NaN

------------------------------
Tableau 10

,"4ACTIF\r\r\r4.1Immobilisations incorporelles\r\rLe détail de cette rubrique au 31/12/2014 est le suivant :\r31/12/201431/12/2013\rLogiciel Informatique2 410 3431 064 484\rDépôt de marques49 26441 410\rImmobilisations en cours14 207525 020\rTotal brut2 473 8141 630 914\rAmortissement<1 139 760><900 535>\rTotal net1 334 054730 379\r\r\rLa variation du solde de la rubrique immobilisation en cours de 510 813 DT est relative à la mise en\rservice de projet SAP le 01/10/2014 .\r\r4.2Immobilisations corporelles\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rTerrain nu1 321 6001 321 600\rTerrain bâti230 400230 400\rBâtiment industriel6 135 4815 910 243\rInstallations générales, agencements et aménagements des\r3 886 3462 770 773\rconstructions\rInstallations techniques4 208 0773 917 739\rMatériels industriels15 526 90715 415 149\rOutillages industriels1 687 3221 642 586\rMatériels de transport des personnes638 850713 298\rMatériels de transport acquis en leasing3 098 1612 189 369\rEquipements de bureau307 142250 370\rMatériels informatiques1 244 152929 481\rImmobilisations encours1 378 973596 382\rTotal brut39 663 41135 887 390\rAmortissement CORP<13 900 515><10 994 265>\rTotal net25 762 89624 893 125\r\r\r\r4.3Immobilisations Financières\r\rCette rubrique se détaille au 31/12/2014 comme suit :\r31/12/201431/12/2013\rDépôts et cautionnements25 33836 009\rTotal net25 33836 009\r\r\r4.4Autres actifs non courants\r\rLe solde de cette rubrique s'analyse comme suit:\r31/12/201431/12/2013\rFrais préliminaires11 940 3432 761 372\rCharges à répartir1 227 6528 638 347\rTotal brut13 167 99511 399 719\rRésorptions<10 998 566><8 938 842>\rTotal net2 169 4292 460 877",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,31/12/2014,NaN,NaN,31/12/2013,NaN
1,NaN,rais préliminaires,NaN,NaN,11 940 34,NaN,NaN,2 761 37,NaN
2,NaN,harges à répartir,NaN,NaN,1 227 65,NaN,NaN,8 638 34,NaN
3,NaN,otal brut,NaN,NaN,13 167 99,NaN,NaN,11 399 71,NaN
4,NaN,Résorptions,NaN,NaN,<10 998 566>,NaN,NaN,<8 938 842,NaN
5,NaN,otal net,NaN,NaN,2 169 42,NaN,NaN,2 460 87,NaN

------------------------------
Tableau 11

,"4ACTIF\r\r\r4.1Immobilisations incorporelles\r\rLe détail de cette rubrique au 31/12/2014 est le suivant :\r31/12/201431/12/2013\rLogiciel Informatique2 410 3431 064 484\rDépôt de marques49 26441 410\rImmobilisations en cours14 207525 020\rTotal brut2 473 8141 630 914\rAmortissement<1 139 760><900 535>\rTotal net1 334 054730 379\r\r\rLa variation du solde de la rubrique immobilisation en cours de 510 813 DT est relative à la mise en\rservice de projet SAP le 01/10/2014 .\r\r4.2Immobilisations corporelles\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rTerrain nu1 321 6001 321 600\rTerrain bâti230 400230 400\rBâtiment industriel6 135 4815 910 243\rInstallations générales, agencements et aménagements des\r3 886 3462 770 773\rconstructions\rInstallations techniques4 208 0773 917 739\rMatériels industriels15 526 90715 415 149\rOutillages industriels1 687 3221 642 586\rMatériels de transport des personnes638 850713 298\rMatériels de transport acquis en leasing3 098 1612 189 369\rEquipements de bureau307 142250 370\rMatériels informatiques1 244 152929 481\rImmobilisations encours1 378 973596 382\rTotal brut39 663 41135 887 390\rAmortissement CORP<13 900 515><10 994 265>\rTotal net25 762 89624 893 125\r\r\r\r4.3Immobilisations Financières\r\rCette rubrique se détaille au 31/12/2014 comme suit :\r31/12/201431/12/2013\rDépôts et cautionnements25 33836 009\rTotal net25 33836 009\r\r\r4.4Autres actifs non courants\r\rLe solde de cette rubrique s'analyse comme suit:\r31/12/201431/12/2013\rFrais préliminaires11 940 3432 761 372\rCharges à répartir1 227 6528 638 347\rTotal brut13 167 99511 399 719\rRésorptions<10 998 566><8 938 842>\rTotal net2 169 4292 460 877",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,31/12/2014,NaN,NaN,31/12/201,NaN
1,NaN,ogiciel Informatique,NaN,NaN,2 410 34,NaN,NaN,1 064 48,NaN
2,NaN,épôt de marques,NaN,NaN,49 26,NaN,NaN,41 41,NaN
3,NaN,mmobilisations en cours,NaN,NaN,14 20,NaN,NaN,525 02,NaN
4,NaN,otal brut,NaN,NaN,2 473 81,NaN,NaN,1 630 91,NaN
5,NaN,mortissement,NaN,NaN,<1 139 760,NaN,NaN,<900 535,NaN
6,NaN,otal net,NaN,NaN,1 334 05,NaN,NaN,730 37,NaN

------------------------------
Tableau 12

,"4ACTIF\r\r\r4.1Immobilisations incorporelles\r\rLe détail de cette rubrique au 31/12/2014 est le suivant :\r31/12/201431/12/2013\rLogiciel Informatique2 410 3431 064 484\rDépôt de marques49 26441 410\rImmobilisations en cours14 207525 020\rTotal brut2 473 8141 630 914\rAmortissement<1 139 760><900 535>\rTotal net1 334 054730 379\r\r\rLa variation du solde de la rubrique immobilisation en cours de 510 813 DT est relative à la mise en\rservice de projet SAP le 01/10/2014 .\r\r4.2Immobilisations corporelles\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rTerrain nu1 321 6001 321 600\rTerrain bâti230 400230 400\rBâtiment industriel6 135 4815 910 243\rInstallations générales, agencements et aménagements des\r3 886 3462 770 773\rconstructions\rInstallations techniques4 208 0773 917 739\rMatériels industriels15 526 90715 415 149\rOutillages industriels1 687 3221 642 586\rMatériels de transport des personnes638 850713 298\rMatériels de transport acquis en leasing3 098 1612 189 369\rEquipements de bureau307 142250 370\rMatériels informatiques1 244 152929 481\rImmobilisations encours1 378 973596 382\rTotal brut39 663 41135 887 390\rAmortissement CORP<13 900 515><10 994 265>\rTotal net25 762 89624 893 125\r\r\r\r4.3Immobilisations Financières\r\rCette rubrique se détaille au 31/12/2014 comme suit :\r31/12/201431/12/2013\rDépôts et cautionnements25 33836 009\rTotal net25 33836 009\r\r\r4.4Autres actifs non courants\r\rLe solde de cette rubrique s'analyse comme suit:\r31/12/201431/12/2013\rFrais préliminaires11 940 3432 761 372\rCharges à répartir1 227 6528 638 347\rTotal brut13 167 99511 399 719\rRésorptions<10 998 566><8 938 842>\rTotal net2 169 4292 460 877",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,31/12/2014,NaN,NaN,31/12/201,NaN
1,NaN,ogiciel Informatique,NaN,NaN,2 410 34,NaN,NaN,1 064 48,NaN
2,NaN,épôt de marques,NaN,NaN,49 26,NaN,NaN,41 41,NaN
3,NaN,mmobilisations en cours,NaN,NaN,14 20,NaN,NaN,525 02,NaN
4,NaN,otal brut,NaN,NaN,2 473 81,NaN,NaN,1 630 91,NaN
5,NaN,mortissement,NaN,NaN,<1 139 760,NaN,NaN,<900 535,NaN
6,NaN,otal net,NaN,NaN,1 334 05,NaN,NaN,730 37,NaN
7,NaN,NaN,NaN,NaN,31/12/2014,NaN,NaN,31/12/2013,NaN
8,NaN,errain nu,NaN,NaN,1 321 60,NaN,NaN,1 321 600,NaN
9,NaN,errain bâti,NaN,NaN,230 40,NaN,NaN,230 400,NaN
10,NaN,âtiment industriel,NaN,NaN,6 135 48,NaN,NaN,5 910 243,NaN
11,NaN,"nstallations générales, agencements et aménag...",NaN,3 886 346,2 770 773,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,3 886 34,2 770 773,NaN,NaN,NaN
13,NaN,onstructions,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,nstallations techniques,NaN,NaN,4 208 07,NaN,NaN,3 917 739,NaN
15,NaN,atériels industriels,NaN,NaN,15 526 90,NaN,NaN,15 415 149,NaN
16,NaN,utillages industriels,NaN,NaN,1 687 32,NaN,NaN,1 642 586,NaN
17,NaN,atériels de transport des personnes,NaN,NaN,638 85,NaN,NaN,713 298,NaN
18,NaN,atériels de transport acquis en leasing,NaN,NaN,3 098 16,NaN,NaN,2 189 369,NaN
19,NaN,quipements de bureau,NaN,NaN,307 14,NaN,NaN,250 370,NaN
20,NaN,atériels informatiques,NaN,NaN,1 244 15,NaN,NaN,929 481,NaN
21,NaN,mmobilisations encours,NaN,NaN,1 378 97,NaN,NaN,596 382,NaN
22,NaN,otal brut,NaN,NaN,39 663 41,NaN,NaN,35 887 390,NaN
23,NaN,mortissement CORP,NaN,NaN,<13 900 515,NaN,NaN,<10 994 265>,NaN
24,NaN,otal net,NaN,NaN,25 762 89,NaN,NaN,24 893 125,NaN
25,NaN,NaN,NaN,NaN,31/12/2014,NaN,NaN,31/12/201,NaN
26,NaN,épôts et cautionnements,NaN,NaN,25 33,NaN,NaN,36 00,NaN
27,NaN,otal net,NaN,NaN,25 33,NaN,NaN,36 00,NaN
28,NaN,NaN,NaN,NaN,31/12/2014,NaN,NaN,31/12/2013,NaN
29,NaN,rais préliminaires,NaN,NaN,11 940 34,NaN,NaN,2 761 37,NaN
30,NaN,harges à répartir,NaN,NaN,1 227 65,NaN,NaN,8 638 34,NaN
31,NaN,otal brut,NaN,NaN,13 167 99,NaN,NaN,11 399 71,NaN
32,NaN,Résorptions,NaN,NaN,<10 998 566>,NaN,NaN,<8 938 842,NaN
33,NaN,otal net,NaN,NaN,2 169 42,NaN,NaN,2 460 87,NaN

------------------------------
Tableau 13

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,4.5Valeurs d’exploitation\r\rLe solde de ce co...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,NaN,NaN,NaN,NaN,otal net,NaN,NaN,1 886 007,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

------------------------------
Tableau 14

,4.5Valeurs d’exploitation\r\rLe solde de ce compte s'analyse de la manière suivante:\r\r31/12/201431/12/2013\rMatières premières5 605 2285 904 946\rEmballages1 650 5082 142 006\rStock en transit711 3542 422 660\rMatières consommables54 1363 902\rProduits finis et en-cours3 514 5223 328 731\rMarchandises6 4762 425 876\rStocks divers1 270 8391 248 763\rTotal brut12 813 06317 476 884\rProvision pour dépréciation de stock<208 841><2 212 131>\rTotal net12 604 22215 264 753\r\r4.6Clients et comptes rattachés\r\rLe détail des comptes clients se présente comme suit:\r\r31/12/201431/12/2013\rClients6 660 1305 021 453\rEffets à recevoir120 678109 663\rChèques à encaisser393 672694 723\rChèques & Effets impayés1 809 5291 437 414\rClients douteux54 019140 073\rTotal brut9 038 0287 403 325\rProvision pour dépréciation des créances<2 100 280><1 657 454>\rTotal net6 937 7485 745 871\r\r4.7Autres actifs courants\r\rLe solde de cette rubrique s'analyse de la manière suivante:\r\r31/12/201431/12/2013\rPersonnel183 457109 182\rFournisseurs / Avances308 554511 763\rEtat et collectivité publique1 827 7012 918 304\rEtat crédit d'impôt2 113 4971 423 519\rImpôt différé actif165 582975 366\rDébiteurs divers194 247245 996\rCompte de régularisation Actif701 942887 593\rSubvention à recevoir-788 628\rTotal brut5 494 9797 860 351\rProvision pour dépréciation débiteurs divers<410 159><204 159>\rTotal net5 084 8207 656 192\r\r\r4.8Liquidités et équivalents de liquidités\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rValeurs à l'encaissement731 152659 704\rBanques1 731 4352 725 318\rAutres Valeurs121 56559 595\rCaisses18 87825 857\rTotal brut2 603 0303 470 474\rProvision pour dépréciation des comptes bancaires<717 023>-\rTotal net1 886 0073 470 474,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,31/12/2014,NaN,NaN,31/12/2013,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Personnel,NaN,NaN,183 457,NaN,NaN,109 182,NaN,NaN,NaN,NaN
4,NaN,NaN,Fournisseurs / Avances,NaN,NaN,308 554,NaN,NaN,511 763,NaN,NaN,NaN,NaN
5,NaN,NaN,Etat et collectivité publique,NaN,NaN,1 827 701,NaN,NaN,2 918 304,NaN,NaN,NaN,NaN
6,NaN,NaN,Etat crédit d'impôt,NaN,NaN,2 113 497,NaN,NaN,1 423 519,NaN,NaN,NaN,NaN
7,NaN,NaN,Impôt différé actif,NaN,NaN,165 582,NaN,NaN,975 366,NaN,NaN,NaN,NaN
8,NaN,NaN,Débiteurs divers,NaN,NaN,194 247,NaN,NaN,245 996,NaN,NaN,NaN,NaN
9,NaN,NaN,Compte de régularisation Actif,NaN,NaN,701 942,NaN,NaN,887 593,NaN,NaN,NaN,NaN
10,NaN,NaN,Subvention à recevoir,NaN,NaN,-,NaN,NaN,788 628,NaN,NaN,NaN,NaN
11,NaN,NaN,Total brut,NaN,NaN,5 494 979,NaN,NaN,7 860 351,NaN,NaN,NaN,NaN
12,NaN,NaN,Provision pour dépréciation débiteurs divers,NaN,NaN,<410 159>,NaN,NaN,<204 159>,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,Total net,NaN,NaN,5 084 820,NaN,NaN,7 656 192,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

------------------------------
Tableau 15

,4.5Valeurs d’exploitation\r\rLe solde de ce compte s'analyse de la manière suivante:\r\r31/12/201431/12/2013\rMatières premières5 605 2285 904 946\rEmballages1 650 5082 142 006\rStock en transit711 3542 422 660\rMatières consommables54 1363 902\rProduits finis et en-cours3 514 5223 328 731\rMarchandises6 4762 425 876\rStocks divers1 270 8391 248 763\rTotal brut12 813 06317 476 884\rProvision pour dépréciation de stock<208 841><2 212 131>\rTotal net12 604 22215 264 753\r\r4.6Clients et comptes rattachés\r\rLe détail des comptes clients se présente comme suit:\r\r31/12/201431/12/2013\rClients6 660 1305 021 453\rEffets à recevoir120 678109 663\rChèques à encaisser393 672694 723\rChèques & Effets impayés1 809 5291 437 414\rClients douteux54 019140 073\rTotal brut9 038 0287 403 325\rProvision pour dépréciation des créances<2 100 280><1 657 454>\rTotal net6 937 7485 745 871\r\r4.7Autres actifs courants\r\rLe solde de cette rubrique s'analyse de la manière suivante:\r\r31/12/201431/12/2013\rPersonnel183 457109 182\rFournisseurs / Avances308 554511 763\rEtat et collectivité publique1 827 7012 918 304\rEtat crédit d'impôt2 113 4971 423 519\rImpôt différé actif165 582975 366\rDébiteurs divers194 247245 996\rCompte de régularisation Actif701 942887 593\rSubvention à recevoir-788 628\rTotal brut5 494 9797 860 351\rProvision pour dépréciation débiteurs divers<410 159><204 159>\rTotal net5 084 8207 656 192\r\r\r4.8Liquidités et équivalents de liquidités\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rValeurs à l'encaissement731 152659 704\rBanques1 731 4352 725 318\rAutres Valeurs121 56559 595\rCaisses18 87825 857\rTotal brut2 603 0303 470 474\rProvision pour dépréciation des comptes bancaires<717 023>-\rTotal net1 886 0073 470 474,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,31/12/2014,NaN,NaN,31/12/2013,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,aleurs à l'encaissement,NaN,NaN,731 152,NaN,NaN,659 704,NaN
3,NaN,anques,NaN,NaN,1 731 435,NaN,NaN,2 725 318,NaN
4,NaN,utres Valeurs,NaN,NaN,121 565,NaN,NaN,59 595,NaN
5,NaN,aisses,NaN,NaN,18 878,NaN,NaN,25 857,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,otal brut,NaN,NaN,2 603 030,NaN,NaN,3 470 474,NaN
8,NaN,rovision pour dépréciation des comptes bancaires,NaN,NaN,<717 023>,NaN,NaN,-,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,otal net,NaN,NaN,1 886 007,NaN,NaN,3 470 474,NaN

------------------------------
Tableau 16

,4.5Valeurs d’exploitation\r\rLe solde de ce compte s'analyse de la manière suivante:\r\r31/12/201431/12/2013\rMatières premières5 605 2285 904 946\rEmballages1 650 5082 142 006\rStock en transit711 3542 422 660\rMatières consommables54 1363 902\rProduits finis et en-cours3 514 5223 328 731\rMarchandises6 4762 425 876\rStocks divers1 270 8391 248 763\rTotal brut12 813 06317 476 884\rProvision pour dépréciation de stock<208 841><2 212 131>\rTotal net12 604 22215 264 753\r\r4.6Clients et comptes rattachés\r\rLe détail des comptes clients se présente comme suit:\r\r31/12/201431/12/2013\rClients6 660 1305 021 453\rEffets à recevoir120 678109 663\rChèques à encaisser393 672694 723\rChèques & Effets impayés1 809 5291 437 414\rClients douteux54 019140 073\rTotal brut9 038 0287 403 325\rProvision pour dépréciation des créances<2 100 280><1 657 454>\rTotal net6 937 7485 745 871\r\r4.7Autres actifs courants\r\rLe solde de cette rubrique s'analyse de la manière suivante:\r\r31/12/201431/12/2013\rPersonnel183 457109 182\rFournisseurs / Avances308 554511 763\rEtat et collectivité publique1 827 7012 918 304\rEtat crédit d'impôt2 113 4971 423 519\rImpôt différé actif165 582975 366\rDébiteurs divers194 247245 996\rCompte de régularisation Actif701 942887 593\rSubvention à recevoir-788 628\rTotal brut5 494 9797 860 351\rProvision pour dépréciation débiteurs divers<410 159><204 159>\rTotal net5 084 8207 656 192\r\r\r4.8Liquidités et équivalents de liquidités\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rValeurs à l'encaissement731 152659 704\rBanques1 731 4352 725 318\rAutres Valeurs121 56559 595\rCaisses18 87825 857\rTotal brut2 603 0303 470 474\rProvision pour dépréciation des comptes bancaires<717 023>-\rTotal net1 886 0073 470 474,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,31/12/2014,NaN,NaN,31/12/2013,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,atières premières,NaN,NaN,5 605 228,NaN,NaN,5 904 946,NaN
5,NaN,mballages,NaN,NaN,1 650 508,NaN,NaN,2 142 006,NaN
6,NaN,tock en transit,NaN,NaN,711 354,NaN,NaN,2 422 660,NaN
7,NaN,atières consommables,NaN,NaN,54 136,NaN,NaN,3 902,NaN
8,NaN,roduits finis et en-cours,NaN,NaN,3 514 522,NaN,NaN,3 328 731,NaN
9,NaN,archandises,NaN,NaN,6 476,NaN,NaN,2 425 876,NaN
10,NaN,tocks divers,NaN,NaN,1 270 839,NaN,NaN,1 248 763,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,otal brut,NaN,NaN,12 813 063,NaN,NaN,17 476 884,NaN
13,NaN,rovision pour dépréciation de stock,NaN,NaN,<208 841>,NaN,NaN,<2 212 131>,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,otal net,NaN,NaN,12 604 222,NaN,NaN,15 264 753,NaN

------------------------------
Tableau 17

,4.5Valeurs d’exploitation\r\rLe solde de ce compte s'analyse de la manière suivante:\r\r31/12/201431/12/2013\rMatières premières5 605 2285 904 946\rEmballages1 650 5082 142 006\rStock en transit711 3542 422 660\rMatières consommables54 1363 902\rProduits finis et en-cours3 514 5223 328 731\rMarchandises6 4762 425 876\rStocks divers1 270 8391 248 763\rTotal brut12 813 06317 476 884\rProvision pour dépréciation de stock<208 841><2 212 131>\rTotal net12 604 22215 264 753\r\r4.6Clients et comptes rattachés\r\rLe détail des comptes clients se présente comme suit:\r\r31/12/201431/12/2013\rClients6 660 1305 021 453\rEffets à recevoir120 678109 663\rChèques à encaisser393 672694 723\rChèques & Effets impayés1 809 5291 437 414\rClients douteux54 019140 073\rTotal brut9 038 0287 403 325\rProvision pour dépréciation des créances<2 100 280><1 657 454>\rTotal net6 937 7485 745 871\r\r4.7Autres actifs courants\r\rLe solde de cette rubrique s'analyse de la manière suivante:\r\r31/12/201431/12/2013\rPersonnel183 457109 182\rFournisseurs / Avances308 554511 763\rEtat et collectivité publique1 827 7012 918 304\rEtat crédit d'impôt2 113 4971 423 519\rImpôt différé actif165 582975 366\rDébiteurs divers194 247245 996\rCompte de régularisation Actif701 942887 593\rSubvention à recevoir-788 628\rTotal brut5 494 9797 860 351\rProvision pour dépréciation débiteurs divers<410 159><204 159>\rTotal net5 084 8207 656 192\r\r\r4.8Liquidités et équivalents de liquidités\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rValeurs à l'encaissement731 152659 704\rBanques1 731 4352 725 318\rAutres Valeurs121 56559 595\rCaisses18 87825 857\rTotal brut2 603 0303 470 474\rProvision pour dépréciation des comptes bancaires<717 023>-\rTotal net1 886 0073 470 474,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,31/12/2014,NaN,NaN,31/12/2013,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,lients,NaN,NaN,6 660 130,NaN,NaN,5 021 453,NaN
4,NaN,ffets à recevoir,NaN,NaN,120 678,NaN,NaN,109 663,NaN
5,NaN,hèques à encaisser,NaN,NaN,393 672,NaN,NaN,694 723,NaN
6,NaN,hèques & Effets impayés,NaN,NaN,1 809 529,NaN,NaN,1 437 414,NaN
7,NaN,lients douteux,NaN,NaN,54 019,NaN,NaN,140 073,NaN
8,NaN,otal brut,NaN,NaN,9 038 028,NaN,NaN,7 403 325,NaN
9,NaN,rovision pour dépréciation des créances,NaN,NaN,<2 100 280,NaN,NaN,<1 657 454>,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,otal net,NaN,NaN,6 937 748,NaN,NaN,5 745 871,NaN

------------------------------
Tableau 18

,"5CAPITAUX PROPRES ET PASSIFS\r\r\r5.1Capitaux propres\r\rLe solde de cette rubrique s'analyse comme suit :\r\r31/12/201431/12/2013\rCapital social4 846 8754 700 000\rAutres capitaux propres12 043 72411 686 522\rRéserves consolidées<11 026 566><4 498 074>\rRésultat de l'exercice consolidé<2 825 591><6 081 569>\rTotal3 038 4425 806 879\rIntérêts minoritaires139153 375\rTotal des capitaux propres3 038 5815 960 254\r\rL’assemblée générale extraordinaire («AGE») du 07/07/2014 de la société mère Land’Or SA a décidé\rl’augmentation du capital d’un montant de 146.875 DT, pour le porter de 4.700.000 DT à 4.846.875 DT, et\rce par l’incorporation d’une partie de la Prime d’émission.\rCette augmentation de capital est réalisée par voie de création de 146.875 actions nouvelles de un (1)\rDinarchacune,toutesnominatives.Ellessontautomatiquementattribuéesgratuitementaux\ractionnaires à raison de 1 action nouvelle pour 32 actions anciennes.\r\rLes actions nouvelles sont créées avec jouissance à compter du 01/01/2014. Elles seraient\rcomplètement assimilées aux actions anciennes à compter de cette date, jouiraient des mêmes droits\ret seraient soumises à toutes les dispositions statutaires\r\r5.2Emprunts\r\rLe solde de cette rubrique s'analyse comme suit :\r\r31/12/201431/12/2013\rCrédits BT3 008 8243 961 765\rCrédits UBCI150 000300 000\rCrédits BH4 038 4774 600 651\rCrédits ATTIJARI1 669 1721 936 148\rCrédits BTK2 000 0002 000 000\rDette de location financière2 113 084638 279\rTotal emprunt12 979 55713 436 843\r\rLa variation des crédits bancaires correspond au reclassement des échéances à moins d’un an parmi\rles passifs financiers à court terme.\r\r\r5.3Provisions\r\rLe solde de cette rubrique s'analyse comme suit :\r31/12/201431/12/2013\rProvision diverses641 470214 470\rTotal641 470214 470\r\r\rEn 2014, le Groupe Land’Or a constaté\r>Une provision pour congés et départ à la retraite pour une valeur de 200.000 DT.\r>Une provision pour risques et charges pour une valeur 227.000 DT.",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,31/12/2014,NaN,NaN,31/12/2013,NaN
1,NaN,rovision diverses,NaN,NaN,641 470,NaN,NaN,214 470,NaN
2,NaN,otal,NaN,NaN,641 470,NaN,NaN,214 470,NaN

------------------------------
Tableau 19

,"5CAPITAUX PROPRES ET PASSIFS\r\r\r5.1Capitaux propres\r\rLe solde de cette rubrique s'analyse comme suit :\r\r31/12/201431/12/2013\rCapital social4 846 8754 700 000\rAutres capitaux propres12 043 72411 686 522\rRéserves consolidées<11 026 566><4 498 074>\rRésultat de l'exercice consolidé<2 825 591><6 081 569>\rTotal3 038 4425 806 879\rIntérêts minoritaires139153 375\rTotal des capitaux propres3 038 5815 960 254\r\rL’assemblée générale extraordinaire («AGE») du 07/07/2014 de la société mère Land’Or SA a décidé\rl’augmentation du capital d’un montant de 146.875 DT, pour le porter de 4.700.000 DT à 4.846.875 DT, et\rce par l’incorporation d’une partie de la Prime d’émission.\rCette augmentation de capital est réalisée par voie de création de 146.875 actions nouvelles de un (1)\rDinarchacune,toutesnominatives.Ellessontautomatiquementattribuéesgratuitementaux\ractionnaires à raison de 1 action nouvelle pour 32 actions anciennes.\r\rLes actions nouvelles sont créées avec jouissance à compter du 01/01/2014. Elles seraient\rcomplètement assimilées aux actions anciennes à compter de cette date, jouiraient des mêmes droits\ret seraient soumises à toutes les dispositions statutaires\r\r5.2Emprunts\r\rLe solde de cette rubrique s'analyse comme suit :\r\r31/12/201431/12/2013\rCrédits BT3 008 8243 961 765\rCrédits UBCI150 000300 000\rCrédits BH4 038 4774 600 651\rCrédits ATTIJARI1 669 1721 936 148\rCrédits BTK2 000 0002 000 000\rDette de location financière2 113 084638 279\rTotal emprunt12 979 55713 436 843\r\rLa variation des crédits bancaires correspond au reclassement des échéances à moins d’un an parmi\rles passifs financiers à court terme.\r\r\r5.3Provisions\r\rLe solde de cette rubrique s'analyse comme suit :\r31/12/201431/12/2013\rProvision diverses641 470214 470\rTotal641 470214 470\r\r\rEn 2014, le Groupe Land’Or a constaté\r>Une provision pour congés et départ à la retraite pour une valeur de 200.000 DT.\r>Une provision pour risques et charges pour une valeur 227.000 DT.",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,31/12/2014,NaN,NaN,31/12/2013,NaN
1,NaN,rovision diverses,NaN,NaN,641 470,NaN,NaN,214 470,NaN
2,NaN,otal,NaN,NaN,641 470,NaN,NaN,214 470,NaN

------------------------------
Tableau 20

,5.4Fournisseurs et comptes rattachés\r\rLe solde de cette rubrique se détaille comme suit:\r\r31/12/201431/12/2013\rFournisseurs ordinaires locaux2 337 1182 959 794\rFournisseurs étrangers430 5544 091 602\rFournisseurs d'immobilisations425 965231 413\rFournisseurs Retenue de garantie102 809283 094\rFournisseurs Factures non parvenues884 5582 595 969\rEffets à payer & Obligations4 262 3585 478 452\rTotal8 443 36215 640 324\r\r\r5.5Autres passifs courants\r\rLe solde de cette rubrique s'analyse comme suit :\r\r\r31/12/201431/12/2013\rRémunération due au personnel1 319 355682 941\rEtat et Collectivités publiques1 315 014942 238\rCréditeurs divers587 932783 348\rCompte régul. Passif348 296460 080\rImpôt différé passif-1 082 134\rImpôt sur les Sociétés10 34311 284\rTotal3 580 9403 962 025\r\r5.6Concours bancaires et autres passifs financiers\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rEchéances à moins d'1 an BT1 041 176648 235\rEchéances à moins d'1 an UBCI150 000212 500\rEchéances à moins d'1 an BH589 583236 381\rEchéances à moins d'1 an ATTIJARI266 97663 852\rDettes de location financière à moins d’un an907 949403 450\rConcours bancaires6 720 9124 279 203\rFinancement de Stock et Préfinancement export4 225 0004 105 000\rPréfinancement factures3 480 0022 349 353\rFinancement en devise9 552 2158 622 904\rIntérêts courus186 791122 885\rTotal27 120 60421 043 763,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,Echéances à moins d'1 an BT,NaN,NaN,1 041 176,NaN,NaN,648 235,NaN
1,NaN,Echéances à moins d'1 an UBCI,NaN,NaN,150 000,NaN,NaN,212 500,NaN
2,NaN,Echéances à moins d'1 an BH,NaN,NaN,589 583,NaN,NaN,236 381,NaN
3,NaN,Echéances à moins d'1 an ATTIJARI,NaN,NaN,266 976,NaN,NaN,63 852,NaN
4,NaN,Dettes de location financière à moins d’un an,NaN,NaN,907 949,NaN,NaN,403 450,NaN
5,NaN,Concours bancaires,NaN,NaN,6 720 912,NaN,NaN,4 279 203,NaN
6,NaN,Financement de Stock et Préfinancement export,NaN,NaN,4 225 000,NaN,NaN,4 105 000,NaN
7,NaN,Préfinancement factures,NaN,NaN,3 480 002,NaN,NaN,2 349 353,NaN
8,NaN,Financement en devise,NaN,NaN,9 552 215,NaN,NaN,8 622 904,NaN
9,NaN,Intérêts courus,NaN,NaN,186 791,NaN,NaN,122 885,NaN

------------------------------
Tableau 21

,5.4Fournisseurs et comptes rattachés\r\rLe solde de cette rubrique se détaille comme suit:\r\r31/12/201431/12/2013\rFournisseurs ordinaires locaux2 337 1182 959 794\rFournisseurs étrangers430 5544 091 602\rFournisseurs d'immobilisations425 965231 413\rFournisseurs Retenue de garantie102 809283 094\rFournisseurs Factures non parvenues884 5582 595 969\rEffets à payer & Obligations4 262 3585 478 452\rTotal8 443 36215 640 324\r\r\r5.5Autres passifs courants\r\rLe solde de cette rubrique s'analyse comme suit :\r\r\r31/12/201431/12/2013\rRémunération due au personnel1 319 355682 941\rEtat et Collectivités publiques1 315 014942 238\rCréditeurs divers587 932783 348\rCompte régul. Passif348 296460 080\rImpôt différé passif-1 082 134\rImpôt sur les Sociétés10 34311 284\rTotal3 580 9403 962 025\r\r5.6Concours bancaires et autres passifs financiers\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rEchéances à moins d'1 an BT1 041 176648 235\rEchéances à moins d'1 an UBCI150 000212 500\rEchéances à moins d'1 an BH589 583236 381\rEchéances à moins d'1 an ATTIJARI266 97663 852\rDettes de location financière à moins d’un an907 949403 450\rConcours bancaires6 720 9124 279 203\rFinancement de Stock et Préfinancement export4 225 0004 105 000\rPréfinancement factures3 480 0022 349 353\rFinancement en devise9 552 2158 622 904\rIntérêts courus186 791122 885\rTotal27 120 60421 043 763,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,31/12/2014,NaN,NaN,31/12/2013,NaN
1,NaN,Fournisseurs ordinaires locaux,NaN,NaN,2 337 118,NaN,NaN,2 959 794,NaN
2,NaN,Fournisseurs étrangers,NaN,NaN,430 554,NaN,NaN,4 091 602,NaN
3,NaN,Fournisseurs d'immobilisations,NaN,NaN,425 965,NaN,NaN,231 413,NaN
4,NaN,Fournisseurs Retenue de garantie,NaN,NaN,102 809,NaN,NaN,283 094,NaN
5,NaN,Fournisseurs Factures non parvenues,NaN,NaN,884 558,NaN,NaN,2 595 969,NaN
6,NaN,Effets à payer & Obligations,NaN,NaN,4 262 358,NaN,NaN,5 478 452,NaN
7,NaN,Total,NaN,NaN,8 443 362,NaN,NaN,15 640 324,NaN
8,NaN,NaN,NaN,NaN,31/12/201,NaN,NaN,31/12/201,NaN
9,NaN,Rémunération due au personnel,NaN,NaN,1 319 35,NaN,NaN,682 94,NaN
10,NaN,Etat et Collectivités publiques,NaN,NaN,1 315 01,NaN,NaN,942 23,NaN
11,NaN,Créditeurs divers,NaN,NaN,587 93,NaN,NaN,783 34,NaN
12,NaN,Compte régul. Passif,NaN,NaN,348 29,NaN,NaN,460 08,NaN
13,NaN,Impôt différé passif,NaN,NaN,NaN,NaN,NaN,1 082 13,NaN
14,NaN,Impôt sur les Sociétés,NaN,NaN,10 34,NaN,NaN,11 28,NaN
15,NaN,Total,NaN,NaN,3 580 94,NaN,NaN,3 962 02,NaN
16,NaN,Echéances à moins d'1 an BT,NaN,NaN,1 041 176,NaN,NaN,648 235,NaN
17,NaN,Echéances à moins d'1 an UBCI,NaN,NaN,150 000,NaN,NaN,212 500,NaN
18,NaN,Echéances à moins d'1 an BH,NaN,NaN,589 583,NaN,NaN,236 381,NaN
19,NaN,Echéances à moins d'1 an ATTIJARI,NaN,NaN,266 976,NaN,NaN,63 852,NaN
20,NaN,Dettes de location financière à moins d’un an,NaN,NaN,907 949,NaN,NaN,403 450,NaN
21,NaN,Concours bancaires,NaN,NaN,6 720 912,NaN,NaN,4 279 203,NaN
22,NaN,Financement de Stock et Préfinancement export,NaN,NaN,4 225 000,NaN,NaN,4 105 000,NaN
23,NaN,Préfinancement factures,NaN,NaN,3 480 002,NaN,NaN,2 349 353,NaN
24,NaN,Financement en devise,NaN,NaN,9 552 215,NaN,NaN,8 622 904,NaN
25,NaN,Intérêts courus,NaN,NaN,186 791,NaN,NaN,122 885,NaN

------------------------------
Tableau 22

,5.4Fournisseurs et comptes rattachés\r\rLe solde de cette rubrique se détaille comme suit:\r\r31/12/201431/12/2013\rFournisseurs ordinaires locaux2 337 1182 959 794\rFournisseurs étrangers430 5544 091 602\rFournisseurs d'immobilisations425 965231 413\rFournisseurs Retenue de garantie102 809283 094\rFournisseurs Factures non parvenues884 5582 595 969\rEffets à payer & Obligations4 262 3585 478 452\rTotal8 443 36215 640 324\r\r\r5.5Autres passifs courants\r\rLe solde de cette rubrique s'analyse comme suit :\r\r\r31/12/201431/12/2013\rRémunération due au personnel1 319 355682 941\rEtat et Collectivités publiques1 315 014942 238\rCréditeurs divers587 932783 348\rCompte régul. Passif348 296460 080\rImpôt différé passif-1 082 134\rImpôt sur les Sociétés10 34311 284\rTotal3 580 9403 962 025\r\r5.6Concours bancaires et autres passifs financiers\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rEchéances à moins d'1 an BT1 041 176648 235\rEchéances à moins d'1 an UBCI150 000212 500\rEchéances à moins d'1 an BH589 583236 381\rEchéances à moins d'1 an ATTIJARI266 97663 852\rDettes de location financière à moins d’un an907 949403 450\rConcours bancaires6 720 9124 279 203\rFinancement de Stock et Préfinancement export4 225 0004 105 000\rPréfinancement factures3 480 0022 349 353\rFinancement en devise9 552 2158 622 904\rIntérêts courus186 791122 885\rTotal27 120 60421 043 763,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,31/12/2014,NaN,NaN,31/12/2013,NaN
1,NaN,Fournisseurs ordinaires locaux,NaN,NaN,2 337 118,NaN,NaN,2 959 794,NaN
2,NaN,Fournisseurs étrangers,NaN,NaN,430 554,NaN,NaN,4 091 602,NaN
3,NaN,Fournisseurs d'immobilisations,NaN,NaN,425 965,NaN,NaN,231 413,NaN
4,NaN,Fournisseurs Retenue de garantie,NaN,NaN,102 809,NaN,NaN,283 094,NaN
5,NaN,Fournisseurs Factures non parvenues,NaN,NaN,884 558,NaN,NaN,2 595 969,NaN
6,NaN,Effets à payer & Obligations,NaN,NaN,4 262 358,NaN,NaN,5 478 452,NaN
7,NaN,Total,NaN,NaN,8 443 362,NaN,NaN,15 640 324,NaN

------------------------------
Tableau 23

,5.4Fournisseurs et comptes rattachés\r\rLe solde de cette rubrique se détaille comme suit:\r\r31/12/201431/12/2013\rFournisseurs ordinaires locaux2 337 1182 959 794\rFournisseurs étrangers430 5544 091 602\rFournisseurs d'immobilisations425 965231 413\rFournisseurs Retenue de garantie102 809283 094\rFournisseurs Factures non parvenues884 5582 595 969\rEffets à payer & Obligations4 262 3585 478 452\rTotal8 443 36215 640 324\r\r\r5.5Autres passifs courants\r\rLe solde de cette rubrique s'analyse comme suit :\r\r\r31/12/201431/12/2013\rRémunération due au personnel1 319 355682 941\rEtat et Collectivités publiques1 315 014942 238\rCréditeurs divers587 932783 348\rCompte régul. Passif348 296460 080\rImpôt différé passif-1 082 134\rImpôt sur les Sociétés10 34311 284\rTotal3 580 9403 962 025\r\r5.6Concours bancaires et autres passifs financiers\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rEchéances à moins d'1 an BT1 041 176648 235\rEchéances à moins d'1 an UBCI150 000212 500\rEchéances à moins d'1 an BH589 583236 381\rEchéances à moins d'1 an ATTIJARI266 97663 852\rDettes de location financière à moins d’un an907 949403 450\rConcours bancaires6 720 9124 279 203\rFinancement de Stock et Préfinancement export4 225 0004 105 000\rPréfinancement factures3 480 0022 349 353\rFinancement en devise9 552 2158 622 904\rIntérêts courus186 791122 885\rTotal27 120 60421 043 763,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,31/12/201,NaN,NaN,31/12/201,NaN
1,NaN,Rémunération due au personnel,NaN,NaN,1 319 35,NaN,NaN,682 94,NaN
2,NaN,Etat et Collectivités publiques,NaN,NaN,1 315 01,NaN,NaN,942 23,NaN
3,NaN,Créditeurs divers,NaN,NaN,587 93,NaN,NaN,783 34,NaN
4,NaN,Compte régul. Passif,NaN,NaN,348 29,NaN,NaN,460 08,NaN
5,NaN,Impôt différé passif,NaN,NaN,NaN,NaN,NaN,1 082 13,NaN
6,NaN,Impôt sur les Sociétés,NaN,NaN,10 34,NaN,NaN,11 28,NaN
7,NaN,Total,NaN,NaN,3 580 94,NaN,NaN,3 962 02,NaN

------------------------------
Tableau 24

,6COMPTE DE RESULTAT\r\r\r6.1Produits d’exploitation\r\rLe solde de cette rubrique se détaille comme suit :\r\r\r31/12/201431/12/2013\rChiffres d’affaires67 000 51170 263 927\rAutres Produits d’Exploitation184 722867 299\rTotal67 185 23371 131 227\r\r6.2Achats Consommés\r\rLe solde de cette rubrique se détaille comme suit :\r31/12/201431/12/2013\rAchats matières premières29 425 61638 362 633\rAchats emballages et autres matières consommables6 372 7409 019 203\rAchats de marchandises497 799374 266\rAchat en transit711 3541 214 841\rVariation de stock en transit<711 354><1 214 841>\rVariation de Stocks5 832 998<357 356>\rTotal42 129 15347 398 746\r\r\r6.3Autres achats\r\rCe poste se détaille comme suit :\r\r31/12/201431/12/2013\rAutres achats non stockables2 204 6761 858 603\rAchats stockables724 7951 811 727\rTotal2 929 4713 670 330\r\r\r6.4Charges de personnel\r\rCe poste se détaille comme suit :\r\r31/12/201431/12/2013\rSalaires & compléments de salaires7 725 0156 633 415\rCharges sociales légales1 248 0181 172 481\rTotal8 973 0337 805 895\r\r\r6.5Dotations aux amortissements et aux provisions\r\rLe solde de cette rubrique se détaille comme suit :\r\rDotations aux amortissements5 576 1804 192 296\rDotations aux provisions2 710 1122 568 428\rTotal8 286 2926 760 724\rReprise sur Provision<3 101 006><256892>\rTotal net5 185 2866 503 832,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,31/12/2014,NaN,NaN,31/12/201,NaN
1,NaN,Achats matières premières,NaN,NaN,29 425 616,NaN,NaN,38 362 63,NaN
2,NaN,Achats emballages et autres matières consommables,NaN,NaN,6 372 740,NaN,NaN,9 019 20,NaN
3,NaN,Achats de marchandises,NaN,NaN,497 799,NaN,NaN,374 26,NaN
4,NaN,Achat en transit,NaN,NaN,711 354,NaN,NaN,1 214 84,NaN
5,NaN,Variation de stock en transit,NaN,NaN,<711 354>,NaN,NaN,<1 214 841,NaN
6,NaN,Variation de Stocks,NaN,NaN,5 832 998,NaN,NaN,<357 356,NaN
7,NaN,Total,NaN,NaN,42 129 153,NaN,NaN,47 398 74,NaN
8,NaN,2 204 67,NaN,NaN,1 858 60,NaN,NaN,NaN,NaN
9,NaN,724 79,NaN,NaN,1 811 72,NaN,NaN,NaN,NaN
10,NaN,2 929 47,NaN,NaN,3 670 33,NaN,NaN,NaN,NaN
11,NaN,2 710 11,NaN,NaN,NaN,NaN,NaN,NaN,NaN

------------------------------
Tableau 25

,6COMPTE DE RESULTAT\r\r\r6.1Produits d’exploitation\r\rLe solde de cette rubrique se détaille comme suit :\r\r\r31/12/201431/12/2013\rChiffres d’affaires67 000 51170 263 927\rAutres Produits d’Exploitation184 722867 299\rTotal67 185 23371 131 227\r\r6.2Achats Consommés\r\rLe solde de cette rubrique se détaille comme suit :\r31/12/201431/12/2013\rAchats matières premières29 425 61638 362 633\rAchats emballages et autres matières consommables6 372 7409 019 203\rAchats de marchandises497 799374 266\rAchat en transit711 3541 214 841\rVariation de stock en transit<711 354><1 214 841>\rVariation de Stocks5 832 998<357 356>\rTotal42 129 15347 398 746\r\r\r6.3Autres achats\r\rCe poste se détaille comme suit :\r\r31/12/201431/12/2013\rAutres achats non stockables2 204 6761 858 603\rAchats stockables724 7951 811 727\rTotal2 929 4713 670 330\r\r\r6.4Charges de personnel\r\rCe poste se détaille comme suit :\r\r31/12/201431/12/2013\rSalaires & compléments de salaires7 725 0156 633 415\rCharges sociales légales1 248 0181 172 481\rTotal8 973 0337 805 895\r\r\r6.5Dotations aux amortissements et aux provisions\r\rLe solde de cette rubrique se détaille comme suit :\r\rDotations aux amortissements5 576 1804 192 296\rDotations aux provisions2 710 1122 568 428\rTotal8 286 2926 760 724\rReprise sur Provision<3 101 006><256892>\rTotal net5 185 2866 503 832,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,NaN,2 204 67,NaN,NaN,1 858 60,NaN
1,NaN,724 79,NaN,NaN,1 811 72,NaN
2,NaN,2 929 47,NaN,NaN,3 670 33,NaN

------------------------------
Tableau 26

,6COMPTE DE RESULTAT\r\r\r6.1Produits d’exploitation\r\rLe solde de cette rubrique se détaille comme suit :\r\r\r31/12/201431/12/2013\rChiffres d’affaires67 000 51170 263 927\rAutres Produits d’Exploitation184 722867 299\rTotal67 185 23371 131 227\r\r6.2Achats Consommés\r\rLe solde de cette rubrique se détaille comme suit :\r31/12/201431/12/2013\rAchats matières premières29 425 61638 362 633\rAchats emballages et autres matières consommables6 372 7409 019 203\rAchats de marchandises497 799374 266\rAchat en transit711 3541 214 841\rVariation de stock en transit<711 354><1 214 841>\rVariation de Stocks5 832 998<357 356>\rTotal42 129 15347 398 746\r\r\r6.3Autres achats\r\rCe poste se détaille comme suit :\r\r31/12/201431/12/2013\rAutres achats non stockables2 204 6761 858 603\rAchats stockables724 7951 811 727\rTotal2 929 4713 670 330\r\r\r6.4Charges de personnel\r\rCe poste se détaille comme suit :\r\r31/12/201431/12/2013\rSalaires & compléments de salaires7 725 0156 633 415\rCharges sociales légales1 248 0181 172 481\rTotal8 973 0337 805 895\r\r\r6.5Dotations aux amortissements et aux provisions\r\rLe solde de cette rubrique se détaille comme suit :\r\rDotations aux amortissements5 576 1804 192 296\rDotations aux provisions2 710 1122 568 428\rTotal8 286 2926 760 724\rReprise sur Provision<3 101 006><256892>\rTotal net5 185 2866 503 832,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,31/12/2014,NaN,NaN,31/12/201,NaN
1,NaN,Achats matières premières,NaN,NaN,29 425 616,NaN,NaN,38 362 63,NaN
2,NaN,Achats emballages et autres matières consommables,NaN,NaN,6 372 740,NaN,NaN,9 019 20,NaN
3,NaN,Achats de marchandises,NaN,NaN,497 799,NaN,NaN,374 26,NaN
4,NaN,Achat en transit,NaN,NaN,711 354,NaN,NaN,1 214 84,NaN
5,NaN,Variation de stock en transit,NaN,NaN,<711 354>,NaN,NaN,<1 214 841,NaN
6,NaN,Variation de Stocks,NaN,NaN,5 832 998,NaN,NaN,<357 356,NaN
7,NaN,Total,NaN,NaN,42 129 153,NaN,NaN,47 398 74,NaN

------------------------------
Tableau 27

,6.6Autres charges d'exploitation\r\rLe solde de ce compte se détaille comme suit :\r\r31/12/201431/12/2013\rAutres Services extérieurs6 158 3817 219 575\rServices extérieurs ACE2 257 2771 778 482\rCharges diverses ordinaires132 657108 866\rImpôts et taxes410 405420 707\rTotal8 958 7209 527 630\r\r\r\r\r6.7Charges financières\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rIntérêts sur crédits bancaires919 751656 773\rAutres charges d’intérêts intérêts130 59468 351\rDifférence de change<277 115>698 369\rAutres frais et commissions sur prestations de services1 893 4591 730 870\rTotal2 666 6893 154 363\r\r\r6.8Autres gains ordinaires\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rProduits Divers Ordinaires136 27173 782\rProduits sur cession d’immobilisations276 32894 332\rReprise sur provision243 697\rTransfert de charges33 143\r\rTotal445 742411 811\r\r6.9Autres Pertes ordinaires :\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rPénalités24 3095 227\rPertes sur créances irrécouvrables31 819-\rTotal56 1285 227\r\r6.10Impôts sur les sociétés\r\rLe solde de cette rubrique se détaille comme suit :\r\r\r31/12/201431/12/2013\rImpôt sur les sociétés155 881403 158\rImpôt différé<272 350><253 357>\rTotal<116 469>149 801,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,31/12/2014,NaN,NaN,31/12/2013,NaN
1,NaN,Intérêts sur crédits bancaires,NaN,NaN,919 751,NaN,NaN,656 773,NaN
2,NaN,Autres charges d’intérêts intérêts,NaN,NaN,130 594,NaN,NaN,68 351,NaN
3,NaN,Différence de change,NaN,NaN,<277 115>,NaN,NaN,698 369,NaN
4,NaN,Autres frais et commissions sur prestations de...,NaN,NaN,1 893 459,NaN,NaN,1 730 870,NaN
5,NaN,Total,NaN,NaN,2 666 689,NaN,NaN,3 154 363,NaN
6,NaN,NaN,NaN,NaN,276 328,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,33 143,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,31/12/2014,NaN,NaN,31/12/2013,NaN
10,NaN,Pénalités,NaN,NaN,24 309,NaN,NaN,5 227,NaN
11,NaN,Pertes sur créances irrécouvrables,NaN,NaN,31 819,NaN,NaN,-,NaN
12,NaN,Total,NaN,NaN,56 128,NaN,NaN,5 227,NaN
13,NaN,NaN,NaN,NaN,31/12/2014,NaN,NaN,31/12/201,NaN
14,NaN,Impôt sur les sociétés,NaN,NaN,155 881,NaN,NaN,403 15,NaN
15,NaN,Impôt différé,NaN,NaN,<272 350>,NaN,NaN,<253 357,NaN
16,NaN,Total,NaN,NaN,<116 469>,NaN,NaN,149 80,NaN

------------------------------
Tableau 28

,6.6Autres charges d'exploitation\r\rLe solde de ce compte se détaille comme suit :\r\r31/12/201431/12/2013\rAutres Services extérieurs6 158 3817 219 575\rServices extérieurs ACE2 257 2771 778 482\rCharges diverses ordinaires132 657108 866\rImpôts et taxes410 405420 707\rTotal8 958 7209 527 630\r\r\r\r\r6.7Charges financières\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rIntérêts sur crédits bancaires919 751656 773\rAutres charges d’intérêts intérêts130 59468 351\rDifférence de change<277 115>698 369\rAutres frais et commissions sur prestations de services1 893 4591 730 870\rTotal2 666 6893 154 363\r\r\r6.8Autres gains ordinaires\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rProduits Divers Ordinaires136 27173 782\rProduits sur cession d’immobilisations276 32894 332\rReprise sur provision243 697\rTransfert de charges33 143\r\rTotal445 742411 811\r\r6.9Autres Pertes ordinaires :\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rPénalités24 3095 227\rPertes sur créances irrécouvrables31 819-\rTotal56 1285 227\r\r6.10Impôts sur les sociétés\r\rLe solde de cette rubrique se détaille comme suit :\r\r\r31/12/201431/12/2013\rImpôt sur les sociétés155 881403 158\rImpôt différé<272 350><253 357>\rTotal<116 469>149 801,Unnamed: 0,Unnamed: 1
0,NaN,276 328,NaN
1,NaN,NaN,NaN
2,NaN,33 143,NaN

------------------------------
Tableau 29

,6.6Autres charges d'exploitation\r\rLe solde de ce compte se détaille comme suit :\r\r31/12/201431/12/2013\rAutres Services extérieurs6 158 3817 219 575\rServices extérieurs ACE2 257 2771 778 482\rCharges diverses ordinaires132 657108 866\rImpôts et taxes410 405420 707\rTotal8 958 7209 527 630\r\r\r\r\r6.7Charges financières\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rIntérêts sur crédits bancaires919 751656 773\rAutres charges d’intérêts intérêts130 59468 351\rDifférence de change<277 115>698 369\rAutres frais et commissions sur prestations de services1 893 4591 730 870\rTotal2 666 6893 154 363\r\r\r6.8Autres gains ordinaires\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rProduits Divers Ordinaires136 27173 782\rProduits sur cession d’immobilisations276 32894 332\rReprise sur provision243 697\rTransfert de charges33 143\r\rTotal445 742411 811\r\r6.9Autres Pertes ordinaires :\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rPénalités24 3095 227\rPertes sur créances irrécouvrables31 819-\rTotal56 1285 227\r\r6.10Impôts sur les sociétés\r\rLe solde de cette rubrique se détaille comme suit :\r\r\r31/12/201431/12/2013\rImpôt sur les sociétés155 881403 158\rImpôt différé<272 350><253 357>\rTotal<116 469>149 801,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,31/12/2014,NaN,NaN,31/12/201,NaN
1,NaN,Impôt sur les sociétés,NaN,NaN,155 881,NaN,NaN,403 15,NaN
2,NaN,Impôt différé,NaN,NaN,<272 350>,NaN,NaN,<253 357,NaN
3,NaN,Total,NaN,NaN,<116 469>,NaN,NaN,149 80,NaN

------------------------------
Tableau 30

,6.6Autres charges d'exploitation\r\rLe solde de ce compte se détaille comme suit :\r\r31/12/201431/12/2013\rAutres Services extérieurs6 158 3817 219 575\rServices extérieurs ACE2 257 2771 778 482\rCharges diverses ordinaires132 657108 866\rImpôts et taxes410 405420 707\rTotal8 958 7209 527 630\r\r\r\r\r6.7Charges financières\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rIntérêts sur crédits bancaires919 751656 773\rAutres charges d’intérêts intérêts130 59468 351\rDifférence de change<277 115>698 369\rAutres frais et commissions sur prestations de services1 893 4591 730 870\rTotal2 666 6893 154 363\r\r\r6.8Autres gains ordinaires\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rProduits Divers Ordinaires136 27173 782\rProduits sur cession d’immobilisations276 32894 332\rReprise sur provision243 697\rTransfert de charges33 143\r\rTotal445 742411 811\r\r6.9Autres Pertes ordinaires :\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rPénalités24 3095 227\rPertes sur créances irrécouvrables31 819-\rTotal56 1285 227\r\r6.10Impôts sur les sociétés\r\rLe solde de cette rubrique se détaille comme suit :\r\r\r31/12/201431/12/2013\rImpôt sur les sociétés155 881403 158\rImpôt différé<272 350><253 357>\rTotal<116 469>149 801,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,31/12/2014,NaN,NaN,31/12/2013,NaN
1,NaN,Intérêts sur crédits bancaires,NaN,NaN,919 751,NaN,NaN,656 773,NaN
2,NaN,Autres charges d’intérêts intérêts,NaN,NaN,130 594,NaN,NaN,68 351,NaN
3,NaN,Différence de change,NaN,NaN,<277 115>,NaN,NaN,698 369,NaN
4,NaN,Autres frais et commissions sur prestations de...,NaN,NaN,1 893 459,NaN,NaN,1 730 870,NaN
5,NaN,Total,NaN,NaN,2 666 689,NaN,NaN,3 154 363,NaN

------------------------------
Tableau 31

,6.6Autres charges d'exploitation\r\rLe solde de ce compte se détaille comme suit :\r\r31/12/201431/12/2013\rAutres Services extérieurs6 158 3817 219 575\rServices extérieurs ACE2 257 2771 778 482\rCharges diverses ordinaires132 657108 866\rImpôts et taxes410 405420 707\rTotal8 958 7209 527 630\r\r\r\r\r6.7Charges financières\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rIntérêts sur crédits bancaires919 751656 773\rAutres charges d’intérêts intérêts130 59468 351\rDifférence de change<277 115>698 369\rAutres frais et commissions sur prestations de services1 893 4591 730 870\rTotal2 666 6893 154 363\r\r\r6.8Autres gains ordinaires\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rProduits Divers Ordinaires136 27173 782\rProduits sur cession d’immobilisations276 32894 332\rReprise sur provision243 697\rTransfert de charges33 143\r\rTotal445 742411 811\r\r6.9Autres Pertes ordinaires :\r\rLe solde de cette rubrique se détaille comme suit :\r\r31/12/201431/12/2013\rPénalités24 3095 227\rPertes sur créances irrécouvrables31 819-\rTotal56 1285 227\r\r6.10Impôts sur les sociétés\r\rLe solde de cette rubrique se détaille comme suit :\r\r\r31/12/201431/12/2013\rImpôt sur les sociétés155 881403 158\rImpôt différé<272 350><253 357>\rTotal<116 469>149 801,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,31/12/2014,NaN,NaN,31/12/2013,NaN
1,NaN,Pénalités,NaN,NaN,24 309,NaN,NaN,5 227,NaN
2,NaN,Pertes sur créances irrécouvrables,NaN,NaN,31 819,NaN,NaN,-,NaN
3,NaN,Total,NaN,NaN,56 128,NaN,NaN,5 227,NaN