In [5]:
import pickle
import pandas as pd

In [16]:
# Chemin du fichier .pkl
file_path = "output/GROUPE_DELICE/DELICE_tables.pkl"

# Charger les données
with open(file_path, "rb") as f:
    data = pickle.load(f)

# Afficher tous les tableaux de toutes les années
for year, tables in data.items():
    print("\n" + "=" * 60)
    print(f"📅 Année : {year} | {len(tables)} tableau(x)")
    print("=" * 60)

    for i, df in enumerate(tables, start=1):
        print(f"\n--- Tableau {i} ---")
        display(df)

============================================================
📅 Année : 2014 | 16 tableau(x)
============================================================

--- Tableau 1 ---

,Unnamed: 0,Unnamed: 1,Unnamed: 2,31.12.2013,31.12.2013.1
0,Actifs,NaN,31.12.2014,NaN,NaN
1,NaN,NaN,NaN,Retraité*,Publié
2,Actifs non courants,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN
4,Immobilisations incorporelles,NaN,2 518 600,2 139 982,2 139 982
...,...,...,...,...,...
40,-Provisions/ liquidités,NaN,-,(238 748),(238 748)
41,NaN,(10)*,20 486 536,25 208 370,26 679 729
42,NaN,NaN,NaN,NaN,NaN
43,Total des actifs courants,NaN,175 522 181,156 552 525,167 434 067
44,Total Actifs,NaN,382 180 380,319 488 915,330 370 457

--- Tableau 2 ---

,Unnamed: 0,Unnamed: 1,Unnamed: 2,31.12.2013,31.12.2013.1
0,Capitaux propres et passifs,NaN,31.12.2014,NaN,NaN
1,NaN,NaN,NaN,Retraité*,Publié
2,NaN,NaN,NaN,NaN,NaN
3,Capital social,NaN,549 072 620,549 072 620,549 072 620
4,Réserves de restructuration,NaN,(472 190 804),(472 190 804),(472 190 804)
...,...,...,...,...,...
40,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN
42,Total des passifs,NaN,249 787 908,212 254 711,223 136 254
43,NaN,NaN,NaN,NaN,NaN
44,Total Capitaux propres et passifs,NaN,382 180 380,319 488 915,330 370 457

--- Tableau 3 ---

,Unnamed: 0,Unnamed: 1,Unnamed: 2,31.12.2013,31.12.2013.1
0,NaN,NaN,31.12.2014,NaN,NaN
1,NaN,NaN,NaN,Retraité*,Publié
2,NaN,NaN,NaN,NaN,NaN
3,Revenus,(17)*,647 588 213,560 723 738,529 773 045
4,Autres produits d'exploitation,(18)*,12 807 509,6 982 368,50 241 196
...,...,...,...,...,...
27,Résultat des activités ordinaires après impôt,NaN,25 256 495,24 637 562,24 637 562
28,Part revenant aux intérêts minoritaires,(11),(569 175),(364 004),(364 004)
29,Résultat net consolidé (Part revenant au groupe),NaN,25 825 670,25 001 566,25 001 566
30,Nombre moyen des actions,NaN,54 907 262,54 907 262,54 907 262
31,Résultat par action,(28),"0,470","0,455","0,455"

--- Tableau 4 ---

,Unnamed: 0,Unnamed: 1,31.12.2014,31.12.2013
0,Résultat net (Groupe),NaN,25 825 670,25 001 566
1,Ajustement pour:,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,*Part revenant aux intérêts minoritaires,(11),(569 175),(364 004)
4,"*Amortissements, Provisions & Reprises de prov...",(21),25 667 082,18 126 730
...,...,...,...,...
33,Variation de trésorerie,NaN,289 728,-5 046 794
34,NaN,NaN,NaN,NaN
35,Trésorerie au début de l’exercice,(27),11 253 407,16 300 200
36,NaN,NaN,NaN,NaN
37,Trésorerie à la clôture de l’exercice,(27),11 543 135,11 253 407

--- Tableau 5 ---

,Société,% de contrôle,% d’intérêts groupe,Type de contrôle,Méthode de comptabilisation
0,DELICE Holding,100%,100%,Société mère,NaN
1,CLC,"99,72%","99,72%",Contrôle exclusif,Intégration globale
2,CLN,"96,98%","96,71%",Contrôle exclusif,Intégration globale
3,CLSB,"99,99%","99,72%",Contrôle exclusif,Intégration globale
4,SBC,"99,99%","99,99%",Contrôle exclusif,Intégration globale
5,CF,"57,50%","57,49%",Contrôle exclusif,Intégration globale
6,Delta plastic,"99,99%","99,99%",Contrôle exclusif,Intégration globale

--- Tableau 6 ---

,La valeur nette des immobilisations incorporelles et corporelles s’élève à 186 734 737 dinars au 31 décembre 2014 et se détaille comme suit :,Unnamed: 0,Unnamed: 1
0,Cession et,NaN,NaN
1,Amortissements Montants en TND Valeur Brute En...,VCN 2013,VCN 2014
2,Dec 2013 2014 Dec 2014 cumulés 2013 2014 / ces...,NaN,NaN
3,2014,NaN,NaN
4,Logiciels 1 865 366 160 344 2 025 710 1 701 33...,164 032,195 038
...,...,...,...
23,Provisions constituées - - - - 1 716 1...,(1 716 120),(1 886 614)
24,Total immobilisations corporelles 276 575 028 ...,144 478 054,186 093 729
25,Total immobilisations incorporelles et,NaN,NaN
26,278 715 010 123 733 910 61 569 925 340 878 999...,144 869 780,186 734 737
27,corporelles,NaN,NaN

--- Tableau 7 ---

,Libellé Solde au 31/12/2014,Solde au 31/12/2013,Solde au 31/12/2013.1
0,NaN,Retraité**,Publié
1,NaN,NaN,NaN
2,Clients locaux 14 003 205,13 033 087,27 959 357
3,Clients douteux 2 372 830,2 384 291,2 384 291
4,Clients effets escomptés non échus 2 879 483,1 252 081,NaN
...,...,...,...
28,Etat retenue à la source 382 889,244 698,244 698
29,Charges constatées d'avance 217 749,221 371,221 371
30,Dépôts et cautionnements 70 578,39 197,39 197
31,Comptes d'attente actif 16 358,27 213,27 213
32,Personnel avances et acomptes 53 382,13 781,13 781

--- Tableau 8 ---

,Total 20 486 536,25 447 118,26 918 477
0,**Les montants relatifs à l’exercice clos le 3...,NaN,NaN
1,Les concours bancaires et autres passifs finan...,NaN,NaN
2,2014 et se détaillent comme suit :,NaN,NaN
3,NaN,NaN,NaN
4,NaN,Solde au 31/12/2013,Solde au
5,Libellé Solde au 31/12/2014,NaN,NaN
6,NaN,Retraité,31/12/2013
7,NaN,NaN,NaN
8,Concours bancaires,23 852 223 14 193 711,14 193 711
9,Crédits financement cycle d'exploitation,12 220 000 31 263 867,31 263 867
10,Emprunts liés aux contrats de portage à moins ...,2 328 800,928 800 928 800
11,Emprunts échéance à moins d'un an,12 276 688,9 070 080 9 070 080
12,Effets escomptés non échus,2 879 483,1 252 081 1 252 081
13,Intérêts courus,2 334 128,278 186 278 186
14,Total,55 891 322 56 986 725,56 986 725

--- Tableau 9 ---

,Unnamed: 0,Note 11 : Capitaux propres\rTABLEAU DES MOUVEMENTS DES CAPITAUX PROPRES\rExercice clos le 31 Décembre 2014\r\rTotal des\rIntérêts desIntérêts desTotal des\rRéserves deRéservesRésultat decapitaux\rCapital socialminoritaires/minoritaires/capitaux\rrestructurationconsolidéesl'exercicepropres (part\rréservesrésultatpropres\rdu groupe)\r\r\rCapitaux propres consolidés au 31 décembre 2013549 072 620(472 190 804)-25 001 566101 883 3825 714 825(364 004)107 234 203\r\r\rAffectation résultat25 001 566(25 001 566)\r-(364 004)364 004-\r\r\rDistribution des Dividendes-(71 583)(71 583)\r\rSubvention d'investissement1 073 8171 073 817(30 567)1 043 249\r\rModifications comptables(832 527)(832 527)(2 367)(834 894)\r\rVariation du périmètre(111 384)2 002(109 382)(123 616)(232 998)\r\rRésultat consolidé de l'exercice 201425 823 66925 823 669(569 174)25 254 495\r\r\rCapitaux propres consolidés au 31 décembre 2014549 072 620(472 190 804)25 131 47225 825 670127 838 9585 122 688(569 174)132 392 472,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,Capital social,Réserves de\rrestructuration,Réserves\rconsolidées,Résultat de\rl'exercice,Total des\rcapitaux\rpropres (part\rdu groupe),Intérêts des\rminoritaires/\rréserves,Intérêts des\rminoritaires/\rrésultat,Total des\rcapitaux\rpropres
1,Capitaux propres consolidés au 31 décembre 2013,549 072 620,(472 190 804),-,25 001 566,101 883 382,5 714 825,(364 004),107 234 203
2,Affectation résultat\r\rDistribution des Divi...,NaN,NaN,25 001 566\r\r\r\r1 073 817\r\r(832 527)\r\r(1...,(25 001 566)\r\r\r\r\r\r\r\r2 002\r\r25 823 669,-\r\r-\r\r1 073 817\r\r(832 527)\r\r(109 382)\...,(364 004)\r\r(71 583)\r\r(30 567)\r\r(2 367)\r...,364 004\r\r\r\r\r\r\r\r\r\r(569 174),-\r\r(71 583)\r\r1 043 249\r\r(834 894)\r\r(23...
3,Capitaux propres consolidés au 31 décembre 2014,549 072 620,(472 190 804),25 131 472,25 825 670,127 838 958,5 122 688,(569 174),132 392 472

--- Tableau 10 ---

,Note 11 : Capitaux propres\rTABLEAU DES MOUVEMENTS DES CAPITAUX PROPRES\rExercice clos le 31 Décembre 2014\r\rTotal des\rIntérêts desIntérêts desTotal des\rRéserves deRéservesRésultat decapitaux\rCapital socialminoritaires/minoritaires/capitaux\rrestructurationconsolidéesl'exercicepropres (part\rréservesrésultatpropres\rdu groupe)\r\r\rCapitaux propres consolidés au 31 décembre 2013549 072 620(472 190 804)-25 001 566101 883 3825 714 825(364 004)107 234 203\r\r\rAffectation résultat25 001 566(25 001 566)\r-(364 004)364 004-\r\r\rDistribution des Dividendes-(71 583)(71 583)\r\rSubvention d'investissement1 073 8171 073 817(30 567)1 043 249\r\rModifications comptables(832 527)(832 527)(2 367)(834 894)\r\rVariation du périmètre(111 384)2 002(109 382)(123 616)(232 998)\r\rRésultat consolidé de l'exercice 201425 823 66925 823 669(569 174)25 254 495\r\r\rCapitaux propres consolidés au 31 décembre 2014549 072 620(472 190 804)25 131 47225 825 670127 838 9585 122 688(569 174)132 392 472,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Capitaux propres consolidés au 31 décembre 2013,549 072 620,(472 190 804),-,25 001 566,101 883 382,5 714 825,(364 004),107 234 203
1,Affectation résultat\r\rDistribution des Divi...,NaN,NaN,25 001 566\r\r\r\r1 073 817\r\r(832 527)\r\r(1...,(25 001 566)\r\r\r\r\r\r\r\r2 002\r\r25 823 669,-\r\r-\r\r1 073 817\r\r(832 527)\r\r(109 382)\...,(364 004)\r\r(71 583)\r\r(30 567)\r\r(2 367)\r...,364 004\r\r\r\r\r\r\r\r\r\r(569 174),-\r\r(71 583)\r\r1 043 249\r\r(834 894)\r\r(23...
2,Capitaux propres consolidés au 31 décembre 2014,549 072 620,(472 190 804),25 131 472,25 825 670,127 838 958,5 122 688,(569 174),132 392 472

--- Tableau 11 ---

,Unnamed: 0,Unnamed: 1,Solde au 31/12/2013,Solde au 31/12/2013.1
0,Libellé,Solde au 31/12/2014,NaN,NaN
1,NaN,NaN,Retraité,Publié
2,NaN,NaN,NaN,NaN
3,Clients avances et acomptes,3 432 360,5 991 232,5 991 232
4,Autres avoirs,3 572,-,-
5,Comptes de personnel,2 332 367,1 880 219,1 880 219
6,Etat impôts/taxes,5 245 875,5 790 634,5 790 634
7,Autres passifs courants,5 422 128,8 860 188,8 860 188
8,Retenues,11 865,49 804,49 804
9,Créditeurs divers,7 432 032,5 502 158,5 502 158
10,Cotisations sociales,2 362 450,2 436 164,2 436 164

--- Tableau 12 ---

                           Note 19 : Achats consommés Unnamed: 0
0                                                 NaN        NaN
1   Les achats consommés s’élèvent à 501 025 458 d...        NaN
2                                                 NaN        NaN
3            Libellé 2014 2013 Retraité** 2013 Publié        NaN
4   Achats matières premières 342 453 489 301 837 ...        NaN
..                                                ...        ...
43  Dotation (nettes) aux provisions pour déprécia...        NaN
44  Dotation (nettes) aux provisions pour déprécia...        NaN
45  Dotation (nettes) aux résorptions des frais pr...        NaN
46        Reprise sur provision Liquidité (238 748) -          -
47           Total 25 667 082  22 549 958  26 306 952        NaN

[48 rows x 2 columns]

--- Tableau 13 ---

,Total 8 639 380,5 941 045,Unnamed: 0,5 941 045.1
0,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,Note 24 : Produits financiers,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN
4,Les produits financiers s’élèvent à 1 245 62...,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN
6,Libellé 2014,2013 Retraité,NaN,2013 Publié
7,NaN,NaN,NaN,NaN
8,Produits des placements 1 245 625,501 854,NaN,501 854
9,Intérêts des comptes courants -,113 343,NaN,113 343
10,Produits des participations -,1 438,NaN,1 438
11,Total 1 245 62,616 634,NaN,616 634

--- Tableau 14 ---

                               Unnamed: 0        2014        2013
0                                     NaN         NaN         NaN
1              Résultat net consolidé (A)  25 825 670  25 001 566
2                                     NaN         NaN         NaN
3  Nombre des actions en début de période  54 907 262  54 907 262
4                                     NaN         NaN         NaN
5    Nombre des actions en fin de période  54 907 262  54 907 262
6                                     NaN         NaN         NaN
7            Nombre moyen des actions (B)  54 907 262  54 907 262
8                                     NaN         NaN         NaN
9     Résultat par action en dinars (A/B)       0,470       0,455

--- Tableau 15 ---

,Unnamed: 0,Unnamed: 1,Unnamed: 2
0,"Liquidités, équivalents de liquidités et place...",Solde au 31/12/2014,Solde au 31/12/2013
1,Placements,15 000 000,-
2,Banques,18 305 339,25 165 275
3,Caisses,5 204,257 681
4,Chèques à l'encaissement,2 084 815,24 162
5,Total (A),35 395 358,25 447 118
6,Concours bancaires et autres passifs financier...,Solde au 31/12/2014,Solde au 31/12/2013
7,Concours bancaires,23 852 223,14 193 711
8,Total (B),23 852 223,14 193 711
9,Trésorerie nette (A-B),11 543 135,11 253 407

--- Tableau 16 ---

,Autres produits,Unnamed: 0,Unnamed: 1,Unnamed: 2,Les reprises,/,provision,pour,un,montant,de
0,NaN,6 982 368,50 241 196,(43 258 828),NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,d'exploitation,NaN,NaN,NaN,3 756 994 dinars relatives à des participatio...,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,cédées ont été,reclassées,au,niveau,de,la rubrique,NaN
3,NaN,NaN,NaN,NaN,"""dotations / reprises des amortissements/provi...",NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,Les reprises,/,provision,pour,un,montant,de
...,...,...,...,...,...,...,...,...,...,...,...
29,NaN,(32 383 796),(34 323 271),1 939 475,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,d'exploitation,NaN,NaN,NaN,servies a été reclassé parmi les charges de pe...,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,Les reprises,/,provision,pour,un,montant,de
32,Autres pertes,NaN,NaN,NaN,4 564 573 dinars relatives à des participatio...,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,(2 195 710),(6 760 283),4 564 573,NaN,NaN,NaN,NaN,NaN,NaN,NaN

============================================================
📅 Année : 2015 | 12 tableau(x)
============================================================

--- Tableau 1 ---

,Actifs,Unnamed: 0,31.12.2015,31.12.2014
0,Actifs non courants,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,Immobilisations incorporelles,NaN,3 109 814,2 518 600
3,-Amortissements Immobilisations incorporelles,NaN,(2 075 258),(1 877 592)
4,NaN,(1),1 034 556,641 008
...,...,...,...,...
38,NaN,NaN,NaN,NaN
39,Total des actifs courants,NaN,196 872 453,175 522 181
40,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN
42,Total Actifs,NaN,405 512 774,382 180 380

--- Tableau 2 ---

          Capitaux propres et passifs Unnamed: 0     31.12.2015     31.12.2014
0                                 NaN        NaN            NaN            NaN
1                      Capital social        NaN    549 072 620    549 072 620
2         Réserves de restructuration        NaN  (472 190 804)  (472 190 804)
3                 Réserves consolidés        NaN     16 729 011     25 131 472
4                                 NaN        NaN            NaN            NaN
..                                ...        ...            ...            ...
43                                NaN        NaN            NaN            NaN
44                                NaN        NaN            NaN            NaN
45                  Total des passifs        NaN    267 253 916    249 787 908
46                                NaN        NaN            NaN            NaN
47  Total Capitaux propres et passifs        NaN    405 512 774    382 180 380

[48 rows x 4 columns]

--- Tableau 3 ---

,Unnamed: 0,Unnamed: 1,2015,2014
0,NaN,NaN,NaN,NaN
1,Revenus,(18),714 952 675,647 588 213
2,Autres produits d'exploitation,(19),15 849 489,12 807 509
3,Total des produits d'exploitation,NaN,730 802 164,660 395 722
4,NaN,NaN,NaN,NaN
...,...,...,...,...
25,Résultat des activités ordinaires après impôt,NaN,40 113 885,25 256 495
26,Part revenant aux intérêts minoritaires,(11),65 550,(569 175)
27,Résultat net consolidé (Part revenant au groupe),NaN,40 048 335,25 825 670
28,Nombre moyen des actions,NaN,54 907 262,54 907 262
29,Résultat par action,NaN,"0,729","0,470"

--- Tableau 4 ---

,Unnamed: 0,Unnamed: 1,2015,2014
0,Résultat net (Groupe),NaN,40 048 335,25 825 670
1,Ajustement pour:,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,*Part revenant aux intérêts minoritaires,(11),65 550,(569 175)
4,"*Amortissements, Provisions & Reprises de prov...",(22),33 252 784,25 667 082
...,...,...,...,...
33,Variation de trésorerie,NaN,27 006 374,289 728
34,NaN,NaN,NaN,NaN
35,Trésorerie au début de l’exercice,(28),11 543 135,11 253 407
36,NaN,NaN,NaN,NaN
37,Trésorerie à la clôture de l’exercice,(28),38 549 509,11 543 135

--- Tableau 5 ---

,Société,% de contrôle,% d’intérêts groupe,Type de contrôle,Méthode de comptabilisation
0,DELICE Holding,100%,100%,Société mère,NaN
1,CLC,"97,45%","97,23%",Contrôle exclusif,Intégration globale
2,CLN,"99,77%","99,77%",Contrôle exclusif,Intégration globale
3,CLSB,"100,00%","99,78%",Contrôle exclusif,Intégration globale
4,SBC,"99,99%","99,99%",Contrôle exclusif,Intégration globale
5,CF,"99,99%","99,99%",Contrôle exclusif,Intégration globale
6,Delta plastic,"57,50%","57,49%",Contrôle exclusif,Intégration globale

--- Tableau 6 ---

      Note 9 : Placements et autres actifs financiers Unnamed: 0
0   Les placements s’élèvent à 15 500 000 dinars a...        NaN
1                                                 NaN        NaN
2                           Libellé Solde au Solde au        NaN
3                               31/12/2015 31/12/2014        NaN
4   Certificat de dépôt – échéance 10/04/2015 - 7 ...        NaN
..                                                ...        ...
31  Emprunts échéance à moins d'un an 15 136 142 1...        NaN
32     Effets escomptés non échus 1 930 132 2 879 483        NaN
33                Intérêts courus 2 234 992 2 334 128        NaN
34                                                NaN        NaN
35                        Total 77 417 726 55 891 322        NaN

[36 rows x 2 columns]

--- Tableau 7 ---

,Unnamed: 0,Note 11 : Capitaux propres\rTABLEAU DES MOUVEMENTS DES CAPITAUX PROPRES\rExercice clos le 31 Décembre 2015\rTotal des\rIntérêts desIntérêts desTotal des\rRéserves deRéservesRésultat decapitaux\rCapital socialminoritaires/minoritaires/capitaux\rrestructurationconsolidéesl'exercicepropres (part\rréservesrésultatpropres\rdu groupe)\r\rCapitaux propres consolidés au 31 décembre 2013549 072 620(472 190 804)-25 001 566101 883 3825 714 825(364 004)107 234 203\r\r\rAffectation résultat25 001 566(25 001 566)-(364 004)364 004-\r\rDistribution des dividendes-(71 583)(71 583)\rSubvention d'investissement1 073 8171 073 817(30 567)1 043 249\rModifications comptables(832 527)(832 527)(2 367)(834 894)\r\rVariation du périmètre(111 384)2 002(109 382)(123 616)(232 998)\r\rRésultat consolidé de l'exercice 201425 823 66925 823 669(569 174)25 254 495\r\rCapitaux propres consolidés au 31 décembre 2014549 072 620(472 190 804)25 131 47225 825 670127 838 9585 122 688(569 174)132 392 472\rAffectation résultat25 825 670(25 825 670)-(569 174)569 174-\rDistribution des dividendes(35 142 645)(35 142 645)(14 063)(35 156 708)\rSubvention d'investissement945 747945 747(37 542)908 205\rModifications comptables972972972\rVariation du pourcentage d'intérêt(32 205)(32 205)32 23732\rRésultat consolidé de l'exercice 201540 048 33540 048 33565 55040 113 885\rCapitaux propres consolidés au 31 décembre 2015549 072 620(472 190 804)16 729 01140 048 335133 659 1624 534 14665 550138 258 858,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,Capital social,Réserves de\rrestructuration,Réserves\rconsolidées,Résultat de\rl'exercice,Total des\rcapitaux\rpropres (part\rdu groupe),Intérêts des\rminoritaires/\rréserves,Intérêts des\rminoritaires/\rrésultat,Total des\rcapitaux\rpropres,NaN
1,Capitaux propres consolidés au 31 décembre 2013,549 072 620,(472 190 804),-,25 001 566,101 883 382,5 714 825,(364 004),107 234 203,NaN
2,Affectation résultat\r\rDistribution des divi...,NaN,NaN,25 001 566\r\r\r1 073 817\r(832 527)\r\r(111 384),(25 001 566)\r\r\r\r\r\r2 002\r\r25 823 669,-\r\r-\r1 073 817\r(832 527)\r\r(109 382)\r\r2...,(364 004)\r\r(71 583)\r(30 567)\r(2 367)\r\r(1...,364 004\r\r\r\r\r\r\r\r(569 174),-\r\r(71 583)\r1 043 249\r(834 894)\r\r(232 99...,NaN
3,Capitaux propres consolidés au 31 décembre 2014,549 072 620,(472 190 804),25 131 472,25 825 670,127 838 958,5 122 688,(569 174),132 392 472,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Affectation résultat\rDistribution des divide...,NaN,NaN,25 825 670\r(35 142 645)\r945 747\r972\r(32 205),(25 825 670)\r\r\r\r\r40 048 335,-\r(35 142 645)\r945 747\r972\r(32 205)\r40 04...,(569 174)\r(14 063)\r(37 542)\r\r32 237,569 174\r\r\r\r\r65 550,-\r(35 156 708)\r908 205\r972\r32\r40 113 885,NaN
6,Capitaux propres consolidés au 31 décembre 2015,549 072 620,(472 190 804),16 729 011,40 048 335,133 659 162,4 534 146,65 550,138 258 858,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Tableau 8 ---

,Note 11 : Capitaux propres\rTABLEAU DES MOUVEMENTS DES CAPITAUX PROPRES\rExercice clos le 31 Décembre 2015\rTotal des\rIntérêts desIntérêts desTotal des\rRéserves deRéservesRésultat decapitaux\rCapital socialminoritaires/minoritaires/capitaux\rrestructurationconsolidéesl'exercicepropres (part\rréservesrésultatpropres\rdu groupe)\r\rCapitaux propres consolidés au 31 décembre 2013549 072 620(472 190 804)-25 001 566101 883 3825 714 825(364 004)107 234 203\r\r\rAffectation résultat25 001 566(25 001 566)-(364 004)364 004-\r\rDistribution des dividendes-(71 583)(71 583)\rSubvention d'investissement1 073 8171 073 817(30 567)1 043 249\rModifications comptables(832 527)(832 527)(2 367)(834 894)\r\rVariation du périmètre(111 384)2 002(109 382)(123 616)(232 998)\r\rRésultat consolidé de l'exercice 201425 823 66925 823 669(569 174)25 254 495\r\rCapitaux propres consolidés au 31 décembre 2014549 072 620(472 190 804)25 131 47225 825 670127 838 9585 122 688(569 174)132 392 472\rAffectation résultat25 825 670(25 825 670)-(569 174)569 174-\rDistribution des dividendes(35 142 645)(35 142 645)(14 063)(35 156 708)\rSubvention d'investissement945 747945 747(37 542)908 205\rModifications comptables972972972\rVariation du pourcentage d'intérêt(32 205)(32 205)32 23732\rRésultat consolidé de l'exercice 201540 048 33540 048 33565 55040 113 885\rCapitaux propres consolidés au 31 décembre 2015549 072 620(472 190 804)16 729 01140 048 335133 659 1624 534 14665 550138 258 858,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Capitaux propres consolidés au 31 décembre 2013,549 072 620,(472 190 804),-,25 001 566,101 883 382,5 714 825,(364 004),107 234 203,NaN
1,Affectation résultat\r\rDistribution des divi...,NaN,NaN,25 001 566\r\r\r1 073 817\r(832 527)\r\r(111 384),(25 001 566)\r\r\r\r\r\r2 002\r\r25 823 669,-\r\r-\r1 073 817\r(832 527)\r\r(109 382)\r\r2...,(364 004)\r\r(71 583)\r(30 567)\r(2 367)\r\r(1...,364 004\r\r\r\r\r\r\r\r(569 174),-\r\r(71 583)\r1 043 249\r(834 894)\r\r(232 99...,NaN
2,Capitaux propres consolidés au 31 décembre 2014,549 072 620,(472 190 804),25 131 472,25 825 670,127 838 958,5 122 688,(569 174),132 392 472,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Affectation résultat\rDistribution des divide...,NaN,NaN,25 825 670\r(35 142 645)\r945 747\r972\r(32 205),(25 825 670)\r\r\r\r\r40 048 335,-\r(35 142 645)\r945 747\r972\r(32 205)\r40 04...,(569 174)\r(14 063)\r(37 542)\r\r32 237,569 174\r\r\r\r\r65 550,-\r(35 156 708)\r908 205\r972\r32\r40 113 885,NaN
5,Capitaux propres consolidés au 31 décembre 2015,549 072 620,(472 190 804),16 729 011,40 048 335,133 659 162,4 534 146,65 550,138 258 858,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Tableau 9 ---

                      Libellé Solde au 31/12/2015 Solde au 31/12/2014
0          Fournisseurs d'exploitation 50 599 080          45 198 254
1          Fournisseurs effets à payer 11 269 248          14 944 184
2        Fournisseurs d'immobilisations 7 306 361          11 201 588
3   Fournisseurs factures non parvenues 4 208 016          19 267 811
4                                             NaN                 NaN
..                                            ...                 ...
19                   Créditeurs divers 12 916 488           7 432 032
20                 Cotisations sociales 2 579 895           2 362 450
21                  Assurance au personnel 65 339             124 785
22                                            NaN                 NaN
23                               Total 41 663 704          26 367 434

[24 rows x 2 columns]

--- Tableau 10 ---

                                           Unnamed: 0   Unnamed: 1
0   Les revenus s’élèvent à 714 952 675 dinars en ...          NaN
1                                                 NaN          NaN
2                                        Libellé 2015         2014
3                          Ventes SOCOGES 391 135 233  351 257 286
4                              Ventes CLC 104 453 344  170 791 616
..                                                ...          ...
24           Autres produits d'exploitation 1 675 888    3 366 113
25             Produits des activités annexes 737 662      842 096
26   Quote part subvention d'investissement 1 387 128    1 040 391
27                                                NaN          NaN
28                                   Total 15 849 489   12 807 509

[29 rows x 2 columns]

--- Tableau 11 ---

                                     Total 33 252 784 Unnamed: 0  25 667 082
0                                                 NaN        NaN         NaN
1                                                 NaN        NaN         NaN
2             Note 23 : Autres charges d'exploitation        NaN         NaN
3                                                 NaN        NaN         NaN
4   Les autres charges d’exploitation s’élèvent à ...        NaN         NaN
5                                                 NaN        NaN         NaN
6                                        Libellé 2015        NaN        2014
7                                                 NaN        NaN         NaN
8            Autres charges d’exploitation 11 894 003        NaN  12 301 706
9   Honoraires & rémunération d'intermédiaire 4 16...        NaN   4 365 132
10                        Charges locatives 5 071 476        NaN   5 812 024
11                charges divers ordinaires 1 868 431        NaN   1 903 440
12                   Entretien & réparation 4 751 307        NaN   3 695 942
13                               Redevances 2 558 657        NaN   2 618 032
14                      Services extérieurs 2 567 815        NaN   2 286 304
15                         Impôts et taxes  2 110 634        NaN   2 546 455

--- Tableau 12 ---

,Unnamed: 0,Unnamed: 1
0,NaN,NaN
1,NaN,Solde au 31/12/2015 Solde au 31/12/2014
2,"Liquidités, équivalents de liquidités et place...",NaN
3,Placements,15 500 000 15 000 000
4,Banques,25 875 934 18 305 339
...,...,...
27,Nombre des actions en fin de période,54 907 262 54 907 262
28,NaN,NaN
29,Nombre moyen des actions (B),54 907 262 54 907 262
30,NaN,NaN
31,Résultat par action en dinars (A/B),"0,729 0,470"

============================================================
📅 Année : 2016 | 15 tableau(x)
============================================================

--- Tableau 1 ---

,Unnamed: 0,Note,31.12.2016,31.12.2015
0,Actifs,NaN,NaN,NaN
1,Actifs non courants,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,Immobilisations incorporelles,NaN,3 978 911,3 109 814
4,-Amortissements Immobilisations incorporelles,NaN,(2 519 206),(2 075 258)
...,...,...,...,...
35,Liquidités et équivalents de liquidités,(10),23 486 179,28 887 169
36,NaN,NaN,NaN,NaN
37,Total des actifs courants,NaN,181 465 777,196 872 453
38,NaN,NaN,NaN,NaN
39,Total Actifs,NaN,397 467 573,405 512 774

--- Tableau 2 ---

                           Unnamed: 0 Note     31.12.2016     31.12.2015
0         Capitaux propres et passifs  NaN            NaN            NaN
1                                 NaN  NaN            NaN            NaN
2                                 NaN  NaN            NaN            NaN
3                      Capital social  NaN    549 072 620    549 072 620
4         Réserves de restructuration  NaN  (472 190 804)  (472 190 804)
..                                ...  ...            ...            ...
30         Total des passifs courants  NaN    185 539 323    192 464 135
31                                NaN  NaN            NaN            NaN
32                      Total passifs  NaN    247 941 504    267 253 916
33                                NaN  NaN            NaN            NaN
34  Total Capitaux propres et passifs  NaN    397 467 573    405 512 774

[35 rows x 4 columns]

--- Tableau 3 ---

,Total produits d'exploitation,Unnamed: 0,763 736 168,730 802 164
0,NaN,NaN,NaN,NaN
1,Variation des stocks des PF et des encours,NaN,(9 936 108),24 854 402
2,Achats consommés,(20),(556 641 851),(564 263 677)
3,Charges de personnel,(21),(64 490 258),(60 134 871)
4,Dotations aux amortissements et aux provisions,(22),(32 593 313),(33 252 784)
...,...,...,...,...
22,Résultat des activités ordinaires après impôt,NaN,37 013 521,40 113 885
23,Part revenant aux intérêts minoritaires,(11),97 585,65 550
24,Résultat net consolidé (part revenant au groupe),NaN,36 915 936,40 048 335
25,Nombre moyen des actions,NaN,54 907 262,54 907 262
26,NaN,NaN,"0,672","0,729"

--- Tableau 4 ---

,"Groupe DELICE\rETAT DE FLUX DE TRESORERIE CONSOLIDE\r(Exprimé en dinars tunisiens)\r\rNotes20162015\rRésultat net (Groupe)36 915 93640 048 335\rAjustement pour:\r\r*Part revenant aux intérêts minoritaires\r(11)97 58565 550\r*Amortissements, Provisions & Reprises de provisions\r(22)32 593 31333 252 784\r*Variation des:\r- Autres actifs et passifs non courants\r173 379592 086\r- Stocks\r13 779 801(15 707 304)\r- Créances clients\r2 200 944(1 674 706)\r- Autres actifs\r(4 972 978)1 968 507\r- Fournisseurs et autres dettes\r15 175 908(17 229 132)\r- Autres passifs courants\r(1 263 071)15 296 271\r- Autres éléments sans incidence sur la trésorerie\r(1 637 161)(259 632)\r\r*Impôt différé\r(504 138)(587 767)\r*Intérêts Emprunts\r(24)467 192747 881\r\rFlux de trésorerie provenant de (affectés à) l'exploitation93 026 71056 512 873\r\r\rVariation de trésorerie provenant de l'acquisition et des cessions des\r\rimmobilisations corp. & incorporelles\r(34 912 192)(26 097 203)\rVariation de trésorerie provenant des immobilisations financières\r1 657 518(649 923)\r\rFlux de trésorerie provenant des (affectés aux) activités\r(33 254 674)(26 747 126)\rd'investissement\r\r\rDividendes et autres distributions\r(28 638 283)(36 386 437)\rVariation de trésorerie provenant des emprunts\r(31 580 978)33 627 064\r\rFlux de trésorerie provenant des (affectés aux) activités de\r(60 219 261)(2 759 373)\r\rVariation de trésorerie\r(447 225)27 006 374\r\rTrésorerie au début de l'exercice38 549 50911 543 135\rTrésorerie à la clôture de l'exercice38 102 28438 549 509",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,Notes,NaN,NaN,2016,NaN,NaN,2015,NaN
1,NaN,Résultat net (Groupe),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Ajustement pour:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,*Part revenant aux intérêts minoritaires,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,"*Amortissements, Provisions & Reprises de prov...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,*Variation des:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Tableau 5 ---

,"Groupe DELICE\rETAT DE FLUX DE TRESORERIE CONSOLIDE\r(Exprimé en dinars tunisiens)\r\rNotes20162015\rRésultat net (Groupe)36 915 93640 048 335\rAjustement pour:\r\r*Part revenant aux intérêts minoritaires\r(11)97 58565 550\r*Amortissements, Provisions & Reprises de provisions\r(22)32 593 31333 252 784\r*Variation des:\r- Autres actifs et passifs non courants\r173 379592 086\r- Stocks\r13 779 801(15 707 304)\r- Créances clients\r2 200 944(1 674 706)\r- Autres actifs\r(4 972 978)1 968 507\r- Fournisseurs et autres dettes\r15 175 908(17 229 132)\r- Autres passifs courants\r(1 263 071)15 296 271\r- Autres éléments sans incidence sur la trésorerie\r(1 637 161)(259 632)\r\r*Impôt différé\r(504 138)(587 767)\r*Intérêts Emprunts\r(24)467 192747 881\r\rFlux de trésorerie provenant de (affectés à) l'exploitation93 026 71056 512 873\r\r\rVariation de trésorerie provenant de l'acquisition et des cessions des\r\rimmobilisations corp. & incorporelles\r(34 912 192)(26 097 203)\rVariation de trésorerie provenant des immobilisations financières\r1 657 518(649 923)\r\rFlux de trésorerie provenant des (affectés aux) activités\r(33 254 674)(26 747 126)\rd'investissement\r\r\rDividendes et autres distributions\r(28 638 283)(36 386 437)\rVariation de trésorerie provenant des emprunts\r(31 580 978)33 627 064\r\rFlux de trésorerie provenant des (affectés aux) activités de\r(60 219 261)(2 759 373)\r\rVariation de trésorerie\r(447 225)27 006 374\r\rTrésorerie au début de l'exercice38 549 50911 543 135\rTrésorerie à la clôture de l'exercice38 102 28438 549 509",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,Notes,NaN,NaN,2016,NaN,NaN,2015,NaN
1,NaN,Résultat net (Groupe),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Ajustement pour:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
45,NaN,NaN,NaN,NaN,NaN,NaN,(447 225),NaN,NaN,NaN,NaN,NaN
46,NaN,Variation de trésorerie,NaN,27 006 374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,Trésorerie au début de l'exercice,NaN,NaN,NaN,NaN,38 549 509,NaN,11 543 135,NaN,NaN,NaN
49,NaN,Trésorerie à la clôture de l'exercice,NaN,NaN,NaN,NaN,38 102 284,NaN,38 549 509,NaN,NaN,NaN

--- Tableau 6 ---

,"Groupe DELICE\rETAT DE FLUX DE TRESORERIE CONSOLIDE\r(Exprimé en dinars tunisiens)\r\rNotes20162015\rRésultat net (Groupe)36 915 93640 048 335\rAjustement pour:\r\r*Part revenant aux intérêts minoritaires\r(11)97 58565 550\r*Amortissements, Provisions & Reprises de provisions\r(22)32 593 31333 252 784\r*Variation des:\r- Autres actifs et passifs non courants\r173 379592 086\r- Stocks\r13 779 801(15 707 304)\r- Créances clients\r2 200 944(1 674 706)\r- Autres actifs\r(4 972 978)1 968 507\r- Fournisseurs et autres dettes\r15 175 908(17 229 132)\r- Autres passifs courants\r(1 263 071)15 296 271\r- Autres éléments sans incidence sur la trésorerie\r(1 637 161)(259 632)\r\r*Impôt différé\r(504 138)(587 767)\r*Intérêts Emprunts\r(24)467 192747 881\r\rFlux de trésorerie provenant de (affectés à) l'exploitation93 026 71056 512 873\r\r\rVariation de trésorerie provenant de l'acquisition et des cessions des\r\rimmobilisations corp. & incorporelles\r(34 912 192)(26 097 203)\rVariation de trésorerie provenant des immobilisations financières\r1 657 518(649 923)\r\rFlux de trésorerie provenant des (affectés aux) activités\r(33 254 674)(26 747 126)\rd'investissement\r\r\rDividendes et autres distributions\r(28 638 283)(36 386 437)\rVariation de trésorerie provenant des emprunts\r(31 580 978)33 627 064\r\rFlux de trésorerie provenant des (affectés aux) activités de\r(60 219 261)(2 759 373)\r\rVariation de trésorerie\r(447 225)27 006 374\r\rTrésorerie au début de l'exercice38 549 50911 543 135\rTrésorerie à la clôture de l'exercice38 102 28438 549 509",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,*Impôt différé,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,*Intérêts Emprunts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,(447 225),NaN,NaN,NaN,NaN,NaN
33,NaN,Variation de trésorerie,NaN,27 006 374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,Trésorerie au début de l'exercice,NaN,NaN,NaN,NaN,38 549 509,NaN,11 543 135,NaN,NaN,NaN

--- Tableau 7 ---

,"Groupe DELICE\rETAT DE FLUX DE TRESORERIE CONSOLIDE\r(Exprimé en dinars tunisiens)\r\rNotes20162015\rRésultat net (Groupe)36 915 93640 048 335\rAjustement pour:\r\r*Part revenant aux intérêts minoritaires\r(11)97 58565 550\r*Amortissements, Provisions & Reprises de provisions\r(22)32 593 31333 252 784\r*Variation des:\r- Autres actifs et passifs non courants\r173 379592 086\r- Stocks\r13 779 801(15 707 304)\r- Créances clients\r2 200 944(1 674 706)\r- Autres actifs\r(4 972 978)1 968 507\r- Fournisseurs et autres dettes\r15 175 908(17 229 132)\r- Autres passifs courants\r(1 263 071)15 296 271\r- Autres éléments sans incidence sur la trésorerie\r(1 637 161)(259 632)\r\r*Impôt différé\r(504 138)(587 767)\r*Intérêts Emprunts\r(24)467 192747 881\r\rFlux de trésorerie provenant de (affectés à) l'exploitation93 026 71056 512 873\r\r\rVariation de trésorerie provenant de l'acquisition et des cessions des\r\rimmobilisations corp. & incorporelles\r(34 912 192)(26 097 203)\rVariation de trésorerie provenant des immobilisations financières\r1 657 518(649 923)\r\rFlux de trésorerie provenant des (affectés aux) activités\r(33 254 674)(26 747 126)\rd'investissement\r\r\rDividendes et autres distributions\r(28 638 283)(36 386 437)\rVariation de trésorerie provenant des emprunts\r(31 580 978)33 627 064\r\rFlux de trésorerie provenant des (affectés aux) activités de\r(60 219 261)(2 759 373)\r\rVariation de trésorerie\r(447 225)27 006 374\r\rTrésorerie au début de l'exercice38 549 50911 543 135\rTrésorerie à la clôture de l'exercice38 102 28438 549 509",Unnamed: 0,Unnamed: 1
0,NaN,- Stocks,NaN
1,NaN,- Créances clients,NaN
2,NaN,- Autres actifs,NaN
3,NaN,- Fournisseurs et autres dettes,NaN
4,NaN,- Autres passifs courants,NaN

--- Tableau 8 ---

,Société,% de contrôle,% d’intérêts groupe,Type de contrôle,Méthode de comptabilisation
0,DELICE Holding,100%,100%,Société mère,NaN
1,CLC,"99,77%","99,77%",Contrôle exclusif,Intégration globale
2,CLN,"98,02%","97,80%",Contrôle exclusif,Intégration globale
3,CLSB,"100,00%","99,78%",Contrôle exclusif,Intégration globale
4,SBC,"99,99%","99,99%",Contrôle exclusif,Intégration globale
5,CF,"57,50%","57,49%",Contrôle exclusif,Intégration globale
6,Delta plastic,"99,99%","99,99%",Contrôle exclusif,Intégration globale

--- Tableau 9 ---

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Entrées,Cession et,VB,Amt cumulés,Unnamed: 3,Cession/,Amortissements,Unnamed: 4,Unnamed: 5
0,NaN,Montants en TND,VB Dec15,31/12/2016,reclassements,Decembre16,31/12/2015,Dotations,régul,Decembre 16,VCN 2015,VCN 2016
1,Logiciels,NaN,2 618 965,1 043 989,109 144,3 553 810,2 018 379,511 197,97 391,2 432 184,600 586,1 121 626
2,Concessions de marques et brevets,NaN,105 633,31 810,-,137 443,46 920,30 142,-,77 062,58 714,60 381
3,Immobilisations incorporelles en cours,NaN,385 216,225 799,323 357,287 658,9 960,NaN,NaN,9 960,375 256,277 698
4,Total immobilisations incorporelles,NaN,3 109 814,1 301 598,432 501,3 978 911,2 075 258,541 339,97 391,2 519 206,1 034 556,1 459 705
...,...,...,...,...,...,...,...,...,...,...,...,...
16,Immobilisations en cours,NaN,6 481 045,14 468 949,6 616 758,14 333 236,-,67 275,NaN,67 275,6 481 045,14 265 961
17,Avances et acomptes sur immobilisations,NaN,57 801,1 629 760,33 583,1 653 978,-,NaN,NaN,-,57 801,1 653 978
18,Provisions constituées,NaN,-,-,-,-,1 799 919,57 690,318 658,1 538 951,(1 799 919),(1 538 951)
19,Total immobilisations corporelles,NaN,363 866 388,48 175 207,14 038 517,398 003 078,178 208 255,30 284 220,5 965 679,202 526 796,185 658 133,195 476 282
20,Total immobilisations incorporelles et corpore...,NaN,366 976 202,49 476 805,14 471 018,401 981 989,180 283 513,30 825 559,6 063 070,205 046 002,186 692 689,196 935 987

--- Tableau 10 ---

,Unnamed: 0,Libellé Solde au 31/12/2016,Solde au 31/12/2015
0,Clients locaux,14 095 334,16 544 928
1,Clients douteux,2 191 072,2 361 250
2,Clients effets escomptés non échus,1 615 808,1 930 132
3,"Client, effets à recevoir",1 596 358,617 870
4,Clients étrangers,112 556,357 891
...,...,...,...
29,Total brut,49 896 917,45 334 634
30,-Provisions dépréciation des autres actifs,NaN,NaN
31,NaN,(1 795 658),(1 564 189)
32,courants,NaN,NaN
33,Total net,48 101 259,43 770 445

--- Tableau 11 ---

,Note 11 : Capitaux propres\rTABLEAU DES MOUVEMENTS DES CAPITAUX PROPRES\rExercice clos le 31 Décembre 2016\rTotal des\rIntérêts desIntérêts desTotal des\rRéserves deRéservesRésultat decapitaux\rCapital socialminoritaires/minoritaires/capitaux\rrestructurationconsolidéesl'exercicepropres (part\rréservesrésultatpropres\rdu groupe)\r\rCapitaux propres consolidés au 31 décembre 2014549 072 620(472 190 804)25 131 47225 825 670127 838 9585 122 688(569 174)132 392 472\r\r\rAffectation résultat25 825 670(25 825 670)-(569 174)569 174-\r\rDistribution des dividendes(35 142 645)(35 142 645)(14 063)(35 156 708)\rSubvention d'investissement945 747945 747(37 542)908 205\rModifications comptables972972972\r\rVariation du pourcentage d’intérêts(32 205)(32 205)32 23732\r\rRésultat consolidé de l'exercice 201540 048 33540 048 33565 55040 113 885\r\rCapitaux propres consolidés au 31 décembre 2015549 072 620(472 190 804)16 729 01140 048 335133 659 1624 534 14665 550138 258 858\rAffectation résultat40 048 335(40 048 335)-65 550(65 550)-\rDistribution des dividendes(24 708 161)(24 708 161)(4 332)(24 712 493)\rSubvention d'investissement(986 166)(986 166)(47 651)(1 033 817)\rVariation du pourcentage d'intérêt(38 420)(38 420)38 420\rRésultat consolidé de l'exercice 201636 915 93636 915 93697 58537 013 521\rCapitaux propres consolidés au 31 décembre 2016549 072 620(472 190 804)31 044 59936 915 936144 842 3514 586 13397 585149 526 069,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Capitaux propres consolidés au 31 décembre 2014,549 072 620,(472 190 804),25 131 472,25 825 670,127 838 958,5 122 688,(569 174),132 392 472,NaN
1,Affectation résultat\r\rDistribution des divi...,NaN,NaN,25 825 670\r(35 142 645)\r945 747\r972\r(32 205),(25 825 670)\r40 048 335,-\r(35 142 645)\r945 747\r972\r(32 205)\r40 04...,(569 174)\r(14 063)\r(37 542)\r32 237,569 174\r65 550,-\r(35 156 708)\r908 205\r972\r32\r40 113 885,NaN
2,Capitaux propres consolidés au 31 décembre 2015,549 072 620,(472 190 804),16 729 011,40 048 335,133 659 162,4 534 146,65 550,138 258 858,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Affectation résultat\rDistribution des divide...,NaN,NaN,40 048 335\r(24 708 161)\r(986 166)\r(38 420),(40 048 335)\r36 915 936,-\r(24 708 161)\r(986 166)\r(38 420)\r36 915 936,65 550\r(4 332)\r(47 651)\r38 420,(65 550)\r97 585,-\r(24 712 493)\r(1 033 817)\r37 013 521,NaN
5,Capitaux propres consolidés au 31 décembre 2016,549 072 620,(472 190 804),31 044 599,36 915 936,144 842 351,4 586 133,97 585,149 526 069,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Tableau 12 ---

,Note 11 : Capitaux propres\rTABLEAU DES MOUVEMENTS DES CAPITAUX PROPRES\rExercice clos le 31 Décembre 2016\rTotal des\rIntérêts desIntérêts desTotal des\rRéserves deRéservesRésultat decapitaux\rCapital socialminoritaires/minoritaires/capitaux\rrestructurationconsolidéesl'exercicepropres (part\rréservesrésultatpropres\rdu groupe)\r\rCapitaux propres consolidés au 31 décembre 2014549 072 620(472 190 804)25 131 47225 825 670127 838 9585 122 688(569 174)132 392 472\r\r\rAffectation résultat25 825 670(25 825 670)-(569 174)569 174-\r\rDistribution des dividendes(35 142 645)(35 142 645)(14 063)(35 156 708)\rSubvention d'investissement945 747945 747(37 542)908 205\rModifications comptables972972972\r\rVariation du pourcentage d’intérêts(32 205)(32 205)32 23732\r\rRésultat consolidé de l'exercice 201540 048 33540 048 33565 55040 113 885\r\rCapitaux propres consolidés au 31 décembre 2015549 072 620(472 190 804)16 729 01140 048 335133 659 1624 534 14665 550138 258 858\rAffectation résultat40 048 335(40 048 335)-65 550(65 550)-\rDistribution des dividendes(24 708 161)(24 708 161)(4 332)(24 712 493)\rSubvention d'investissement(986 166)(986 166)(47 651)(1 033 817)\rVariation du pourcentage d'intérêt(38 420)(38 420)38 420\rRésultat consolidé de l'exercice 201636 915 93636 915 93697 58537 013 521\rCapitaux propres consolidés au 31 décembre 2016549 072 620(472 190 804)31 044 59936 915 936144 842 3514 586 13397 585149 526 069,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,NaN,Capital social,Réserves de\rrestructuration,Réserves\rconsolidées,Résultat de\rl'exercice,Total des\rcapitaux\rpropres (part\rdu groupe),Intérêts des\rminoritaires/\rréserves,Intérêts des\rminoritaires/\rrésultat,Total des\rcapitaux\rpropres
1,Capitaux propres consolidés au 31 décembre 2014,549 072 620,(472 190 804),25 131 472,25 825 670,127 838 958,5 122 688,(569 174),132 392 472,NaN
2,Affectation résultat\r\rDistribution des divi...,NaN,NaN,25 825 670\r(35 142 645)\r945 747\r972\r(32 205),(25 825 670)\r40 048 335,-\r(35 142 645)\r945 747\r972\r(32 205)\r40 04...,(569 174)\r(14 063)\r(37 542)\r32 237,569 174\r65 550,-\r(35 156 708)\r908 205\r972\r32\r40 113 885,NaN
3,Capitaux propres consolidés au 31 décembre 2015,549 072 620,(472 190 804),16 729 011,40 048 335,133 659 162,4 534 146,65 550,138 258 858,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Affectation résultat\rDistribution des divide...,NaN,NaN,40 048 335\r(24 708 161)\r(986 166)\r(38 420),(40 048 335)\r36 915 936,-\r(24 708 161)\r(986 166)\r(38 420)\r36 915 936,65 550\r(4 332)\r(47 651)\r38 420,(65 550)\r97 585,-\r(24 712 493)\r(1 033 817)\r37 013 521,NaN
6,Capitaux propres consolidés au 31 décembre 2016,549 072 620,(472 190 804),31 044 599,36 915 936,144 842 351,4 586 133,97 585,149 526 069,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Tableau 13 ---

                     Libellé  Solde au 31/12/2016 Solde au 31/12/2015
0          Fournisseurs d'exploitation 65 567 979          50 599 080
1          Fournisseurs effets à payer 14 713 413          11 269 248
2        Fournisseurs d'immobilisations 4 520 602           7 306 361
3   Fournisseurs factures non parvenues 5 970 878           4 208 016
4                                Total 90 772 872          73 382 705
..                                            ...                 ...
17                                Retenues 35 360             352 975
18                    Créditeurs divers 6 133 171          12 916 488
19                 Cotisations sociales 2 699 825           2 579 895
20                  Assurance au personnel 37 582              65 339
21                               Total 40 400 633          41 663 704

[22 rows x 2 columns]

--- Tableau 14 ---

                                           Unnamed: 0 Unnamed: 1
0                Note 24 : Charges financières nettes        NaN
1                                                 NaN        NaN
2   Les charges financières nettes s’élèvent à 8 7...        NaN
3                                                 NaN        NaN
4                                        Libellé 2016       2015
5               Agios et intérêts bancaires 3 036 686  3 748 725
6                     Intérêts sur emprunts 2 788 507  3 404 267
7                   Pertes/gains de changes 2 484 014    715 647
8                          Intérêts / Portage 467 192    747 881
9                                     Total 8 776 399  8 616 520
10                                                NaN        NaN
11                                                NaN        NaN
12                      Note 25 : Produits financiers        NaN
13                                                NaN        NaN
14  Les produits financiers s’élèvent à  1 217 833...        NaN
15                                                NaN        NaN
16                                       Libellé 2016       2015
17                  Produits des placements 1 178 550  1 876 389
18               Intérêts des comptes courants 39 283     33 709
19                                    Total 1 217 833  1 910 098

--- Tableau 15 ---

,Unnamed: 0,Unnamed: 1
0,NaN,Solde au 31/12/2016 Solde au 31/12/2015
1,"Liquidités, équivalents de liquidités et place...",NaN
2,Placements,17 400 000 15 500 000
3,Banques,14 053 618 25 875 934
4,Caisses,9 695 10 449
...,...,...
27,Nombre des actions en fin de période,54 907 262 54 907 262
28,NaN,NaN
29,Nombre moyen des actions (B),54 907 262 54 907 262
30,NaN,NaN
31,Résultat par action en dinars (A/B),"0,672 0,729"

============================================================
📅 Année : 2017 | 15 tableau(x)
============================================================

--- Tableau 1 ---

,Unnamed: 0,Notes,31.12.2017,31.12.2016
0,Actifs,NaN,NaN,NaN
1,Actifs non courants,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,Immobilisations incorporelles,NaN,4 682 765,3 978 911
4,-Amortissements Immobilisations incorporelles,NaN,(3 280 475),(2 519 206)
...,...,...,...,...
36,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN
38,Total des actifs courants,NaN,209 733 177,181 465 777
39,NaN,NaN,NaN,NaN
40,Total Actifs,NaN,445 523 093,397 467 573

--- Tableau 2 ---

,Total Capitaux propres consolidés avant résultat de l'exercice,Unnamed: 0,120 645 726,107 926 415
0,NaN,NaN,NaN,NaN
1,Résultat de l'exercice,NaN,38 624 678,36 915 936
2,NaN,NaN,NaN,NaN
3,Total Capitaux propres consolidés,NaN,159 270 404,144 842 351
4,NaN,NaN,NaN,NaN
...,...,...,...,...
22,Total des passifs courants,NaN,196 761 971,185 539 323
23,NaN,NaN,NaN,NaN
24,Total passifs,NaN,281 194 122,247 941 504
25,NaN,NaN,NaN,NaN
26,Total Capitaux propres et passifs,NaN,445 523 093,397 467 573

--- Tableau 3 ---

,Unnamed: 0,Notes,31.12.2017,31.12.2016
0,Capitaux propres et passifs,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,Capital social,NaN,549 072 620,549 072 620
3,Réserves de restructuration,NaN,(472 190 804),(472 190 804)
4,Réserves consolidés,NaN,43 763 910,31 044 599
5,NaN,NaN,NaN,NaN
6,Total Capitaux propres consolidés avant résult...,NaN,120 645 726,107 926 415

--- Tableau 4 ---

,Unnamed: 0,Notes,2017,2016
0,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,Revenus,(17),794 547 793,746 900 859
3,Autres produits d'exploitation,(18),14 681 121,16 835 309
4,NaN,NaN,NaN,NaN
...,...,...,...,...
30,Part revenant aux intérêts minoritaires,(11),426 742,97 585
31,Résultat net consolidé (part revenant au groupe),NaN,38 624 678,36 915 936
32,NaN,NaN,NaN,NaN
33,Nombre moyen des actions,NaN,54 907 262,54 907 262
34,NaN,NaN,"0,703","0,672"

--- Tableau 5 ---

,Unnamed: 0,Notes,2017,2016
0,Résultat net (Groupe),NaN,38 624 678,36 915 936
1,Ajustement pour:,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,*Part revenant aux intérêts minoritaires,(11),426 742,97 585
4,"*Amortissements, Provisions & Reprises de prov...",(21),31 962 737,32 593 313
...,...,...,...,...
44,NaN,NaN,NaN,NaN
45,(*) Variation de trésorerie,NaN,5 542 057,(2 347 225)
46,NaN,NaN,NaN,NaN
47,(*) Trésorerie au début de l'exercice,(27),20 702 284,23 049 509
48,(*) Trésorerie à la clôture de l'exercice,(27),26 244 341,20 702 284

--- Tableau 6 ---

,"La société Compagnie Fromagère « CF » est une société anonyme spécialisée dans la fabrication de\rproduits de fromage.\r\rDELTA Plastic est une société à responsabilité limitée créée en 2002 spécialisée dans la production des\rbouteilles et des emballages en plastique. L’activité de DELTA Plastic consiste exclusivement dans le\rtravail à façon pour le compte de la société du groupe STIAL. Elle produit les bouteilles en plastique\rpour l’emballage des produits DUNUP.\r\rLa Société Tunisienne de l’Industrie Alimentaire « STIAL » est une société anonyme créée en 1978\rspécialisée dans la fabrication et la vente de yaourt et autres dérivés de produits laitiers.\r\r\rLasociétédecommerceetdegestion« SOCOGES »estunesociétéàresponsabilitélimitée\rspécialisée dans la commercialisation et la distribution de tous produits, notamment les produits laitiers,\ralimentaires, agricoles et industriels. La SOCOGES assure la distribution des produits des sociétés du\rgroupe.\r\rII.Périmètre de consolidation au 31/12/2017\r\rLe périmètre de consolidation du groupe DELICE Holding est présenté au niveau du schéma suivant :\rDélice H olding\r49 ,62 %\r99,81 %\rSOCOGES\rCentraleLaitière\rDELTA Plastic99,99%\rdu Cap -Bon\r31 ,01%\rCompagnie\r26,49%\r1,26 %\rFromagère\r96,98 %Sté des Boissons98,73%\r43 ,01%96,43 %\rdu Cap B- on\rSTIAL\rCentrale LaitièreCentrale Laitière\rdu NordSidi Bouzid\r1,34%3,57%",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,"Délice H olding\r49 ,62 %\r99,81 %\rSOCOGES\rC...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,Délice H olding,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,SOCOGES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Tableau 7 ---

,"La société Compagnie Fromagère « CF » est une société anonyme spécialisée dans la fabrication de\rproduits de fromage.\r\rDELTA Plastic est une société à responsabilité limitée créée en 2002 spécialisée dans la production des\rbouteilles et des emballages en plastique. L’activité de DELTA Plastic consiste exclusivement dans le\rtravail à façon pour le compte de la société du groupe STIAL. Elle produit les bouteilles en plastique\rpour l’emballage des produits DUNUP.\r\rLa Société Tunisienne de l’Industrie Alimentaire « STIAL » est une société anonyme créée en 1978\rspécialisée dans la fabrication et la vente de yaourt et autres dérivés de produits laitiers.\r\r\rLasociétédecommerceetdegestion« SOCOGES »estunesociétéàresponsabilitélimitée\rspécialisée dans la commercialisation et la distribution de tous produits, notamment les produits laitiers,\ralimentaires, agricoles et industriels. La SOCOGES assure la distribution des produits des sociétés du\rgroupe.\r\rII.Périmètre de consolidation au 31/12/2017\r\rLe périmètre de consolidation du groupe DELICE Holding est présenté au niveau du schéma suivant :\rDélice H olding\r49 ,62 %\r99,81 %\rSOCOGES\rCentraleLaitière\rDELTA Plastic99,99%\rdu Cap -Bon\r31 ,01%\rCompagnie\r26,49%\r1,26 %\rFromagère\r96,98 %Sté des Boissons98,73%\r43 ,01%96,43 %\rdu Cap B- on\rSTIAL\rCentrale LaitièreCentrale Laitière\rdu NordSidi Bouzid\r1,34%3,57%",Unnamed: 0,Unnamed: 1
0,"Délice H olding\r49 ,62 %\r99,81 %\rSOCOGES\rC...",NaN,NaN
1,NaN,NaN,NaN
2,NaN,NaN,NaN
3,NaN,"96,98 %\r96,43 %",NaN

--- Tableau 8 ---

,"La société Compagnie Fromagère « CF » est une société anonyme spécialisée dans la fabrication de\rproduits de fromage.\r\rDELTA Plastic est une société à responsabilité limitée créée en 2002 spécialisée dans la production des\rbouteilles et des emballages en plastique. L’activité de DELTA Plastic consiste exclusivement dans le\rtravail à façon pour le compte de la société du groupe STIAL. Elle produit les bouteilles en plastique\rpour l’emballage des produits DUNUP.\r\rLa Société Tunisienne de l’Industrie Alimentaire « STIAL » est une société anonyme créée en 1978\rspécialisée dans la fabrication et la vente de yaourt et autres dérivés de produits laitiers.\r\r\rLasociétédecommerceetdegestion« SOCOGES »estunesociétéàresponsabilitélimitée\rspécialisée dans la commercialisation et la distribution de tous produits, notamment les produits laitiers,\ralimentaires, agricoles et industriels. La SOCOGES assure la distribution des produits des sociétés du\rgroupe.\r\rII.Périmètre de consolidation au 31/12/2017\r\rLe périmètre de consolidation du groupe DELICE Holding est présenté au niveau du schéma suivant :\rDélice H olding\r49 ,62 %\r99,81 %\rSOCOGES\rCentraleLaitière\rDELTA Plastic99,99%\rdu Cap -Bon\r31 ,01%\rCompagnie\r26,49%\r1,26 %\rFromagère\r96,98 %Sté des Boissons98,73%\r43 ,01%96,43 %\rdu Cap B- on\rSTIAL\rCentrale LaitièreCentrale Laitière\rdu NordSidi Bouzid\r1,34%3,57%",Unnamed: 0,Unnamed: 1,Unnamed: 2
0,"Délice H olding\r49 ,62 %\r99,81 %\rSOCOGES\rC...",NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN

--- Tableau 9 ---

,"La société Compagnie Fromagère « CF » est une société anonyme spécialisée dans la fabrication de\rproduits de fromage.\r\rDELTA Plastic est une société à responsabilité limitée créée en 2002 spécialisée dans la production des\rbouteilles et des emballages en plastique. L’activité de DELTA Plastic consiste exclusivement dans le\rtravail à façon pour le compte de la société du groupe STIAL. Elle produit les bouteilles en plastique\rpour l’emballage des produits DUNUP.\r\rLa Société Tunisienne de l’Industrie Alimentaire « STIAL » est une société anonyme créée en 1978\rspécialisée dans la fabrication et la vente de yaourt et autres dérivés de produits laitiers.\r\r\rLasociétédecommerceetdegestion« SOCOGES »estunesociétéàresponsabilitélimitée\rspécialisée dans la commercialisation et la distribution de tous produits, notamment les produits laitiers,\ralimentaires, agricoles et industriels. La SOCOGES assure la distribution des produits des sociétés du\rgroupe.\r\rII.Périmètre de consolidation au 31/12/2017\r\rLe périmètre de consolidation du groupe DELICE Holding est présenté au niveau du schéma suivant :\rDélice H olding\r49 ,62 %\r99,81 %\rSOCOGES\rCentraleLaitière\rDELTA Plastic99,99%\rdu Cap -Bon\r31 ,01%\rCompagnie\r26,49%\r1,26 %\rFromagère\r96,98 %Sté des Boissons98,73%\r43 ,01%96,43 %\rdu Cap B- on\rSTIAL\rCentrale LaitièreCentrale Laitière\rdu NordSidi Bouzid\r1,34%3,57%",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,"Délice H olding\r49 ,62 %\r99,81 %\rSOCOGES\rC...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,Délice H olding,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,SOCOGES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Tableau 10 ---

,Société,% de contrôle,% d’intérêts groupe,Type de contrôle,Méthode de comptabilisation
0,DELICE Holding,100%,100%,Société mère,NaN
1,CLC,"99,81%","99,81%",Contrôle exclusif,Intégration globale
2,CLN,"98,33%","98,15%",Contrôle exclusif,Intégration globale
3,CLSB,"100,00%","99,82%",Contrôle exclusif,Intégration globale
4,SBC,"99,99%","99,99%",Contrôle exclusif,Intégration globale
5,CF,"57,50%","57,50%",Contrôle exclusif,Intégration globale
6,Delta plastic,"99,99%","99,99%",Contrôle exclusif,Intégration globale

--- Tableau 11 ---

,Unnamed: 0,La valeur nette des immobilisations incorporelles et corporelles s’élève à 218 098 655 dinars au 31 décembre 2017 et se détaille comme suit :,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,NaN,Entrées,NaN,NaN,NaN
1,NaN,Amortissements,Amortissements,NaN,NaN
2,NaN,Montants en KDT VB Dec16 Cessions Reclassemen...,NaN,VCN 2016,VCN 2017
3,NaN,31/12/2017 cumulés 2016,Cumulés 2017,NaN,NaN
4,NaN,Régul 2017,NaN,NaN,NaN
...,...,...,...,...,...
21,Avances et acomptes sur immobilisations,1 653 978 79 101(1 571 133) 161 946 - - -,-,1 653 978,161 946
22,Provisions constituées,- - - - - 1 538 951 (292 647) (35 725),1 210 579,(1 538 951),(1 210 579)
23,Total immobilisations corporelles,398 003 078 53 957 569 (6 953 219) (1 145 001)...,227 166 062,195 476 282,216 696 365
24,Total immobilisations incorporelles et,NaN,NaN,NaN,NaN
25,corporelles,401 981 988 54 688 704 (6 953 219) (1 172 282)...,230 446 537,196 935 987,218 098 655

--- Tableau 12 ---

,Libellé,Solde au 31/12/2017,Solde au 31/12/2016
0,Actifs d'impôts différés CLN,2 067 968,3 357 063
1,Actifs d'impôts différés CF,1 625 851,1 889 568
2,Actifs d'impôts différés CLC,993 712,522 966
3,Actifs d'impôts différés STIAL,1 404 697,1 359 553
4,Actifs d'impôts différés SBC,604 650,603 481
5,Actifs d'impôts différés SOCOGES,867 062,599 931
6,Actifs d'impôts différés Delta plastic,191 997,193 030
7,NaN,NaN,NaN
8,Actif d'impôts différés,7 755 937,8 525 592

--- Tableau 13 ---

,Note 11 : Capitaux propres\rTABLEAU DES MOUVEMENTS DES CAPITAUX PROPRES\rExercice clos le 31 Décembre 2017\rTotal des\rIntérêts desIntérêts desTotal des\rCapitalRéserves deRéservesRésultat decapitaux\rminoritaires/minoritaires/capitaux\rsocialrestructurationconsolidéesl'exercicepropres (part\rréservesrésultatpropres\rdu groupe)\r\rCapitaux propres consolidés au 31 décembre 2015549 072 620\r(472 190 804)16 729 01140 048 335133 659 1624 534 14665 550138 258 8\r\r\rAffectation résultat\r40 048 335(40 048 335)-65 550(65 550)\r\rDistribution des dividendes\r(24 708 161)(24 708 161)(4 332)(24 712 49\r\rSubvention d'investissement\r(986 166)(986 166)(47 651)(1 003 81\r\rVariation du pourcentage d'intérêt\r(38 420)(38 420)38 420\r\rRésultat consolidé de l'exercice 2016\r36 915 93636 915 93697 58537 013 5\r\r\rCapitaux propres consolidés au 31 décembre 2016549 072 620\r(472 190 804)31 044 59936 915 936144 842 3514 586 13397 585149 526 0\r\r\rAffectation résultat\r36 915 936(36 915 936)-97 585(97 585)\r\rDistribution des dividendes\r(23 062 943)(23 062 943)(8 456)(23 071 39\r\rSubvention d'investissement\r(1 128 740)(1 128 740)(48 378)(1 177 11\r\rVariation du pourcentage d'intérêt\r(4 942)-(4 942)4 942\r\rRésultat consolidé de l'exercice 2017\r38 624 67838 624 678426 74239 051 4\r\r\rCapitaux propres consolidés au 31 décembre 2017549 072 620\r(472 190 804)43 763 91038 624 678159 270 4044 631 825426 742164 328 9,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Capitaux propres consolidés au 31 décembre 2015,549 072 620,(472 190 804),16 729 011,40 048 335,133 659 162,4 534 146,65 550,138 258 8,8
1,Affectation résultat\r\rDistribution des divi...,NaN,NaN,40 048 335\r(24 708 161)\r(986 166)\r(38 420),(40 048 335)\r36 915 936,-\r(24 708 161)\r(986 166)\r(38 420)\r36 915 936,65 550\r(4 332)\r(47 651)\r38 420,(65 550)\r97 585,(24 712 49\r(1 003 81\r37 013 5,-\r)\r)\r1
2,Capitaux propres consolidés au 31 décembre 2016,549 072 620,(472 190 804),31 044 599,36 915 936,144 842 351,4 586 133,97 585,149 526 0,9
3,Affectation résultat\r\rDistribution des divi...,NaN,NaN,36 915 936\r(23 062 943)\r(1 128 740)\r(4 942),(36 915 936)\r-\r38 624 678,-\r(23 062 943)\r(1 128 740)\r(4 942)\r38 624 678,97 585\r(8 456)\r(48 378)\r4 942,(97 585)\r426 742,(23 071 39\r(1 177 11\r39 051 4,-\r)\r)\r-\r0
4,Capitaux propres consolidés au 31 décembre 2017,549 072 620,(472 190 804),43 763 910,38 624 678,159 270 404,4 631 825,426 742,164 328 9,1

--- Tableau 14 ---

,Note 11 : Capitaux propres\rTABLEAU DES MOUVEMENTS DES CAPITAUX PROPRES\rExercice clos le 31 Décembre 2017\rTotal des\rIntérêts desIntérêts desTotal des\rCapitalRéserves deRéservesRésultat decapitaux\rminoritaires/minoritaires/capitaux\rsocialrestructurationconsolidéesl'exercicepropres (part\rréservesrésultatpropres\rdu groupe)\r\rCapitaux propres consolidés au 31 décembre 2015549 072 620\r(472 190 804)16 729 01140 048 335133 659 1624 534 14665 550138 258 8\r\r\rAffectation résultat\r40 048 335(40 048 335)-65 550(65 550)\r\rDistribution des dividendes\r(24 708 161)(24 708 161)(4 332)(24 712 49\r\rSubvention d'investissement\r(986 166)(986 166)(47 651)(1 003 81\r\rVariation du pourcentage d'intérêt\r(38 420)(38 420)38 420\r\rRésultat consolidé de l'exercice 2016\r36 915 93636 915 93697 58537 013 5\r\r\rCapitaux propres consolidés au 31 décembre 2016549 072 620\r(472 190 804)31 044 59936 915 936144 842 3514 586 13397 585149 526 0\r\r\rAffectation résultat\r36 915 936(36 915 936)-97 585(97 585)\r\rDistribution des dividendes\r(23 062 943)(23 062 943)(8 456)(23 071 39\r\rSubvention d'investissement\r(1 128 740)(1 128 740)(48 378)(1 177 11\r\rVariation du pourcentage d'intérêt\r(4 942)-(4 942)4 942\r\rRésultat consolidé de l'exercice 2017\r38 624 67838 624 678426 74239 051 4\r\r\rCapitaux propres consolidés au 31 décembre 2017549 072 620\r(472 190 804)43 763 91038 624 678159 270 4044 631 825426 742164 328 9,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,Capital\rsocial,Réserves de\rrestructuration,Réserves\rconsolidées,Résultat de\rl'exercice,Total des\rcapitaux\rpropres (part\rdu groupe),Intérêts des\rminoritaires/\rréserves,Intérêts des\rminoritaires/\rrésultat,Total des\rcapitaux\rpropres
1,Capitaux propres consolidés au 31 décembre 2015,549 072 620,(472 190 804),16 729 011,40 048 335,133 659 162,4 534 146,65 550,138 258 8
2,Affectation résultat\r\rDistribution des divi...,NaN,NaN,40 048 335\r(24 708 161)\r(986 166)\r(38 420),(40 048 335)\r36 915 936,-\r(24 708 161)\r(986 166)\r(38 420)\r36 915 936,65 550\r(4 332)\r(47 651)\r38 420,(65 550)\r97 585,(24 712 49\r(1 003 81\r37 013 5
3,Capitaux propres consolidés au 31 décembre 2016,549 072 620,(472 190 804),31 044 599,36 915 936,144 842 351,4 586 133,97 585,149 526 0
4,Affectation résultat\r\rDistribution des divi...,NaN,NaN,36 915 936\r(23 062 943)\r(1 128 740)\r(4 942),(36 915 936)\r-\r38 624 678,-\r(23 062 943)\r(1 128 740)\r(4 942)\r38 624 678,97 585\r(8 456)\r(48 378)\r4 942,(97 585)\r426 742,(23 071 39\r(1 177 11\r39 051 4
5,Capitaux propres consolidés au 31 décembre 2017,549 072 620,(472 190 804),43 763 910,38 624 678,159 270 404,4 631 825,426 742,164 328 9

--- Tableau 15 ---

,Unnamed: 0,Unnamed: 1
0,NaN,Solde au 31/12/2017 Solde au 31/12/2016
1,"Liquidités, équivalents de liquidités (A)",NaN
2,Banques,21 465 589 14 053 618
3,Caisses,11 608 9 695
4,Intérêts courus / liquidités,15 153 -
...,...,...
27,Nombre des actions en fin de période,54 907 262 54 907 262
28,NaN,NaN
29,Nombre moyen des actions (B),54 907 262 54 907 262
30,NaN,NaN
31,Résultat par action en dinars (A/B),"0,703 0,672"

============================================================
📅 Année : 2018 | 13 tableau(x)
============================================================

--- Tableau 1 ---

,Unnamed: 0,Notes,31.12.2018,31.12.2017
0,Actifs,NaN,NaN,NaN
1,Actifs non courants,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,Immobilisations incorporelles,NaN,4 914 908,4 682 765
4,-Amortissements Immobilisations incorporelles,NaN,(4 080 187),(3 280 475)
...,...,...,...,...
35,Liquidités et équivalents de liquidités,(10),32 014 544,29 364 303
36,NaN,NaN,NaN,NaN
37,Total des actifs courants,NaN,258 793 851,209 733 177
38,NaN,NaN,NaN,NaN
39,Total Actifs,NaN,526 946 725,445 523 093

--- Tableau 2 ---

,Groupe DELICE\rBILAN CONSOLIDE\r(Exprimé en dinars tunisiens)\r\r\rNotes31.12.201831.12.2017\rCapitaux propres et passifs\r\rCapital social549 072 620549 072 620\rRéserves de restructuration(472 190 804)(472 190 804)\rRéserves consolidés64 324 95743 763 910\r\rTotal Capitaux propres consolidés avant résultat de l'exercice141 206 773120 645 726\r\rRésultat de l'exercice\r30 891 57038 624 678\r\rTotal Capitaux propres consolidés172 098 343159 270 404\r\rIntérêts des minoritaires\r10 194 3375 058 567\r\rTotal Capitaux propres consolidés et intérêts minoritaires(11)182 292 680164 328 971\r\rPassifs non courants\r\rEmprunts(12)112 299 43465 059 521\rProvisions pour risques et charges(13)17 024 55416 732 674\rPassifs d'impôts différés(14)1 292 2232 639 956\r\r\rTotal des passifs non courants130 616 21184 432 151\r\rPassifs courants\r\rFournisseurs et comptes rattachés(15)105 514 26498 778 899\rAutres passifs courants(16)43 061 05143 718 923\rConcours bancaires et autres passifs financiers(10)65 462 51954 264 149\r\r\rTotal des passifs courants214 037 834196 761 971\r\rTotal passifs344 654 045281 194 122\r\r\rTotal Capitaux propres et passifs526 946 725445 523 093,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,Total Capitaux propres consolidés avant résult...,NaN,NaN,141 206 77,NaN,NaN,120 645 72,NaN,NaN
1,NaN,NaN,30 891 570,38 624 67,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Résultat de l'exercice,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Résultat de l'exercice,30 891 57,38 624 67,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,NaN,Total Capitaux propres et passifs,NaN,NaN,NaN,526 946 72,NaN,NaN,445 523 09,NaN
65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Tableau 3 ---

,Groupe DELICE\rBILAN CONSOLIDE\r(Exprimé en dinars tunisiens)\r\r\rNotes31.12.201831.12.2017\rCapitaux propres et passifs\r\rCapital social549 072 620549 072 620\rRéserves de restructuration(472 190 804)(472 190 804)\rRéserves consolidés64 324 95743 763 910\r\rTotal Capitaux propres consolidés avant résultat de l'exercice141 206 773120 645 726\r\rRésultat de l'exercice\r30 891 57038 624 678\r\rTotal Capitaux propres consolidés172 098 343159 270 404\r\rIntérêts des minoritaires\r10 194 3375 058 567\r\rTotal Capitaux propres consolidés et intérêts minoritaires(11)182 292 680164 328 971\r\rPassifs non courants\r\rEmprunts(12)112 299 43465 059 521\rProvisions pour risques et charges(13)17 024 55416 732 674\rPassifs d'impôts différés(14)1 292 2232 639 956\r\r\rTotal des passifs non courants130 616 21184 432 151\r\rPassifs courants\r\rFournisseurs et comptes rattachés(15)105 514 26498 778 899\rAutres passifs courants(16)43 061 05143 718 923\rConcours bancaires et autres passifs financiers(10)65 462 51954 264 149\r\r\rTotal des passifs courants214 037 834196 761 971\r\rTotal passifs344 654 045281 194 122\r\r\rTotal Capitaux propres et passifs526 946 725445 523 093,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,Notes,NaN,NaN,31.12.2018,NaN,NaN,31.12.2017,NaN
1,Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Tableau 4 ---

,Groupe DELICE\rBILAN CONSOLIDE\r(Exprimé en dinars tunisiens)\r\r\rNotes31.12.201831.12.2017\rCapitaux propres et passifs\r\rCapital social549 072 620549 072 620\rRéserves de restructuration(472 190 804)(472 190 804)\rRéserves consolidés64 324 95743 763 910\r\rTotal Capitaux propres consolidés avant résultat de l'exercice141 206 773120 645 726\r\rRésultat de l'exercice\r30 891 57038 624 678\r\rTotal Capitaux propres consolidés172 098 343159 270 404\r\rIntérêts des minoritaires\r10 194 3375 058 567\r\rTotal Capitaux propres consolidés et intérêts minoritaires(11)182 292 680164 328 971\r\rPassifs non courants\r\rEmprunts(12)112 299 43465 059 521\rProvisions pour risques et charges(13)17 024 55416 732 674\rPassifs d'impôts différés(14)1 292 2232 639 956\r\r\rTotal des passifs non courants130 616 21184 432 151\r\rPassifs courants\r\rFournisseurs et comptes rattachés(15)105 514 26498 778 899\rAutres passifs courants(16)43 061 05143 718 923\rConcours bancaires et autres passifs financiers(10)65 462 51954 264 149\r\r\rTotal des passifs courants214 037 834196 761 971\r\rTotal passifs344 654 045281 194 122\r\r\rTotal Capitaux propres et passifs526 946 725445 523 093,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,Notes,NaN,NaN,31.12.2018,NaN,NaN,31.12.2017,NaN
1,Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,NaN,Total Capitaux propres et passifs,NaN,NaN,NaN,526 946 72,NaN,NaN,445 523 09,NaN,NaN,NaN
73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Tableau 5 ---

,Unnamed: 0,Notes,2018,2017
0,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,Revenus,(17),844 483 415,794 547 793
3,Autres produits d'exploitation,(18),7 296 451,14 681 121
4,NaN,NaN,NaN,NaN
...,...,...,...,...
35,Résultat net consolidé (part revenant au groupe),NaN,30 891 570,38 624 678
36,NaN,NaN,NaN,NaN
37,Nombre moyen des actions,NaN,54 907 262,54 907 262
38,NaN,NaN,NaN,NaN
39,NaN,NaN,"0,563","0,703"

--- Tableau 6 ---

,Unnamed: 0,Notes,2018,2017
0,Résultat net (Groupe),NaN,30 891 570,38 624 678
1,Ajustement pour :,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,*Part revenant aux intérêts minoritaires,(11),(838 435),426 742
4,"*Amortissements, Provisions & Reprises de prov...",(21),36 332 192,31 962 737
...,...,...,...,...
34,NaN,NaN,NaN,NaN
35,Variation de trésorerie,NaN,(3 932 175),5 542 057
36,NaN,NaN,NaN,NaN
37,Trésorerie au début de l'exercice,(27),26 244 341,20 702 284
38,Trésorerie à la clôture de l'exercice,(27),22 312 166,26 244 341

--- Tableau 7 ---

,,"La société « DELICE Holding » est une société anonyme de droit tunisien, constituée le 20 Mai 2014."
0,NaN,"Lors de la création de la société, le capital ..."
1,NaN,chacune. Conformément à la première résolution...
2,NaN,"Août 2013, les actionnaires ont décidé d’augme..."
3,NaN,"pour le porter à 154.188.880 dinars, et ce par..."
4,NaN,chacune. L’assemblée générale extraordinaire ...
...,...,...
20,,DELTA Plastic est une société à responsabilité...
21,NaN,bouteilles et des emballages en plastique. L’a...
22,NaN,travail à façon pour le compte de la société d...
23,NaN,pour l’emballage des produits DUNUP.
24,,La Société Tunisienne de l’Industrie Alimentai...

--- Tableau 8 ---

,Société,% de contrôle,% d’intérêts groupe,Type de contrôle,Méthode de comptabilisation
0,DELICE Holding,100%,100%,Société mère,NaN
1,CLC,"99,81%","99,81%",Contrôle exclusif,Intégration globale
2,CLN,"98,33%","98,15%",Contrôle exclusif,Intégration globale
3,CLSB,"100,00%","99,81%",Contrôle exclusif,Intégration globale
4,SBC,"99,99%","99,99%",Contrôle exclusif,Intégration globale
5,CF,"50,00%","50,00%",Contrôle exclusif,Intégration globale
6,Delta plastic,"99,99%","99,99%",Contrôle exclusif,Intégration globale

--- Tableau 9 ---

,Immobilisations corporelles,508 023 749,443 862 427
0,AmortissementsConstructions,(21 045 140),(18 036 297)
1,AmortissementsMatériel industriel,(143 470 320),(134 035 321)
2,AmortissementsOutillage industriel,(5 292 489),(4 567 344)
3,AmortissementsMatériel de transport,(30 290 600),(27 095 687)
4,"Amortissementsinstallations Techniques,",NaN,NaN
5,NaN,(35 012 144),(30 149 637)
6,"agencements, aménagements et installations divers",NaN,NaN
7,AmortissementsEquipements de bureau,(1 594 147),(1 392 687)
8,AmortissementsMatériel informatique,(7 585 395),(6 892 368)
9,AmortissementsMatériel d'emballage,(2 650 634),(1 778 166)
10,AmortissementsAutres Equipements,(2 103 075),(2 007 975)

--- Tableau 10 ---

                                Outillage industriel    7 943 014    7 283 843
0                              Matériel de transport   43 819 426   43 359 305
1  Installations Techniques, agencements, aménage...          NaN          NaN
2                                                NaN   64 191 884   55 531 526
3                            et installations divers          NaN          NaN
4                              Equipements de bureau    2 127 083    2 090 827
5                              Matériel informatique    9 100 871    8 614 919
6                               Matériel d'emballage    3 478 173    2 982 739
7                                 Autres Equipements    2 149 512    2 149 512
8                           Immobilisations en cours   53 422 205   33 869 102
9                        Immobilisations corporelles  508 023 749  443 862 427

--- Tableau 11 ---

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,VB AMORT,Unnamed: 6,Amortissements/,Amortissements,Unnamed: 7,Unnamed: 8
0,NaN,Montants en KDT,VB Dec17,Entrées,Cession,reclassements,VCN 2018 Decembre18 2017,Dotations 2018,Cession/Reprise,Cumulés 18,VCN 2017,NaN
1,Logiciels,NaN,4 361 247,387 854,-,(6 055),4 743 047 3 233 555,799 712,-,4 033 267,1 176 670,709 780
2,Concessions de marques et brevets,NaN,46 920,-,-,-,46 920 46 920,-,-,46 920,-,-
3,Immobilisations incorporelles en cours,NaN,274 598,(28 517),(121 140),-,124 941,- -,-,-,225 612,124 941
4,Total immobilisations incorporelles,NaN,4 682 765,359 337,(121 140),(6 055),4 914 908 3 280 475,799 712,-,4 080 187,1 402 283,834 721
...,...,...,...,...,...,...,...,...,...,...,...,...
16,Immobilisations en cours,NaN,33 869 102,49 060 439,(1 433 973),(28 073 362),53 422 205,- -,-,-,33 869 102,53 422 205
17,Provisions constituées,NaN,-,-,-,-,- 1 210 579,433 218,397 283,1 246 514,(1 210 579),(1 246 514)
18,Total immobilisations corporelles,NaN,443 862 427,98 057 079,(11 576 155),(22 319 602),508 023 749 227 166 062,34 209 635,11 028 081,250 290 457,216 696 365,257 733 292
19,Total immobilisations incorporelles et,NaN,448 545 192,98 416 416,(11 697 295),(22 325 657),512 938 657 230 446 537,35 009 347,11 028 081,254 370 644,218 098 648,258 568 013
20,coporelles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Tableau 12 ---

,Unnamed: 0,Note 11 : Capitaux propres\rTABLEAU DES MOUVEMENTS DES CAPITAUX PROPRES\rExercice clos le 31 Décembre 2018\rTotal des\rIntérêts desIntérêts desTotal des\rCapitalRéserves deRéservesRésultat de\rcapitaux\rminoritaires/minoritaires/capitaux\rsocialrestructurationconsolidéesl'exercice\rpropres (part\rréservesrésultatpropres\rdu groupe),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,Capital\rsocial,Réserves de\rrestructuration,Réserves\rconsolidées,Résultat de\rl'exercice,Total des\rcapitaux\rpropres (part\rdu groupe),Intérêts des\rminoritaires/\rréserves,Intérêts des\rminoritaires/\rrésultat,Total des\rcapitaux\rpropres,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Capitaux propres consolidés au 31 décembre 2016,549 072 620,(472 190 804),31 044 599,36 915 936,144 842 351,4 586 133,97 585,149 526 069,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Affectation résultat\r\rDistribution des divid...,NaN,NaN,36 915 936\r\r(23 062 943)\r\r(1 128 740)\r\r(...,(36 915 936)\r38 624 678,-\r(23 062 943)\r(1 128 740)\r(4 942)\r38 624 678,97 585\r(8 456)\r(48 378)\r4 942,(97 585)\r426 742,-\r\r(23 071 399)\r\r(1 177 119)\r\r-\r\r39 05...,NaN
...,...,...,...,...,...,...,...,...,...,...,...
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,Capitaux propres consolidés au 31 décembre 2018,549 072 620,(472 190 804),64 324 957,30 891 570,172 098 343,11 032 772,(838 435),182 292 680,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Tableau 13 ---

                            Libellé Solde au 31/12/2018 Solde au 31/12/2017
0                   Charges à payer          11 414 988          10 456 743
1       Clients avances et acomptes           6 820 142           5 304 026
2              Comptes de personnel           4 285 775           3 603 777
3              Cotisations sociales           3 800 911           3 973 678
4                 Etat impôts/taxes           5 198 123           6 824 618
5  Actionnaires, dividendes à payer           7 498 492           8 898 603
6                 Créditeurs divers           4 042 620           4 657 479
7                             Total          43 061 051          43 718 923

============================================================
📅 Année : 2020 | 13 tableau(x)
============================================================

--- Tableau 1 ---

,Unnamed: 0,Notes,31.12.2020,31.12.2019
0,Actifs,NaN,NaN,NaN
1,Actifs non courants,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,Immobilisations incorporelles,NaN,5 542 934,5 121 340
4,-Amortissements Immobilisations incorporelles,NaN,(4 918 016),(4 623 618)
...,...,...,...,...
35,Liquidités et équivalents de liquidités,(10),64 368 386,62 697 550
36,NaN,NaN,NaN,NaN
37,Total des actifs courants,NaN,342 425 415,322 173 968
38,NaN,NaN,NaN,NaN
39,Total Actifs,NaN,671 939 505,640 918 067

--- Tableau 2 ---

,Groupe DELICE\rBILAN CONSOLIDE\r(Exprimé en dinars tunisiens)\r\r\r\rNotes31.12.202031.12.2019\rCapitaux propres et passifs\r\r\rCapital social549 072 620549 072 620\rRéserves de restructuration(472 190 804)(472 190 804)\rRéserves consolidés106 449 96580 884 039\r\rTotal Capitaux propres consolidés avant résultat de l'exercice183 331 781157 765 855\r\rRésultat de l'exercice\r57 816 01846 529 346\r\rTotal Capitaux propres consolidés241 147 799204 295 201\r\rIntérêts des minoritaires\r9 546 5416 700 063\r\rTotal Capitaux propres consolidés et intérêts minoritaires(11)250 694 340210 995 264\r\rPassifs non courants\r\rEmprunts(12)146 424 752148 009 232\rProvisions pour risques et charges(13)24 102 76319 918 024\rPassifs d'impôts différés(14)3 956 4452 488 418\r\r\rTotal des passifs non courants174 483 960170 415 674\r\rPassifs courants\r\rFournisseurs et comptes rattachés(15)129 182 531112 273 321\rAutres passifs courants(16)46 604 15543 251 113\rConcours bancaires et autres passifs financiers(10)70 974 519103 982 695\r\r\rTotal des passifs courants246 761 205259 507 129\r\rTotal passifs421 245 165429 922 803\r\r\rTotal Capitaux propres et passifs671 939 505640 918 067,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,Notes,NaN,NaN,31.12.2020,NaN,NaN,31.12.2019,NaN
1,Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Tableau 3 ---

,Groupe DELICE\rBILAN CONSOLIDE\r(Exprimé en dinars tunisiens)\r\r\r\rNotes31.12.202031.12.2019\rCapitaux propres et passifs\r\r\rCapital social549 072 620549 072 620\rRéserves de restructuration(472 190 804)(472 190 804)\rRéserves consolidés106 449 96580 884 039\r\rTotal Capitaux propres consolidés avant résultat de l'exercice183 331 781157 765 855\r\rRésultat de l'exercice\r57 816 01846 529 346\r\rTotal Capitaux propres consolidés241 147 799204 295 201\r\rIntérêts des minoritaires\r9 546 5416 700 063\r\rTotal Capitaux propres consolidés et intérêts minoritaires(11)250 694 340210 995 264\r\rPassifs non courants\r\rEmprunts(12)146 424 752148 009 232\rProvisions pour risques et charges(13)24 102 76319 918 024\rPassifs d'impôts différés(14)3 956 4452 488 418\r\r\rTotal des passifs non courants174 483 960170 415 674\r\rPassifs courants\r\rFournisseurs et comptes rattachés(15)129 182 531112 273 321\rAutres passifs courants(16)46 604 15543 251 113\rConcours bancaires et autres passifs financiers(10)70 974 519103 982 695\r\r\rTotal des passifs courants246 761 205259 507 129\r\rTotal passifs421 245 165429 922 803\r\r\rTotal Capitaux propres et passifs671 939 505640 918 067,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,Total Capitaux propres consolidés avant résult...,NaN,NaN,183 331 78,NaN,NaN,157 765 85,NaN,NaN
1,NaN,NaN,57 816 018,46 529 346,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Résultat de l'exercice,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Résultat de l'exercice,57 816 018,46 529 34,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,NaN,Total Capitaux propres et passifs,NaN,NaN,NaN,671 939 505,NaN,NaN,640 918 06,NaN
65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Tableau 4 ---

,Groupe DELICE\rBILAN CONSOLIDE\r(Exprimé en dinars tunisiens)\r\r\r\rNotes31.12.202031.12.2019\rCapitaux propres et passifs\r\r\rCapital social549 072 620549 072 620\rRéserves de restructuration(472 190 804)(472 190 804)\rRéserves consolidés106 449 96580 884 039\r\rTotal Capitaux propres consolidés avant résultat de l'exercice183 331 781157 765 855\r\rRésultat de l'exercice\r57 816 01846 529 346\r\rTotal Capitaux propres consolidés241 147 799204 295 201\r\rIntérêts des minoritaires\r9 546 5416 700 063\r\rTotal Capitaux propres consolidés et intérêts minoritaires(11)250 694 340210 995 264\r\rPassifs non courants\r\rEmprunts(12)146 424 752148 009 232\rProvisions pour risques et charges(13)24 102 76319 918 024\rPassifs d'impôts différés(14)3 956 4452 488 418\r\r\rTotal des passifs non courants174 483 960170 415 674\r\rPassifs courants\r\rFournisseurs et comptes rattachés(15)129 182 531112 273 321\rAutres passifs courants(16)46 604 15543 251 113\rConcours bancaires et autres passifs financiers(10)70 974 519103 982 695\r\r\rTotal des passifs courants246 761 205259 507 129\r\rTotal passifs421 245 165429 922 803\r\r\rTotal Capitaux propres et passifs671 939 505640 918 067,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,Notes,NaN,NaN,31.12.2020,NaN,NaN,31.12.2019,NaN
1,Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,NaN,Total Capitaux propres et passifs,NaN,NaN,NaN,671 939 505,NaN,NaN,640 918 06,NaN,NaN,NaN
73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Tableau 5 ---

,Unnamed: 0,Notes,2020,2019
0,Résultat net (Groupe),NaN,57 816 018,46 529 346
1,Ajustement pour :,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,* Part revenant aux intérêts minoritaires,(11),417 611,(3 518 125)
4,"* Amortissements, Provisions & Reprises de pro...",(21),52 649 276,46 778 673
...,...,...,...,...
35,NaN,NaN,NaN,NaN
36,Variation de trésorerie,NaN,12 940 024,19 468 008
37,NaN,NaN,NaN,NaN
38,Trésorerie au début de l'exercice,(27),41 780 174,22 312 166
39,Trésorerie à la clôture de l'exercice,(27),54 720 198,41 780 174

--- Tableau 6 ---

,,"La société « DELICE Holding » est une société anonyme de droit tunisien, constituée le 20 Mai 2014."
0,NaN,"Lors de la création de la société, le capital ..."
1,NaN,chacune. Conformément à la première résolution...
2,NaN,"Août 2013, les actionnaires ont décidé d’augme..."
3,NaN,"pour le porter à 154.188.880 dinars, et ce par..."
4,NaN,chacune. L’assemblée générale extraordinaire ...
...,...,...
20,,DELTA Plastic est une société à responsabilité...
21,NaN,bouteilles et des emballages en plastique. L’a...
22,NaN,travail à façon pour le compte de la société d...
23,NaN,pour l’emballage des produits DUNUP.
24,,La Société Tunisienne de l’Industrie Alimentai...

--- Tableau 7 ---

,Société,% de contrôle,% d’intérêts groupe,Type de contrôle,Méthode de comptabilisation
0,DELICE Holding,100%,100%,Société mère,NaN
1,CLC,"99,81%","99,81%",Contrôle exclusif,Intégration globale
2,CLN,"98,33%","98,15%",Contrôle exclusif,Intégration globale
3,CLSB,"99,95%","99,76%",Contrôle exclusif,Intégration globale
4,SBC,"99,99%","99,99%",Contrôle exclusif,Intégration globale
5,CF,"50,00%","50,00%",Contrôle exclusif,Intégration globale
6,Delta plastic,"99,99%","99,99%",Contrôle exclusif,Intégration globale
7,SDEM,"99,99%","99,76%",Contrôle exclusif,Intégration globale
8,STIAL,"43,01%","43,01%",Contrôle conjoint,Intégration proportionnelle
9,SOCOGES,"50,00%","50,00%",Contrôle conjoint,Intégration proportionnelle

--- Tableau 8 ---

,Unnamed: 0,Libellé,Solde au 31/12/2020,Solde au 31/12/2019
0,Logiciels,NaN,5 213 550,4 984 403
1,Concessions de marques et brevets,NaN,46 920,46 920
2,Immobilisations incorporelles en cours,NaN,282 465,90 018
3,Immobilisations corporelles,NaN,5 542 935,5 121 340
4,Amortissements,Logiciels,(4 871 097),(4 576 698)
...,...,...,...,...
34,Amortissements,Matériel d'emballage,(2 343 373),(3 003 633)
35,Amortissements,Autres Equipements,(2 145 717),(2 140 914)
36,Provisions sur immobilisations corporelles,NaN,(1 592 613),(1 255 937)
37,Amortissements Immobilisations corporelles,NaN,(321 216 779),(285 155 628)
38,Immobilisations corporelles nettes,NaN,321 071 026,307 149 359

--- Tableau 9 ---

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,reclassements,Unnamed: 6,Unnamed: 7,Unnamed: 8,Amortissem,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VB Decembre,NaN,NaN,NaN,Reprise &,Amortissements,NaN,NaN
1,NaN,Montants en KDT,VB Dec19,Entrées,Cession,NaN,&,NaN,AMORT 2019,Dotations 2020,ents/Cession,NaN,NaN,VCN 2019,VCN 2020
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20,NaN,NaN,NaN,retraitements,Cumulés 20,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,retraitements,NaN,NaN,NaN,/Reprise,NaN,NaN,NaN,NaN
4,Logiciels,NaN,4 984 403,41 100,-,NaN,188 047,5 213 550,4 576 699,294 398,-,-,4 871 097,407 704,342 453
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16,Matériel d'emballage,NaN,4 098 060,215 331,(1 282 969),NaN,683 392,3 713 813,3 003 633,731 722,1 372 872,(19 110),2 343 373,1 094 427,1 370 441
17,Autres Equipements,NaN,2 149 512,3 150,-,NaN,-,2 152 662,2 140 914,4 803,-,-,2 145 717,8 598,6 945
18,Immobilisations en cours,NaN,33 760 315,42 087 962,-,NaN,(51 234 853),24 613 424,-,-,-,-,-,33 760 315,24 613 424
19,Prov isions constituées,NaN,-,-,-,NaN,-,-,1 255 937,480 997,144 320,-,1 592 613,(1 255 937),(1 592 613)
20,Total immobilisations corporelles,NaN,592 304 987,59 383 319,(6 694 372),NaN,(2 706 128),642 287 805,285 155 627,42 902 281,6 069 006,(772 123),321 216 779,307 149 359,321 071 026

--- Tableau 10 ---

,Note 11 : Capitaux propres\rTABLEAU DES MOUVEMENTS DES CAPITAUX PROPRES\rExercice clos le 31 Décembre 2020\rTotal des\rIntérêts desIntérêts desTotal des\rCapitalRéserves deRéservesRésultat de\rcapitaux\rminoritaires/minoritaires/capitaux\rsocialrestructurationconsolidéesl'exercice\rpropres (part\rréservesrésultatpropres\rdu groupe)\r\rCapitaux propres consolidés au 31 décembre 2018549 072 620\r(472 190 804)64 324 95730 891 570172 098 34311 032 772(838 435)182 292 680\r\rAffectation résultat\r30 891 570(30 891 570)(838 435)838 435-\r\r\rDistribution des dividendes\r(22 536 503)(22 536 503)(10 024)(22 546 527)\r\r\rSubvention d'investissement\r8 314 3258 314 325(22 842)8 291 483\r\r\rVariation du pourcentage d'intérêt\r(110 310)(110 310)56 717(53 593)\r\r\rRésultat consolidé de l'exercice 2019\r46 529 34646 529 346(3 518 125)43 011 221\r\r\rCapitaux propres consolidés au 31 décembre 2019549 072 620\r(472 190 804)80 884 03946 529 346204 295 20110 218 188(3 518 125)210 995 264\r\rAffectation résultat\r46 529 346(46 529 346)(3 518 125)3 518 125-\r\r\rDistribution des dividendes\r(18 284 118)(18 284 118)(46 401)(18 330 519)\r\r\rSubvention d'investissement\r(2 679 214)(2 679 214)(24 940)(2 704 154)\r\r\rVariation du pourcentage d'intérêt\r(88)(88)88-\r\r\rAugmentation du capital\r2 500 1202 500 120\r\r\rRésultat consolidé de l'exercice 2020\r57 816 01857 816 018417 61158 233 629\r\r\rCapitaux propres consolidés au 31 décembre 2020549 072 620\r(472 190 804)106 449 96557 816 018241 147 7999 128 930417 611250 694 340,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Capitaux propres consolidés au 31 décembre 2018,549 072 620,(472 190 804),64 324 957,30 891 570,172 098 343,11 032 772,(838 435),182 292 680
1,Affectation résultat\r\rDistribution des divid...,NaN,NaN,30 891 570\r\r(22 536 503)\r\r8 314 325\r\r(11...,(30 891 570)\r46 529 346,(22 536 503)\r8 314 325\r(110 310)\r46 529 346,(838 435)\r(10 024)\r(22 842)\r56 717,838 435\r(3 518 125),-\r\r(22 546 527)\r\r8 291 483\r\r(53 593)\r\r...
2,Capitaux propres consolidés au 31 décembre 2019,549 072 620,(472 190 804),80 884 039,46 529 346,204 295 201,10 218 188,(3 518 125),210 995 264
3,Affectation résultat\r\rDistribution des divid...,NaN,NaN,46 529 346\r\r(18 284 118)\r\r(2 679 214)\r\r(88),(46 529 346)\r57 816 018,(18 284 118)\r(2 679 214)\r(88)\r57 816 018,(3 518 125)\r(46 401)\r(24 940)\r88\r2 500 120,3 518 125\r417 611,-\r\r(18 330 519)\r\r(2 704 154)\r\r-\r\r2 500...
4,Capitaux propres consolidés au 31 décembre 2020,549 072 620,(472 190 804),106 449 965,57 816 018,241 147 799,9 128 930,417 611,250 694 340

--- Tableau 11 ---

,Note 11 : Capitaux propres\rTABLEAU DES MOUVEMENTS DES CAPITAUX PROPRES\rExercice clos le 31 Décembre 2020\rTotal des\rIntérêts desIntérêts desTotal des\rCapitalRéserves deRéservesRésultat de\rcapitaux\rminoritaires/minoritaires/capitaux\rsocialrestructurationconsolidéesl'exercice\rpropres (part\rréservesrésultatpropres\rdu groupe)\r\rCapitaux propres consolidés au 31 décembre 2018549 072 620\r(472 190 804)64 324 95730 891 570172 098 34311 032 772(838 435)182 292 680\r\rAffectation résultat\r30 891 570(30 891 570)(838 435)838 435-\r\r\rDistribution des dividendes\r(22 536 503)(22 536 503)(10 024)(22 546 527)\r\r\rSubvention d'investissement\r8 314 3258 314 325(22 842)8 291 483\r\r\rVariation du pourcentage d'intérêt\r(110 310)(110 310)56 717(53 593)\r\r\rRésultat consolidé de l'exercice 2019\r46 529 34646 529 346(3 518 125)43 011 221\r\r\rCapitaux propres consolidés au 31 décembre 2019549 072 620\r(472 190 804)80 884 03946 529 346204 295 20110 218 188(3 518 125)210 995 264\r\rAffectation résultat\r46 529 346(46 529 346)(3 518 125)3 518 125-\r\r\rDistribution des dividendes\r(18 284 118)(18 284 118)(46 401)(18 330 519)\r\r\rSubvention d'investissement\r(2 679 214)(2 679 214)(24 940)(2 704 154)\r\r\rVariation du pourcentage d'intérêt\r(88)(88)88-\r\r\rAugmentation du capital\r2 500 1202 500 120\r\r\rRésultat consolidé de l'exercice 2020\r57 816 01857 816 018417 61158 233 629\r\r\rCapitaux propres consolidés au 31 décembre 2020549 072 620\r(472 190 804)106 449 96557 816 018241 147 7999 128 930417 611250 694 340,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,Capital\rsocial,Réserves de\rrestructuration,Réserves\rconsolidées,Résultat de\rl'exercice,Total des\rcapitaux\rpropres (part,Intérêts des\rminoritaires/\rréserves,Intérêts des\rminoritaires/\rrésultat,Total des\rcapitaux\rpropres
1,Capitaux propres consolidés au 31 décembre 2018,549 072 620,(472 190 804),64 324 957,30 891 570,172 098 343,11 032 772,(838 435),182 292 680
2,Affectation résultat\r\rDistribution des divid...,NaN,NaN,30 891 570\r\r(22 536 503)\r\r8 314 325\r\r(11...,(30 891 570)\r46 529 346,(22 536 503)\r8 314 325\r(110 310)\r46 529 346,(838 435)\r(10 024)\r(22 842)\r56 717,838 435\r(3 518 125),-\r\r(22 546 527)\r\r8 291 483\r\r(53 593)\r\r...
3,Capitaux propres consolidés au 31 décembre 2019,549 072 620,(472 190 804),80 884 039,46 529 346,204 295 201,10 218 188,(3 518 125),210 995 264
4,Affectation résultat\r\rDistribution des divid...,NaN,NaN,46 529 346\r\r(18 284 118)\r\r(2 679 214)\r\r(88),(46 529 346)\r57 816 018,(18 284 118)\r(2 679 214)\r(88)\r57 816 018,(3 518 125)\r(46 401)\r(24 940)\r88\r2 500 120,3 518 125\r417 611,-\r\r(18 330 519)\r\r(2 704 154)\r\r-\r\r2 500...
5,Capitaux propres consolidés au 31 décembre 2020,549 072 620,(472 190 804),106 449 965,57 816 018,241 147 799,9 128 930,417 611,250 694 340

--- Tableau 12 ---

                               Unnamed: 0        2020        2019
0                                     NaN         NaN         NaN
1              Résultat net consolidé (A)  57 816 018  46 529 346
2                                     NaN         NaN         NaN
3  Nombre des actions en début de période  54 907 262  54 907 262
4                                     NaN         NaN         NaN
5    Nombre des actions en fin de période  54 907 262  54 907 262
6                                     NaN         NaN         NaN
7            Nombre moyen des actions (B)  54 907 262  54 907 262
8                                     NaN         NaN         NaN
9     Résultat par action en dinars (A/B)       1,053       0,847

--- Tableau 13 ---

  Unnamed: 0                          Désignation Montant en DT
0        NaN  Nantissement du fonds de commerce et matériel ...
1        NaN  Nantissement du fonds de commerce et matériel ...
2        NaN                                    TOTAL 8 000 000
3        NaN                                                NaN
4          -  La SBC a obtenu deux emprunts auprès d’ATTIJAR...
5        NaN  rémunérés au taux de TMM + 1%. En garantie des...
6        NaN  du Cap Bon a accordé des hypothèques immobiliè...
7        NaN          et du matériel au profit d’Attijari Bank.
8        NaN                                                NaN
9          -  La « CLC » a accordé des hypothèques et des na...

============================================================
📅 Année : 2021 | 12 tableau(x)
============================================================

--- Tableau 1 ---

,Unnamed: 0,(6),126 827 942,144 343 732
0,NaN,NaN,NaN,NaN
1,Clients et comptes rattachés,NaN,42 570 921,35 619 603
2,-Provisions dépréciation des clients,NaN,(7 501 854),(6 816 027)
3,NaN,(7),35 069 067,28 803 576
4,NaN,NaN,NaN,NaN
5,Autres actifs courants,NaN,154 107 169,106 579 096
6,-Provisions dépréciation des autres actifs cou...,NaN,(2 473 424),(2 365 645)
7,NaN,(8),151 633 745,104 213 451
8,NaN,NaN,NaN,NaN
9,Placements et autres actifs financiers,(9),17 632 453,696 270
10,NaN,NaN,NaN,NaN
11,Liquidités et équivalents de liquidités,(10),63 946 637,64 368 386
12,NaN,NaN,NaN,NaN
13,Total des actifs courants,NaN,395 109 844,342 425 415
14,NaN,NaN,NaN,NaN
15,Total Actifs,NaN,708 409 044,671 939 505

--- Tableau 2 ---

,Unnamed: 0,Notes,31.12.2021,31.12.2020
0,Actifs,NaN,NaN,NaN
1,Actifs non courants,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,Immobilisations incorporelles,NaN,6 499 706,5 542 934
4,-Amortissements Immobilisations incorporelles,NaN,(5 266 185),(4 918 016)
...,...,...,...,...
18,Total des actifs non courants,NaN,313 299 200,329 514 090
19,Actifs courants,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN
21,Stocks,NaN,140 848 268,156 232 823
22,- Provisions pour dépréciation des stocks,NaN,(14 020 326),(11 889 091)

--- Tableau 3 ---

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,NaN,Groupe DELICE,NaN,NaN
1,NaN,ETAT DE RESULTAT CONSOLIDE,NaN,NaN
2,NaN,(Exprimé en dinars tunisiens),NaN,NaN
3,NaN,NaN,NaN,NaN
4,NaN,Notes 2021,NaN,2020
...,...,...,...,...
27,Part revenant aux intérêts minoritaires,(11) 1 652 081,NaN,417 611
28,Résultat net consolidé (part revenant au groupe),70 352 493,NaN,57 816 018
29,Nombre moyen des actions,54 907 262,NaN,54 907 262
30,NaN,"(28) 1,281",NaN,"1,053"
31,* : Montants retraités pour les besoins de com...,NaN,NaN,NaN

--- Tableau 4 ---

                               Unnamed: 0 Notes        2021        2020
0                   Résultat net (Groupe)   NaN  70 352 493  57 816 018
1                       Ajustement pour :   NaN         NaN         NaN
2                                     NaN   NaN         NaN         NaN
3                                     NaN   NaN         NaN         NaN
4                                     NaN   NaN         NaN         NaN
..                                    ...   ...         ...         ...
42                                    NaN   NaN         NaN         NaN
43                                    NaN   NaN         NaN         NaN
44      Trésorerie au début de l'exercice   NaN  54 720 197  41 780 174
45                                    NaN   NaN         NaN         NaN
46  Trésorerie à la clôture de l'exercice  (27)  59 187 800  54 720 198

[47 rows x 4 columns]

--- Tableau 5 ---

,,"La société « DELICE Holding » est une société anonyme de droit tunisien, constituée le 20 Mai 2014."
0,NaN,"Lors de la création de la société, le capital ..."
1,NaN,chacune. Conformément à la première résolution...
2,NaN,"Août 2013, les actionnaires ont décidé d’augme..."
3,NaN,"pour le porter à 154.188.880 dinars, et ce par..."
4,NaN,chacune. L’assemblée générale extraordinaire ...
...,...,...
20,,DELTA Plastic est une société à responsabilité...
21,NaN,bouteilles et des emballages en plastique. L’a...
22,NaN,travail à façon pour le compte de la société d...
23,NaN,pour l’emballage des produits DUNUP.
24,,La Société Tunisienne de l’Industrie Alimentai...

--- Tableau 6 ---

,Société,% contrôle,% d'intérêts,Type de contrôle,Méthode de comptabilisation
0,DH,"100,00%","100,00%",Contrôle exclusif,Intégration globale
1,CLN,"98,33%","98,18%",Contrôle exclusif,Intégration globale
2,CLC,"99,81%","99,81%",Contrôle exclusif,Intégration globale
3,SDEM,"99,99%","99,76%",Contrôle exclusif,Intégration globale
4,SBC,"99,99%","99,99%",Contrôle exclusif,Intégration globale
5,Delta plastic,"99,99%","99,99%",Contrôle exclusif,Intégration globale
6,CF,"50,00%","50,00%",Contrôle exclusif,Intégration globale
7,CLSB,"99,95%","99,76%",Contrôle exclusif,Intégration globale
8,STIAL,"43,01%","43,01%",Contrôle conjoint,Intégration proportionnelle
9,SOCOGES,"50,00%","50,00%",Contrôle conjoint,Intégration proportionnelle
10,GDI LISSADIRAT,"100,00%","100,00%",Contrôle exclusif,Intégration globale

--- Tableau 7 ---

,AmortissementsEquipements de bureau,Unnamed: 0,(2 316 456),(1 989 393)
0,AmortissementsMatériel informatique,NaN,(9 887 107),(9 031 912)
1,AmortissementsMatériel d'emballage,NaN,(2 984 685),(2 343 373)
2,AmortissementsAutres Equipements,NaN,(2 158 492),(2 145 717)
3,Provisions sur immobilisations corporelles,NaN,(1 813 662),(1 592 613)
4,Amortissements Immobilisations corporelles,NaN,(362 296 576),(321 216 779)
5,Immobilisations corporelles nettes,NaN,303 821 316,321 071 026

--- Tableau 8 ---

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,reclassement,Unnamed: 6,Unnamed: 7,Unnamed: 8,Amortissement,Unnamed: 9,Amortissements,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VB Décembre,NaN,NaN,NaN,Reprise &,NaN,NaN,NaN
1,NaN,Montants en KDT,VB Dec20,Entrées,Cession,NaN,s &,NaN,AMORT 2020,Dotations 2021,s/Cession/Repri,NaN,&Provisions,VCN 2020,VCN 2021
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21,NaN,NaN,NaN,retraitements,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,retraitements,NaN,NaN,NaN,se,NaN,Cumulés 21,NaN,NaN
4,Logiciels,NaN,5 213 550,111 315,-,NaN,978 493,6 303 358,4 871 096,331 369,-,16 800,5 219 266,342 453,1 084 092
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19,Immobilisations en cours,NaN,24 613 424,16 564 353,(6 675 291),NaN,(18 461 174),16 041 314,-,-,-,-,-,24 613 424,16 041 314
20,Prov isions constituées,NaN,-,-,-,NaN,-,-,1 592 613,221 049,-,-,1 813 662,(1 592 613),(1 813 662)
21,Total immobilisations corporelles,NaN,642 287 805,37 788 947,(13 117 069),NaN,(841 792),666 117 891,321 216 779,47 438 402,6 358 605,-,362 296 576,321 071 026,303 821 316
22,Total immobilisations incorporelles et,NaN,647 830 740,38 282 828,(13 117 069),NaN,(378 901),672 617 597,326 134 795,47 786 534,6 358 605,38,367 562 761,321 695 944,305 054 836
23,corporelles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Tableau 9 ---

,Note 11 : Capitaux propres\rTABLEAU DES MOUVEMENTS DES CAPITAUX PROPRES\rExercice clos le 31 Décembre 2021\r\rTotal des\rcapitauxIntérêts desIntérêts desTotal des\rCapitalRéserves deRéservesRésultat de\rpropresminoritaires/minoritaires/capitaux\rsocialrestructurationconsolidéesl'exercice\r(part duréservesrésultatpropres\rgroupe)\r\r\rCapitaux propres consolidés au 31 décembre 2019549 072 620(472 190 804)80 884 03946 529 346204 295 20110 218 188(3 518 125)210 995 264\r\r\r\r\rAffectation résultat46 529 346(46 529 346)(3 518 125)3 518 125-\r\rDistribution des dividendes(18 284 118)(18 284 118)(46 401)(18 330 519)\r\rSubvention d'investissement(2 679 214)(2 679 214)(24 940)(2 704 154)\r\rVariation du pourcentage d'intérêt(88)(88)88-\r\rAugmentation du capital2 500 1202 500 120\r\rRésultat consolidé de l'exercice 202057 816 01857 816 018417 61158 233 629\r\r\rCapitaux propres consolidés au 31 décembre 2020549 072 620(472 190 804)106 449 96557 816 018241 147 7999 128 930417 611250 694 340\r\r\rAffectation résultat57 816 018(57 816 018)417 611(417 611)-\r\rDistribution des dividendes(20 315 688)(20 315 688)(121)(20 315 809)\r\rSubvention d'investissement(806 015)(806 015)25 976(780 040)\r\rVariation du pourcentage d'intérêt2 7462 74641 25343 999\r\rAugmentation du capital2 500 1202 500 120\r\rRésultat consolidé de l'exercice 202170 352 49370 352 4931 652 08172 004 574\r\r\rCapitaux propres consolidés au 31 décembre 2021549 072 620(472 190 804)143 147 02570 352 493290 381 33412 113 7691 652 081304 147 184,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Capitaux propres consolidés au 31 décembre 2019,549 072 620,(472 190 804),80 884 039,46 529 346,204 295 201,10 218 188,(3 518 125),210 995 264
1,Affectation résultat\r\rDistribution des divid...,NaN,NaN,46 529 346\r\r(18 284 118)\r\r(2 679 214)\r\r(88),(46 529 346)\r\r\r\r\r\r\r\r\r\r57 816 018,(18 284 118)\r\r(2 679 214)\r\r(88)\r\r\r\r57 ...,(3 518 125)\r\r(46 401)\r\r(24 940)\r\r88\r\r2...,3 518 125\r\r\r\r\r\r\r\r\r\r417 611,-\r\r(18 330 519)\r\r(2 704 154)\r\r-\r\r2 500...
2,Capitaux propres consolidés au 31 décembre 2020,549 072 620,(472 190 804),106 449 965,57 816 018,241 147 799,9 128 930,417 611,250 694 340
3,Affectation résultat\r\rDistribution des divid...,NaN,NaN,57 816 018\r\r(20 315 688)\r\r(806 015)\r\r2 746,(57 816 018)\r\r\r\r\r\r\r\r\r\r70 352 493,(20 315 688)\r\r(806 015)\r\r2 746\r\r\r\r70 3...,417 611\r\r(121)\r\r25 976\r\r41 253\r\r2 500 120,(417 611)\r\r\r\r\r\r\r\r\r\r1 652 081,-\r\r(20 315 809)\r\r(780 040)\r\r43 999\r\r2 ...
4,Capitaux propres consolidés au 31 décembre 2021,549 072 620,(472 190 804),143 147 025,70 352 493,290 381 334,12 113 769,1 652 081,304 147 184

--- Tableau 10 ---

,Note 11 : Capitaux propres\rTABLEAU DES MOUVEMENTS DES CAPITAUX PROPRES\rExercice clos le 31 Décembre 2021\r\rTotal des\rcapitauxIntérêts desIntérêts desTotal des\rCapitalRéserves deRéservesRésultat de\rpropresminoritaires/minoritaires/capitaux\rsocialrestructurationconsolidéesl'exercice\r(part duréservesrésultatpropres\rgroupe)\r\r\rCapitaux propres consolidés au 31 décembre 2019549 072 620(472 190 804)80 884 03946 529 346204 295 20110 218 188(3 518 125)210 995 264\r\r\r\r\rAffectation résultat46 529 346(46 529 346)(3 518 125)3 518 125-\r\rDistribution des dividendes(18 284 118)(18 284 118)(46 401)(18 330 519)\r\rSubvention d'investissement(2 679 214)(2 679 214)(24 940)(2 704 154)\r\rVariation du pourcentage d'intérêt(88)(88)88-\r\rAugmentation du capital2 500 1202 500 120\r\rRésultat consolidé de l'exercice 202057 816 01857 816 018417 61158 233 629\r\r\rCapitaux propres consolidés au 31 décembre 2020549 072 620(472 190 804)106 449 96557 816 018241 147 7999 128 930417 611250 694 340\r\r\rAffectation résultat57 816 018(57 816 018)417 611(417 611)-\r\rDistribution des dividendes(20 315 688)(20 315 688)(121)(20 315 809)\r\rSubvention d'investissement(806 015)(806 015)25 976(780 040)\r\rVariation du pourcentage d'intérêt2 7462 74641 25343 999\r\rAugmentation du capital2 500 1202 500 120\r\rRésultat consolidé de l'exercice 202170 352 49370 352 4931 652 08172 004 574\r\r\rCapitaux propres consolidés au 31 décembre 2021549 072 620(472 190 804)143 147 02570 352 493290 381 33412 113 7691 652 081304 147 184,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Capital\rsocial,Réserves de\rrestructuration,Réserves\rconsolidées,Résultat de\rl'exercice,Total des\rcapitaux\rpropres\r(part du\rgroupe),Intérêts des\rminoritaires/\rréserves,Intérêts des\rminoritaires/\rrésultat,Total des\rcapitaux\rpropres,NaN
1,Capitaux propres consolidés au 31 décembre 2019,549 072 620,(472 190 804),80 884 039,46 529 346,204 295 201,10 218 188,(3 518 125),210 995 264
2,Affectation résultat\r\rDistribution des divid...,NaN,NaN,46 529 346\r\r(18 284 118)\r\r(2 679 214)\r\r(88),(46 529 346)\r\r\r\r\r\r\r\r\r\r57 816 018,(18 284 118)\r\r(2 679 214)\r\r(88)\r\r\r\r57 ...,(3 518 125)\r\r(46 401)\r\r(24 940)\r\r88\r\r2...,3 518 125\r\r\r\r\r\r\r\r\r\r417 611,-\r\r(18 330 519)\r\r(2 704 154)\r\r-\r\r2 500...
3,Capitaux propres consolidés au 31 décembre 2020,549 072 620,(472 190 804),106 449 965,57 816 018,241 147 799,9 128 930,417 611,250 694 340
4,Affectation résultat\r\rDistribution des divid...,NaN,NaN,57 816 018\r\r(20 315 688)\r\r(806 015)\r\r2 746,(57 816 018)\r\r\r\r\r\r\r\r\r\r70 352 493,(20 315 688)\r\r(806 015)\r\r2 746\r\r\r\r70 3...,417 611\r\r(121)\r\r25 976\r\r41 253\r\r2 500 120,(417 611)\r\r\r\r\r\r\r\r\r\r1 652 081,-\r\r(20 315 809)\r\r(780 040)\r\r43 999\r\r2 ...
5,Capitaux propres consolidés au 31 décembre 2021,549 072 620,(472 190 804),143 147 025,70 352 493,290 381 334,12 113 769,1 652 081,304 147 184

--- Tableau 11 ---

                                     Total 58 002 228  52 649 276
0                                                 NaN         NaN
1             Note 22 : Autres charges d'exploitation         NaN
2                                                 NaN         NaN
3   Les autres charges d’exploitation s’élèvent à ...         NaN
4                                                 NaN         NaN
5                       Libellé 31/12/2021 31/12/2020         NaN
6                                                 NaN         NaN
7                                Publicité 19 841 069  16 968 788
8   Honoraires & rémunération d'intermédiaire 7 26...   6 662 182
9                   Entretien & réparation 13 061 422   9 068 190
10                                Locations 8 206 789   9 442 861
11                      Charges d'assurance 2 363 902   2 690 290
12                               Redevances 3 093 885   2 752 357

--- Tableau 12 ---

   Unnamed: 0                          Désignation Montant en DT
0         NaN  Nantissement du fonds de commerce et matériel ...
1         NaN  Nantissement du fonds de commerce et matériel ...
2         NaN  Nantissement de fonds de commerce et matériel ...
3         NaN                                   TOTAL 14 000 000
4         NaN                                                NaN
5           -  La SBC a obtenu deux emprunts auprès d’ATTIJAR...
6         NaN  rémunérés au taux de TMM + 1%. En garantie des...
7         NaN  du Cap Bon a accordé des hypothèques immobiliè...
8         NaN          et du matériel au profit d’Attijari Bank.
9         NaN                                                NaN
10          -  En garantie du crédit de gestion octroyé en 20...
11        NaN  Délice des Eaux Minérales a accordé des nantis...
12        NaN      installé à l'usine au profit d’Attijari Bank.
13        NaN                                                NaN
14          -  La « CLC » a accordé des hypothèques et des na...

============================================================
📅 Année : 2022 | 14 tableau(x)
============================================================

--- Tableau 1 ---

,Unnamed: 0,Notes,31.12.2022,31.12.2021
0,Actifs,NaN,NaN,NaN
1,Actifs non courants,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,Immobilisations incorporelles,NaN,6 899 131,6 499 706
4,-Amortissements Immobilisations incorporelles,NaN,(5 760 424),(5 266 185)
...,...,...,...,...
35,Liquidités et équivalents de liquidités,(10),59 162 798,63 946 637
36,NaN,NaN,NaN,NaN
37,Total des actifs courants,NaN,518 208 067,395 109 844
38,NaN,NaN,NaN,NaN
39,Total Actifs,NaN,815 104 818,708 409 044

--- Tableau 2 ---

,Groupe DELICE\rBILAN CONSOLIDE\r(Exprimé en dinars tunisiens)\r\rNotes31.12.202231.12.2021\rCapitaux propres et passifs\r\r\r\rCapital social549 072 620549 072 620\rRéserves de restructuration(472 190 804)(472 190 804)\rRéserves consolidés193 021 304143 147 025\r\r\rTotal Capitaux propres consolidés avant résultat de l'exercice269 903 120220 028 841\r\r\rRésultat de l'exercice78 543 63570 352 493\r\r\rTotal Capitaux propres consolidés\r348 446 755290 381 334\r\r\rIntérêts des minoritaires15 742 51413 765 850\r\r\rTotal Capitaux propres consolidés et intérêts minoritaires(11)364 189 269304 147 184\r\r\rPassifs non courants\r\rEmprunts(12)121 411 794128 812 489\rProvisions(13)37 117 82027 934 475\rPassifs d'impôts différés(14)9 977 5356 227 650\r\r\rTotal des passifs non courants\r168 507 149162 974 614\r\r\rPassifs courants\r\r\r\rFournisseurs et comptes rattachés(15)152 436 335144 756 817\rAutres passifs courants(16)47 902 00745 756 425\rConcours bancaires et autres passifs financiers(10)82 070 05850 774 004\r\r\rTotal des passifs courants\r282 408 400241 287 246\r\r\rTotal passifs\r450 915 549404 261 860\r\r\rTotal Capitaux propres et passifs\r815 104 818708 409 044,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,Notes,NaN,NaN,31.12.2022,NaN,NaN,31.12.2021,NaN
1,Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
53,Total passifs,NaN,450 915 549,404 261 860,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,Total passifs,NaN,450 915 549,404 261 860,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,NaN,Total Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,815 104 818,NaN,NaN,708 409 044,NaN

--- Tableau 3 ---

,Groupe DELICE\rBILAN CONSOLIDE\r(Exprimé en dinars tunisiens)\r\rNotes31.12.202231.12.2021\rCapitaux propres et passifs\r\r\r\rCapital social549 072 620549 072 620\rRéserves de restructuration(472 190 804)(472 190 804)\rRéserves consolidés193 021 304143 147 025\r\r\rTotal Capitaux propres consolidés avant résultat de l'exercice269 903 120220 028 841\r\r\rRésultat de l'exercice78 543 63570 352 493\r\r\rTotal Capitaux propres consolidés\r348 446 755290 381 334\r\r\rIntérêts des minoritaires15 742 51413 765 850\r\r\rTotal Capitaux propres consolidés et intérêts minoritaires(11)364 189 269304 147 184\r\r\rPassifs non courants\r\rEmprunts(12)121 411 794128 812 489\rProvisions(13)37 117 82027 934 475\rPassifs d'impôts différés(14)9 977 5356 227 650\r\r\rTotal des passifs non courants\r168 507 149162 974 614\r\r\rPassifs courants\r\r\r\rFournisseurs et comptes rattachés(15)152 436 335144 756 817\rAutres passifs courants(16)47 902 00745 756 425\rConcours bancaires et autres passifs financiers(10)82 070 05850 774 004\r\r\rTotal des passifs courants\r282 408 400241 287 246\r\r\rTotal passifs\r450 915 549404 261 860\r\r\rTotal Capitaux propres et passifs\r815 104 818708 409 044,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,Total Capitaux propres consolidés avant résult...,NaN,NaN,269 903 120,NaN,NaN,220 028 841,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Résultat de l'exercice,NaN,NaN,78 543 635,NaN,NaN,70 352 493,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
47,Total passifs,NaN,450 915 549,404 261 860,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Total passifs,NaN,450 915 549,404 261 860,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,Total Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,815 104 818,NaN,NaN,708 409 044,NaN

--- Tableau 4 ---

,Groupe DELICE\rBILAN CONSOLIDE\r(Exprimé en dinars tunisiens)\r\rNotes31.12.202231.12.2021\rCapitaux propres et passifs\r\r\r\rCapital social549 072 620549 072 620\rRéserves de restructuration(472 190 804)(472 190 804)\rRéserves consolidés193 021 304143 147 025\r\r\rTotal Capitaux propres consolidés avant résultat de l'exercice269 903 120220 028 841\r\r\rRésultat de l'exercice78 543 63570 352 493\r\r\rTotal Capitaux propres consolidés\r348 446 755290 381 334\r\r\rIntérêts des minoritaires15 742 51413 765 850\r\r\rTotal Capitaux propres consolidés et intérêts minoritaires(11)364 189 269304 147 184\r\r\rPassifs non courants\r\rEmprunts(12)121 411 794128 812 489\rProvisions(13)37 117 82027 934 475\rPassifs d'impôts différés(14)9 977 5356 227 650\r\r\rTotal des passifs non courants\r168 507 149162 974 614\r\r\rPassifs courants\r\r\r\rFournisseurs et comptes rattachés(15)152 436 335144 756 817\rAutres passifs courants(16)47 902 00745 756 425\rConcours bancaires et autres passifs financiers(10)82 070 05850 774 004\r\r\rTotal des passifs courants\r282 408 400241 287 246\r\r\rTotal passifs\r450 915 549404 261 860\r\r\rTotal Capitaux propres et passifs\r815 104 818708 409 044,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,Notes,NaN,NaN,31.12.2022,NaN,NaN,31.12.2021,NaN
1,Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Tableau 5 ---

,Unnamed: 0,Groupe DELICE,Unnamed: 1,Unnamed: 2
0,NaN,ETAT DE RESULTAT CONSOLIDE,NaN,NaN
1,NaN,(Exprimé en dinars tunisiens),NaN,NaN
2,NaN,NaN,NaN,NaN
3,NaN,Notes,2022,2021
4,NaN,NaN,NaN,NaN
...,...,...,...,...
25,Résultat Net de l'exercice,NaN,80 870 602,72 004 574
26,Part revenant aux intérêts minoritaires,(11),2 326 967,1 652 081
27,Résultat net consolidé (part revenant au groupe),NaN,78 543 635,70 352 493
28,Nombre moyen des actions,NaN,54 907 262,54 907 262
29,NaN,(28),"1,430","1,281"

--- Tableau 6 ---

                               Unnamed: 0       Notes 2022        2021
0                   Résultat net (Groupe)       78 543 635  70 352 493
1                       Ajustement pour :              NaN         NaN
2                                     NaN              NaN         NaN
3                                     NaN              NaN         NaN
4                                     NaN              NaN         NaN
..                                    ...              ...         ...
41                                    NaN              NaN         NaN
42                                    NaN              NaN         NaN
43      Trésorerie au début de l'exercice       59 187 800  54 720 197
44                                    NaN              NaN         NaN
45  Trésorerie à la clôture de l'exercice  (27) 54 106 903  59 187 800

[46 rows x 3 columns]

--- Tableau 7 ---

,,"La société « DELICE Holding » est une société anonyme de droit tunisien, constituée le 20 Mai 2014."
0,NaN,"Lors de la création de la société, le capital ..."
1,NaN,chacune. Conformément à la première résolution...
2,NaN,"Août 2013, les actionnaires ont décidé d’augme..."
3,NaN,"dinars pour le porter à 154.188.880 dinars, et..."
4,NaN,dinars chacune. L’assemblée générale extraordi...
...,...,...
20,,DELTA Plastic est une société à responsabilité...
21,NaN,des bouteilles et des emballages en plastique....
22,NaN,dans le travail à façon pour le compte de la s...
23,NaN,plastique pour l’emballage des produits DUNUP.
24,,La Société Tunisienne de l’Industrie Alimentai...

--- Tableau 8 ---

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,Société,% contrôle,% d'intérêts,Type de contrôle,Méthode de comptabilisation
1,DH,NaN,"100,00%","100,00%",Contrôle exclusif,Intégration globale
2,CLN,NaN,"98,33%","98,18%",Contrôle exclusif,Intégration globale
3,CLC,NaN,"99,81%","99,81%",Contrôle exclusif,Intégration globale
4,SDEM,NaN,"99,99%","99,76%",Contrôle exclusif,Intégration globale
5,SBC,NaN,"99,99%","99,99%",Contrôle exclusif,Intégration globale
6,Delta plastic,NaN,"99,99%","99,99%",Contrôle exclusif,Intégration globale
7,CF,NaN,"50,00%","50,00%",Contrôle exclusif,Intégration globale
8,CLSB,NaN,"99,95%","99,76%",Contrôle exclusif,Intégration globale
9,STIAL,NaN,"43,01%","43,01%",Contrôle conjoint,Intégration proportionnelle
10,SOCOGES,NaN,"50,00%","50,00%",Contrôle conjoint,Intégration proportionnelle
11,GDI LISSADIRAT,NaN,"100,00%","100,00%",Contrôle exclusif,Intégration globale
12,DELICE ACADEMY,NaN,"90,00%","90,00%",Contrôle exclusif,Intégration globale

--- Tableau 9 ---

,AmortissementsEquipements de bureau,Unnamed: 0,(2 597 454),(2 316 456)
0,AmortissementsMatériel informatique,NaN,(9 830 239),(9 887 107)
1,AmortissementsMatériel d'emballage,NaN,(3 587 898),(2 984 685)
2,AmortissementsAutres Equipements,NaN,(2 176 444),(2 158 492)
3,Provisions sur immobilisations corporelles,NaN,(1 713 633),(1 813 662)
4,Amortissements Immobilisations corporelles,NaN,(407 376 770),(362 296 576)
5,Immobilisations corporelles nettes,NaN,287 298 240,303 821 316

--- Tableau 10 ---

                                 Unnamed: 0 Libellé  31/12/2022  31/12/2021
0                                       NaN     NaN         NaN         NaN
1                        Concours bancaires     NaN   5 055 895   4 758 837
2  Crédits financement cycle d'exploitation     NaN  36 000 000   3 000 000
3         Emprunts échéance à moins d'un an     NaN  11 945 706  12 627 105
4                    Financement en devises     NaN  11 984 877  15 801 280
5                           Intérêts courus     NaN  17 083 580  14 586 783
6                                       NaN     NaN         NaN         NaN
7                                     Total     NaN  82 070 058  50 774 004

--- Tableau 11 ---

,Note 11 : Capitaux propres\rTABLEAU DES MOUVEMENTS DES CAPITAUX PROPRES\rExercice clos le 31 Décembre 2022\r\rTotal des\rIntérêts desIntérêts desTotal des\rCapitalRéserves deRéservesRésultat decapitaux\rminoritaires/minoritaires/capitaux\rsocialrestructurationconsolidéesl'exercicepropres (part\rréservesrésultatpropres\rdu groupe)\r\r\rCapitaux propres consolidés au 31 décembre 2020549 072 620(472 190 804)106 449 96557 816 018241 147 7999 128 930417 611250 694 340\r\r\r\r\rAffectation résultat57 816 018(57 816 018)417 611(417 611)-\r\rDistribution des dividendes(20 315 688)(20 315 688)(121)(20 315 809)\r\rSubvention d'investissement(806 015)(806 015)25 976(780 040)\r\rVariation du pourcentage d'intérêt2 7462 74641 25343 999\r\rAugmentation du capital2 500 1202 500 120\r\rRésultat consolidé de l'exercice 202170 352 49370 352 4931 652 08172 004 574\r\r\rCapitaux propres consolidés au 31 décembre 2021549 072 620(472 190 804)143 147 02570 352 493290 381 33412 113 7691 652 081304 147 184\r\r\rAffectation résultat70 352 493(70 352 493)1 652 081(1 652 081)\r-\r\r\rDistribution des dividendes(19 082 813)(19 082 813)(330 957)(19 413 770)\r\rSubvention d'investissement(1 395 402)(1 395 402)(19 346)(1 414 748)\r\rRésultat consolidé de l'exercice 202278 543 63578 543 6352 326 96780 870 602\r\r\rCapitaux propres consolidés au 31 décembre 2022549 072 620(472 190 804)193 021 30478 543 635348 446 75513 415 5472 326 967364 189 269,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Capitaux propres consolidés au 31 décembre 2020,549 072 620,(472 190 804),106 449 965,57 816 018,241 147 799,9 128 930,417 611,250 694 340
1,Affectation résultat\r\rDistribution des divid...,NaN,NaN,57 816 018\r\r(20 315 688)\r\r(806 015)\r\r2 746,(57 816 018)\r\r\r\r\r\r\r\r\r70 352 493,(20 315 688)\r\r(806 015)\r\r2 746\r\r\r\r70 3...,417 611\r\r(121)\r\r25 976\r\r41 253\r\r2 500 120,(417 611)\r\r\r\r\r\r\r\r\r\r1 652 081,-\r\r(20 315 809)\r\r(780 040)\r\r43 999\r\r2 ...
2,Capitaux propres consolidés au 31 décembre 2021,549 072 620,(472 190 804),143 147 025,70 352 493,290 381 334,12 113 769,1 652 081,304 147 184
3,Affectation résultat\r\rDistribution des divid...,NaN,NaN,70 352 493\r\r(19 082 813)\r\r(1 395 402),(70 352 493)\r78 543 635,(19 082 813)\r(1 395 402)\r78 543 635,1 652 081\r(330 957)\r(19 346),(1 652 081)\r2 326 967,-\r\r(19 413 770)\r\r(1 414 748)\r\r80 870 602
4,Capitaux propres consolidés au 31 décembre 2022,549 072 620,(472 190 804),193 021 304,78 543 635,348 446 755,13 415 547,2 326 967,364 189 269

--- Tableau 12 ---

,Note 11 : Capitaux propres\rTABLEAU DES MOUVEMENTS DES CAPITAUX PROPRES\rExercice clos le 31 Décembre 2022\r\rTotal des\rIntérêts desIntérêts desTotal des\rCapitalRéserves deRéservesRésultat decapitaux\rminoritaires/minoritaires/capitaux\rsocialrestructurationconsolidéesl'exercicepropres (part\rréservesrésultatpropres\rdu groupe)\r\r\rCapitaux propres consolidés au 31 décembre 2020549 072 620(472 190 804)106 449 96557 816 018241 147 7999 128 930417 611250 694 340\r\r\r\r\rAffectation résultat57 816 018(57 816 018)417 611(417 611)-\r\rDistribution des dividendes(20 315 688)(20 315 688)(121)(20 315 809)\r\rSubvention d'investissement(806 015)(806 015)25 976(780 040)\r\rVariation du pourcentage d'intérêt2 7462 74641 25343 999\r\rAugmentation du capital2 500 1202 500 120\r\rRésultat consolidé de l'exercice 202170 352 49370 352 4931 652 08172 004 574\r\r\rCapitaux propres consolidés au 31 décembre 2021549 072 620(472 190 804)143 147 02570 352 493290 381 33412 113 7691 652 081304 147 184\r\r\rAffectation résultat70 352 493(70 352 493)1 652 081(1 652 081)\r-\r\r\rDistribution des dividendes(19 082 813)(19 082 813)(330 957)(19 413 770)\r\rSubvention d'investissement(1 395 402)(1 395 402)(19 346)(1 414 748)\r\rRésultat consolidé de l'exercice 202278 543 63578 543 6352 326 96780 870 602\r\r\rCapitaux propres consolidés au 31 décembre 2022549 072 620(472 190 804)193 021 30478 543 635348 446 75513 415 5472 326 967364 189 269,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Capital\rsocial,Réserves de\rrestructuration,Réserves\rconsolidées,Résultat de\rl'exercice,Total des\rcapitaux\rpropres (part\rdu groupe),Intérêts des\rminoritaires/\rréserves,Intérêts des\rminoritaires/\rrésultat,Total des\rcapitaux\rpropres,NaN
1,Capitaux propres consolidés au 31 décembre 2020,549 072 620,(472 190 804),106 449 965,57 816 018,241 147 799,9 128 930,417 611,250 694 340
2,Affectation résultat\r\rDistribution des divid...,NaN,NaN,57 816 018\r\r(20 315 688)\r\r(806 015)\r\r2 746,(57 816 018)\r\r\r\r\r\r\r\r\r70 352 493,(20 315 688)\r\r(806 015)\r\r2 746\r\r\r\r70 3...,417 611\r\r(121)\r\r25 976\r\r41 253\r\r2 500 120,(417 611)\r\r\r\r\r\r\r\r\r\r1 652 081,-\r\r(20 315 809)\r\r(780 040)\r\r43 999\r\r2 ...
3,Capitaux propres consolidés au 31 décembre 2021,549 072 620,(472 190 804),143 147 025,70 352 493,290 381 334,12 113 769,1 652 081,304 147 184
4,Affectation résultat\r\rDistribution des divid...,NaN,NaN,70 352 493\r\r(19 082 813)\r\r(1 395 402),(70 352 493)\r78 543 635,(19 082 813)\r(1 395 402)\r78 543 635,1 652 081\r(330 957)\r(19 346),(1 652 081)\r2 326 967,-\r\r(19 413 770)\r\r(1 414 748)\r\r80 870 602
5,Capitaux propres consolidés au 31 décembre 2022,549 072 620,(472 190 804),193 021 304,78 543 635,348 446 755,13 415 547,2 326 967,364 189 269

--- Tableau 13 ---

         Voyages et déplacements   1 533 211   1 216 139
0             Services bancaires     782 902     368 827
1    Frais de télécommunications     781 870     578 070
2                 Sous-traitance     365 478     453 991
3                Impôts et taxes   3 879 212   3 194 315
4             Jetons de présence     171 000     183 750
5    Charges diverses ordinaires   2 800 208   3 052 239
6  Autres charges d'exploitation   3 729 117   4 283 619
7                            NaN         NaN         NaN
8                          Total  84 907 408  86 443 206

--- Tableau 14 ---

,Unnamed: 0,Unnamed: 1,Unnamed: 2
0,NaN,Solde au 31/12/2022,Solde au 31/12/2021
1,"Liquidités, équivalents de liquidités (A)",NaN,NaN
2,Banques,43 390 122,48 674 788
3,Valeurs à l'encaissement,15 753 907,15 253 286
4,Caisses,18 769,18 563
...,...,...,...
17,Nombre des actions en début de période,54 907 262,54 907 262
18,Nombre des actions en fin de période,54 907 262,54 907 262
19,NaN,NaN,NaN
20,Nombre moyen des actions (B),54 907 262,54 907 262
21,Résultat par action en dinars (A/B),"1,430","1,281"

============================================================
📅 Année : 2023 | 18 tableau(x)
============================================================

--- Tableau 1 ---

,Unnamed: 0,(5),154 681 598,131 989 241
0,NaN,NaN,NaN,NaN
1,Clients et comptes rattachés,NaN,34 427 416,36 229 219
2,-Provisions dépréciation des clients,NaN,(6 812 409),(6 089 530)
3,NaN,(6),27 615 007,30 139 689
4,NaN,NaN,NaN,NaN
5,Autres actifs courants,NaN,355 947 116,248 244 453
6,-Provisions dépréciation des autres actifs cou...,NaN,(3 419 256),(2 875 224)
7,NaN,(7),352 527 860,245 369 229
8,NaN,NaN,NaN,NaN
9,Placements et autres actifs financiers,(8),90 162 093,51 547 110
10,NaN,NaN,NaN,NaN
11,Liquidités et équivalents de liquidités,(9),40 060 253,59 162 798
12,NaN,NaN,NaN,NaN
13,Total des actifs courants,NaN,665 046 811,518 208 067
14,NaN,NaN,NaN,NaN
15,Total Actifs,NaN,963 682 272,815 104 818

--- Tableau 2 ---

,Unnamed: 0,(1),1 070 880,1 138 707
0,NaN,NaN,NaN,NaN
1,Immobilisations corporelles,NaN,742 170 561,694 675 010
2,-Amortissements immobilisations corporelles,NaN,(456 293 737),(407 376 770)
3,NaN,(2),285 876 824,287 298 240
4,NaN,NaN,NaN,NaN
5,Immobilisations financières,NaN,3 742 244,3 552 821
6,-Provisions pour dépréciation des immobilisati...,NaN,(55 755),(82 122)
7,NaN,(3),3 686 489,3 470 699
8,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN
10,Actifs d'impôts différés,(4),8 001 268,4 989 105
11,NaN,NaN,NaN,NaN
12,Total des actifs non courants,NaN,298 635 460,296 896 751

--- Tableau 3 ---

,Unnamed: 0,Notes,31.12.2023,31.12.2022
0,Actifs,NaN,NaN,NaN
1,Actifs non courants,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,Immobilisations incorporelles,NaN,7 400 931,6 899 131
4,-Amortissements Immobilisations incorporelles,NaN,(6 330 051),(5 760 424)

--- Tableau 4 ---

               Total des actifs non courants   298 635 460   296 896 751
0                            Actifs courants           NaN           NaN
1                                        NaN           NaN           NaN
2                                     Stocks   171 537 931   145 867 993
3  - Provisions pour dépréciation des stocks  (16 856 333)  (13 878 752)

--- Tableau 5 ---

,Groupe DELICE\rBILAN CONSOLIDE\r(Exprimé en dinars tunisiens)\r\rNotes31.12.202331.12.2022\rCapitaux propres et passifs\r\r\r\rCapital social549 072 620549 072 620\rRéserves de restructuration(472 190 804)(472 190 804)\rRéserves consolidés248 270 945193 021 304\r\r\rTotal Capitaux propres consolidés avant résultat de l'exercice325 152 761269 903 120\r\r\rRésultat de l'exercice97 781 36778 543 635\r\r\rTotal Capitaux propres consolidés\r422 934 128348 446 755\r\r\rIntérêts des minoritaires18 592 49315 742 514\r\r\rTotal Capitaux propres consolidés et intérêts minoritaires(10)441 526 622364 189 269\r\r\rPassifs non courants\r\rEmprunts(11)100 459 278121 411 794\rProvisions(12)38 721 30637 117 820\rPassifs d'impôts différés(13)12 214 6779 977 535\r\r\rTotal des passifs non courants\r151 395 262168 507 149\r\r\rPassifs courants\r\r\r\rFournisseurs et comptes rattachés(14)143 685 920152 436 335\rAutres passifs courants(15)55 731 10947 902 007\rConcours bancaires et autres passifs financiers(09)171 343 35982 070 058\r\r\rTotal des passifs courants\r370 760 388282 408 400\r\r\rTotal passifs\r522 155 650450 915 549\r\r\rTotal Capitaux propres et passifs\r963 682 272815 104 818,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,Notes,NaN,NaN,31.12.2023,NaN,NaN,31.12.2022,NaN
1,Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
53,Total passifs,NaN,522 155 650,450 915 549,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,Total passifs,NaN,522 155 650,450 915 549,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,NaN,Total Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,963 682 272,NaN,NaN,815 104 818,NaN

--- Tableau 6 ---

,Groupe DELICE\rBILAN CONSOLIDE\r(Exprimé en dinars tunisiens)\r\rNotes31.12.202331.12.2022\rCapitaux propres et passifs\r\r\r\rCapital social549 072 620549 072 620\rRéserves de restructuration(472 190 804)(472 190 804)\rRéserves consolidés248 270 945193 021 304\r\r\rTotal Capitaux propres consolidés avant résultat de l'exercice325 152 761269 903 120\r\r\rRésultat de l'exercice97 781 36778 543 635\r\r\rTotal Capitaux propres consolidés\r422 934 128348 446 755\r\r\rIntérêts des minoritaires18 592 49315 742 514\r\r\rTotal Capitaux propres consolidés et intérêts minoritaires(10)441 526 622364 189 269\r\r\rPassifs non courants\r\rEmprunts(11)100 459 278121 411 794\rProvisions(12)38 721 30637 117 820\rPassifs d'impôts différés(13)12 214 6779 977 535\r\r\rTotal des passifs non courants\r151 395 262168 507 149\r\r\rPassifs courants\r\r\r\rFournisseurs et comptes rattachés(14)143 685 920152 436 335\rAutres passifs courants(15)55 731 10947 902 007\rConcours bancaires et autres passifs financiers(09)171 343 35982 070 058\r\r\rTotal des passifs courants\r370 760 388282 408 400\r\r\rTotal passifs\r522 155 650450 915 549\r\r\rTotal Capitaux propres et passifs\r963 682 272815 104 818,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,Total Capitaux propres consolidés avant résult...,NaN,NaN,325 152 761,NaN,NaN,269 903 120,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Résultat de l'exercice,NaN,NaN,97 781 367,NaN,NaN,78 543 635,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
47,Total passifs,NaN,522 155 650,450 915 549,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Total passifs,NaN,522 155 650,450 915 549,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,Total Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,963 682 272,NaN,NaN,815 104 818,NaN

--- Tableau 7 ---

,Groupe DELICE\rBILAN CONSOLIDE\r(Exprimé en dinars tunisiens)\r\rNotes31.12.202331.12.2022\rCapitaux propres et passifs\r\r\r\rCapital social549 072 620549 072 620\rRéserves de restructuration(472 190 804)(472 190 804)\rRéserves consolidés248 270 945193 021 304\r\r\rTotal Capitaux propres consolidés avant résultat de l'exercice325 152 761269 903 120\r\r\rRésultat de l'exercice97 781 36778 543 635\r\r\rTotal Capitaux propres consolidés\r422 934 128348 446 755\r\r\rIntérêts des minoritaires18 592 49315 742 514\r\r\rTotal Capitaux propres consolidés et intérêts minoritaires(10)441 526 622364 189 269\r\r\rPassifs non courants\r\rEmprunts(11)100 459 278121 411 794\rProvisions(12)38 721 30637 117 820\rPassifs d'impôts différés(13)12 214 6779 977 535\r\r\rTotal des passifs non courants\r151 395 262168 507 149\r\r\rPassifs courants\r\r\r\rFournisseurs et comptes rattachés(14)143 685 920152 436 335\rAutres passifs courants(15)55 731 10947 902 007\rConcours bancaires et autres passifs financiers(09)171 343 35982 070 058\r\r\rTotal des passifs courants\r370 760 388282 408 400\r\r\rTotal passifs\r522 155 650450 915 549\r\r\rTotal Capitaux propres et passifs\r963 682 272815 104 818,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,Notes,NaN,NaN,31.12.2023,NaN,NaN,31.12.2022,NaN
1,Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Tableau 8 ---

,Unnamed: 0,Groupe DELICE,Unnamed: 1,Unnamed: 2
0,NaN,ETAT DE RESULTAT CONSOLIDE,NaN,NaN
1,NaN,(Exprimé en dinars tunisiens),NaN,NaN
2,NaN,NaN,NaN,NaN
3,NaN,Notes,31.12.2023,31.12.2022
4,NaN,NaN,NaN,NaN
...,...,...,...,...
25,Résultat Net de l'exercice,NaN,100 839 566,80 870 602
26,Part revenant aux intérêts minoritaires,(10),(3 058 199),(2 326 967)
27,Résultat net consolidé (part revenant au groupe),NaN,97 781 367,78 543 635
28,Nombre moyen des actions,NaN,54 907 262,54 907 262
29,NaN,(27),"1,781","1,430"

--- Tableau 9 ---

,,"La société « DELICE Holding » est une société anonyme de droit tunisien, constituée le 20 Mai 2013."
0,NaN,"Lors de la création de la société, le capital ..."
1,NaN,chacune. Conformément à la première résolution...
2,NaN,"Août 2013, les actionnaires ont décidé d’augme..."
3,NaN,"dinars pour le porter à 154.188.880 dinars, et..."
4,NaN,dinars chacune. L’assemblée générale extraordi...
...,...,...
20,,DELTA Plastic est une société à responsabilité...
21,NaN,des bouteilles et des emballages en plastique....
22,NaN,dans le travail à façon pour le compte de la s...
23,NaN,plastique pour l’emballage des produits DUNUP.
24,,La Société Tunisienne de l’Industrie Alimentai...

--- Tableau 10 ---

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,Société,% contrôle,% d'intérêts,Type de contrôle,Méthode de comptabilisation
1,DH,NaN,"100,00%","100,00%",Contrôle exclusif,Intégration globale
2,CLN,NaN,"98,33%","98,18%",Contrôle exclusif,Intégration globale
3,CLC,NaN,"99,81%","99,81%",Contrôle exclusif,Intégration globale
4,SDEM,NaN,"99,99%","99,76%",Contrôle exclusif,Intégration globale
5,SBC,NaN,"99,99%","99,99%",Contrôle exclusif,Intégration globale
6,Delta plastic,NaN,"99,99%","99,99%",Contrôle exclusif,Intégration globale
7,CF,NaN,"50,00%","50,00%",Contrôle exclusif,Intégration globale
8,CLSB,NaN,"99,95%","99,76%",Contrôle exclusif,Intégration globale
9,STIAL,NaN,"43,01%","43,01%",Contrôle conjoint,Intégration proportionnelle
10,SOCOGES,NaN,"50,00%","50,00%",Contrôle conjoint,Intégration proportionnelle
11,GDI LISSADIRAT,NaN,"100,00%","100,00%",Contrôle exclusif,Intégration globale
12,DELICE ACADEMY,NaN,"90,00%","90,00%",Contrôle exclusif,Intégration globale

--- Tableau 11 ---

,AmortissementsEquipements de bureau,Unnamed: 0,(2 816 159),(2 597 454)
0,AmortissementsMatériel informatique,NaN,(10 700 270),(9 830 239)
1,AmortissementsMatériel d'emballage,NaN,(4 146 421),(3 587 898)
2,AmortissementsAutres Equipements,NaN,(2 195 533),(2 176 444)
3,Provisions sur immobilisations corporelles,NaN,(2 931 634),(1 713 633)
4,Amortissements Immobilisations corporelles,NaN,(456 293 737),(407 376 770)
5,Immobilisations corporelles nettes,NaN,285 876 824,287 298 240

--- Tableau 12 ---

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Reclassements,Amortissements,Unnamed: 4,Amortissements.1,Amortissements.2,Unnamed: 5,Unnamed: 6
0,NaN,Reprise & Montants en TND VB 2022,Entrées,Cession,& VB 2023,Cumulés,Dotations,/Cession,Cumulés,VCN 2022,VCN 2023
1,NaN,NaN,NaN,NaN,retraitements retraitements,2022,2023,/Reprise,2023,NaN,NaN
2,Logiciels,6 818 948,201 473,-,(82 488) 6 937 933,5 713 504,543 256,-,26 372 6 283 132,1 105 443,654 501
3,Concessions de marques et brevets,79 890,40 945,-,(40 945) 79 890,46 920,26 372,-,(26 372) 46 920,32 970,32 970
4,Immobilisations incorporelles en cours,294,215 303,-,167 512 383 109,-,-,-,- -,294,383 409
...,...,...,...,...,...,...,...,...,...,...,...
19,Provisions constituées,NaN,-,- -,-,- 1 713 633,1 256 731,(33 681),(72 412) 2 931 634,(1 713 633),(2 931 634)
20,Total immobilisations corporelles,694 675 010,51 235 009,(3 713 660),(25 797) 742 170 561,407 376 770,52 046 178,2 990 964,(138 244) 456 293 737,287 298 240,285 876 824
21,Total immobilisations incorporelles et,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,701 574 141,51 692 730,(3 713 648),18 270 749 571 492,413 137 193,52 615 805,2 990 964,(138 244) 462 623 789,288 436 947,286 947 704
23,corporelles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Tableau 13 ---

,Unnamed: 0,Libellé 31/12/2023,31/12/2022
0,Produits finis,19 491 462,16 888 196
1,Produits en cours,838 555,451 980
2,Matières premières,54 117 161,37 664 833
3,Emballages,47 858 826,51 680 711
4,Pièces de rechanges,43 445 982,32 662 097
...,...,...,...
33,Débiteurs divers,9 483 639,10 065 597
34,NaN,NaN,NaN
35,Total brut,355 947 116,248 244 453
36,Provisions dépréciation des autres actifs cour...,(3 419 256),(2 875 224)
37,Total net,352 527 860,245 369 229

--- Tableau 14 ---

,Note 10 : Capitaux propres\rTABLEAU DES MOUVEMENTS DES CAPITAUX PROPRES\rExercice clos le 31 Décembre 2023\r\rTotal des\rIntérêts desIntérêts desTotal des\rCapitalRéserves deRéservesRésultat decapitaux\rminoritaires/minoritaires/capitaux\rsocialrestructurationconsolidéesl'exercicepropres (part\rréservesrésultatpropres\rdu groupe)\r\r\rCapitaux propres consolidés au 31 décembre 2021549 072 620(472 190 804)143 147 02570 352 493290 381 33412 113 7691 652 081304 147 184\r\r\r\rAffectation résultat70 352 493(70 352 493)-1 652 081(1 652 081)-\r\rDistribution des dividendes(19 082 813)(19 082 813)(330 957)(19 413 770)\r\rSubvention d'investissement(1 395 402)(1 395 402)(19 346)(1 414 748)\r\rRésultat consolidé de l'exercice 202278 543 63578 543 6352 326 96780 870 602\r\r\rCapitaux propres consolidés au 31 décembre 2022549 072 620(472 190 804)193 021 30478 543 635348 446 75513 415 5472 326 967364 189 269\r\r\rAffectation résultat78 543 635(78 543 635)-2 326 967(2 326 967)-\r\rDistribution des dividendes(21 963 204)(21 963 204)(192 343)(22 155 547)\r\rSubvention d'investissement(1 330 789)(1 330 789)(15 877)(1 346 666)\r\rRésultat consolidé de l'exercice 202397 781 36797 781 3673 058 199100 839 566\r\r\rCapitaux propres consolidés au 31 décembre 2023549 072 620(472 190 804)248 270 94597 781 367422 934 12815 534 2943 058 199441 526 622,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Capitaux propres consolidés au 31 décembre 2021,549 072 620,(472 190 804),143 147 025,70 352 493,290 381 334,12 113 769,1 652 081,304 147 184
1,Affectation résultat\r\rDistribution des divid...,NaN,NaN,70 352 493\r\r(19 082 813)\r\r(1 395 402),(70 352 493)\r\r\r\r\r78 543 635,-\r\r(19 082 813)\r\r(1 395 402)\r\r78 543 635,1 652 081\r\r(330 957)\r\r(19 346),(1 652 081)\r\r\r\r\r\r2 326 967,-\r\r(19 413 770)\r\r(1 414 748)\r\r80 870 602
2,Capitaux propres consolidés au 31 décembre 2022,549 072 620,(472 190 804),193 021 304,78 543 635,348 446 755,13 415 547,2 326 967,364 189 269
3,Affectation résultat\r\rDistribution des divid...,NaN,NaN,78 543 635\r(21 963 204)\r(1 330 789),(78 543 635)\r97 781 367,-\r(21 963 204)\r(1 330 789)\r97 781 367,2 326 967\r(192 343)\r(15 877),(2 326 967)\r3 058 199,-\r\r(22 155 547)\r\r(1 346 666)\r\r100 839 566
4,Capitaux propres consolidés au 31 décembre 2023,549 072 620,(472 190 804),248 270 945,97 781 367,422 934 128,15 534 294,3 058 199,441 526 622

--- Tableau 15 ---

,Note 10 : Capitaux propres\rTABLEAU DES MOUVEMENTS DES CAPITAUX PROPRES\rExercice clos le 31 Décembre 2023\r\rTotal des\rIntérêts desIntérêts desTotal des\rCapitalRéserves deRéservesRésultat decapitaux\rminoritaires/minoritaires/capitaux\rsocialrestructurationconsolidéesl'exercicepropres (part\rréservesrésultatpropres\rdu groupe)\r\r\rCapitaux propres consolidés au 31 décembre 2021549 072 620(472 190 804)143 147 02570 352 493290 381 33412 113 7691 652 081304 147 184\r\r\r\rAffectation résultat70 352 493(70 352 493)-1 652 081(1 652 081)-\r\rDistribution des dividendes(19 082 813)(19 082 813)(330 957)(19 413 770)\r\rSubvention d'investissement(1 395 402)(1 395 402)(19 346)(1 414 748)\r\rRésultat consolidé de l'exercice 202278 543 63578 543 6352 326 96780 870 602\r\r\rCapitaux propres consolidés au 31 décembre 2022549 072 620(472 190 804)193 021 30478 543 635348 446 75513 415 5472 326 967364 189 269\r\r\rAffectation résultat78 543 635(78 543 635)-2 326 967(2 326 967)-\r\rDistribution des dividendes(21 963 204)(21 963 204)(192 343)(22 155 547)\r\rSubvention d'investissement(1 330 789)(1 330 789)(15 877)(1 346 666)\r\rRésultat consolidé de l'exercice 202397 781 36797 781 3673 058 199100 839 566\r\r\rCapitaux propres consolidés au 31 décembre 2023549 072 620(472 190 804)248 270 94597 781 367422 934 12815 534 2943 058 199441 526 622,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Capital\rsocial,Réserves de\rrestructuration,Réserves\rconsolidées,Résultat de\rl'exercice,Total des\rcapitaux\rpropres (part\rdu groupe),Intérêts des\rminoritaires/\rréserves,Intérêts des\rminoritaires/\rrésultat,Total des\rcapitaux\rpropres,NaN
1,Capitaux propres consolidés au 31 décembre 2021,549 072 620,(472 190 804),143 147 025,70 352 493,290 381 334,12 113 769,1 652 081,304 147 184
2,Affectation résultat\r\rDistribution des divid...,NaN,NaN,70 352 493\r\r(19 082 813)\r\r(1 395 402),(70 352 493)\r\r\r\r\r78 543 635,-\r\r(19 082 813)\r\r(1 395 402)\r\r78 543 635,1 652 081\r\r(330 957)\r\r(19 346),(1 652 081)\r\r\r\r\r\r2 326 967,-\r\r(19 413 770)\r\r(1 414 748)\r\r80 870 602
3,Capitaux propres consolidés au 31 décembre 2022,549 072 620,(472 190 804),193 021 304,78 543 635,348 446 755,13 415 547,2 326 967,364 189 269
4,Affectation résultat\r\rDistribution des divid...,NaN,NaN,78 543 635\r(21 963 204)\r(1 330 789),(78 543 635)\r97 781 367,-\r(21 963 204)\r(1 330 789)\r97 781 367,2 326 967\r(192 343)\r(15 877),(2 326 967)\r3 058 199,-\r\r(22 155 547)\r\r(1 346 666)\r\r100 839 566
5,Capitaux propres consolidés au 31 décembre 2023,549 072 620,(472 190 804),248 270 945,97 781 367,422 934 128,15 534 294,3 058 199,441 526 622

--- Tableau 16 ---

   Honoraires & rémunération d'intermédiaire   6 572 300   8 456 839
0                                 Redevances   4 081 794   3 572 432
1                            Impôts et taxes   3 433 890   3 879 212
2                   Missions et déplacements   1 898 797   1 533 211
3                Frais de télécommunications     785 425     781 870
4                         Services bancaires     465 927     782 902
5                             Sous-traitance     404 107     365 478
6                        Services extérieurs     167 705     107 615
7                         Jetons de présence     190 000     171 000
8                Charges diverses ordinaires   3 971 271   2 800 208
9              Autres charges d'exploitation   5 228 488   3 729 117
10                                       NaN         NaN         NaN
11                                     Total  89 781 847  84 907 408

--- Tableau 17 ---

                                     Total 58 341 589 Unnamed: 0  55 025 595
0                                                 NaN        NaN         NaN
1             Note 21 : Autres charges d'exploitation        NaN         NaN
2                                                 NaN        NaN         NaN
3   Les autres charges d’exploitation s’élèvent à ...        NaN         NaN
4                                                 NaN        NaN         NaN
5                                  Libellé 31/12/2023        NaN  31/12/2022
6                                                 NaN        NaN         NaN
7                   Entretien & réparation 14 444 006        NaN  11 264 721
8                       Charges d'assurance 2 542 851        NaN   2 387 712
9                       Transport de biens 23 000 756        NaN  21 713 555
10                                Locations 9 133 342        NaN   8 668 140
11                               Publicité 13 461 189        NaN  14 693 396

--- Tableau 18 ---

                  Note 29 : Engagements hors bilan :     Unnamed: 0
0  Les engagements hors bilan donnés se présenten...            NaN
1                                    Libellé Société        Montant
2  Crédits documentaires auprès de la Banque Zito...      150 500 €
3  Engagements par signature sur cautions en doua...     135 200 DT
4  Nantissement du matériel et des installations ...  91 478 700 DT
5             Engagements donnés à la douane SOCOGES      67 501 DT
6        Nantissement de 1er rang sur matériel STIAL  15 000 000 DT
7      Engagement par Signature Attijari Bank  STIAL  10 986 644 DT
8                Engagement par Signature BIAT STIAL   8 242 954 DT

============================================================
📅 Année : 2024 | 14 tableau(x)
============================================================

--- Tableau 1 ---

                                 Unnamed: 0 Notes     31.12.2024   31.12.2023
0                                    Actifs   NaN            NaN          NaN
1                       Actifs non courants   NaN            NaN          NaN
2                                       NaN   NaN            NaN          NaN
3             Immobilisations incorporelles   NaN      8 047 508    7 400 931
4             -Amortissements et provisions   NaN    (6 838 414)  (6 330 051)
..                                      ...   ...            ...          ...
37  Liquidités et équivalents de liquidités   (9)     43 460 105   40 060 253
38                                      NaN   NaN            NaN          NaN
39                Total des actifs courants   NaN    758 445 573  665 046 811
40                                      NaN   NaN            NaN          NaN
41                             Total Actifs   NaN  1 076 492 932  963 682 272

[42 rows x 4 columns]

--- Tableau 2 ---

,Groupe DELICE\rBILAN CONSOLIDE\r(Exprimé en dinars tunisiens)\r\r\rNotes31.12.202431.12.2023\rCapitaux propres et passifs\r\r\r\r\rCapital social\r549 072 620549 072 620\rRéserves de restructuration\r(472 190 804)(472 190 804)\rRéserves consolidés\r311 902 342248 270 945\r\r\rTotal Capitaux propres consolidés avant résultat de l'exercice388 784 158325 152 761\r\r\rRésultat de l'exercice101 013 37197 781 367\r\r\rTotal Capitaux propres consolidés\r489 797 529422 934 128\r\r\r\rIntérêts des minoritaires21 864 06518 592 493\r\r\rTotal Capitaux propres consolidés et intérêts minoritaires(10)511 661 593441 526 622\r\r\rPassifs non courants\r\rEmprunts(11)23 400 730100 459 278\rProvisions pour risques et charges(12)39 627 44438 721 306\rPassifs d'impôts différés(13)15 587 62712 214 677\r\r\rTotal des passifs non courants\r78 615 802151 395 262\r\r\rPassifs courants\r\r\r\rFournisseurs et comptes rattachés(14)162 345 080143 685 920\rAutres passifs courants(15)55 357 95355 731 109\rConcours bancaires et autres passifs financiers(09)268 512 504171 343 359\r\r\rTotal des passifs courants\r486 215 537370 760 388\r\r\rTotal passifs\r564 831 339522 155 650\r\r\rTotal Capitaux propres et passifs\r1 076 492 932963 682 272,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,Notes,NaN,NaN,31.12.2024,NaN,NaN,31.12.2023,NaN
1,Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--- Tableau 3 ---

,Groupe DELICE\rBILAN CONSOLIDE\r(Exprimé en dinars tunisiens)\r\r\rNotes31.12.202431.12.2023\rCapitaux propres et passifs\r\r\r\r\rCapital social\r549 072 620549 072 620\rRéserves de restructuration\r(472 190 804)(472 190 804)\rRéserves consolidés\r311 902 342248 270 945\r\r\rTotal Capitaux propres consolidés avant résultat de l'exercice388 784 158325 152 761\r\r\rRésultat de l'exercice101 013 37197 781 367\r\r\rTotal Capitaux propres consolidés\r489 797 529422 934 128\r\r\r\rIntérêts des minoritaires21 864 06518 592 493\r\r\rTotal Capitaux propres consolidés et intérêts minoritaires(10)511 661 593441 526 622\r\r\rPassifs non courants\r\rEmprunts(11)23 400 730100 459 278\rProvisions pour risques et charges(12)39 627 44438 721 306\rPassifs d'impôts différés(13)15 587 62712 214 677\r\r\rTotal des passifs non courants\r78 615 802151 395 262\r\r\rPassifs courants\r\r\r\rFournisseurs et comptes rattachés(14)162 345 080143 685 920\rAutres passifs courants(15)55 357 95355 731 109\rConcours bancaires et autres passifs financiers(09)268 512 504171 343 359\r\r\rTotal des passifs courants\r486 215 537370 760 388\r\r\rTotal passifs\r564 831 339522 155 650\r\r\rTotal Capitaux propres et passifs\r1 076 492 932963 682 272,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,Total Capitaux propres consolidés avant résult...,NaN,NaN,388 784 158,NaN,NaN,325 152 761,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Résultat de l'exercice,NaN,NaN,101 013 371,NaN,NaN,97 781 367,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
47,Total passifs,NaN,564 831 339,522 155 650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,Total passifs,NaN,564 831 339,522 155 650,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,Total Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,1 076 492 932,NaN,NaN,963 682 272,NaN

--- Tableau 4 ---

,Groupe DELICE\rBILAN CONSOLIDE\r(Exprimé en dinars tunisiens)\r\r\rNotes31.12.202431.12.2023\rCapitaux propres et passifs\r\r\r\r\rCapital social\r549 072 620549 072 620\rRéserves de restructuration\r(472 190 804)(472 190 804)\rRéserves consolidés\r311 902 342248 270 945\r\r\rTotal Capitaux propres consolidés avant résultat de l'exercice388 784 158325 152 761\r\r\rRésultat de l'exercice101 013 37197 781 367\r\r\rTotal Capitaux propres consolidés\r489 797 529422 934 128\r\r\r\rIntérêts des minoritaires21 864 06518 592 493\r\r\rTotal Capitaux propres consolidés et intérêts minoritaires(10)511 661 593441 526 622\r\r\rPassifs non courants\r\rEmprunts(11)23 400 730100 459 278\rProvisions pour risques et charges(12)39 627 44438 721 306\rPassifs d'impôts différés(13)15 587 62712 214 677\r\r\rTotal des passifs non courants\r78 615 802151 395 262\r\r\rPassifs courants\r\r\r\rFournisseurs et comptes rattachés(14)162 345 080143 685 920\rAutres passifs courants(15)55 357 95355 731 109\rConcours bancaires et autres passifs financiers(09)268 512 504171 343 359\r\r\rTotal des passifs courants\r486 215 537370 760 388\r\r\rTotal passifs\r564 831 339522 155 650\r\r\rTotal Capitaux propres et passifs\r1 076 492 932963 682 272,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,Notes,NaN,NaN,31.12.2024,NaN,NaN,31.12.2023,NaN
1,Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
53,Total passifs,NaN,564 831 339,522 155 650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,NaN,Total passifs,NaN,564 831 339,522 155 650,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,NaN,Total Capitaux propres et passifs,NaN,NaN,NaN,NaN,NaN,1 076 492 932,NaN,NaN,963 682 272,NaN

--- Tableau 5 ---

,Unnamed: 0,Notes,31.12.2024,31.12.2023
0,NaN,NaN,NaN,NaN
1,Revenus,(16),1 442 665 250,1 388 767 638
2,Autres produits d'exploitation,(17),10 862 750,10 684 294
3,NaN,NaN,NaN,NaN
4,Total produits d'exploitation,NaN,1 453 528 000,1 399 451 932
...,...,...,...,...
36,Résultat net consolidé (part revenant au groupe),NaN,101 013 371,97 781 367
37,NaN,NaN,NaN,NaN
38,Nombre moyen des actions,NaN,54 907 262,54 907 262
39,NaN,NaN,NaN,NaN
40,NaN,(27),"1,840","1,781"

--- Tableau 6 ---

,Unnamed: 0,Notes,31.12.2024,31.12.2023
0,Résultat net (Groupe),NaN,101 013 371,97 781 367
1,Ajustement pour :,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,* Part revenant aux intérêts minoritaires,(10),3 564 656,3 058 199
4,"* Amortissements, Provisions & Reprises de pro...",(20),51 893 578,58 341 589
...,...,...,...,...
35,NaN,NaN,NaN,NaN
36,Trésorerie au début de l'exercice,NaN,33 800 254,54 106 903
37,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN
39,Trésorerie à la clôture de l'exercice,(26),40 016 750,33 800 254

--- Tableau 7 ---

  Unnamed: 0                                         Unnamed: 1
0            soit de la détention directe ou indirecte, par...
1        NaN        droits de vote de l’entreprise consolidée ;
2            soit du pouvoir sur plus de la moitié des droi...
3        NaN                                    investisseurs ;
4                           soit des statuts ou d’un contrat ;
5            soit du pouvoir de nommer ou de révoquer la ma...
6        NaN           ou de l’organe de direction équivalent ;
7            soit du pouvoir de réunir la majorité des droi...

--- Tableau 8 ---

,Unnamed: 0,Société,% contrôle,% d'intérêts,Type de contrôle,Méthode de comptabilisation
0,DH,NaN,"100,00%","100,00%",Contrôle exclusif,Intégration globale
1,CLN,NaN,"98,33%","98,18%",Contrôle exclusif,Intégration globale
2,CLC,NaN,"99,81%","99,81%",Contrôle exclusif,Intégration globale
3,SDEM,NaN,"99,99%","99,81%",Contrôle exclusif,Intégration globale
4,SBC,NaN,"99,99%","99,99%",Contrôle exclusif,Intégration globale
5,Delta plastic,NaN,"99,99%","99,99%",Contrôle exclusif,Intégration globale
6,CF,NaN,"50,00%","50,00%",Contrôle exclusif,Intégration globale
7,NaN,NaN,NaN,NaN,NaN,NaN
8,CLSB,NaN,"99,95%","99,76%",Contrôle exclusif,Intégration globale
9,STIAL,NaN,"43,01%","43,01%",Contrôle conjoint,Intégration proportionnelle
10,SOCOGES,NaN,"50,00%","50,00%",Contrôle conjoint,Intégration proportionnelle

--- Tableau 9 ---

,Unnamed: 0,Libellé,31/12/2024,31/12/2023
0,Logiciels,NaN,7 475 752,6 937 633
1,Concessions de marques et brevets,NaN,127 986,79 890
2,Immobilisations incorporelles en cours,NaN,443 770,383 409
3,Immobilisations incorporelles,NaN,8 047 508,7 400 931
4,Amortissements,Logiciels,(6 770 115),(6 269 951)
...,...,...,...,...
30,Amortissements,Matériel d'emballage,(4 745 384),(4 146 421)
31,Amortissements,Autres Equipements,(2 206 162),(2 195 533)
32,Provisions sur immobilisations corporelles,NaN,(2 849 777),(2 931 634)
33,Amortissements Immobilisations corporelles,NaN,(500 509 680),(456 293 737)
34,Immobilisations corporelles nettes,NaN,295 778 973,285 876 824

--- Tableau 10 ---

,Note 10 : Capitaux propres\rTABLEAU DES MOUVEMENTS DES CAPITAUX PROPRES\rExercice clos le 31 Décembre 2024\r\r\rTotal des\rIntérêts desIntérêts desTotal des\rCapitalRéserves deRéservesRésultat decapitaux\rminoritaires/minoritaires/capitaux\rsocialrestructurationconsolidéesl'exercicepropres (part\rréservesrésultatpropres\rdu groupe)\r\r\r\r\rCapitaux propres consolidés au 31 décembre 2022549 072 620(472 190 804)193 021 30378 543 635348 446 75413 415 5472 326 967364 189 268\r\r\r\rAffectation résultat\r--\r78 543 635(78 543 635)-\r2 326 967(2 326 967)-\r\rDistribution des dividendes--\r(21 963 204)-\r(21 963 204)(192 343)-\r(22 155 547)\r\rSubvention d'investissement--\r(1 330 789)-\r(1 330 789)(15 877)-\r(1 346 666)\r\rRésultat consolidé de l'exercice 2023--\r97 781 36797 781 367-\r3 058 199100 839 566\r\r\rCapitaux propres consolidés au 31 décembre 2023549 072 620(472 190 804)248 270 94597 781 367422 934 12815 534 2943 058 199441 526 622\r\r\rAffectation résultat--\r97 781 367(97 781 367)-3 058 199(3 058 199)-\r\rDistribution des dividendes--\r(32 944 357)-\r(32 944 357)(264 439)-\r(33 208 796)\r\rSubvention d'investissement--\r(1 230 763)-\r(1 230 763)(3 497)-\r(1 234 260)\r\rVariation du périmètre--\r25 150-\r25 150(25 150)--\r\rRésultat consolidé de l'exercice 2024--\r101 013 371101 013 371-\r3 564 657104 578 028\r\r\rCapitaux propres consolidés au 31 décembre 2024549 072 620(472 190 804)311 902 342101 013 371489 797 52918 299 4083 564 657511 661 593,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Capital\rsocial,Réserves de\rrestructuration,Réserves\rconsolidées,Résultat de\rl'exercice,Total des\rcapitaux\rpropres (part\rdu groupe),Intérêts des\rminoritaires/\rréserves,Intérêts des\rminoritaires/\rrésultat,Total des\rcapitaux\rpropres,NaN
1,Capitaux propres consolidés au 31 décembre 2022,549 072 620,(472 190 804),193 021 303,78 543 635,348 446 754,13 415 547,2 326 967,364 189 268
2,Affectation résultat\r\rDistribution des divid...,-\r-\r-\r-,-\r\r-\r\r-\r\r-,78 543 635\r\r(21 963 204)\r\r(1 330 789),(78 543 635)\r-\r\r-\r\r97 781 367,-\r\r(21 963 204)\r\r(1 330 789)\r\r97 781 367,2 326 967\r\r(192 343)\r\r(15 877)\r\r-,(2 326 967)\r\r-\r\r-\r\r3 058 199,-\r\r(22 155 547)\r\r(1 346 666)\r\r100 839 566
3,Capitaux propres consolidés au 31 décembre 2023,549 072 620,(472 190 804),248 270 945,97 781 367,422 934 128,15 534 294,3 058 199,441 526 622
4,Affectation résultat\r\rDistribution des divid...,-\r\r-\r\r-\r-\r-,-\r\r-\r\r-\r-\r\r-,97 781 367\r(32 944 357)\r(1 230 763)\r25 150,(97 781 367)\r-\r-\r-\r101 013 371,-\r(32 944 357)\r(1 230 763)\r25 150\r101 013 371,3 058 199\r(264 439)\r(3 497)\r(25 150)\r-,(3 058 199)\r-\r-\r-\r3 564 657,-\r\r(33 208 796)\r\r(1 234 260)\r\r-\r\r104 5...
5,Capitaux propres consolidés au 31 décembre 2024,549 072 620,(472 190 804),311 902 342,101 013 371,489 797 529,18 299 408,3 564 657,511 661 593

--- Tableau 11 ---

,Note 10 : Capitaux propres\rTABLEAU DES MOUVEMENTS DES CAPITAUX PROPRES\rExercice clos le 31 Décembre 2024\r\r\rTotal des\rIntérêts desIntérêts desTotal des\rCapitalRéserves deRéservesRésultat decapitaux\rminoritaires/minoritaires/capitaux\rsocialrestructurationconsolidéesl'exercicepropres (part\rréservesrésultatpropres\rdu groupe)\r\r\r\r\rCapitaux propres consolidés au 31 décembre 2022549 072 620(472 190 804)193 021 30378 543 635348 446 75413 415 5472 326 967364 189 268\r\r\r\rAffectation résultat\r--\r78 543 635(78 543 635)-\r2 326 967(2 326 967)-\r\rDistribution des dividendes--\r(21 963 204)-\r(21 963 204)(192 343)-\r(22 155 547)\r\rSubvention d'investissement--\r(1 330 789)-\r(1 330 789)(15 877)-\r(1 346 666)\r\rRésultat consolidé de l'exercice 2023--\r97 781 36797 781 367-\r3 058 199100 839 566\r\r\rCapitaux propres consolidés au 31 décembre 2023549 072 620(472 190 804)248 270 94597 781 367422 934 12815 534 2943 058 199441 526 622\r\r\rAffectation résultat--\r97 781 367(97 781 367)-3 058 199(3 058 199)-\r\rDistribution des dividendes--\r(32 944 357)-\r(32 944 357)(264 439)-\r(33 208 796)\r\rSubvention d'investissement--\r(1 230 763)-\r(1 230 763)(3 497)-\r(1 234 260)\r\rVariation du périmètre--\r25 150-\r25 150(25 150)--\r\rRésultat consolidé de l'exercice 2024--\r101 013 371101 013 371-\r3 564 657104 578 028\r\r\rCapitaux propres consolidés au 31 décembre 2024549 072 620(472 190 804)311 902 342101 013 371489 797 52918 299 4083 564 657511 661 593,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Capitaux propres consolidés au 31 décembre 2022,549 072 620,(472 190 804),193 021 303,78 543 635,348 446 754,13 415 547,2 326 967,364 189 268
1,Affectation résultat\r\rDistribution des divid...,-\r-\r-\r-,-\r\r-\r\r-\r\r-,78 543 635\r\r(21 963 204)\r\r(1 330 789),(78 543 635)\r-\r\r-\r\r97 781 367,-\r\r(21 963 204)\r\r(1 330 789)\r\r97 781 367,2 326 967\r\r(192 343)\r\r(15 877)\r\r-,(2 326 967)\r\r-\r\r-\r\r3 058 199,-\r\r(22 155 547)\r\r(1 346 666)\r\r100 839 566
2,Capitaux propres consolidés au 31 décembre 2023,549 072 620,(472 190 804),248 270 945,97 781 367,422 934 128,15 534 294,3 058 199,441 526 622
3,Affectation résultat\r\rDistribution des divid...,-\r\r-\r\r-\r-\r-,-\r\r-\r\r-\r-\r\r-,97 781 367\r(32 944 357)\r(1 230 763)\r25 150,(97 781 367)\r-\r-\r-\r101 013 371,-\r(32 944 357)\r(1 230 763)\r25 150\r101 013 371,3 058 199\r(264 439)\r(3 497)\r(25 150)\r-,(3 058 199)\r-\r-\r-\r3 564 657,-\r\r(33 208 796)\r\r(1 234 260)\r\r-\r\r104 5...
4,Capitaux propres consolidés au 31 décembre 2024,549 072 620,(472 190 804),311 902 342,101 013 371,489 797 529,18 299 408,3 564 657,511 661 593

--- Tableau 12 ---

                                           Unnamed: 0  Unnamed: 1
0                Note 22 : Charges financières nettes         NaN
1   Les charges financières nettes s’élèvent à 19 ...         NaN
2                                                 NaN         NaN
3                                  Libellé 31/12/2024  31/12/2023
4                                                 NaN         NaN
..                                                ...         ...
32                                                NaN         NaN
33        Pertes sur cession d'immobilisations 78 010     301 928
34                 Autres pertes ordinaires 2 428 564     385 538
35                                                NaN         NaN
36                                    Total 2 506 574     687 467

[37 rows x 2 columns]

--- Tableau 13 ---

                                           Unnamed: 0     Unnamed: 1
0                  Note 28 : Engagements hors bilan :            NaN
1   Les engagements hors bilan donnés se présenten...            NaN
2                                     Libellé Société        Montant
3   Crédits documentaires auprès de ATTIJARI BANK CLN      170 700 €
4   Engagements par signature sur les financements...  12 000 000 DT
5   Engagements par signature sur cautions en doua...     126 000 DT
6   Engagements par signature sur les financements...  10 000 000 DT
7   Engagements par signature sur les financements...   8 900 414 DT
8   Nantissement du matériel et des installations ...   8 505 000 DT
9              Engagements donnés à la douane SOCOGES      67 501 DT
10        Nantissement de 1er rang sur matériel STIAL  15 000 000 DT
11      Engagement par Signature Attijari Bank  STIAL   8 878 790 DT
12                Engagement par Signature BIAT STIAL   1 064 920 DT

--- Tableau 14 ---

   Unnamed: 0                                         Unnamed: 1
0             Nous tirons une conclusion quant au caractère ...
1         NaN  principe comptable de continuité d’exploitatio...
2         NaN  l’existence ou non d’une incertitude significa...
3         NaN  de jeter un doute important sur la capacité de...
4         NaN  exploitations. Si nous concluons à l’existence...
..        ...                                                ...
22        NaN  que nous nous sommes conformés aux règles de d...
23        NaN  l’indépendance, et leur communiquons toutes le...
24        NaN  raisonnablement être considérés comme suscepti...
25        NaN  indépendance ainsi que les sauvegardes connexe...
26            Parmi les questions communiquées aux responsab...

[27 rows x 2 columns]

In [7]:
for year, tables in data.items():
    for i, df in enumerate(tables):
        print(f"Year {year} - Table {i}")
        print(df.head(3))  # juste aperçu

Year 2014 - Table 0
            Unnamed: 0 Unnamed: 1  Unnamed: 2 31.12.2013 31.12.2013.1
0               Actifs        NaN  31.12.2014        NaN          NaN
1                  NaN        NaN         NaN  Retraité*       Publié
2  Actifs non courants        NaN         NaN        NaN          NaN
Year 2014 - Table 1
                    Unnamed: 0 Unnamed: 1  Unnamed: 2 31.12.2013 31.12.2013.1
0  Capitaux propres et passifs        NaN  31.12.2014        NaN          NaN
1                          NaN        NaN         NaN  Retraité*       Publié
2                          NaN        NaN         NaN        NaN          NaN
Year 2014 - Table 2
  Unnamed: 0 Unnamed: 1  Unnamed: 2 31.12.2013 31.12.2013.1
0        NaN        NaN  31.12.2014        NaN          NaN
1        NaN        NaN         NaN  Retraité*       Publié
2        NaN        NaN         NaN        NaN          NaN
Year 2014 - Table 3
              Unnamed: 0 Unnamed: 1  31.12.2014  31.12.2013
0  Résultat net (Groupe)        NaN  25 825 670  25 001 566
1       Ajustement pour:        NaN         NaN         NaN
2                    NaN        NaN         NaN         NaN
Year 2014 - Table 4
          Société % de contrôle % d’intérêts groupe   Type de contrôle  \
0  DELICE Holding          100%                100%       Société mère
1             CLC        99,72%              99,72%  Contrôle exclusif
2             CLN        96,98%              96,71%  Contrôle exclusif

  Méthode de comptabilisation
0                         NaN
1         Intégration globale
2         Intégration globale
Year 2014 - Table 5
  La valeur nette des immobilisations incorporelles et corporelles s’élève à 186 734 737 dinars au 31 décembre 2014 et se détaille comme suit :  \
0                                         Cession et
1  Amortissements Montants en TND Valeur Brute En...
2  Dec 2013 2014 Dec 2014 cumulés 2013 2014 / ces...

  Unnamed: 0 Unnamed: 1
0        NaN        NaN
1   VCN 2013   VCN 2014
2        NaN        NaN
Year 2014 - Table 6
  Libellé Solde au 31/12/2014 Solde au 31/12/2013 Solde au 31/12/2013.1
0                         NaN          Retraité**                Publié
1                         NaN                 NaN                   NaN
2   Clients locaux 14 003 205          13 033 087            27 959 357
Year 2014 - Table 7
                                    Total 20 486 536 25 447 118 26 918 477
0  **Les montants relatifs à l’exercice clos le 3...        NaN        NaN
1  Les concours bancaires et autres passifs finan...        NaN        NaN
2                 2014 et se détaillent comme suit :        NaN        NaN
Year 2014 - Table 8
                                          Unnamed: 0  \
0                                                NaN
1    Capitaux propres consolidés au 31 décembre 2013
2  Affectation résultat\r\rDistribution des  Divi...

  Note 11 : Capitaux propres\rTABLEAU DES MOUVEMENTS DES CAPITAUX PROPRES\rExercice clos le 31 Décembre 2014\r\rTotal des\rIntérêts desIntérêts desTotal des\rRéserves deRéservesRésultat decapitaux\rCapital socialminoritaires/minoritaires/capitaux\rrestructurationconsolidéesl'exercicepropres (part\rréservesrésultatpropres\rdu groupe)\r\r\rCapitaux propres consolidés au 31 décembre 2013549 072 620(472 190 804)-25 001 566101 883 3825 714 825(364 004)107 234 203\r\r\rAffectation résultat25 001 566(25 001 566)\r-(364 004)364 004-\r\r\rDistribution des  Dividendes-(71 583)(71 583)\r\rSubvention d'investissement1 073 8171 073 817(30 567)1 043 249\r\rModifications comptables(832 527)(832 527)(2 367)(834 894)\r\rVariation du périmètre(111 384)2 002(109 382)(123 616)(232 998)\r\rRésultat consolidé de l'exercice 201425 823 66925 823 669(569 174)25 254 495\r\r\rCapitaux propres consolidés au 31 décembre 2014549 072 620(472 190 804)25 131 47225 825 670127 838 9585 122 688(569 174)132 392 472  \
0                                     Capital social
1                                        549 072 620
2                                                NaN

                     Unnamed: 1  \
0  Réserves de\rrestructuration
1                 (472 190 804)
2                           NaN

                                          Unnamed: 2  \
0                              Réserves\rconsolidées
1                                                  -
2  25 001 566\r\r\r\r1 073 817\r\r(832 527)\r\r(1...

                                        Unnamed: 3  \
0                          Résultat de\rl'exercice
1                                       25 001 566
2  (25 001 566)\r\r\r\r\r\r\r\r2 002\r\r25 823 669

                                          Unnamed: 4  \
0     Total des\rcapitaux\rpropres (part\rdu groupe)
1                                        101 883 382
2  -\r\r-\r\r1 073 817\r\r(832 527)\r\r(109 382)\...

                                          Unnamed: 5  \
0              Intérêts des\rminoritaires/\rréserves
1                                          5 714 825
2  (364 004)\r\r(71 583)\r\r(30 567)\r\r(2 367)\r...

                              Unnamed: 6  \
0  Intérêts des\rminoritaires/\rrésultat
1                              (364 004)
2   364 004\r\r\r\r\r\r\r\r\r\r(569 174)

                                          Unnamed: 7
0                       Total des\rcapitaux\rpropres
1                                        107 234 203
2  -\r\r(71 583)\r\r1 043 249\r\r(834 894)\r\r(23...
Year 2014 - Table 9
  Note 11 : Capitaux propres\rTABLEAU DES MOUVEMENTS DES CAPITAUX PROPRES\rExercice clos le 31 Décembre 2014\r\rTotal des\rIntérêts desIntérêts desTotal des\rRéserves deRéservesRésultat decapitaux\rCapital socialminoritaires/minoritaires/capitaux\rrestructurationconsolidéesl'exercicepropres (part\rréservesrésultatpropres\rdu groupe)\r\r\rCapitaux propres consolidés au 31 décembre 2013549 072 620(472 190 804)-25 001 566101 883 3825 714 825(364 004)107 234 203\r\r\rAffectation résultat25 001 566(25 001 566)\r-(364 004)364 004-\r\r\rDistribution des  Dividendes-(71 583)(71 583)\r\rSubvention d'investissement1 073 8171 073 817(30 567)1 043 249\r\rModifications comptables(832 527)(832 527)(2 367)(834 894)\r\rVariation du périmètre(111 384)2 002(109 382)(123 616)(232 998)\r\rRésultat consolidé de l'exercice 201425 823 66925 823 669(569 174)25 254 495\r\r\rCapitaux propres consolidés au 31 décembre 2014549 072 620(472 190 804)25 131 47225 825 670127 838 9585 122 688(569 174)132 392 472  \
0    Capitaux propres consolidés au 31 décembre 2013
1  Affectation résultat\r\rDistribution des  Divi...
2    Capitaux propres consolidés au 31 décembre 2014

    Unnamed: 0     Unnamed: 1  \
0  549 072 620  (472 190 804)
1          NaN            NaN
2  549 072 620  (472 190 804)

                                          Unnamed: 2  \
0                                                  -
1  25 001 566\r\r\r\r1 073 817\r\r(832 527)\r\r(1...
2                                         25 131 472

                                        Unnamed: 3  \
0                                       25 001 566
1  (25 001 566)\r\r\r\r\r\r\r\r2 002\r\r25 823 669
2                                       25 825 670

                                          Unnamed: 4  \
0                                        101 883 382
1  -\r\r-\r\r1 073 817\r\r(832 527)\r\r(109 382)\...
2                                        127 838 958

                                          Unnamed: 5  \
0                                          5 714 825
1  (364 004)\r\r(71 583)\r\r(30 567)\r\r(2 367)\r...
2                                          5 122 688

                             Unnamed: 6  \
0                             (364 004)
1  364 004\r\r\r\r\r\r\r\r\r\r(569 174)
2                             (569 174)

                                          Unnamed: 7
0                                        107 234 203
1  -\r\r(71 583)\r\r1 043 249\r\r(834 894)\r\r(23...
2                                        132 392 472
Year 2014 - Table 10
  Unnamed: 0           Unnamed: 1 Solde au 31/12/2013 Solde au 31/12/2013.1
0    Libellé  Solde au 31/12/2014                 NaN                   NaN
1        NaN                  NaN            Retraité                Publié
2        NaN                  NaN                 NaN                   NaN
Year 2014 - Table 11
                          Note 19 : Achats consommés Unnamed: 0
0                                                NaN        NaN
1  Les achats consommés s’élèvent à 501 025 458 d...        NaN
2                                                NaN        NaN
Year 2014 - Table 12
                 Total 8 639 380 5 941 045 Unnamed: 0 5 941 045.1
0                            NaN       NaN        NaN         NaN
1                            NaN       NaN        NaN         NaN
2  Note 24 : Produits financiers       NaN        NaN         NaN
Year 2014 - Table 13
                   Unnamed: 0        2014        2013
0                         NaN         NaN         NaN
1  Résultat net consolidé (A)  25 825 670  25 001 566
2                         NaN         NaN         NaN
Year 2014 - Table 14
                                          Unnamed: 0           Unnamed: 1  \
0  Liquidités, équivalents de liquidités et place...  Solde au 31/12/2014
1                                         Placements           15 000 000
2                                            Banques           18 305 339

            Unnamed: 2
0  Solde au 31/12/2013
1                    -
2           25 165 275
Year 2014 - Table 15
  Autres produits Unnamed: 0  Unnamed: 1    Unnamed: 2  \
0             NaN  6 982 368  50 241 196  (43 258 828)
1  d'exploitation        NaN         NaN           NaN
2             NaN        NaN         NaN           NaN

                                        Les reprises           / provision  \
0                                                NaN         NaN       NaN
1  3 756 994  dinars relatives à des participatio...         NaN       NaN
2                                     cédées ont été  reclassées        au

     pour   un      montant   de
0     NaN  NaN          NaN  NaN
1     NaN  NaN          NaN  NaN
2  niveau   de  la rubrique  NaN
Year 2015 - Table 0
                          Actifs Unnamed: 0 31.12.2015 31.12.2014
0            Actifs non courants        NaN        NaN        NaN
1                            NaN        NaN        NaN        NaN
2  Immobilisations incorporelles        NaN  3 109 814  2 518 600
Year 2015 - Table 1
   Capitaux propres et passifs Unnamed: 0     31.12.2015     31.12.2014
0                          NaN        NaN            NaN            NaN
1               Capital social        NaN    549 072 620    549 072 620
2  Réserves de restructuration        NaN  (472 190 804)  (472 190 804)
Year 2015 - Table 2
                       Unnamed: 0 Unnamed: 1         2015         2014
0                             NaN        NaN          NaN          NaN
1                         Revenus       (18)  714 952 675  647 588 213
2  Autres produits d'exploitation       (19)   15 849 489   12 807 509
Year 2015 - Table 3
              Unnamed: 0 Unnamed: 1        2015        2014
0  Résultat net (Groupe)        NaN  40 048 335  25 825 670
1       Ajustement pour:        NaN         NaN         NaN
2                    NaN        NaN         NaN         NaN
Year 2015 - Table 4
          Société % de contrôle % d’intérêts groupe   Type de contrôle  \
0  DELICE Holding          100%                100%       Société mère
1             CLC        97,45%              97,23%  Contrôle exclusif
2             CLN        99,77%              99,77%  Contrôle exclusif

  Méthode de comptabilisation
0                         NaN
1         Intégration globale
2         Intégration globale
Year 2015 - Table 5
     Note 9 : Placements et autres actifs financiers Unnamed: 0
0  Les placements s’élèvent à 15 500 000 dinars a...        NaN
1                                                NaN        NaN
2                          Libellé Solde au Solde au        NaN
Year 2015 - Table 6
                                          Unnamed: 0  \
0                                                NaN
1    Capitaux propres consolidés au 31 décembre 2013
2  Affectation résultat\r\rDistribution des  divi...

  Note 11 : Capitaux propres\rTABLEAU DES MOUVEMENTS DES CAPITAUX PROPRES\rExercice clos le 31 Décembre 2015\rTotal des\rIntérêts desIntérêts desTotal des\rRéserves deRéservesRésultat decapitaux\rCapital socialminoritaires/minoritaires/capitaux\rrestructurationconsolidéesl'exercicepropres (part\rréservesrésultatpropres\rdu groupe)\r\rCapitaux propres consolidés au 31 décembre 2013549 072 620(472 190 804)-25 001 566101 883 3825 714 825(364 004)107 234 203\r\r\rAffectation résultat25 001 566(25 001 566)-(364 004)364 004-\r\rDistribution des  dividendes-(71 583)(71 583)\rSubvention d'investissement1 073 8171 073 817(30 567)1 043 249\rModifications comptables(832 527)(832 527)(2 367)(834 894)\r\rVariation du périmètre(111 384)2 002(109 382)(123 616)(232 998)\r\rRésultat consolidé de l'exercice 201425 823 66925 823 669(569 174)25 254 495\r\rCapitaux propres consolidés au 31 décembre 2014549 072 620(472 190 804)25 131 47225 825 670127 838 9585 122 688(569 174)132 392 472\rAffectation résultat25 825 670(25 825 670)-(569 174)569 174-\rDistribution des  dividendes(35 142 645)(35 142 645)(14 063)(35 156 708)\rSubvention d'investissement945 747945 747(37 542)908 205\rModifications comptables972972972\rVariation du pourcentage d'intérêt(32 205)(32 205)32 23732\rRésultat consolidé de l'exercice 201540 048 33540 048 33565 55040 113 885\rCapitaux propres consolidés au 31 décembre 2015549 072 620(472 190 804)16 729 01140 048 335133 659 1624 534 14665 550138 258 858  \
0                                     Capital social
1                                        549 072 620
2                                                NaN

                     Unnamed: 1  \
0  Réserves de\rrestructuration
1                 (472 190 804)
2                           NaN

                                          Unnamed: 2  \
0                              Réserves\rconsolidées
1                                                  -
2  25 001 566\r\r\r1 073 817\r(832 527)\r\r(111 384)

                                    Unnamed: 3  \
0                      Résultat de\rl'exercice
1                                   25 001 566
2  (25 001 566)\r\r\r\r\r\r2 002\r\r25 823 669

                                          Unnamed: 4  \
0     Total des\rcapitaux\rpropres (part\rdu groupe)
1                                        101 883 382
2  -\r\r-\r1 073 817\r(832 527)\r\r(109 382)\r\r2...

                                          Unnamed: 5  \
0              Intérêts des\rminoritaires/\rréserves
1                                          5 714 825
2  (364 004)\r\r(71 583)\r(30 567)\r(2 367)\r\r(1...

                              Unnamed: 6  \
0  Intérêts des\rminoritaires/\rrésultat
1                              (364 004)
2       364 004\r\r\r\r\r\r\r\r(569 174)

                                          Unnamed: 7 Unnamed: 8
0                       Total des\rcapitaux\rpropres        NaN
1                                        107 234 203        NaN
2  -\r\r(71 583)\r1 043 249\r(834 894)\r\r(232 99...        NaN
Year 2015 - Table 7
  Note 11 : Capitaux propres\rTABLEAU DES MOUVEMENTS DES CAPITAUX PROPRES\rExercice clos le 31 Décembre 2015\rTotal des\rIntérêts desIntérêts desTotal des\rRéserves deRéservesRésultat decapitaux\rCapital socialminoritaires/minoritaires/capitaux\rrestructurationconsolidéesl'exercicepropres (part\rréservesrésultatpropres\rdu groupe)\r\rCapitaux propres consolidés au 31 décembre 2013549 072 620(472 190 804)-25 001 566101 883 3825 714 825(364 004)107 234 203\r\r\rAffectation résultat25 001 566(25 001 566)-(364 004)364 004-\r\rDistribution des  dividendes-(71 583)(71 583)\rSubvention d'investissement1 073 8171 073 817(30 567)1 043 249\rModifications comptables(832 527)(832 527)(2 367)(834 894)\r\rVariation du périmètre(111 384)2 002(109 382)(123 616)(232 998)\r\rRésultat consolidé de l'exercice 201425 823 66925 823 669(569 174)25 254 495\r\rCapitaux propres consolidés au 31 décembre 2014549 072 620(472 190 804)25 131 47225 825 670127 838 9585 122 688(569 174)132 392 472\rAffectation résultat25 825 670(25 825 670)-(569 174)569 174-\rDistribution des  dividendes(35 142 645)(35 142 645)(14 063)(35 156 708)\rSubvention d'investissement945 747945 747(37 542)908 205\rModifications comptables972972972\rVariation du pourcentage d'intérêt(32 205)(32 205)32 23732\rRésultat consolidé de l'exercice 201540 048 33540 048 33565 55040 113 885\rCapitaux propres consolidés au 31 décembre 2015549 072 620(472 190 804)16 729 01140 048 335133 659 1624 534 14665 550138 258 858  \
0    Capitaux propres consolidés au 31 décembre 2013
1  Affectation résultat\r\rDistribution des  divi...
2    Capitaux propres consolidés au 31 décembre 2014

    Unnamed: 0     Unnamed: 1  \
0  549 072 620  (472 190 804)
1          NaN            NaN
2  549 072 620  (472 190 804)

                                          Unnamed: 2  \
0                                                  -
1  25 001 566\r\r\r1 073 817\r(832 527)\r\r(111 384)
2                                         25 131 472

                                    Unnamed: 3  \
0                                   25 001 566
1  (25 001 566)\r\r\r\r\r\r2 002\r\r25 823 669
2                                   25 825 670

                                          Unnamed: 4  \
0                                        101 883 382
1  -\r\r-\r1 073 817\r(832 527)\r\r(109 382)\r\r2...
2                                        127 838 958

                                          Unnamed: 5  \
0                                          5 714 825
1  (364 004)\r\r(71 583)\r(30 567)\r(2 367)\r\r(1...
2                                          5 122 688

                         Unnamed: 6  \
0                         (364 004)
1  364 004\r\r\r\r\r\r\r\r(569 174)
2                         (569 174)

                                          Unnamed: 7 Unnamed: 8
0                                        107 234 203        NaN
1  -\r\r(71 583)\r1 043 249\r(834 894)\r\r(232 99...        NaN
2                                        132 392 472        NaN
Year 2015 - Table 8
                Libellé Solde au 31/12/2015 Solde au 31/12/2014
0    Fournisseurs d'exploitation 50 599 080          45 198 254
1    Fournisseurs effets à payer 11 269 248          14 944 184
2  Fournisseurs d'immobilisations 7 306 361          11 201 588
Year 2015 - Table 9
                                          Unnamed: 0 Unnamed: 1
0  Les revenus s’élèvent à 714 952 675 dinars en ...        NaN
1                                                NaN        NaN
2                                       Libellé 2015       2014
Year 2015 - Table 10
                          Total 33 252 784 Unnamed: 0 25 667 082
0                                      NaN        NaN        NaN
1                                      NaN        NaN        NaN
2  Note 23 : Autres charges d'exploitation        NaN        NaN
Year 2015 - Table 11
                                          Unnamed: 0  \
0                                                NaN
1                                                NaN
2  Liquidités, équivalents de liquidités et place...

                                Unnamed: 1
0                                      NaN
1  Solde au 31/12/2015 Solde au 31/12/2014
2                                      NaN
Year 2016 - Table 0
            Unnamed: 0 Note 31.12.2016 31.12.2015
0               Actifs  NaN        NaN        NaN
1  Actifs non courants  NaN        NaN        NaN
2                  NaN  NaN        NaN        NaN
Year 2016 - Table 1
                    Unnamed: 0 Note 31.12.2016 31.12.2015
0  Capitaux propres et passifs  NaN        NaN        NaN
1                          NaN  NaN        NaN        NaN

In [9]:
all_df = []

for year, tables in data.items():
    for df in tables:
        df = df.copy()
        df["year"] = year
        all_df.append(df)

final_df = pd.concat(all_df, ignore_index=True)
print(final_df.shape)
print(final_df.empty)

(3345, 174)
False

In [15]:
from IPython.display import display
import pandas as pd

# Vérifier les années disponibles
print(data.keys())

# Afficher un tableau précis
print("Nombre de tableaux en 2014 :", len(data[2014]))
display(data[2014][0])

# Afficher un autre tableau
print("Nombre de tableaux en 2018 :", len(data[2018]))
display(data[2018][1])

# Si display() ne fonctionne pas dans PyCharm
print(data[2014][0].head().to_string())

dict_keys([2014, 2015, 2016, 2017, 2018, 2020, 2021, 2022, 2023, 2024])
Nombre de tableaux en 2014 : 16

,Unnamed: 0,Unnamed: 1,Unnamed: 2,31.12.2013,31.12.2013.1
0,Actifs,NaN,31.12.2014,NaN,NaN
1,NaN,NaN,NaN,Retraité*,Publié
2,Actifs non courants,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN
4,Immobilisations incorporelles,NaN,2 518 600,2 139 982,2 139 982
...,...,...,...,...,...
40,-Provisions/ liquidités,NaN,-,(238 748),(238 748)
41,NaN,(10)*,20 486 536,25 208 370,26 679 729
42,NaN,NaN,NaN,NaN,NaN
43,Total des actifs courants,NaN,175 522 181,156 552 525,167 434 067
44,Total Actifs,NaN,382 180 380,319 488 915,330 370 457

Nombre de tableaux en 2018 : 13

,Groupe DELICE\rBILAN CONSOLIDE\r(Exprimé en dinars tunisiens)\r\r\rNotes31.12.201831.12.2017\rCapitaux propres et passifs\r\rCapital social549 072 620549 072 620\rRéserves de restructuration(472 190 804)(472 190 804)\rRéserves consolidés64 324 95743 763 910\r\rTotal Capitaux propres consolidés avant résultat de l'exercice141 206 773120 645 726\r\rRésultat de l'exercice\r30 891 57038 624 678\r\rTotal Capitaux propres consolidés172 098 343159 270 404\r\rIntérêts des minoritaires\r10 194 3375 058 567\r\rTotal Capitaux propres consolidés et intérêts minoritaires(11)182 292 680164 328 971\r\rPassifs non courants\r\rEmprunts(12)112 299 43465 059 521\rProvisions pour risques et charges(13)17 024 55416 732 674\rPassifs d'impôts différés(14)1 292 2232 639 956\r\r\rTotal des passifs non courants130 616 21184 432 151\r\rPassifs courants\r\rFournisseurs et comptes rattachés(15)105 514 26498 778 899\rAutres passifs courants(16)43 061 05143 718 923\rConcours bancaires et autres passifs financiers(10)65 462 51954 264 149\r\r\rTotal des passifs courants214 037 834196 761 971\r\rTotal passifs344 654 045281 194 122\r\r\rTotal Capitaux propres et passifs526 946 725445 523 093,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,Total Capitaux propres consolidés avant résult...,NaN,NaN,141 206 77,NaN,NaN,120 645 72,NaN,NaN
1,NaN,NaN,30 891 570,38 624 67,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Résultat de l'exercice,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Résultat de l'exercice,30 891 57,38 624 67,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,NaN,Total Capitaux propres et passifs,NaN,NaN,NaN,526 946 72,NaN,NaN,445 523 09,NaN
65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

                      Unnamed: 0 Unnamed: 1  Unnamed: 2 31.12.2013 31.12.2013.1
0                         Actifs        NaN  31.12.2014        NaN          NaN
1                            NaN        NaN         NaN  Retraité*       Publié
2            Actifs non courants        NaN         NaN        NaN          NaN
3                            NaN        NaN         NaN        NaN          NaN
4  Immobilisations incorporelles        NaN   2 518 600  2 139 982    2 139 982