In [5]:
import pickle
from pathlib import Path
import pandas as pd

In [6]:
file_path = Path("output/GROUPE_DELICE/DELICE_tables.pkl")

with open(file_path, "rb") as f:
    data = pickle.load(f)

print("Type de données :", type(data))

Type de données : <class 'dict'>

In [7]:
print("Contenu (clés principales) :")
print(data.keys())

Contenu (clés principales) :
dict_keys([2014, 2015, 2016, 2017, 2018, 2020, 2021, 2022, 2023, 2024])

In [9]:
# Supposons que 'data' soit ton dict {year: [tables]}
year = 2014   # année cible

if year in data:
    tables = data[year]
    print("\n" + "="*60)
    print(f"📅 Année : {year}")
    print(f"📊 Nombre de tableaux : {len(tables)}")

    for i, df in enumerate(tables):
        print("\n------------------------------")
        print(f"Tableau {i+1}")
        display(df)   # Jupyter affiche le DataFrame proprement
else:
    print(f"⚠️ Aucun tableau trouvé pour l'année {year}")

============================================================
📅 Année : 2014
📊 Nombre de tableaux : 16

------------------------------
Tableau 1

,Unnamed: 0,Unnamed: 1,Unnamed: 2,31.12.2013,31.12.2013.1
0,Actifs,NaN,31.12.2014,NaN,NaN
1,NaN,NaN,NaN,Retraité*,Publié
2,Actifs non courants,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN
4,Immobilisations incorporelles,NaN,2 518 600,2 139 982,2 139 982
5,-Amortissements Immobilisations incorporelles,NaN,(1 877 592),(1 748 255),(1 748 255)
6,NaN,(1),641 008,391 727,391 727
7,NaN,NaN,NaN,NaN,NaN
8,Immobilisations corporelles,NaN,338 360 399,276 575 028,276 575 028
9,-Amortissements immobilisations corporelles,NaN,(152 266 670),(132 096 974),(132 096 974)
10,NaN,(2),186 093 729,144 478 054,144 478 054
11,NaN,NaN,NaN,NaN,NaN
12,Immobilisations financières,NaN,12 056 366,11 755 350,11 755 350
13,-Provisions pour dépréciation des immobilisations,NaN,NaN,NaN,NaN
14,NaN,NaN,(2 067 251),(2 060 375),(2 060 375)
15,financières,NaN,NaN,NaN,NaN
16,NaN,(3),9 989 115,9 694 975,9 694 975
17,NaN,NaN,NaN,NaN,NaN
18,Autres actifs non courants,(4),2 598 222,1 985 729,1 985 729
19,NaN,NaN,NaN,NaN,NaN
20,Actifs d'impôts différés,(5),7 336 125,6 385 905,6 385 904
21,NaN,NaN,NaN,NaN,NaN
22,Total des actifs non courants,NaN,206 658 199,162 936 390,162 936 390
23,Actifs non courants,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN
25,Stocks,NaN,79 668 106,53 481 539,53 481 539
26,- Provisions pour dépréciation des stocks,NaN,(2 880 395),(2 401 576),(2 401 577)
27,NaN,(6),76 787 711,51 079 963,51 079 963
28,NaN,NaN,NaN,NaN,NaN
29,Clients et comptes rattachés,NaN,20 137 365,17 563 391,30 498 486
30,-Provisions pour dépréciation des clients,NaN,(2 848 625),(3 258 971),(3 258 971)
31,NaN,(7)*,17 288 740,14 304 420,27 239 515
32,NaN,NaN,NaN,NaN,NaN
33,Autres actifs courants,NaN,47 303 140,66 754 028,63 229 117
34,-Provisions pour dépréciation des autres actif...,NaN,(1 343 946),(794 256),(794 256)
35,NaN,(8)*,45 959 194,65 959 772,62 434 861
36,NaN,NaN,NaN,NaN,NaN
37,Placements et autres actifs financiers,(9),15 000 000,-,-
38,NaN,NaN,NaN,NaN,NaN
39,Liquidités et équivalents de liquidités,NaN,20 486 536,25 447 118,26 918 477
40,-Provisions/ liquidités,NaN,-,(238 748),(238 748)
41,NaN,(10)*,20 486 536,25 208 370,26 679 729
42,NaN,NaN,NaN,NaN,NaN
43,Total des actifs courants,NaN,175 522 181,156 552 525,167 434 067
44,Total Actifs,NaN,382 180 380,319 488 915,330 370 457

------------------------------
Tableau 2

,Unnamed: 0,Unnamed: 1,Unnamed: 2,31.12.2013,31.12.2013.1
0,Capitaux propres et passifs,NaN,31.12.2014,NaN,NaN
1,NaN,NaN,NaN,Retraité*,Publié
2,NaN,NaN,NaN,NaN,NaN
3,Capital social,NaN,549 072 620,549 072 620,549 072 620
4,Réserves de restructuration,NaN,(472 190 804),(472 190 804),(472 190 804)
5,Réserves consolidés,NaN,25 131 472,-,-
6,NaN,NaN,NaN,NaN,NaN
7,Total des capitaux propres consolidés avant ré...,NaN,NaN,NaN,NaN
8,NaN,NaN,102 013 288,76 881 816,76 881 816
9,l'exercice,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN
11,Résultat de l'exercice,NaN,25 825 670,25 001 566,25 001 566
12,NaN,NaN,NaN,NaN,NaN
13,Total des capitaux propres consolidés,NaN,127 838 958,101 883 382,101 883 382
14,NaN,NaN,NaN,NaN,NaN
15,Intérêts des minoritaires,NaN,4 553 514,5 350 821,5 350 821
16,NaN,NaN,NaN,NaN,NaN
17,Total des capitaux propres consolidés et intér...,NaN,NaN,NaN,NaN
18,NaN,(11),132 392 472,107 234 203,107 234 203
19,minoritaires,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN
21,Passifs non courants,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN
23,Emprunts,(12),63 138 204,39 055 077,39 055 077
24,NaN,NaN,NaN,NaN,NaN
25,Provisions,(13),12 924 296,12 073 838,12 073 838
26,NaN,NaN,NaN,NaN,NaN
27,Passifs d'impôts différés,(14),854 815,854 815,854 815
28,NaN,NaN,NaN,NaN,NaN
29,Total des passifs non courants,NaN,76 917 315,51 983 730,51 983 730
30,NaN,NaN,NaN,NaN,NaN
31,Passifs courants,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN
33,Fournisseurs et comptes rattachés,(15)*,90 611 837,72 514 690,83 396 233
34,NaN,NaN,NaN,NaN,NaN
35,Autres passifs courants,(16),26 367 434,30 769 566,30 769 566
36,NaN,NaN,NaN,NaN,NaN
37,Concours bancaires et autres passifs financiers,(10),55 891 322,56 986 725,56 986 725
38,NaN,NaN,NaN,NaN,NaN
39,Total des passifs courants,NaN,172 870 593,160 270 980,171 152 524
40,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN
42,Total des passifs,NaN,249 787 908,212 254 711,223 136 254
43,NaN,NaN,NaN,NaN,NaN
44,Total Capitaux propres et passifs,NaN,382 180 380,319 488 915,330 370 457

------------------------------
Tableau 3

,Unnamed: 0,Unnamed: 1,Unnamed: 2,31.12.2013,31.12.2013.1
0,NaN,NaN,31.12.2014,NaN,NaN
1,NaN,NaN,NaN,Retraité*,Publié
2,NaN,NaN,NaN,NaN,NaN
3,Revenus,(17)*,647 588 213,560 723 738,529 773 045
4,Autres produits d'exploitation,(18)*,12 807 509,6 982 368,50 241 196
5,Total des produits d'exploitation,NaN,660 395 722,567 706 106,580 014 242
6,NaN,NaN,NaN,NaN,NaN
7,Variation des stocks des Produits Finis,NaN,(690 675),6 004 351,4 861 352
8,Achats consommés,(19)*,(501 025 458),(433 710 276),(436 553 845)
9,Charges de personnel,(20)*,(52 702 542),(44 285 123),(42 345 648)
10,Dotations aux amortissements et aux provisions,(21)*,(25 667 082),(22 549 958),(26 306 952)
11,Autres charges d'exploitation,(22)*,(38 769 810),(32 383 796),(34 323 271)
12,NaN,NaN,NaN,NaN,NaN
13,Total des charges d'exploitation,NaN,(618 855 567),(526 924 802),(534 668 364)
14,NaN,NaN,NaN,NaN,NaN
15,Résultat d'exploitation,NaN,41 540 155,40 781 304,45 345 878
16,NaN,NaN,NaN,NaN,NaN
17,Charges financières nettes,(23),(8 639 380),(5 941 045),(5 941 045)
18,Produits financiers,(24),1 245 625,616 634,616 634
19,Autres gains ordinaires,(25),225 449,539 470,539 470
20,Autres pertes ordinaires,(26)*,(334 994),(2 195 710),(6 760 283)
21,NaN,NaN,NaN,NaN,NaN
22,Résultat des activités ordinaires avant impôt,NaN,34 036 855,33 800 653,33 800 653
23,NaN,NaN,NaN,NaN,NaN
24,Impôts sur les bénéfices,NaN,(9 637 815),(9 888 352),(9 888 352)
25,Impôt différé,NaN,857 455,725 261,725 261
26,NaN,NaN,NaN,NaN,NaN
27,Résultat des activités ordinaires après impôt,NaN,25 256 495,24 637 562,24 637 562
28,Part revenant aux intérêts minoritaires,(11),(569 175),(364 004),(364 004)
29,Résultat net consolidé (Part revenant au groupe),NaN,25 825 670,25 001 566,25 001 566
30,Nombre moyen des actions,NaN,54 907 262,54 907 262,54 907 262
31,Résultat par action,(28),"0,470","0,455","0,455"

------------------------------
Tableau 4

,Unnamed: 0,Unnamed: 1,31.12.2014,31.12.2013
0,Résultat net (Groupe),NaN,25 825 670,25 001 566
1,Ajustement pour:,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,*Part revenant aux intérêts minoritaires,(11),(569 175),(364 004)
4,"*Amortissements, Provisions & Reprises de prov...",(21),25 667 082,18 126 730
5,*Variation des:,NaN,NaN,NaN
6,-Autres actifs non courants,NaN,(1 521 667),(737 652)
7,- Stocks,NaN,(26 186 567),(9 039 778)
8,- Créances clients,NaN,(2 573 974),(10 238 419)
9,- Autres actifs,NaN,19 450 888,(7 452 946)
10,- Fournisseurs et autres dettes,NaN,22 405 415,13 430 684
11,-Autres passifs courants,NaN,(4 402 132),9 402 878
12,-Autres éléments sans incidence sur la trésorerie,NaN,2 244 787,5 848 672
13,NaN,NaN,NaN,NaN
14,*Impôt différé,NaN,(857 455),(725 261)
15,*Intérêts Emprunts,(23),1 094 784,317 803
16,NaN,NaN,NaN,NaN
17,Flux de trésorerie provenant de (affectés à) l...,NaN,60 577 656,43 570 272
18,NaN,NaN,NaN,NaN
19,Variation de trésorerie provenant de l'acquisi...,NaN,NaN,NaN
20,NaN,NaN,(59 062 807),(56 958 039)
21,corporelles et incorporelles,NaN,NaN,NaN
22,Variation de trésorerie provenant des immobili...,NaN,(1 499 881),(6 687 966)
23,NaN,NaN,NaN,NaN
24,Flux de trésorerie provenant des (affectés aux...,NaN,(60 562 688),(63 646 005)
25,NaN,NaN,NaN,NaN
26,Encaissement suite à l'augmentation du capital,NaN,6 000 000,18 010 000
27,Dividendes et autres distributions,NaN,-,(15 836 723)
28,Encaissements provenant des subventions d'inve...,NaN,1 183 640,455 628
29,Variation de trésorerie provenant des emprunts,NaN,(6 908 880),12 400 033
30,NaN,NaN,NaN,NaN
31,Flux de trésorerie provenant des (affectés aux...,NaN,274 760,15 028 938
32,NaN,NaN,NaN,NaN
33,Variation de trésorerie,NaN,289 728,-5 046 794
34,NaN,NaN,NaN,NaN
35,Trésorerie au début de l’exercice,(27),11 253 407,16 300 200
36,NaN,NaN,NaN,NaN
37,Trésorerie à la clôture de l’exercice,(27),11 543 135,11 253 407

------------------------------
Tableau 5

,Société,% de contrôle,% d’intérêts groupe,Type de contrôle,Méthode de comptabilisation
0,DELICE Holding,100%,100%,Société mère,NaN
1,CLC,"99,72%","99,72%",Contrôle exclusif,Intégration globale
2,CLN,"96,98%","96,71%",Contrôle exclusif,Intégration globale
3,CLSB,"99,99%","99,72%",Contrôle exclusif,Intégration globale
4,SBC,"99,99%","99,99%",Contrôle exclusif,Intégration globale
5,CF,"57,50%","57,49%",Contrôle exclusif,Intégration globale
6,Delta plastic,"99,99%","99,99%",Contrôle exclusif,Intégration globale

------------------------------
Tableau 6

,La valeur nette des immobilisations incorporelles et corporelles s’élève à 186 734 737 dinars au 31 décembre 2014 et se détaille comme suit :,Unnamed: 0,Unnamed: 1
0,Cession et,NaN,NaN
1,Amortissements Montants en TND Valeur Brute En...,VCN 2013,VCN 2014
2,Dec 2013 2014 Dec 2014 cumulés 2013 2014 / ces...,NaN,NaN
3,2014,NaN,NaN
4,Logiciels 1 865 366 160 344 2 025 710 1 701 33...,164 032,195 038
5,Concessions de marques et brevets 46 920 - ...,-,-
6,Immobilisations incorporelles en cours 227 696...,227 696,445 970
7,Total immobilisations incorporelles 2 139 982 ...,391 726,641 008
8,Terrains 7 900 025 981 702 - 8 881 727 - ...,7 900 025,8 881 727
9,Constructions 21 689 455 21 555 390 1 204 132 ...,12 995 853,31 616 345
10,Matériel industriel 129 502 344 55 488 162 3 0...,48 140 957,90 338 796
11,Outillage industriel 3 619 470 1 961 807 47 06...,1 939 903,3 203 431
12,Matériel de transport 25 589 729 7 631 695 1 4...,9 930 294,13 528 620
13,"Agencements, aménagements et installations",NaN,NaN
14,31 600 922 6 760 041 322 871 38 038 092 14 767...,16 833 342,20 101 920
15,divers,NaN,NaN
16,Equipements de bureau 1 308 480 559 245 - 1 ...,331 732,723 940
17,Matériel informatique 5 254 592 1 124 605 - ...,1 604 473,2 003 116
18,Matériel d'emballage 2 636 703 219 879 155 811...,1 093 990,774 284
19,Frigos 1 772 770 8 557 - 1 781 327 1 697 036...,75 734,25 715
20,Immobilisation à statut juridique particulier ...,1 121 695,1 010 480
21,Immobilisations en cours 36 302 437 26 470 877...,36 302 437,15 651 821
22,Avances et acomptes sur immobilisations 7 923 ...,7 923 741,120 145
23,Provisions constituées - - - - 1 716 1...,(1 716 120),(1 886 614)
24,Total immobilisations corporelles 276 575 028 ...,144 478 054,186 093 729
25,Total immobilisations incorporelles et,NaN,NaN
26,278 715 010 123 733 910 61 569 925 340 878 999...,144 869 780,186 734 737
27,corporelles,NaN,NaN

------------------------------
Tableau 7

,Libellé Solde au 31/12/2014,Solde au 31/12/2013,Solde au 31/12/2013.1
0,NaN,Retraité**,Publié
1,NaN,NaN,NaN
2,Clients locaux 14 003 205,13 033 087,27 959 357
3,Clients douteux 2 372 830,2 384 291,2 384 291
4,Clients effets escomptés non échus 2 879 483,1 252 081,NaN
5,Effets à l'encaissement 392 015,739 095,NaN
6,Clients étrangers 489 832,154 837,154 837
7,NaN,NaN,NaN
8,Total brut 20 137 365,17 563 391,30 498 486
9,NaN,NaN,NaN
10,Provisions sur créances clients (2 848 625),(3 258 971),(3 258 971)
11,NaN,NaN,NaN
12,Total net 17 288 740,14 304 420,27 239 515
13,**Les montants relatifs à l’exercice clos le 3...,NaN,NaN
14,Note 8 : Autres actifs courants,NaN,NaN
15,Les autres actifs courants présentent un solde...,NaN,NaN
16,comme suit :,NaN,NaN
17,NaN,NaN,NaN
18,NaN,Solde au 31/12/2013,Solde au 31/12/2013
19,Libellé Solde au 31/12/2014,Retraité**,Publié
20,Débiteurs divers 6 523 161,29 809 925,30 124 775
21,Fournisseurs avances et acomptes 18 624 612,14 024 696,10 184 935
22,Etat subventions à recevoir 8 846 706,8 548 148,8 548 148
23,Etat impôts et taxes 4 011 735,5 581 328,5 581 328
24,Produits à recevoir 5 077 746,5 247 071,5 247 071
25,Autres actifs courants 599 600,1 054 774,1 054 774
26,Acomptes provisionnels 1 840 322,1 031 582,1 031 582
27,Prêts aux personnels 1 038 302,910 245,910 245
28,Etat retenue à la source 382 889,244 698,244 698
29,Charges constatées d'avance 217 749,221 371,221 371
30,Dépôts et cautionnements 70 578,39 197,39 197
31,Comptes d'attente actif 16 358,27 213,27 213
32,Personnel avances et acomptes 53 382,13 781,13 781

------------------------------
Tableau 8

,Total 20 486 536,25 447 118,26 918 477
0,**Les montants relatifs à l’exercice clos le 3...,NaN,NaN
1,Les concours bancaires et autres passifs finan...,NaN,NaN
2,2014 et se détaillent comme suit :,NaN,NaN
3,NaN,NaN,NaN
4,NaN,Solde au 31/12/2013,Solde au
5,Libellé Solde au 31/12/2014,NaN,NaN
6,NaN,Retraité,31/12/2013
7,NaN,NaN,NaN
8,Concours bancaires,23 852 223 14 193 711,14 193 711
9,Crédits financement cycle d'exploitation,12 220 000 31 263 867,31 263 867
10,Emprunts liés aux contrats de portage à moins ...,2 328 800,928 800 928 800
11,Emprunts échéance à moins d'un an,12 276 688,9 070 080 9 070 080
12,Effets escomptés non échus,2 879 483,1 252 081 1 252 081
13,Intérêts courus,2 334 128,278 186 278 186
14,Total,55 891 322 56 986 725,56 986 725

------------------------------
Tableau 9

,Unnamed: 0,Note 11 : Capitaux propres\rTABLEAU DES MOUVEMENTS DES CAPITAUX PROPRES\rExercice clos le 31 Décembre 2014\r\rTotal des\rIntérêts desIntérêts desTotal des\rRéserves deRéservesRésultat decapitaux\rCapital socialminoritaires/minoritaires/capitaux\rrestructurationconsolidéesl'exercicepropres (part\rréservesrésultatpropres\rdu groupe)\r\r\rCapitaux propres consolidés au 31 décembre 2013549 072 620(472 190 804)-25 001 566101 883 3825 714 825(364 004)107 234 203\r\r\rAffectation résultat25 001 566(25 001 566)\r-(364 004)364 004-\r\r\rDistribution des Dividendes-(71 583)(71 583)\r\rSubvention d'investissement1 073 8171 073 817(30 567)1 043 249\r\rModifications comptables(832 527)(832 527)(2 367)(834 894)\r\rVariation du périmètre(111 384)2 002(109 382)(123 616)(232 998)\r\rRésultat consolidé de l'exercice 201425 823 66925 823 669(569 174)25 254 495\r\r\rCapitaux propres consolidés au 31 décembre 2014549 072 620(472 190 804)25 131 47225 825 670127 838 9585 122 688(569 174)132 392 472,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,Capital social,Réserves de\rrestructuration,Réserves\rconsolidées,Résultat de\rl'exercice,Total des\rcapitaux\rpropres (part\rdu groupe),Intérêts des\rminoritaires/\rréserves,Intérêts des\rminoritaires/\rrésultat,Total des\rcapitaux\rpropres
1,Capitaux propres consolidés au 31 décembre 2013,549 072 620,(472 190 804),-,25 001 566,101 883 382,5 714 825,(364 004),107 234 203
2,Affectation résultat\r\rDistribution des Divi...,NaN,NaN,25 001 566\r\r\r\r1 073 817\r\r(832 527)\r\r(1...,(25 001 566)\r\r\r\r\r\r\r\r2 002\r\r25 823 669,-\r\r-\r\r1 073 817\r\r(832 527)\r\r(109 382)\...,(364 004)\r\r(71 583)\r\r(30 567)\r\r(2 367)\r...,364 004\r\r\r\r\r\r\r\r\r\r(569 174),-\r\r(71 583)\r\r1 043 249\r\r(834 894)\r\r(23...
3,Capitaux propres consolidés au 31 décembre 2014,549 072 620,(472 190 804),25 131 472,25 825 670,127 838 958,5 122 688,(569 174),132 392 472

------------------------------
Tableau 10

,Note 11 : Capitaux propres\rTABLEAU DES MOUVEMENTS DES CAPITAUX PROPRES\rExercice clos le 31 Décembre 2014\r\rTotal des\rIntérêts desIntérêts desTotal des\rRéserves deRéservesRésultat decapitaux\rCapital socialminoritaires/minoritaires/capitaux\rrestructurationconsolidéesl'exercicepropres (part\rréservesrésultatpropres\rdu groupe)\r\r\rCapitaux propres consolidés au 31 décembre 2013549 072 620(472 190 804)-25 001 566101 883 3825 714 825(364 004)107 234 203\r\r\rAffectation résultat25 001 566(25 001 566)\r-(364 004)364 004-\r\r\rDistribution des Dividendes-(71 583)(71 583)\r\rSubvention d'investissement1 073 8171 073 817(30 567)1 043 249\r\rModifications comptables(832 527)(832 527)(2 367)(834 894)\r\rVariation du périmètre(111 384)2 002(109 382)(123 616)(232 998)\r\rRésultat consolidé de l'exercice 201425 823 66925 823 669(569 174)25 254 495\r\r\rCapitaux propres consolidés au 31 décembre 2014549 072 620(472 190 804)25 131 47225 825 670127 838 9585 122 688(569 174)132 392 472,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Capitaux propres consolidés au 31 décembre 2013,549 072 620,(472 190 804),-,25 001 566,101 883 382,5 714 825,(364 004),107 234 203
1,Affectation résultat\r\rDistribution des Divi...,NaN,NaN,25 001 566\r\r\r\r1 073 817\r\r(832 527)\r\r(1...,(25 001 566)\r\r\r\r\r\r\r\r2 002\r\r25 823 669,-\r\r-\r\r1 073 817\r\r(832 527)\r\r(109 382)\...,(364 004)\r\r(71 583)\r\r(30 567)\r\r(2 367)\r...,364 004\r\r\r\r\r\r\r\r\r\r(569 174),-\r\r(71 583)\r\r1 043 249\r\r(834 894)\r\r(23...
2,Capitaux propres consolidés au 31 décembre 2014,549 072 620,(472 190 804),25 131 472,25 825 670,127 838 958,5 122 688,(569 174),132 392 472

------------------------------
Tableau 11

,Unnamed: 0,Unnamed: 1,Solde au 31/12/2013,Solde au 31/12/2013.1
0,Libellé,Solde au 31/12/2014,NaN,NaN
1,NaN,NaN,Retraité,Publié
2,NaN,NaN,NaN,NaN
3,Clients avances et acomptes,3 432 360,5 991 232,5 991 232
4,Autres avoirs,3 572,-,-
5,Comptes de personnel,2 332 367,1 880 219,1 880 219
6,Etat impôts/taxes,5 245 875,5 790 634,5 790 634
7,Autres passifs courants,5 422 128,8 860 188,8 860 188
8,Retenues,11 865,49 804,49 804
9,Créditeurs divers,7 432 032,5 502 158,5 502 158
10,Cotisations sociales,2 362 450,2 436 164,2 436 164

------------------------------
Tableau 12

                           Note 19 : Achats consommés Unnamed: 0
0                                                 NaN        NaN
1   Les achats consommés s’élèvent à 501 025 458 d...        NaN
2                                                 NaN        NaN
3            Libellé 2014 2013 Retraité** 2013 Publié        NaN
4   Achats matières premières 342 453 489 301 837 ...        NaN
5   Achats emballages 132 175 638 112 774 813 114 ...        NaN
6   Achat de prestation de services 2 454 476 720 ...        NaN
7      Electricité 11 409 324   8 563 002   8 563 002        NaN
8   Achats matières consommables 5 842 405   4 765...        NaN
9   Achats pièces de rechange 6 205 749   4 232 84...        NaN
10  Achats de marchandises consommées 4 888 917   ...        NaN
11       Carburants 1 521 066   1 528 830   1 528 830        NaN
12                     Eaux 1 401 594 874 806 874 806        NaN
13                      Gaz 1 632 121 717 103 717 103        NaN
14          Frais sur achats 87 017   78 804   78 804        NaN
15  Rabais et ristournes sur achats (9 046 338) (6...        NaN
16          Total 501 025 458 433 710 276 436 553 846        NaN
17  **Les montants relatifs à l’exercice clos le 3...        NaN
18                                                NaN        NaN
19                                                NaN        NaN
20                     Note 20 : Charges de personnel        NaN
21                                                NaN        NaN
22  Les charges de personnel s’élèvent à 52 702 54...        NaN
23                                                NaN        NaN
24           Libellé 2014 2013 Retraité** 2013 Publié        NaN
25  Appointements et salaires 41 837 792 35 224 74...        NaN
26     Charges sociales 6 590 846 5 595 572 5 116 808        NaN
27      Cotisations assurance 846 825 755 151 755 151        NaN
28  Autres charges de personnel 3 427 079 2 709 65...        NaN
29             Total 52 702 542 44 285 123 42 345 649        NaN
30  **Les montants relatifs à l’exercice clos le 3...        NaN
31                                                NaN        NaN
32  Note 21 : Dotations aux amortissements et aux ...        NaN
33                                                NaN        NaN
34  Les dotations aux amortissements et aux provis...        NaN
35                                             suit :        NaN
36                                                NaN        NaN
37                                               2013        NaN
38                           Libellé 2014 2013 Publié        NaN
39                                         Retraité**        NaN
40  Dotations aux amortissements et provisions des...        NaN
41  Dotation (nettes) aux provisions pour risques ...        NaN
42  Dotation (nettes) aux provisions /des titres d...        NaN
43  Dotation (nettes) aux provisions pour déprécia...        NaN
44  Dotation (nettes) aux provisions pour déprécia...        NaN
45  Dotation (nettes) aux résorptions des frais pr...        NaN
46        Reprise sur provision Liquidité (238 748) -          -
47           Total 25 667 082  22 549 958  26 306 952        NaN

------------------------------
Tableau 13

,Total 8 639 380,5 941 045,Unnamed: 0,5 941 045.1
0,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,Note 24 : Produits financiers,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN
4,Les produits financiers s’élèvent à 1 245 62...,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN
6,Libellé 2014,2013 Retraité,NaN,2013 Publié
7,NaN,NaN,NaN,NaN
8,Produits des placements 1 245 625,501 854,NaN,501 854
9,Intérêts des comptes courants -,113 343,NaN,113 343
10,Produits des participations -,1 438,NaN,1 438
11,Total 1 245 62,616 634,NaN,616 634

------------------------------
Tableau 14

                               Unnamed: 0        2014        2013
0                                     NaN         NaN         NaN
1              Résultat net consolidé (A)  25 825 670  25 001 566
2                                     NaN         NaN         NaN
3  Nombre des actions en début de période  54 907 262  54 907 262
4                                     NaN         NaN         NaN
5    Nombre des actions en fin de période  54 907 262  54 907 262
6                                     NaN         NaN         NaN
7            Nombre moyen des actions (B)  54 907 262  54 907 262
8                                     NaN         NaN         NaN
9     Résultat par action en dinars (A/B)       0,470       0,455

------------------------------
Tableau 15

,Unnamed: 0,Unnamed: 1,Unnamed: 2
0,"Liquidités, équivalents de liquidités et place...",Solde au 31/12/2014,Solde au 31/12/2013
1,Placements,15 000 000,-
2,Banques,18 305 339,25 165 275
3,Caisses,5 204,257 681
4,Chèques à l'encaissement,2 084 815,24 162
5,Total (A),35 395 358,25 447 118
6,Concours bancaires et autres passifs financier...,Solde au 31/12/2014,Solde au 31/12/2013
7,Concours bancaires,23 852 223,14 193 711
8,Total (B),23 852 223,14 193 711
9,Trésorerie nette (A-B),11 543 135,11 253 407

------------------------------
Tableau 16

,Autres produits,Unnamed: 0,Unnamed: 1,Unnamed: 2,Les reprises,/,provision,pour,un,montant,de
0,NaN,6 982 368,50 241 196,(43 258 828),NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,d'exploitation,NaN,NaN,NaN,3 756 994 dinars relatives à des participatio...,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,cédées ont été,reclassées,au,niveau,de,la rubrique,NaN
3,NaN,NaN,NaN,NaN,"""dotations / reprises des amortissements/provi...",NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,Les reprises,/,provision,pour,un,montant,de
5,NaN,NaN,NaN,NaN,4 564 573 dinars relatives à des participatio...,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,ont été reclassées,NaN,au niveau,de la,rubrique,"""autres",NaN
7,NaN,NaN,NaN,NaN,"pertes ordinaires""",NaN,NaN,NaN,NaN,NaN,NaN
8,Variation des,NaN,NaN,NaN,Un montant de 1 142 999 dinars relatif à une v...,NaN,NaN,NaN,NaN,NaN,NaN
9,stocks des PF et,6 004 351,4 861 352,1 142 999,du stock d'emballages a été reclassé parmi les...,NaN,NaN,NaN,NaN,NaN,NaN
10,des encours,NaN,NaN,NaN,consommés,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,Les ristournes,NaN,sur achats,ont,été,reclassées,en
12,NaN,NaN,NaN,NaN,déduction des achats consommés pour le montant de,NaN,NaN,NaN,NaN,NaN,NaN
13,Achats,NaN,NaN,NaN,3 986 568 dinars,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,(433 710 276),(436 553 845),2 843 569,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,consommés,NaN,NaN,NaN,Un montant de 1 142 999 dinars relatif à une v...,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,du stock d'emballages a été reclassé parmi les...,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,consommés,NaN,NaN,NaN,NaN,NaN,NaN
18,Charges de,NaN,NaN,NaN,Un montant de 1 939 475 dinars et relatif à d...,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,(44 285 123),(42 345 648),(1 939 475),NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,personnel,NaN,NaN,NaN,servies a été reclassé parmi les charges de pe...,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,Les reprises / provision pour un montant de,NaN,NaN,NaN,NaN,NaN,3
22,Dotations aux,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,756 994 dinars,NaN,relatives à,des,participations,NaN,non
24,amortissements,(22 549 958),(26 306 952),3 756 994,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,cédées ont été,reclassées,au,niveau,de,la rubrique,NaN
26,et aux provisions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,"""dotations / reprises des amortissements/provi...",NaN,NaN,NaN,NaN,NaN,NaN
28,Autres charges,NaN,NaN,NaN,Un montant de 1 939 475 dinars et relatif à d...,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,(32 383 796),(34 323 271),1 939 475,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,d'exploitation,NaN,NaN,NaN,servies a été reclassé parmi les charges de pe...,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,Les reprises,/,provision,pour,un,montant,de
32,Autres pertes,NaN,NaN,NaN,4 564 573 dinars relatives à des participatio...,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,(2 195 710),(6 760 283),4 564 573,NaN,NaN,NaN,NaN,NaN,NaN,NaN