In [1]:
import pickle
from pathlib import Path
import pandas as pd

In [2]:
file_path = Path("output/GROUPE_POULINA/POULINA_tables.pkl")

with open(file_path, "rb") as f:
    data = pickle.load(f)

print("Type de données :", type(data))

Type de données : <class 'dict'>

In [3]:
print("Contenu (clés principales) :")
print(data.keys())

Contenu (clés principales) :
dict_keys([2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024])

In [4]:
year = 2014  # 👉 change ici l'année que tu veux

if year in data:
    tables = data[year]

    print("="*60)
    print(f"📅 Année : {year}")
    print(f"📊 Nombre de tableaux : {len(tables)}")

    for i, df in enumerate(tables):
        print("\n------------------------------")
        print(f"Tableau {i+1}")
        display(df)
else:
    print("❌ Année introuvable :", year)

============================================================
📅 Année : 2014
📊 Nombre de tableaux : 53

------------------------------
Tableau 1

,Unnamed: 0,POULINA GROUP HOLDING S.A. ( P G H )
0,NaN,BILAN CONSOLIDE
1,NaN,Au 30/06/2014
2,NaN,(Exprimé en TND)
3,ACTIFS,NaN
4,ACTIFS NON COURANTS,Notes 30/06/2014 30/06/2013 31/12/2013
5,Actifs immobilisés,NaN
6,Immobilisations incorporelles,11 577 992 11 527 341 11 664 558
7,Amortissements des immobilisations incorporelles,-7 679 515 -6 624 647 -7 103 235
8,Immobilisations incorporelles nettes,1 3 898 477 4 902 694 4 561 324
9,Immobilisations corporelles,1 274 258 679 1 171 949 325 1 237 059 102
10,Amortissements des immobilisations corporelles,-619 312 814 -556 379 170 -589 825 894
11,Immobilisations corporelles nettes,2 654 945 865 615 570 155 647 233 208
12,Immobilisations financières,234 107 623 228 691 639 231 744 984
13,Provisions pour dépréciation,-4 305 122 -2 345 145 -4 263 355
14,Immobilisations financières nettes,3 229 802 501 226 346 494 227 481 628
15,Total des actifs immobilisés,888 646 842 846 819 343 879 276 160
16,Autres actifs non courants,4 8 369 865 3 349 634 5 765 396
17,Total des autres actifs non courants,8 369 865 3 349 634 5 765 396
18,Total des actifs non courants,897 016 707 850 168 977 885 041 557
19,ACTIFS COURANTS,NaN
20,Stocks,409 736 651 381 977 474 415 460 771
21,Provisions sur stocks,-4 389 945 -4 139 471 -4 550 524
22,Stocks nets,5 405 346 706 377 838 002 410 910 248
23,Clients et comptes rattachés,330 593 922 287 240 326 268 544 863
24,Provisions sur comptes clients,-23 397 260 -21 979 569 -23 573 610
25,Clients nets,6 307 196 662 265 260 757 244 971 253
26,Autres actifs courants,7 88 034 629 78 444 658 130 382 675
27,Placements et autres actifs financiers,8 11 740 958 24 302 962 17 914 804
28,Liquidités et équivalents de liquidités,9 70 431 221 71 913 656 87 037 500
29,Total des actifs courants,882 750 176 817 760 035 891 216 480
30,TOTAL DES ACTIFS,1 779 766 883 1 667 929 012 1 776 258 036

------------------------------
Tableau 2

,Unnamed: 0,POULINA GROUP HOLDING S.A. ( P G H )
0,NaN,BILAN CONSOLIDE
1,NaN,Au 30/06/2014
2,NaN,(Exprimé en TND)
3,CAPITAUX PROPRES ET PASSIFS,NaN
4,CAPITAUX PROPRES,Notes 30/06/2014 30/06/2013 31/12/2013
5,Capital social,180 003 600 180 003 600 180 003 600
6,Réserves consolidées,329 398 446 293 222 385 308 191 767
7,Résultats consolidés,44 386 560 40 316 492 67 243 989
8,Total des capitaux propres,10 553 788 606 513 542 477 555 439 356
9,INTERETS DES MINORITAIRES,NaN
10,Part des minoritaires dans les réserves,18 494 169 15 150 562 18 448 952
11,Part des minoritaires dans le résultat,-673 642 -644 029 -1 276 272
12,Total des intérêts des minoritaires,11 17 820 527 14 506 533 17 172 680
13,Total des capitaux propres et intérêts des min...,571 609 133 528 049 010 572 612 037
14,PASSIFS,NaN
15,PASSIFS NON COURANTS,NaN
16,Emprunts,539 791 170 534 631 126 573 470 163
17,Provisions pour risques et charges,3 498 683 3 779 098 3 671 599
18,Total des passifs non courants,12 543 289 853 538 410 223 577 141 762
19,PASSIFS COURANTS,NaN
20,Fournisseurs et comptes rattachés,13 200 244 280 130 636 472 195 393 165
21,Autres passifs courants,14 91 768 344 64 001 347 36 044 834
22,Concours bancaires et autres passifs financiers,15 372 855 274 406 831 959 395 066 238
23,Total des passifs courants,664 867 897 572 295 980 626 504 237
24,Total des passifs,1 208 157 750 1 139 880 001 1 203 646 000
25,TOTAL DES CAPITAUX PROPRES ET PASSIFS,1 779 766 883 1 667 929 012 1 776 258 036

------------------------------
Tableau 3

,Unnamed: 0,POULINA GROUP HOLDING S.A. ( P G H )
0,NaN,ETAT DE RESULTAT CONSOLIDE
1,NaN,Au 30/06/2014
2,NaN,(Exprimé en TND)
3,PRODUITS D'EXPLOITATION,Notes 30/06/2014 30/06/2013 31/12/2013
4,Revenus,16 784 859 683 747 710 395 1 495 494 818
5,Autres produits d'exploitation,17 2 757 279 2 562 155 6 399 375
6,Production Immobilisée,86 899 15 795 132 802
7,Total des produits d'exploitation,787 703 860 750 288 345 1 502 026 996
8,CHARGES D'EXPLOITATION,NaN
9,Achats de marchandises et d'approvisionnements,-543 364 637 -524 323 853 -1 035 159 628
10,Charges de personnel,-47 152 967 -47 422 185 -93 488 611
11,Dotation aux amortissements et aux provisions,-39 882 578 -35 493 267 -77 521 401
12,Autres charges d'exploitation,18 -80 146 243 -77 324 830 -167 941 968
13,Total des charges d'exploitation,-710 546 424 -684 564 135 -1 374 111 608
14,Résultat d'exploitation,77 157 435 65 724 210 127 915 388
15,Charges financières nettes,19 -29 796 851 -22 164 502 -56 042 122
16,Produits des placements,26 136 17 058 1 719 998
17,Autres gains ordinaires,140 714 1 358 457 1 981 629
18,Autres pertes ordinaires,-515 441 -388 783 -2 093 567
19,Dotation aux Amortissements écart d'acquisitio...,-224 069 -224 069 -448 138
20,Quote-part des titres mis en équivalence,1 161 963 -199 938 -184 027
21,Résultat des activités ordinaires avant impôt,47 949 887 44 122 433 72 849 160
22,Impôts sur les bénéfices,-4 236 970 -4 449 969 -6 881 442
23,Résultat des activités ordinaires après impôt,43 712 918 39 672 464 65 967 718
24,Part des minoritaires dans le résultat,-673 642 -644 029 -1 276 272
25,RESULTAT NET CONSOLIDE DE L'EXERCICE,44 386 560 40 316 492 67 243 989

------------------------------
Tableau 4

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,NaN,NaN,NaN,POULINA GROUP HOLDING S.A. ( P G H )\rETAT DES...,NaN
1,NaN,30/06/201330/06/201331/12/2013,NaN,NaN,NaN
2,NaN,LUX DE TRESORERIE LIES À L'EXPLOITATION,NaN,NaN,NaN
3,NaN,ésultat Net consolidé de l'exercice44 386 5604...,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN
5,NaN,Variation de trésorerie suite aux acquisitions...,NaN,NaN,NaN
6,NaN,Encaissement suite à la libération du capital1...,NaN,NaN,NaN
7,NaN,ARIATION DE TRESORERIE19 502 048-14 374 95012 ...,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN
9,NaN,- Trésorerie au début de l'exercice-43 806 274...,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN
11,NaN,- Trésorerie à la clôture de l'exercice-24 304...,NaN,NaN,NaN
12,NaN,Les Notes de 1 à 19 font partie intégrante des...,NaN,NaN,NaN

------------------------------
Tableau 5

                                          Unnamed: 0 Taux d'Amort.
0                                                NaN        (en %)
1                                      Constructions             5
2  Installations Techniques, Matériel et outillag...            10
3                              Matériel de transport            20
4  Installations générales, Agencements et Aménag...            10
5                              Matériel informatique            15
6                    Mobilier et matériel de bureaux            10
7                               Matériel d’emballage            10
8                      Petit matériel d’exploitation         33,33

------------------------------
Tableau 6

,Unnamed: 0,% d'intérêt,% Contrôle,Unnamed: 1,Unnamed: 2
0,NaN,NaN,NaN,Qualification,NaN
1,NaN,NaN,NaN,NaN,Méthode
2,NaN,30/06/2014 31/12/2013,30/06/2014 31/12/2013,de la,NaN
3,NaN,NaN,NaN,NaN,de consolidation
4,NaN,NaN,NaN,participation,NaN
...,...,...,...,...,...
84,Sté Tunisienne Alimentaire du Sahel,"79,98% 79,98%","80,00% 80,00%",NaN,NaN
85,NaN,NaN,NaN,exclusif,Globale
86,NaN,NaN,NaN,Contrôle,Intégration
87,LES GRANDS ATELIERS DU NORD,"100,00% 100,00%","100,00% 100,00%",NaN,NaN
88,NaN,NaN,NaN,exclusif,Globale

------------------------------
Tableau 7

,"% d'intérêt% Contrôle\rQualification\rMéthode\r30/06/201431/12/201330/06/201431/12/2013de la\rde consolidation\rparticipation\rContrôleIntégration\rP.A.F.100,00%100,00%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rPROINJECT99,90%99,90%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rTECHNOFLEX99,95%99,95%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rESSANAOUBAR98,91%98,91%99,99%99,99%\rexclusifGlobale\rContrôleIntégration\rM.B.G100,00%100,00%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rCARTHAGO100,00%100,00%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rUNIPACK99,96%99,96%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rTRANSPOOL99,99%99,99%99,99%99,99%\rexclusifGlobale\rContrôleIntégration\rT'PAP99,95%99,95%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rSABA99,64%99,64%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rALMES SA99,99%99,99%99,99%99,99%\rexclusifGlobale\rContrôleIntégration\rSIDI OTHMAN99,93%99,93%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rPoulina Bâtiments et Travaux Publics60,24%60,24%60,25%60,25%\rexclusifGlobale\rContrôleIntégration\rSTE AGRICOLE SAOUEF100,00%100,00%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rMED INDUSTRIE100,00%100,00%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rAVIPACK99,89%99,89%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rLa Générale des Produits Laitiers99,97%99,97%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rMECAWAYS97,42%97,42%97,43%97,43%\rexclusifGlobale\rContrôleIntégration\rAgro-Industrielle ESMIRALDA99,89%99,89%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rSELMA100,00%100,00%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rPROMETAL PLUS60,00%60,00%60,00%60,00%\rexclusifGlobale\rContrôleIntégration\rINDUSTRIE ET TECHNIQUE100,00%100,00%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rINTERNATIONAL TRADING COMPANY91,48%91,48%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rSTE SUD PACK84,93%84,93%85,00%85,00%\rexclusifGlobale\rContrôleIntégration\rCONCORDE TRADE COMPANY99,70%99,70%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rMAGHREB INDUSTRIE99,89%99,89%99,89%99,89%\rexclusifGlobale\rContrôleIntégration\rBRIQUETERIE BIR M'CHERGA99,73%99,73%99,74%99,74%\rexclusifGlobale\rContrôleIntégration\rSTE F.M.A99,92%99,92%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rELIOS LOCALISATION40,00%40,00%40,00%40,00%\rexclusifGlobale\rContrôleIntégration\rPARTNER INVESTMENT99,96%99,96%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rMEDFACTOR99,98%99,98%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rSTEO99,89%99,89%100,00%100,00%\rexclusifGlobale\r% d'intérêt% Contrôle\rQualificationMéthode\r30/06/201431/12/201330/06/201431/12/2013\rde lade consolidation",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,% d'intérêt,% Contrôle,NaN,NaN,NaN,NaN
1,NaN,30/06/2014,31/12/2013,30/06/2014,31/12/2013,Qualification\rde la\rparticipation,Méthode\rde consolidation
2,P.A.F.,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
3,PROINJECT,"99,90%","99,90%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
4,TECHNOFLEX,"99,95%","99,95%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
5,ESSANAOUBAR,"98,91%","98,91%","99,99%","99,99%",Contrôle\rexclusif,Intégration\rGlobale
6,M.B.G,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
7,CARTHAGO,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
8,UNIPACK,"99,96%","99,96%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
9,TRANSPOOL,"99,99%","99,99%","99,99%","99,99%",Contrôle\rexclusif,Intégration\rGlobale
10,T'PAP,"99,95%","99,95%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
11,SABA,"99,64%","99,64%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
12,ALMES SA,"99,99%","99,99%","99,99%","99,99%",Contrôle\rexclusif,Intégration\rGlobale
13,SIDI OTHMAN,"99,93%","99,93%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
14,Poulina Bâtiments et Travaux Publics,"60,24%","60,24%","60,25%","60,25%",Contrôle\rexclusif,Intégration\rGlobale
15,STE AGRICOLE SAOUEF,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
16,MED INDUSTRIE,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
17,AVIPACK,"99,89%","99,89%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
18,La Générale des Produits Laitiers,"99,97%","99,97%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
19,MECAWAYS,"97,42%","97,42%","97,43%","97,43%",Contrôle\rexclusif,Intégration\rGlobale
20,Agro-Industrielle ESMIRALDA,"99,89%","99,89%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
21,SELMA,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
22,PROMETAL PLUS,"60,00%","60,00%","60,00%","60,00%",Contrôle\rexclusif,Intégration\rGlobale
23,INDUSTRIE ET TECHNIQUE,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
24,INTERNATIONAL TRADING COMPANY,"91,48%","91,48%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
25,STE SUD PACK,"84,93%","84,93%","85,00%","85,00%",Contrôle\rexclusif,Intégration\rGlobale
26,CONCORDE TRADE COMPANY,"99,70%","99,70%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
27,MAGHREB INDUSTRIE,"99,89%","99,89%","99,89%","99,89%",Contrôle\rexclusif,Intégration\rGlobale
28,BRIQUETERIE BIR M'CHERGA,"99,73%","99,73%","99,74%","99,74%",Contrôle\rexclusif,Intégration\rGlobale
29,STE F.M.A,"99,92%","99,92%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
30,ELIOS LOCALISATION,"40,00%","40,00%","40,00%","40,00%",Contrôle\rexclusif,Intégration\rGlobale
31,PARTNER INVESTMENT,"99,96%","99,96%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
32,MEDFACTOR,"99,98%","99,98%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
33,STEO,"99,89%","99,89%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
34,NaN,% d'intérêt,% Contrôle,NaN,NaN,NaN,NaN
35,NaN,30/06/2014,31/12/2013,30/06/2014,31/12/2013,Qualification\rde la,Méthode\rde consolidation

------------------------------
Tableau 8

,"% d'intérêt% Contrôle\rQualification\rMéthode\r30/06/201431/12/201330/06/201431/12/2013de la\rde consolidation\rparticipation\rContrôleIntégration\rP.A.F.100,00%100,00%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rPROINJECT99,90%99,90%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rTECHNOFLEX99,95%99,95%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rESSANAOUBAR98,91%98,91%99,99%99,99%\rexclusifGlobale\rContrôleIntégration\rM.B.G100,00%100,00%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rCARTHAGO100,00%100,00%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rUNIPACK99,96%99,96%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rTRANSPOOL99,99%99,99%99,99%99,99%\rexclusifGlobale\rContrôleIntégration\rT'PAP99,95%99,95%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rSABA99,64%99,64%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rALMES SA99,99%99,99%99,99%99,99%\rexclusifGlobale\rContrôleIntégration\rSIDI OTHMAN99,93%99,93%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rPoulina Bâtiments et Travaux Publics60,24%60,24%60,25%60,25%\rexclusifGlobale\rContrôleIntégration\rSTE AGRICOLE SAOUEF100,00%100,00%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rMED INDUSTRIE100,00%100,00%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rAVIPACK99,89%99,89%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rLa Générale des Produits Laitiers99,97%99,97%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rMECAWAYS97,42%97,42%97,43%97,43%\rexclusifGlobale\rContrôleIntégration\rAgro-Industrielle ESMIRALDA99,89%99,89%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rSELMA100,00%100,00%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rPROMETAL PLUS60,00%60,00%60,00%60,00%\rexclusifGlobale\rContrôleIntégration\rINDUSTRIE ET TECHNIQUE100,00%100,00%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rINTERNATIONAL TRADING COMPANY91,48%91,48%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rSTE SUD PACK84,93%84,93%85,00%85,00%\rexclusifGlobale\rContrôleIntégration\rCONCORDE TRADE COMPANY99,70%99,70%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rMAGHREB INDUSTRIE99,89%99,89%99,89%99,89%\rexclusifGlobale\rContrôleIntégration\rBRIQUETERIE BIR M'CHERGA99,73%99,73%99,74%99,74%\rexclusifGlobale\rContrôleIntégration\rSTE F.M.A99,92%99,92%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rELIOS LOCALISATION40,00%40,00%40,00%40,00%\rexclusifGlobale\rContrôleIntégration\rPARTNER INVESTMENT99,96%99,96%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rMEDFACTOR99,98%99,98%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rSTEO99,89%99,89%100,00%100,00%\rexclusifGlobale\r% d'intérêt% Contrôle\rQualificationMéthode\r30/06/201431/12/201330/06/201431/12/2013\rde lade consolidation",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,% d'intérêt,% Contrôle,NaN,NaN,NaN,NaN
1,NaN,30/06/2014,31/12/2013,30/06/2014,31/12/2013,Qualification\rde la\rparticipation,Méthode\rde consolidation
2,P.A.F.,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
3,PROINJECT,"99,90%","99,90%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
4,TECHNOFLEX,"99,95%","99,95%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
5,ESSANAOUBAR,"98,91%","98,91%","99,99%","99,99%",Contrôle\rexclusif,Intégration\rGlobale
6,M.B.G,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
7,CARTHAGO,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
8,UNIPACK,"99,96%","99,96%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
9,TRANSPOOL,"99,99%","99,99%","99,99%","99,99%",Contrôle\rexclusif,Intégration\rGlobale
10,T'PAP,"99,95%","99,95%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
11,SABA,"99,64%","99,64%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
12,ALMES SA,"99,99%","99,99%","99,99%","99,99%",Contrôle\rexclusif,Intégration\rGlobale
13,SIDI OTHMAN,"99,93%","99,93%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
14,Poulina Bâtiments et Travaux Publics,"60,24%","60,24%","60,25%","60,25%",Contrôle\rexclusif,Intégration\rGlobale
15,STE AGRICOLE SAOUEF,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
16,MED INDUSTRIE,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
17,AVIPACK,"99,89%","99,89%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
18,La Générale des Produits Laitiers,"99,97%","99,97%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
19,MECAWAYS,"97,42%","97,42%","97,43%","97,43%",Contrôle\rexclusif,Intégration\rGlobale
20,Agro-Industrielle ESMIRALDA,"99,89%","99,89%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
21,SELMA,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
22,PROMETAL PLUS,"60,00%","60,00%","60,00%","60,00%",Contrôle\rexclusif,Intégration\rGlobale
23,INDUSTRIE ET TECHNIQUE,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
24,INTERNATIONAL TRADING COMPANY,"91,48%","91,48%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
25,STE SUD PACK,"84,93%","84,93%","85,00%","85,00%",Contrôle\rexclusif,Intégration\rGlobale
26,CONCORDE TRADE COMPANY,"99,70%","99,70%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
27,MAGHREB INDUSTRIE,"99,89%","99,89%","99,89%","99,89%",Contrôle\rexclusif,Intégration\rGlobale
28,BRIQUETERIE BIR M'CHERGA,"99,73%","99,73%","99,74%","99,74%",Contrôle\rexclusif,Intégration\rGlobale
29,STE F.M.A,"99,92%","99,92%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
30,ELIOS LOCALISATION,"40,00%","40,00%","40,00%","40,00%",Contrôle\rexclusif,Intégration\rGlobale
31,PARTNER INVESTMENT,"99,96%","99,96%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
32,MEDFACTOR,"99,98%","99,98%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
33,STEO,"99,89%","99,89%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
34,NaN,% d'intérêt,% Contrôle,NaN,NaN,NaN,NaN
35,NaN,30/06/2014,31/12/2013,30/06/2014,31/12/2013,Qualification\rde la,Méthode\rde consolidation

------------------------------
Tableau 9

,"participation\rContrôleIntégration\rSociété de Construction Industrialisée100,00%100,00%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rIdéal Industrie de l'Est Algérie99,92%99,92%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rSTE GENERALE NOUHOUD99,95%99,95%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rGIPAM97,28%94,44%98,23%98,23%\rexclusifGlobale\rContrôleIntégration\rSICMA97,99%97,99%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rORCADE NEGOCE99,95%99,95%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rSOKAPO93,32%93,32%93,36%93,36%\rexclusifGlobale\rContrôleIntégration\rCARVEN68,02%73,62%68,13%73,93%\rexclusifGlobale\rContrôleIntégration\rSTE ETTAAMIR95,09%95,09%95,09%95,09%\rexclusifGlobale\rContrôleIntégration\rKELY DISTRIBUTION99,75%99,75%99,75%99,75%\rexclusifGlobale\rContrôleIntégration\rTransport Maritime et Terrestre ""TMT""99,96%99,96%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rHERMES INT BUSINESS LTD100,00%100,00%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rTUNISIE DEVELOPPEMENT SICAR79,98%79,98%79,98%79,98%\rexclusifGlobale\rContrôleIntégration\rGLOBAL TRADING99,96%99,96%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rETTAAMIR NEGOCE99,17%99,17%99,55%99,55%\rexclusifGlobale\rContrôleIntégration\rCompagnie Générale de Bâtiment ""CGB""97,44%97,44%100,00%97,45%\rexclusifGlobale\rContrôleIntégration\rLARIA international50,00%50,00%50,00%50,00%\rexclusifGlobale\rContrôleIntégration\rCARTHAGO BETON CELLULAIRE99,72%99,72%99,74%99,74%\rexclusifGlobale\rContrôleIntégration\rCARTHAGO BRIQUES99,94%99,94%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rSOVIT100,00%100,00%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rBITUMEX69,98%69,98%69,98%69,98%\rexclusifGlobale\rContrôleIntégration\rIDEAL CERAMIQUE80,79%80,79%80,91%80,91%\rexclusifGlobale\rContrôleIntégration\rATHENA FINANCES HOLDING OFFSHORE99,80%99,80%99,91%99,91%\rexclusifGlobale\rContrôleIntégration\rBORAQ100,00%100,00%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rCHAHRAZED99,97%99,97%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rKISSES70,00%77,33%70,00%77,33%\rexclusifGlobale\rContrôleIntégration\rLINPACK99,92%99,92%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rMED FOOD100,00%100,00%100,00%100,00%\rexclusifGlobale\rSTE D'INVESTISSEMENT ET DEContrôleIntégration\r100,00%100,00%100,00%100,00%\rDEVELOPPEMENTexclusifGlobale\rContrôleIntégration\rFRUITS DE CARTHAGE100,00%100,00%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rMED OIL SENEGAL69,90%69,90%70,00%70,00%\rexclusifGlobale\rContrôleIntégration\rNUTRIMIX100,00%100,00%100,00%10,00%\rexclusifGlobale\r% d'intérêt% Contrôle\rQualification\rMéthode\r30/06/201431/12/201330/06/201431/12/2013de la\rde consolidation\rparticipation\rContrôleIntégration\rPremix Sebri100,00%100,00%100,00%10,00%\rexclusifGlobale",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,Société de Construction Industrialisée,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
1,Idéal Industrie de l'Est Algérie,"99,92%","99,92%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
2,STE GENERALE NOUHOUD,"99,95%","99,95%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
3,GIPAM,"97,28%","94,44%","98,23%","98,23%",Contrôle\rexclusif,Intégration\rGlobale
4,SICMA,"97,99%","97,99%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
5,ORCADE NEGOCE,"99,95%","99,95%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
6,SOKAPO,"93,32%","93,32%","93,36%","93,36%",Contrôle\rexclusif,Intégration\rGlobale
7,CARVEN,"68,02%","73,62%","68,13%","73,93%",Contrôle\rexclusif,Intégration\rGlobale
8,STE ETTAAMIR,"95,09%","95,09%","95,09%","95,09%",Contrôle\rexclusif,Intégration\rGlobale
9,KELY DISTRIBUTION,"99,75%","99,75%","99,75%","99,75%",Contrôle\rexclusif,Intégration\rGlobale
10,"Transport Maritime et Terrestre ""TMT""","99,96%","99,96%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
11,HERMES INT BUSINESS LTD,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
12,TUNISIE DEVELOPPEMENT SICAR,"79,98%","79,98%","79,98%","79,98%",Contrôle\rexclusif,Intégration\rGlobale
13,GLOBAL TRADING,"99,96%","99,96%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
14,ETTAAMIR NEGOCE,"99,17%","99,17%","99,55%","99,55%",Contrôle\rexclusif,Intégration\rGlobale
15,"Compagnie Générale de Bâtiment ""CGB""","97,44%","97,44%","100,00%","97,45%",Contrôle\rexclusif,Intégration\rGlobale
16,LARIA international,"50,00%","50,00%","50,00%","50,00%",Contrôle\rexclusif,Intégration\rGlobale
17,CARTHAGO BETON CELLULAIRE,"99,72%","99,72%","99,74%","99,74%",Contrôle\rexclusif,Intégration\rGlobale
18,CARTHAGO BRIQUES,"99,94%","99,94%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
19,SOVIT,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
20,BITUMEX,"69,98%","69,98%","69,98%","69,98%",Contrôle\rexclusif,Intégration\rGlobale
21,IDEAL CERAMIQUE,"80,79%","80,79%","80,91%","80,91%",Contrôle\rexclusif,Intégration\rGlobale
22,ATHENA FINANCES HOLDING OFFSHORE,"99,80%","99,80%","99,91%","99,91%",Contrôle\rexclusif,Intégration\rGlobale
23,BORAQ,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
24,CHAHRAZED,"99,97%","99,97%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
25,KISSES,"70,00%","77,33%","70,00%","77,33%",Contrôle\rexclusif,Intégration\rGlobale
26,LINPACK,"99,92%","99,92%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
27,MED FOOD,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
28,STE D'INVESTISSEMENT ET DE\rDEVELOPPEMENT,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
29,FRUITS DE CARTHAGE,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
30,MED OIL SENEGAL,"69,90%","69,90%","70,00%","70,00%",Contrôle\rexclusif,Intégration\rGlobale
31,NUTRIMIX,"100,00%","100,00%","100,00%","10,00%",Contrôle\rexclusif,Intégration\rGlobale
32,NaN,% d'intérêt,% Contrôle,NaN,NaN,NaN,NaN
33,NaN,30/06/2014,31/12/2013,30/06/2014,31/12/2013,Qualification\rde la\rparticipation,Méthode\rde consolidation
34,Premix Sebri,"100,00%","100,00%","100,00%","10,00%",Contrôle\rexclusif,Intégration\rGlobale

------------------------------
Tableau 10

,"participation\rContrôleIntégration\rSociété de Construction Industrialisée100,00%100,00%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rIdéal Industrie de l'Est Algérie99,92%99,92%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rSTE GENERALE NOUHOUD99,95%99,95%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rGIPAM97,28%94,44%98,23%98,23%\rexclusifGlobale\rContrôleIntégration\rSICMA97,99%97,99%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rORCADE NEGOCE99,95%99,95%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rSOKAPO93,32%93,32%93,36%93,36%\rexclusifGlobale\rContrôleIntégration\rCARVEN68,02%73,62%68,13%73,93%\rexclusifGlobale\rContrôleIntégration\rSTE ETTAAMIR95,09%95,09%95,09%95,09%\rexclusifGlobale\rContrôleIntégration\rKELY DISTRIBUTION99,75%99,75%99,75%99,75%\rexclusifGlobale\rContrôleIntégration\rTransport Maritime et Terrestre ""TMT""99,96%99,96%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rHERMES INT BUSINESS LTD100,00%100,00%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rTUNISIE DEVELOPPEMENT SICAR79,98%79,98%79,98%79,98%\rexclusifGlobale\rContrôleIntégration\rGLOBAL TRADING99,96%99,96%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rETTAAMIR NEGOCE99,17%99,17%99,55%99,55%\rexclusifGlobale\rContrôleIntégration\rCompagnie Générale de Bâtiment ""CGB""97,44%97,44%100,00%97,45%\rexclusifGlobale\rContrôleIntégration\rLARIA international50,00%50,00%50,00%50,00%\rexclusifGlobale\rContrôleIntégration\rCARTHAGO BETON CELLULAIRE99,72%99,72%99,74%99,74%\rexclusifGlobale\rContrôleIntégration\rCARTHAGO BRIQUES99,94%99,94%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rSOVIT100,00%100,00%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rBITUMEX69,98%69,98%69,98%69,98%\rexclusifGlobale\rContrôleIntégration\rIDEAL CERAMIQUE80,79%80,79%80,91%80,91%\rexclusifGlobale\rContrôleIntégration\rATHENA FINANCES HOLDING OFFSHORE99,80%99,80%99,91%99,91%\rexclusifGlobale\rContrôleIntégration\rBORAQ100,00%100,00%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rCHAHRAZED99,97%99,97%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rKISSES70,00%77,33%70,00%77,33%\rexclusifGlobale\rContrôleIntégration\rLINPACK99,92%99,92%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rMED FOOD100,00%100,00%100,00%100,00%\rexclusifGlobale\rSTE D'INVESTISSEMENT ET DEContrôleIntégration\r100,00%100,00%100,00%100,00%\rDEVELOPPEMENTexclusifGlobale\rContrôleIntégration\rFRUITS DE CARTHAGE100,00%100,00%100,00%100,00%\rexclusifGlobale\rContrôleIntégration\rMED OIL SENEGAL69,90%69,90%70,00%70,00%\rexclusifGlobale\rContrôleIntégration\rNUTRIMIX100,00%100,00%100,00%10,00%\rexclusifGlobale\r% d'intérêt% Contrôle\rQualification\rMéthode\r30/06/201431/12/201330/06/201431/12/2013de la\rde consolidation\rparticipation\rContrôleIntégration\rPremix Sebri100,00%100,00%100,00%10,00%\rexclusifGlobale",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,Société de Construction Industrialisée,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
1,Idéal Industrie de l'Est Algérie,"99,92%","99,92%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
2,STE GENERALE NOUHOUD,"99,95%","99,95%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
3,GIPAM,"97,28%","94,44%","98,23%","98,23%",Contrôle\rexclusif,Intégration\rGlobale
4,SICMA,"97,99%","97,99%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
5,ORCADE NEGOCE,"99,95%","99,95%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
6,SOKAPO,"93,32%","93,32%","93,36%","93,36%",Contrôle\rexclusif,Intégration\rGlobale
7,CARVEN,"68,02%","73,62%","68,13%","73,93%",Contrôle\rexclusif,Intégration\rGlobale
8,STE ETTAAMIR,"95,09%","95,09%","95,09%","95,09%",Contrôle\rexclusif,Intégration\rGlobale
9,KELY DISTRIBUTION,"99,75%","99,75%","99,75%","99,75%",Contrôle\rexclusif,Intégration\rGlobale
10,"Transport Maritime et Terrestre ""TMT""","99,96%","99,96%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
11,HERMES INT BUSINESS LTD,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
12,TUNISIE DEVELOPPEMENT SICAR,"79,98%","79,98%","79,98%","79,98%",Contrôle\rexclusif,Intégration\rGlobale
13,GLOBAL TRADING,"99,96%","99,96%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
14,ETTAAMIR NEGOCE,"99,17%","99,17%","99,55%","99,55%",Contrôle\rexclusif,Intégration\rGlobale
15,"Compagnie Générale de Bâtiment ""CGB""","97,44%","97,44%","100,00%","97,45%",Contrôle\rexclusif,Intégration\rGlobale
16,LARIA international,"50,00%","50,00%","50,00%","50,00%",Contrôle\rexclusif,Intégration\rGlobale
17,CARTHAGO BETON CELLULAIRE,"99,72%","99,72%","99,74%","99,74%",Contrôle\rexclusif,Intégration\rGlobale
18,CARTHAGO BRIQUES,"99,94%","99,94%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
19,SOVIT,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
20,BITUMEX,"69,98%","69,98%","69,98%","69,98%",Contrôle\rexclusif,Intégration\rGlobale
21,IDEAL CERAMIQUE,"80,79%","80,79%","80,91%","80,91%",Contrôle\rexclusif,Intégration\rGlobale
22,ATHENA FINANCES HOLDING OFFSHORE,"99,80%","99,80%","99,91%","99,91%",Contrôle\rexclusif,Intégration\rGlobale
23,BORAQ,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
24,CHAHRAZED,"99,97%","99,97%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
25,KISSES,"70,00%","77,33%","70,00%","77,33%",Contrôle\rexclusif,Intégration\rGlobale
26,LINPACK,"99,92%","99,92%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
27,MED FOOD,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
28,STE D'INVESTISSEMENT ET DE\rDEVELOPPEMENT,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
29,FRUITS DE CARTHAGE,"100,00%","100,00%","100,00%","100,00%",Contrôle\rexclusif,Intégration\rGlobale
30,MED OIL SENEGAL,"69,90%","69,90%","70,00%","70,00%",Contrôle\rexclusif,Intégration\rGlobale
31,NUTRIMIX,"100,00%","100,00%","100,00%","10,00%",Contrôle\rexclusif,Intégration\rGlobale
32,NaN,% d'intérêt,% Contrôle,NaN,NaN,NaN,NaN
33,NaN,30/06/2014,31/12/2013,30/06/2014,31/12/2013,Qualification\rde la\rparticipation,Méthode\rde consolidation
34,Premix Sebri,"100,00%","100,00%","100,00%","10,00%",Contrôle\rexclusif,Intégration\rGlobale

------------------------------
Tableau 11

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Influence,Mise en
0,MED INVEST COMPANY,"48,85%","48,85%","48,99%","48,99%",NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,notable,équivalence
2,NaN,NaN,NaN,NaN,NaN,Influence,Mise en
3,ENNAKL AUTOMOBILES,"27,19%","27,19%","27,92%","27,92%",NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,notable,équivalence
5,NaN,NaN,NaN,NaN,NaN,Influence,Mise en
6,Sté International Dealer,"35,33%","35,34%","48,00%","48,00%",NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,notable,équivalence

------------------------------
Tableau 12

,Unnamed: 0,% d'intérêt,% Contrôle,Unnamed: 1,Unnamed: 2
0,NaN,NaN,NaN,Qualification de la,Méthode de
1,NaN,30/06/2014 31/12/2013,30/06/2014 31/12/2013,NaN,NaN
2,NaN,NaN,NaN,participation,consolidation
3,Africaine de Transformation de Métaux,"100,00% 100,00%","100,00% 100,00%",Exclue du périmètre,Non consolidée
4,Tarapols Li Intaj Alaf Hayawania,"40,98% 40,98%","41,00% 41,00%",Exclue du périmètre,Non consolidée
5,Sahel Lebda Lissinaat Mawed El Binaa,"72,00% 72,00%","72,00% 72,00%",Exclue du périmètre,Non consolidée
6,Technique d'Emballage en Carton Lybie,"92,31% 92,31%","92,36% 92,36%",Exclue du périmètre,Non consolidée
7,Selja Lisinaat Elmothalajat,"68,91% 68,91%","70,00% 70,00%",Exclue du périmètre,Non consolidée
8,Poulina Libye de Constructions et Travaux Publics,"59,02% 59,02%","59,75% 59,75%",Exclue du périmètre,Non consolidée
9,Achghal Ezzaouia Poulina Bouzguenda lilinchaet,"33,13% 33,13%","55,00% 55,00%",Exclue du périmètre,Non consolidée
10,LebdaLissinaat El Plastiquia El Moussahama,"51,98% 51,98%","52,00% 52,00%",Exclue du périmètre,Non consolidée
11,Ettatouir Ettanmiaa El Omrania El Mochtaraka,"36,15% 36,15%","60,00% 60,00%",Exclue du périmètre,Non consolidée
12,Charika Afriquia Lissinaat Elajor,"69,81% 69,81%","70,34% 70,34%",Exclue du périmètre,Non consolidée

------------------------------
Tableau 13

,Unnamed: 0,% d'intérêt,% Contrôle,Unnamed: 1,Unnamed: 2
0,NaN,NaN,NaN,Qualification de la,Méthode de
1,NaN,30/06/2014 31/12/2013,30/06/2014 31/12/2013,NaN,NaN
2,NaN,NaN,NaN,participation,consolidation
3,AGROMED,"87,98% 87,98%","87,98% 87,98%",Exclue du périmètre,Non consolidée

------------------------------
Tableau 14

,"II. 3.ACTIFS:\rNote 1 : Immobilisations incorporelles :\rLavaleurnettedesimmobilisationsincorporelless'élèveau30Juin2014à3 898477DT\rcontre 4 561 324 DT au 31 Décembre 2013. Cette rubrique se détaille comme suit:\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 31/12/2013\rInvestissement en recherche et développement\r72 40367 063\rConcessions de marques, brevets, licences\r654 275612 338\rLogiciels\r6 758 1506 647 367\rFonds commercial\r2 169 2962 197 749\rDroit au bail\r81 00081 000\rAutres immobilisations incorporelles\r157 036149 140\rGoodwill net d’amortissements\r(i)\r1 685 8321 909 901\rTotal11 577 99211 664 558\rMoins Amortissements (Hors Amortissements du Goodwill)\r-7 679 515-7 103 235\rTotal net3 898 4774 561 324\r(i) Goodwill :\rCe poste correspond à la différence entre le coût d’acquisition des titres de participation et\rla quote-part du groupe dans l’actif net des sociétés acquises. Il présente au 30 Juin2014\run solde net d’amortissements de 1 685 832 DT.",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,Solde au 30/06/2014,Solde au 31/12/2013,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Investissement en recherche et développement,72 403,67 063,NaN,NaN,NaN,NaN,NaN,NaN
3,"Concessions de marques, brevets, licences",654 275,612 338,NaN,NaN,NaN,NaN,NaN,NaN
4,Logiciels,6 758 150,6 647 367,NaN,NaN,NaN,NaN,NaN,NaN
5,Fonds commercial,2 169 296,2 197 749,NaN,NaN,NaN,NaN,NaN,NaN
6,Droit au bail,81 000,81 000,NaN,NaN,NaN,NaN,NaN,NaN
7,Autres immobilisations incorporelles,157 036,149 140,NaN,NaN,NaN,NaN,NaN,NaN
8,Goodwill net d’amortissements\r(i),1 685 832,1 909 901,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Total,11 577 992,11 664 558,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Moins Amortissements (Hors Amortissements du G...,-7 679 515,-7 103 235,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,Total net,NaN,NaN,3 898 477,NaN,NaN,4 561 32,NaN

------------------------------
Tableau 15

,"II. 3.ACTIFS:\rNote 1 : Immobilisations incorporelles :\rLavaleurnettedesimmobilisationsincorporelless'élèveau30Juin2014à3 898477DT\rcontre 4 561 324 DT au 31 Décembre 2013. Cette rubrique se détaille comme suit:\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 31/12/2013\rInvestissement en recherche et développement\r72 40367 063\rConcessions de marques, brevets, licences\r654 275612 338\rLogiciels\r6 758 1506 647 367\rFonds commercial\r2 169 2962 197 749\rDroit au bail\r81 00081 000\rAutres immobilisations incorporelles\r157 036149 140\rGoodwill net d’amortissements\r(i)\r1 685 8321 909 901\rTotal11 577 99211 664 558\rMoins Amortissements (Hors Amortissements du Goodwill)\r-7 679 515-7 103 235\rTotal net3 898 4774 561 324\r(i) Goodwill :\rCe poste correspond à la différence entre le coût d’acquisition des titres de participation et\rla quote-part du groupe dans l’actif net des sociétés acquises. Il présente au 30 Juin2014\run solde net d’amortissements de 1 685 832 DT.",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,Solde au 30/06/2014,Solde au 31/12/2013,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Investissement en recherche et développement,72 403,67 063,NaN,NaN,NaN,NaN,NaN,NaN
3,"Concessions de marques, brevets, licences",654 275,612 338,NaN,NaN,NaN,NaN,NaN,NaN
4,Logiciels,6 758 150,6 647 367,NaN,NaN,NaN,NaN,NaN,NaN
5,Fonds commercial,2 169 296,2 197 749,NaN,NaN,NaN,NaN,NaN,NaN
6,Droit au bail,81 000,81 000,NaN,NaN,NaN,NaN,NaN,NaN
7,Autres immobilisations incorporelles,157 036,149 140,NaN,NaN,NaN,NaN,NaN,NaN
8,Goodwill net d’amortissements\r(i),1 685 832,1 909 901,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Total,11 577 992,11 664 558,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Moins Amortissements (Hors Amortissements du G...,-7 679 515,-7 103 235,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,Total net,NaN,NaN,3 898 477,NaN,NaN,4 561 32,NaN

------------------------------
Tableau 16

,"Note 2 : Immobilisations corporelles :\rLavaleurnettedesimmobilisationscorporelless'élèveau3 0Juin2014à654 945 865DT\rcontre 647 233 208 DT au 31 Décembre 2013. Cette rubrique se détaille comme suit :\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 31/12/2013\rTerrains\r61 795 82161 768 643\rConstructions\r278 350 138284 702 614\rPlantations et cheptels\r7 393 5499 395 727\rInstallations Techniques Matériel et outillage industriel\r579 589 576572 577 522\rMatériel de Transport\r60 610 60558 006 671\rInstallations générales, agencements et aménagements divers\r127 957 901125 829 619\rEquipements de bureaux\r21 186 48120 427 622\rMatériel d'emballage\r18 865 65120 678 281\rPetit matériel d'exploitation\r17 475 57817 476 749\rImmobilisations à statut juridique particulier\r12 520 02211 725 493\rImmobilisations en cours\r88 513 35754 470 162\rTotal1 274 258 6791 237 059 102\rMoins Amortissements\r-619 312 814-589 825 894\rTotal net654 945 865647 233 208\rNote 3 : Immobilisations financières :\rLavaleurnettedesimmobilisationsfinancièress'élèveau30Juin2014à229 802 501DT\rcontre 227 481 628 DT au 31 Décembre 2013 et se détaille comme suit:\r(Exprimés en TND)\rSolde au 30/06/2014\rSolde au 31/12/2013\rTitres de participation\r83 325 46081 350 331\rTitres mis en équivalence\r140 875 551142 710 739\rPrêts\r1 908 6282 683 223\rDépôts et cautionnements\r6 719 5404 099 940\rAutres immobilisations financières\r1 278 443900 750\rTotal brut234 107 623231 744 984\rMoins Provisions\r-4 305 122-4 263 355\rTotal net229 802 501227 481 628",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,Solde au 30/06/2014,Solde au 31/12/2013,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Terrains,61 795 821,61 768 643,NaN,NaN,NaN,NaN,NaN,NaN
3,Terrains,61 795 821,61 768 643,NaN,NaN,NaN,NaN,NaN,NaN
4,Constructions,278 350 138,284 702 614,NaN,NaN,NaN,NaN,NaN,NaN
5,Constructions,278 350 138,284 702 614,NaN,NaN,NaN,NaN,NaN,NaN
6,Plantations et cheptels,7 393 549,9 395 727,NaN,NaN,NaN,NaN,NaN,NaN
7,Plantations et cheptels,7 393 549,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Installations Techniques Matériel et outillage...,579 589 576,572 577 522,NaN,NaN,NaN,NaN,NaN,NaN
9,Installations Techniques Matériel et outillage...,579 589 576,572 577 522,NaN,NaN,NaN,NaN,NaN,NaN
10,Matériel de Transport,60 610 605,58 006 671,NaN,NaN,NaN,NaN,NaN,NaN
11,Matériel de Transport,60 610 605,58 006 671,NaN,NaN,NaN,NaN,NaN,NaN
12,"Installations générales, agencements et aménag...",127 957 901,125 829 619,NaN,NaN,NaN,NaN,NaN,NaN
13,"Installations générales, agencements et aménag...",127 957 901,125 829 619,NaN,NaN,NaN,NaN,NaN,NaN
14,Equipements de bureaux,21 186 481,20 427 622,NaN,NaN,NaN,NaN,NaN,NaN
15,Equipements de bureaux,21 186 481,20 427 622,NaN,NaN,NaN,NaN,NaN,NaN
16,Matériel d'emballage,18 865 651,20 678 281,NaN,NaN,NaN,NaN,NaN,NaN
17,Matériel d'emballage,18 865 651,20 678 281,NaN,NaN,NaN,NaN,NaN,NaN
18,Petit matériel d'exploitation,17 475 578,17 476 749,NaN,NaN,NaN,NaN,NaN,NaN
19,Petit matériel d'exploitation,17 475 578,17 476 749,NaN,NaN,NaN,NaN,NaN,NaN
20,Immobilisations à statut juridique particulier,12 520 022,11 725 493,NaN,NaN,NaN,NaN,NaN,NaN
21,Immobilisations à statut juridique particulier,12 520 022,11 725 493,NaN,NaN,NaN,NaN,NaN,NaN
22,Immobilisations en cours,88 513 357,54 470 162,NaN,NaN,NaN,NaN,NaN,NaN
23,Immobilisations en cours,88 513 357,54 470 162,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Total,1 274 258 679,1 237 059 102,NaN,NaN,NaN,NaN,NaN,NaN
27,Total,1 274 258 679,1 237 059 102,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Moins Amortissements,-619 312 814,-589 825 894,NaN,NaN,NaN,NaN,NaN,NaN
31,Moins Amortissements,-619 312 814,-589 825 894,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Total net,654 945 865,647 233 208,NaN,NaN,NaN,NaN,NaN,NaN
35,Total net,654 945 865,647 233 208,NaN,NaN,NaN,NaN,NaN,NaN

------------------------------
Tableau 17

,"Note 2 : Immobilisations corporelles :\rLavaleurnettedesimmobilisationscorporelless'élèveau3 0Juin2014à654 945 865DT\rcontre 647 233 208 DT au 31 Décembre 2013. Cette rubrique se détaille comme suit :\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 31/12/2013\rTerrains\r61 795 82161 768 643\rConstructions\r278 350 138284 702 614\rPlantations et cheptels\r7 393 5499 395 727\rInstallations Techniques Matériel et outillage industriel\r579 589 576572 577 522\rMatériel de Transport\r60 610 60558 006 671\rInstallations générales, agencements et aménagements divers\r127 957 901125 829 619\rEquipements de bureaux\r21 186 48120 427 622\rMatériel d'emballage\r18 865 65120 678 281\rPetit matériel d'exploitation\r17 475 57817 476 749\rImmobilisations à statut juridique particulier\r12 520 02211 725 493\rImmobilisations en cours\r88 513 35754 470 162\rTotal1 274 258 6791 237 059 102\rMoins Amortissements\r-619 312 814-589 825 894\rTotal net654 945 865647 233 208\rNote 3 : Immobilisations financières :\rLavaleurnettedesimmobilisationsfinancièress'élèveau30Juin2014à229 802 501DT\rcontre 227 481 628 DT au 31 Décembre 2013 et se détaille comme suit:\r(Exprimés en TND)\rSolde au 30/06/2014\rSolde au 31/12/2013\rTitres de participation\r83 325 46081 350 331\rTitres mis en équivalence\r140 875 551142 710 739\rPrêts\r1 908 6282 683 223\rDépôts et cautionnements\r6 719 5404 099 940\rAutres immobilisations financières\r1 278 443900 750\rTotal brut234 107 623231 744 984\rMoins Provisions\r-4 305 122-4 263 355\rTotal net229 802 501227 481 628",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,Solde au 30/06/2014,Solde au 31/12/2013,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Titres de participation,83 325 460,81 350 331,NaN,NaN,NaN,NaN
3,Titres mis en équivalence,140 875 551,142 710 739,NaN,NaN,NaN,NaN
4,Prêts,1 908 628,2 683 223,NaN,NaN,NaN,NaN
5,Dépôts et cautionnements,6 719 540,4 099 940,NaN,NaN,NaN,NaN
6,Autres immobilisations financières,1 278 443,900 750,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Total brut,234 107 623,231 744 984,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Moins Provisions,NaN,-4 305 122,NaN,NaN,-4 263 355,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Total net,229 802 501,227 481 628,NaN,NaN,NaN,NaN
14,Total net,229 802 501,227 481 628,NaN,NaN,NaN,NaN

------------------------------
Tableau 18

,"Note 2 : Immobilisations corporelles :\rLavaleurnettedesimmobilisationscorporelless'élèveau3 0Juin2014à654 945 865DT\rcontre 647 233 208 DT au 31 Décembre 2013. Cette rubrique se détaille comme suit :\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 31/12/2013\rTerrains\r61 795 82161 768 643\rConstructions\r278 350 138284 702 614\rPlantations et cheptels\r7 393 5499 395 727\rInstallations Techniques Matériel et outillage industriel\r579 589 576572 577 522\rMatériel de Transport\r60 610 60558 006 671\rInstallations générales, agencements et aménagements divers\r127 957 901125 829 619\rEquipements de bureaux\r21 186 48120 427 622\rMatériel d'emballage\r18 865 65120 678 281\rPetit matériel d'exploitation\r17 475 57817 476 749\rImmobilisations à statut juridique particulier\r12 520 02211 725 493\rImmobilisations en cours\r88 513 35754 470 162\rTotal1 274 258 6791 237 059 102\rMoins Amortissements\r-619 312 814-589 825 894\rTotal net654 945 865647 233 208\rNote 3 : Immobilisations financières :\rLavaleurnettedesimmobilisationsfinancièress'élèveau30Juin2014à229 802 501DT\rcontre 227 481 628 DT au 31 Décembre 2013 et se détaille comme suit:\r(Exprimés en TND)\rSolde au 30/06/2014\rSolde au 31/12/2013\rTitres de participation\r83 325 46081 350 331\rTitres mis en équivalence\r140 875 551142 710 739\rPrêts\r1 908 6282 683 223\rDépôts et cautionnements\r6 719 5404 099 940\rAutres immobilisations financières\r1 278 443900 750\rTotal brut234 107 623231 744 984\rMoins Provisions\r-4 305 122-4 263 355\rTotal net229 802 501227 481 628",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,Solde au 30/06/2014,Solde au 31/12/2013,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Terrains,61 795 821,61 768 643,NaN,NaN,NaN,NaN,NaN,NaN
3,Terrains,61 795 821,61 768 643,NaN,NaN,NaN,NaN,NaN,NaN
4,Constructions,278 350 138,284 702 614,NaN,NaN,NaN,NaN,NaN,NaN
5,Constructions,278 350 138,284 702 614,NaN,NaN,NaN,NaN,NaN,NaN
6,Plantations et cheptels,7 393 549,9 395 727,NaN,NaN,NaN,NaN,NaN,NaN
7,Plantations et cheptels,7 393 549,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Installations Techniques Matériel et outillage...,579 589 576,572 577 522,NaN,NaN,NaN,NaN,NaN,NaN
9,Installations Techniques Matériel et outillage...,579 589 576,572 577 522,NaN,NaN,NaN,NaN,NaN,NaN
10,Matériel de Transport,60 610 605,58 006 671,NaN,NaN,NaN,NaN,NaN,NaN
11,Matériel de Transport,60 610 605,58 006 671,NaN,NaN,NaN,NaN,NaN,NaN
12,"Installations générales, agencements et aménag...",127 957 901,125 829 619,NaN,NaN,NaN,NaN,NaN,NaN
13,"Installations générales, agencements et aménag...",127 957 901,125 829 619,NaN,NaN,NaN,NaN,NaN,NaN
14,Equipements de bureaux,21 186 481,20 427 622,NaN,NaN,NaN,NaN,NaN,NaN
15,Equipements de bureaux,21 186 481,20 427 622,NaN,NaN,NaN,NaN,NaN,NaN
16,Matériel d'emballage,18 865 651,20 678 281,NaN,NaN,NaN,NaN,NaN,NaN
17,Matériel d'emballage,18 865 651,20 678 281,NaN,NaN,NaN,NaN,NaN,NaN
18,Petit matériel d'exploitation,17 475 578,17 476 749,NaN,NaN,NaN,NaN,NaN,NaN
19,Petit matériel d'exploitation,17 475 578,17 476 749,NaN,NaN,NaN,NaN,NaN,NaN
20,Immobilisations à statut juridique particulier,12 520 022,11 725 493,NaN,NaN,NaN,NaN,NaN,NaN
21,Immobilisations à statut juridique particulier,12 520 022,11 725 493,NaN,NaN,NaN,NaN,NaN,NaN
22,Immobilisations en cours,88 513 357,54 470 162,NaN,NaN,NaN,NaN,NaN,NaN
23,Immobilisations en cours,88 513 357,54 470 162,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Total,1 274 258 679,1 237 059 102,NaN,NaN,NaN,NaN,NaN,NaN
27,Total,1 274 258 679,1 237 059 102,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Moins Amortissements,-619 312 814,-589 825 894,NaN,NaN,NaN,NaN,NaN,NaN
31,Moins Amortissements,-619 312 814,-589 825 894,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Total net,654 945 865,647 233 208,NaN,NaN,NaN,NaN,NaN,NaN
35,Total net,654 945 865,647 233 208,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,Solde au 30/06/2014,Solde au 31/12/2013,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Titres de participation,83 325 460,81 350 331,NaN,NaN,NaN,NaN,NaN,NaN
39,Titres mis en équivalence,140 875 551,142 710 739,NaN,NaN,NaN,NaN,NaN,NaN
40,Prêts,1 908 628,2 683 223,NaN,NaN,NaN,NaN,NaN,NaN
41,Dépôts et cautionnements,6 719 540,4 099 940,NaN,NaN,NaN,NaN,NaN,NaN
42,Autres immobilisations financières,1 278 443,900 750,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Total brut,234 107 623,231 744 984,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Moins Provisions,NaN,-4 305 122,NaN,NaN,-4 263 355,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Total net,229 802 501,227 481 628,NaN,NaN,NaN,NaN,NaN,NaN
50,Total net,229 802 501,227 481 628,NaN,NaN,NaN,NaN,NaN,NaN

------------------------------
Tableau 19

,Titres,30/06/2014,31/12/2013,Variations
0,ACM,501 000,501 000,0
1,AFFICHE TUNISIE,70 000,70 000,0
2,AGROMED,1 057 348,1 057 348,0
3,AMEN SICAR,167 882,167 882,0
4,BANQUE POPULAIRE,226,226,0
5,BANQUE ZITOUNA,4 000 000,4 000 000,0
6,BTS,47 500,47 500,0
7,CM LASER,90 000,90 000,0
8,COMPROAGRI,10 000,10 000,0
9,CONSORTIUM TUNISIEN DES COMPOSANTS AUTOMOBILE,12 500,12 500,0
10,Daouajine Bouznika,226 001,226 001,0
11,FIT,20 000,20 000,0
12,ICC,4 034 424,3 284 256,750 168
13,LA MARINA,200 000,200 000,0
14,MAILLE MODE,26 250,26 250,0
15,MONTAZAH HAMMAMET SUD,195 228,195 228,0
16,NEGOCIM,26 000,26 000,0
17,NORD PARK,10 000,10 000,0
18,NUTRISTAR INT,43 886,43 886,0
19,O'claire,7 500,7 500,0
20,OXYMETAL France,324 267,324 267,0
21,SICAB,50 000,50 000,0
22,TECHNIQUE INSPECTION ET CONTRÔLE,306 787,306 787,0
23,Technopole Technologie de Sfax,50 000,50 000,0
24,TUNICODE,39 000,39 000,0
25,TUNIFIB,2 000 000,2 000 000,0
26,UMA,55 806,55 806,0
27,UNIFACTOR,300 000,300 000,0
28,BITUMEN,99 300,99 300,0
29,BTP France,567 815,567 815,0
30,MAGASIN GENERAL,5 158 601,5 158 601,0
31,Africaine De Transformation de Métaux,16 019 914,16 019 914,0
32,ASHARIKA AL IFRIQUIA LISINAAT AL AAJOR,17 725 339,17 725 339,0
33,EZZAOUIA,2 216 061,2 216 061,0
34,GIPA LYBIE,2 958 611,2 958 611,0
35,POULINA LIBYE DE CONSTRUCTION ET TRAVAUX PUBLIC,6 665 188,6 665 188,0
36,SAHEL LEBDA LISINAAT MAWED ALBINA,7 591 441,7 591 441,0
37,SHARIKAT LIBDA LISINAAT ALPLASTIKIA ALMOUSAHIMA.,1 172 097,1 172 097,0

------------------------------
Tableau 20

                 Unnamed: 0 Unnamed: 1      (Exprimés en TND)  Unnamed: 2
0                    Titres        NaN  30/06/2014 31/12/2013  Variations
1  STE Trabols LIINTEJ ALAF        NaN        790 129 790 129           0
2                 TEC LYBIE        NaN    7 264 398 7 264 398           0
3      CLOUD TEMPLE TUNISIA        NaN            1 224 960 0   1 224 960
4                       NaN      Total  83 325 460 81 350 331   1 975 129

------------------------------
Tableau 21

,Unnamed: 0,Unnamed: 1,Quote-part dans les,Quote-part dans les.1
0,NaN,Titres mis en équivalence,NaN,NaN
1,Société,NaN,réserves,résultats
2,NaN,30/06/2014 31/12/2013,30/06/2014 31/12/2013,30/06/2014 31/12/2013
3,MED INVEST COMPANY,34 358 016 34 855 776,-904 169 -569 998,-497 761 -334 171
4,DEALER,349 091 356 057,160 792 173 227,-6 966 -12 435
5,ENNAKL,106 168 445 107 498 906,833 529 670 951,1 666 690 162 578
6,Total,140 875 551 142 710 739,274 180 274 180,1 161 963 -184 027

------------------------------
Tableau 22

            Unnamed: 0 Unnamed: 1 Solde au 30/06/2014 Solde au 31/12/2013
0  Frais préliminaires        NaN           8 037 352           5 332 816
1   Charges à répartir        NaN             332 513             432 580
2                  NaN      Total           8 369 865           5 765 396

------------------------------
Tableau 23

,Unnamed: 0,Unnamed: 1,Solde au 30/06/2014,Solde au 31/12/2013
0,Matières premières,NaN,218 610 058,241 463 760
1,Fournitures et consommables,NaN,14 937 796,12 153 676
2,Travaux en cours,NaN,36 375 602,40 609 687
3,Produits finis,NaN,82 418 128,77 277 350
4,Stocks de marchandises,NaN,57 395 067,43 956 299
5,NaN,Total,409 736 651,415 460 771
6,Provisions sur stocks,NaN,-4 389 945,-4 550 524
7,NaN,Total net,405 346 706,410 910 248

------------------------------
Tableau 24

,Unnamed: 0,Unnamed: 1,Solde au 30/06/2014,Solde au 31/12/2013
0,Clients,NaN,175 129 924,125 093 682
1,"Clients, effets à recevoir",NaN,43 601 946,49 275 507
2,Clients étrangers,NaN,111 862 053,94 175 674
3,NaN,Total,330 593 922,268 544 863
4,Provisions clients,NaN,-23 397 260,-23 573 610
5,NaN,Total net,307 196 662,244 971 253

------------------------------
Tableau 25

,"Note 7 : Autres actifs courants :\rAu 30 Juin 2014, les autres actifs courants se détaillent comme suit:\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 31/12/2013\rEtat impôts et taxes\r52 902 34271 051 538\rDébiteurs divers\r4 198 7831 297 916\rComptes de régularisations\r30 933 50358 033 221\rTotal88 034 629130 382 675\rNote 8 : Placements et autres actifs financiers :\rAu 30 Juin 2014, les placements et autres actifs financiers sedétaillent comme suit :\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 31/12/2013\rÉchéances courantes sur prêts\r4 4704 398\rPlacements courants\r7 325 8017 099 718\rPlacement en billets de trésorerie\r4 600 00011 000 000\rProvisions\r-189 312-189 312\rTotal11 740 95817 914 804\rNote 9 : Liquidités et équivalents de liquidités:\rLesoldedecetterubriqueaatteintau30Juin2014unmontant de70 431221DTcontre\r87 037 500 DT au 31 Décembre 2013 et s'analyse comme suit:\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 31/12/2013\rEffets remis à l’encaissement\r12 426 51812 413 490\rBanques\r57 171 35774 359 415\rCaisses\r833 346264 595\rTotal70 431 22187 037 500",Unnamed: 0,Unnamed: 1
0,NaN,Solde au 30/06/2014,Solde au 31/12/2013
1,NaN,NaN,NaN
2,Etat impôts et taxes,52 902 342,71 051 538
3,Débiteurs divers,4 198 783,1 297 916
4,Comptes de régularisations,30 933 503,58 033 221
5,NaN,NaN,NaN
6,Total,88 034 629,130 382 675

------------------------------
Tableau 26

,"Note 7 : Autres actifs courants :\rAu 30 Juin 2014, les autres actifs courants se détaillent comme suit:\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 31/12/2013\rEtat impôts et taxes\r52 902 34271 051 538\rDébiteurs divers\r4 198 7831 297 916\rComptes de régularisations\r30 933 50358 033 221\rTotal88 034 629130 382 675\rNote 8 : Placements et autres actifs financiers :\rAu 30 Juin 2014, les placements et autres actifs financiers sedétaillent comme suit :\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 31/12/2013\rÉchéances courantes sur prêts\r4 4704 398\rPlacements courants\r7 325 8017 099 718\rPlacement en billets de trésorerie\r4 600 00011 000 000\rProvisions\r-189 312-189 312\rTotal11 740 95817 914 804\rNote 9 : Liquidités et équivalents de liquidités:\rLesoldedecetterubriqueaatteintau30Juin2014unmontant de70 431221DTcontre\r87 037 500 DT au 31 Décembre 2013 et s'analyse comme suit:\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 31/12/2013\rEffets remis à l’encaissement\r12 426 51812 413 490\rBanques\r57 171 35774 359 415\rCaisses\r833 346264 595\rTotal70 431 22187 037 500",Unnamed: 0,Unnamed: 1
0,NaN,Solde au 30/06/2014,Solde au 31/12/2013
1,NaN,NaN,NaN
2,Effets remis à l’encaissement,12 426 518,12 413 490
3,Banques,57 171 357,74 359 415
4,Caisses,833 346,264 595
5,NaN,NaN,NaN
6,Total,70 431 221,87 037 500

------------------------------
Tableau 27

,"Note 7 : Autres actifs courants :\rAu 30 Juin 2014, les autres actifs courants se détaillent comme suit:\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 31/12/2013\rEtat impôts et taxes\r52 902 34271 051 538\rDébiteurs divers\r4 198 7831 297 916\rComptes de régularisations\r30 933 50358 033 221\rTotal88 034 629130 382 675\rNote 8 : Placements et autres actifs financiers :\rAu 30 Juin 2014, les placements et autres actifs financiers sedétaillent comme suit :\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 31/12/2013\rÉchéances courantes sur prêts\r4 4704 398\rPlacements courants\r7 325 8017 099 718\rPlacement en billets de trésorerie\r4 600 00011 000 000\rProvisions\r-189 312-189 312\rTotal11 740 95817 914 804\rNote 9 : Liquidités et équivalents de liquidités:\rLesoldedecetterubriqueaatteintau30Juin2014unmontant de70 431221DTcontre\r87 037 500 DT au 31 Décembre 2013 et s'analyse comme suit:\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 31/12/2013\rEffets remis à l’encaissement\r12 426 51812 413 490\rBanques\r57 171 35774 359 415\rCaisses\r833 346264 595\rTotal70 431 22187 037 500",Unnamed: 0,Unnamed: 1
0,NaN,Solde au 30/06/2014,Solde au 31/12/2013
1,NaN,NaN,NaN
2,Etat impôts et taxes,52 902 342,71 051 538
3,Débiteurs divers,4 198 783,1 297 916
4,Comptes de régularisations,30 933 503,58 033 221
5,NaN,NaN,NaN
6,Total,88 034 629,130 382 675
7,NaN,Solde au 30/06/2014,Solde au 31/12/2013
8,NaN,NaN,NaN
9,Échéances courantes sur prêts,4 470,4 398
10,Placements courants,7 325 801,7 099 718
11,Placement en billets de trésorerie,4 600 000,11 000 000
12,Provisions,-189 312,-189 312
13,NaN,NaN,NaN
14,Total,11 740 958,17 914 804
15,NaN,Solde au 30/06/2014,Solde au 31/12/2013
16,NaN,NaN,NaN
17,Effets remis à l’encaissement,12 426 518,12 413 490
18,Banques,57 171 357,74 359 415
19,Caisses,833 346,264 595
20,NaN,NaN,NaN
21,Total,70 431 221,87 037 500

------------------------------
Tableau 28

,"Note 7 : Autres actifs courants :\rAu 30 Juin 2014, les autres actifs courants se détaillent comme suit:\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 31/12/2013\rEtat impôts et taxes\r52 902 34271 051 538\rDébiteurs divers\r4 198 7831 297 916\rComptes de régularisations\r30 933 50358 033 221\rTotal88 034 629130 382 675\rNote 8 : Placements et autres actifs financiers :\rAu 30 Juin 2014, les placements et autres actifs financiers sedétaillent comme suit :\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 31/12/2013\rÉchéances courantes sur prêts\r4 4704 398\rPlacements courants\r7 325 8017 099 718\rPlacement en billets de trésorerie\r4 600 00011 000 000\rProvisions\r-189 312-189 312\rTotal11 740 95817 914 804\rNote 9 : Liquidités et équivalents de liquidités:\rLesoldedecetterubriqueaatteintau30Juin2014unmontant de70 431221DTcontre\r87 037 500 DT au 31 Décembre 2013 et s'analyse comme suit:\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 31/12/2013\rEffets remis à l’encaissement\r12 426 51812 413 490\rBanques\r57 171 35774 359 415\rCaisses\r833 346264 595\rTotal70 431 22187 037 500",Unnamed: 0,Unnamed: 1
0,NaN,Solde au 30/06/2014,Solde au 31/12/2013
1,NaN,NaN,NaN
2,Échéances courantes sur prêts,4 470,4 398
3,Placements courants,7 325 801,7 099 718
4,Placement en billets de trésorerie,4 600 000,11 000 000
5,Provisions,-189 312,-189 312
6,NaN,NaN,NaN
7,Total,11 740 958,17 914 804

------------------------------
Tableau 29

,Unnamed: 0,Solde au 30/06/2014,Solde au 31/12/2013
0,Capital social,180 003 600,180 003 600
1,Réserves consolidées (hors actions propres dét...,337 123 194,308 191 767
2,Actions propres détenues,-7 724 748,0
3,Résultats consolidés,44 386 560,67 243 989
4,Total,553 788 606,555 439 356

------------------------------
Tableau 30

,Unnamed: 0,Solde au 30/06/2014,Solde au 31/12/2013
0,Part des minoritaires dans les réserves,18 494 169,18 448 952
1,Part des minoritaires dans le résultat,-673 642,-1 276 272
2,Total,17 820 527,17 172 680

------------------------------
Tableau 31

,Unnamed: 0,Solde au 30/06/2014,Solde au 31/12/2013
0,Emprunts et autres passifs financiers à long t...,539 791 170,573 470 163
1,Provisions pour risques et charges,3 498 683,3 671 599
2,Total,543 289 853,577 141 762

------------------------------
Tableau 32

                            Unnamed: 0 Solde au 30/06/2014 Solde au 31/12/2013
0                  Fournisseurs locaux          53 667 977         105 668 722
1          Fournisseurs effets à payer          43 809 056          41 818 231
2    Fournisseurs retenues de garantie             535 369             562 194
3       Fournisseurs d'immobilisations           1 179 145           1 747 371
4               Fournisseurs étrangers          19 645 948          36 703 639
5  Fournisseurs factures non parvenues          81 406 785           8 893 008
6                                Total         200 244 280         195 393 165

------------------------------
Tableau 33

,Unnamed: 0,Solde au 30/06/2014,Solde au 31/12/2013
0,Clients avances et acomptes,2 109 696,1 568 782
1,Personnel et comptes rattachés,7 103 876,7 193 455
2,Impôts et taxes,2 480 134,2 940 163
3,Comptes d’actionnaires et d’associés,38 719 681,16 536
4,Créditeurs divers,15 051 108,7 839 371
5,Comptes de régularisation,26 194 774,13 725 070
6,Provisions courantes,109 075,2 761 457
7,Total,91 768 344,36 044 834

------------------------------
Tableau 34

,Unnamed: 0,Solde au 30/06/2014,Solde au 31/12/2013
0,Échéance à moins d'un an sur emprunts,212 531 073,194 586 320
1,Emprunts courants liés au cycle d’exploitation,65 588 755,69 636 144
2,Découverts bancaires,94 735 447,130 843 774
3,Total,372 855 275,395 066 238

------------------------------
Tableau 35

,"II. 5. ETAT DE RESULTAT :\rNote 16 : Revenus :\rLes revenus ont totalisé 784 859 683 DT au 30 Juin 2014 et se détaillent comme suit:\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 30/06/2013Solde au 31/12/2013\rVente des produits finis et prestations de services\r746 667 467698 402 9371 398 460 687\rVente de marchandises\r55 387 07463 438 410122 229 126\rRemises, rabais et ristournes accordées\r-17 194 859-14 130 952-25 194 994\rTotal784 859 683747 710 3951 495 494 818\rNote 17 : Autres produits d’exploitation :\rLes autres produits d’exploitation ont totalisé2 757 279 DT au 30 Juin 2014 et se détaillent\rcomme suit :\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 30/06/2013Solde au 31/12/2013\rQuote-part des subventions d'investissements\r470 788472 4411 477 019\rinscrite au compte de résultat\rSubventions d'exploitation\r2 269 5512 080 8754 910 712\rAutres produits d'exploitation\r16 9398 83911 644\rTotal2 757 2792 562 1556 399 375",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,NaN,Solde au 30/06/2014,NaN,Solde au 30/06/2013,NaN,Solde au 31/12/2013,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Vente des produits finis et prestations de ser...,NaN,746 667 467,NaN,698 402 937,NaN,1 398 460 687,NaN
3,Vente de marchandises,NaN,55 387 074,NaN,63 438 410,NaN,122 229 126,NaN
4,"Remises, rabais et ristournes accordées",NaN,-17 194 859,NaN,-14 130 952,NaN,-25 194 994,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Total,NaN,784 859 683,NaN,747 710 395,NaN,1 495 494 818,NaN

------------------------------
Tableau 36

,"II. 5. ETAT DE RESULTAT :\rNote 16 : Revenus :\rLes revenus ont totalisé 784 859 683 DT au 30 Juin 2014 et se détaillent comme suit:\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 30/06/2013Solde au 31/12/2013\rVente des produits finis et prestations de services\r746 667 467698 402 9371 398 460 687\rVente de marchandises\r55 387 07463 438 410122 229 126\rRemises, rabais et ristournes accordées\r-17 194 859-14 130 952-25 194 994\rTotal784 859 683747 710 3951 495 494 818\rNote 17 : Autres produits d’exploitation :\rLes autres produits d’exploitation ont totalisé2 757 279 DT au 30 Juin 2014 et se détaillent\rcomme suit :\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 30/06/2013Solde au 31/12/2013\rQuote-part des subventions d'investissements\r470 788472 4411 477 019\rinscrite au compte de résultat\rSubventions d'exploitation\r2 269 5512 080 8754 910 712\rAutres produits d'exploitation\r16 9398 83911 644\rTotal2 757 2792 562 1556 399 375",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,NaN,Solde au 30/06/2014,NaN,Solde au 30/06/2013,NaN,Solde au 31/12/2013,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Vente des produits finis et prestations de ser...,NaN,746 667 467,NaN,698 402 937,NaN,1 398 460 687,NaN
3,Vente de marchandises,NaN,55 387 074,NaN,63 438 410,NaN,122 229 126,NaN
4,"Remises, rabais et ristournes accordées",NaN,-17 194 859,NaN,-14 130 952,NaN,-25 194 994,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Total,NaN,784 859 683,NaN,747 710 395,NaN,1 495 494 818,NaN
7,NaN,Solde au 30/06/2014,Solde au 30/06/2013,Solde au 31/12/2013,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Quote-part des subventions d'investissements\r...,470 788,472 441,1 477 019,NaN,NaN,NaN,NaN
10,Subventions d'exploitation,2 269 551,2 080 875,4 910 712,NaN,NaN,NaN,NaN
11,Autres produits d'exploitation,16 939,8 839,11 644,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Total,2 757 279,2 562 155,6 399 375,NaN,NaN,NaN,NaN

------------------------------
Tableau 37

,"II. 5. ETAT DE RESULTAT :\rNote 16 : Revenus :\rLes revenus ont totalisé 784 859 683 DT au 30 Juin 2014 et se détaillent comme suit:\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 30/06/2013Solde au 31/12/2013\rVente des produits finis et prestations de services\r746 667 467698 402 9371 398 460 687\rVente de marchandises\r55 387 07463 438 410122 229 126\rRemises, rabais et ristournes accordées\r-17 194 859-14 130 952-25 194 994\rTotal784 859 683747 710 3951 495 494 818\rNote 17 : Autres produits d’exploitation :\rLes autres produits d’exploitation ont totalisé2 757 279 DT au 30 Juin 2014 et se détaillent\rcomme suit :\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 30/06/2013Solde au 31/12/2013\rQuote-part des subventions d'investissements\r470 788472 4411 477 019\rinscrite au compte de résultat\rSubventions d'exploitation\r2 269 5512 080 8754 910 712\rAutres produits d'exploitation\r16 9398 83911 644\rTotal2 757 2792 562 1556 399 375",Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,NaN,Solde au 30/06/2014,Solde au 30/06/2013,Solde au 31/12/2013,NaN
1,NaN,NaN,NaN,NaN,NaN
2,Quote-part des subventions d'investissements\r...,470 788,472 441,1 477 019,NaN
3,Subventions d'exploitation,2 269 551,2 080 875,4 910 712,NaN
4,Autres produits d'exploitation,16 939,8 839,11 644,NaN
5,NaN,NaN,NaN,NaN,NaN
6,Total,2 757 279,2 562 155,6 399 375,NaN

------------------------------
Tableau 38

,Note 18 : Autres charges d’exploitation :\rLes autres charges d’exploitation ont totalisé80 146 243 DT au 30 Juin 2014 et se détaillent\rcomme suit :\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 30/06/2013Solde au 31/12/2013\rAchat non stockés de fournitures\r17 802 71415 359 38742 311 314\rServices extérieurs\r60 329 39960 571 396121 064 887\rImpôts et taxes\r2 014 1301 394 0474 565 767\rTotal80 146 24377 324 830167 941 968\rNote 19 : Charges financières nettes :\rLeschargesfinancièresnettesonttotalisé29796 851DTau30Juin2014etsedétaillent\rcomme suit :\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 30/06/2013Solde au 31/12/2013\rCharges d'intérêt\r-27 773 835-23 258 391-54 021 930\rProduits financiers nets\r1 005 0812 438 6951 509 606\rPertes de change\r-5 744 610-2 301 584-11 309 499\rGains de change\r2 716 512956 7787 779 700\rTotal-29 796 851-22 164 502-56 042 122,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,NaN,Solde au 30/06/2014,Solde au 30/06/2013,Solde au 31/12/2013,NaN
1,NaN,NaN,NaN,NaN,NaN
2,Charges d'intérêt,-27 773 835,-23 258 391,-54 021 930,NaN
3,Produits financiers nets,1 005 081,2 438 695,1 509 606,NaN
4,Pertes de change,-5 744 610,-2 301 584,-11 309 499,NaN
5,Gains de change,2 716 512,956 778,7 779 700,NaN
6,NaN,NaN,NaN,NaN,NaN
7,Total,-29 796 851,-22 164 502,-56 042 122,NaN

------------------------------
Tableau 39

,Note 18 : Autres charges d’exploitation :\rLes autres charges d’exploitation ont totalisé80 146 243 DT au 30 Juin 2014 et se détaillent\rcomme suit :\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 30/06/2013Solde au 31/12/2013\rAchat non stockés de fournitures\r17 802 71415 359 38742 311 314\rServices extérieurs\r60 329 39960 571 396121 064 887\rImpôts et taxes\r2 014 1301 394 0474 565 767\rTotal80 146 24377 324 830167 941 968\rNote 19 : Charges financières nettes :\rLeschargesfinancièresnettesonttotalisé29796 851DTau30Juin2014etsedétaillent\rcomme suit :\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 30/06/2013Solde au 31/12/2013\rCharges d'intérêt\r-27 773 835-23 258 391-54 021 930\rProduits financiers nets\r1 005 0812 438 6951 509 606\rPertes de change\r-5 744 610-2 301 584-11 309 499\rGains de change\r2 716 512956 7787 779 700\rTotal-29 796 851-22 164 502-56 042 122,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,NaN,Solde au 30/06/2014,Solde au 30/06/2013,Solde au 31/12/2013,NaN
1,NaN,NaN,NaN,NaN,NaN
2,Achat non stockés de fournitures,17 802 714,15 359 387,42 311 314,NaN
3,Services extérieurs,60 329 399,60 571 396,121 064 887,NaN
4,Impôts et taxes,2 014 130,1 394 047,4 565 767,NaN
5,NaN,NaN,NaN,NaN,NaN
6,Total,80 146 243,77 324 830,167 941 968,NaN
7,NaN,Solde au 30/06/2014,Solde au 30/06/2013,Solde au 31/12/2013,NaN
8,NaN,NaN,NaN,NaN,NaN
9,Charges d'intérêt,-27 773 835,-23 258 391,-54 021 930,NaN
10,Produits financiers nets,1 005 081,2 438 695,1 509 606,NaN
11,Pertes de change,-5 744 610,-2 301 584,-11 309 499,NaN
12,Gains de change,2 716 512,956 778,7 779 700,NaN
13,NaN,NaN,NaN,NaN,NaN
14,Total,-29 796 851,-22 164 502,-56 042 122,NaN

------------------------------
Tableau 40

,Note 18 : Autres charges d’exploitation :\rLes autres charges d’exploitation ont totalisé80 146 243 DT au 30 Juin 2014 et se détaillent\rcomme suit :\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 30/06/2013Solde au 31/12/2013\rAchat non stockés de fournitures\r17 802 71415 359 38742 311 314\rServices extérieurs\r60 329 39960 571 396121 064 887\rImpôts et taxes\r2 014 1301 394 0474 565 767\rTotal80 146 24377 324 830167 941 968\rNote 19 : Charges financières nettes :\rLeschargesfinancièresnettesonttotalisé29796 851DTau30Juin2014etsedétaillent\rcomme suit :\r(Exprimés en TND)\rSolde au 30/06/2014Solde au 30/06/2013Solde au 31/12/2013\rCharges d'intérêt\r-27 773 835-23 258 391-54 021 930\rProduits financiers nets\r1 005 0812 438 6951 509 606\rPertes de change\r-5 744 610-2 301 584-11 309 499\rGains de change\r2 716 512956 7787 779 700\rTotal-29 796 851-22 164 502-56 042 122,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,NaN,Solde au 30/06/2014,Solde au 30/06/2013,Solde au 31/12/2013,NaN
1,NaN,NaN,NaN,NaN,NaN
2,Achat non stockés de fournitures,17 802 714,15 359 387,42 311 314,NaN
3,Services extérieurs,60 329 399,60 571 396,121 064 887,NaN
4,Impôts et taxes,2 014 130,1 394 047,4 565 767,NaN
5,NaN,NaN,NaN,NaN,NaN
6,Total,80 146 243,77 324 830,167 941 968,NaN

------------------------------
Tableau 41

,Unnamed: 0,POULINA GROUP HOLDING S.A. ( P G H )
0,NaN,ETAT DES FLUX DE TRESORERIE CONSOLIDE
1,NaN,Au 30/06/2014
2,NaN,(Exprimé en TND)
3,NaN,30/06/2013 30/06/2013 31/12/2013
4,FLUX DE TRESORERIE LIES À L'EXPLOITATION,NaN
5,Résultat Net consolidé de l'exercice,44 386 560 40 316 492 67 243 989
6,Ajustements pour :,NaN
7,• Dotations aux amortissements et aux provisions,40 106 647 37 831 181 77 969 539
8,• Variation du besoin en fonds de roulement,-10 127 771 -48 703 497 -33 199 327
9,• Plus ou moins-values sur cessions,-7 021 2 076 373 2 510 172
10,• Quote-part des intérêts des minoritaires dan...,673 642 644 029 1 276 272
11,• Quote-part des subventions d'investissement ...,-470 788 -472 441 -1 477 019
12,• Quote-part dans le résultat des sociétés mis...,-1 161 963 -1 913 907 184 027
13,Flux de trésorerie provenant de l'exploitation,73 399 306 29 778 231 114 507 653
14,FLUX DE TRESORERIE LIES AUX ACTIVITES D'INVEST...,NaN
15,-Variation de trésorerie suite aux acquisition...,NaN
16,NaN,-39 106 900 -50 174 807 -115 936 910
17,corporelles et incorporelles,NaN
18,-Variation de trésorerie suite aux acquisition...,NaN
19,NaN,-2 362 640 -474 205 -3 527 550
20,financières et autres actifs non courants,NaN
21,Flux de trésorerie affectés aux activités d'in...,-41 469 539 -50 649 012 -119 464 460
22,FLUX DE TRESORERIE LIES AUX ACTIVITES DE FINAN...,NaN
23,- Encaissement suite à la libération du capital,1 017 750 0 2 769 745
24,- Dividendes et autres distributions,0 0 -38 057 230
25,-Variation de trésorerie provenant des emprunt...,NaN
26,NaN,-13 613 125 5 692 603 51 342 191
27,financement,NaN
28,- Subventions reçues,167 656 803 228 1 791 768
29,Flux de trésorerie affectés aux activités de f...,-12 427 719 6 495 831 17 846 474
30,VARIATION DE TRESORERIE,19 502 048 -14 374 950 12 889 667
31,- Trésorerie au début de l'exercice,-43 806 274 -56 695 941 -56 695 941
32,- Trésorerie à la clôture de l'exercice,-24 304 226 -71 070 891 -43 806 274
33,Les Notes de 1 à 19 font partie intégrante des...,NaN

------------------------------
Tableau 42

,Unnamed: 0,% d'intérêt,% Contrôle,Unnamed: 1,Unnamed: 2
0,NaN,NaN,NaN,Qualification,NaN
1,NaN,NaN,NaN,NaN,Méthode
2,NaN,30/06/2014 31/12/2013,30/06/2014 31/12/2013,de la,NaN
3,NaN,NaN,NaN,NaN,de consolidation
4,NaN,NaN,NaN,participation,NaN
...,...,...,...,...,...
100,NaN,NaN,NaN,exclusif,Globale
101,NaN,% d'intérêt,% Contrôle,NaN,NaN
102,NaN,NaN,NaN,Qualification,Méthode
103,NaN,30/06/2014 31/12/2013,30/06/2014 31/12/2013,NaN,NaN
104,NaN,NaN,NaN,de la,de consolidation

------------------------------
Tableau 43

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,participation,Unnamed: 5
0,NaN,NaN,NaN,NaN,NaN,Contrôle,Intégration
1,Société de Construction Industrialisée,"100,00% 100,00%",NaN,"100,00% 100,00%",NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,exclusif,Globale
3,NaN,NaN,NaN,NaN,NaN,Contrôle,Intégration
4,Idéal Industrie de l'Est Algérie,"99,92% 99,92%",NaN,"100,00% 100,00%",NaN,NaN,NaN
...,...,...,...,...,...,...,...
100,NaN,NaN,NaN,NaN,NaN,NaN,de consolidation
101,NaN,NaN,NaN,NaN,NaN,participation,NaN
102,NaN,NaN,NaN,NaN,NaN,Contrôle,Intégration
103,Premix Sebri,"100,00% 100,00%",NaN,"100,00% 10,00%",NaN,NaN,NaN
104,NaN,NaN,NaN,NaN,NaN,exclusif,Globale

------------------------------
Tableau 44

,Unnamed: 0,Solde au 30/06/2014,Solde au 31/12/2013
0,Investissement en recherche et développement,72 403,67 063
1,"Concessions de marques, brevets, licences",654 275,612 338
2,Logiciels,6 758 150,6 647 367
3,Fonds commercial,2 169 296,2 197 749
4,Droit au bail,81 000,81 000
5,Autres immobilisations incorporelles,157 036,149 140
6,Goodwill net d’amortissements (i),1 685 832,1 909 901
7,Total,11 577 992,11 664 558
8,Moins Amortissements (Hors Amortissements du G...,-7 679 515,-7 103 235
9,Total net,3 898 477,4 561 324

------------------------------
Tableau 45

,Unnamed: 0,Solde au 30/06/2014,Solde au 31/12/2013
0,Terrains,61 795 821,61 768 643
1,Constructions,278 350 138,284 702 614
2,Plantations et cheptels,7 393 549,9 395 727
3,Installations Techniques Matériel et outillage...,579 589 576,572 577 522
4,Matériel de Transport,60 610 605,58 006 671
5,"Installations générales, agencements et aménag...",127 957 901,125 829 619
6,Equipements de bureaux,21 186 481,20 427 622
7,Matériel d'emballage,18 865 651,20 678 281
8,Petit matériel d'exploitation,17 475 578,17 476 749
9,Immobilisations à statut juridique particulier,12 520 022,11 725 493
10,Immobilisations en cours,88 513 357,54 470 162
11,Total,1 274 258 679,1 237 059 102
12,Moins Amortissements,-619 312 814,-589 825 894
13,Total net,654 945 865,647 233 208

------------------------------
Tableau 46

                           Unnamed: 0 Solde au 30/06/2014 Solde au 31/12/2013
0             Titres de participation          83 325 460          81 350 331
1           Titres mis en équivalence         140 875 551         142 710 739
2                               Prêts           1 908 628           2 683 223
3            Dépôts et cautionnements           6 719 540           4 099 940
4  Autres immobilisations financières           1 278 443             900 750
5                          Total brut         234 107 623         231 744 984
6                    Moins Provisions          -4 305 122          -4 263 355
7                           Total net         229 802 501         227 481 628

------------------------------
Tableau 47

,Unnamed: 0,Unnamed: 1,Solde au 30/06/2014,Solde au 31/12/2013
0,Etat impôts et taxes,NaN,52 902 342,71 051 538
1,Débiteurs divers,NaN,4 198 783,1 297 916
2,Comptes de régularisations,NaN,30 933 503,58 033 221
3,NaN,Total,88 034 629,130 382 675

------------------------------
Tableau 48

                           Unnamed: 0 Solde au 30/06/2014 Solde au 31/12/2013
0       Échéances courantes sur prêts               4 470               4 398
1                 Placements courants           7 325 801           7 099 718
2  Placement en billets de trésorerie           4 600 000          11 000 000
3                          Provisions            -189 312            -189 312
4                               Total          11 740 958          17 914 804

------------------------------
Tableau 49

,Unnamed: 0,Unnamed: 1,Solde au 30/06/2014,Solde au 31/12/2013
0,Effets remis à l’encaissement,NaN,12 426 518,12 413 490
1,Banques,NaN,57 171 357,74 359 415
2,Caisses,NaN,833 346,264 595
3,NaN,Total,70 431 221,87 037 500

------------------------------
Tableau 50

,Unnamed: 0,Solde au 30/06/2014,Solde au 30/06/2013,Solde au 31/12/2013
0,Vente des produits finis et prestations de ser...,746 667 467,698 402 937,1 398 460 687
1,Vente de marchandises,55 387 074,63 438 410,122 229 126
2,"Remises, rabais et ristournes accordées",-17 194 859,-14 130 952,-25 194 994
3,Total,784 859 683,747 710 395,1 495 494 818

------------------------------
Tableau 51

,Unnamed: 0,Solde au 30/06/2014,Solde au 30/06/2013,Solde au 31/12/2013
0,Quote-part des subventions d'investissements,NaN,NaN,NaN
1,NaN,470 788,472 441,1 477 019
2,inscrite au compte de résultat,NaN,NaN,NaN
3,Subventions d'exploitation,2 269 551,2 080 875,4 910 712
4,Autres produits d'exploitation,16 939,8 839,11 644
5,Total,2 757 279,2 562 155,6 399 375

------------------------------
Tableau 52

,Unnamed: 0,Solde au 30/06/2014,Solde au 30/06/2013,Solde au 31/12/2013
0,Achat non stockés de fournitures,17 802 714,15 359 387,42 311 314
1,Services extérieurs,60 329 399,60 571 396,121 064 887
2,Impôts et taxes,2 014 130,1 394 047,4 565 767
3,Total,80 146 243,77 324 830,167 941 968

------------------------------
Tableau 53

,Unnamed: 0,Solde au 30/06/2014,Solde au 30/06/2013,Solde au 31/12/2013
0,Charges d'intérêt,-27 773 835,-23 258 391,-54 021 930
1,Produits financiers nets,1 005 081,2 438 695,1 509 606
2,Pertes de change,-5 744 610,-2 301 584,-11 309 499
3,Gains de change,2 716 512,956 778,7 779 700
4,Total,-29 796 851,-22 164 502,-56 042 122